### ISSUE TITLE
CudaCompileFlagCheck for major and minor versions

### ISSUE THREAD

**Issue by jtristano** [hypre-space/hypre#1000]
Hello,
I am building hypre for multiple architectures, Quadro, Volta, and Ampere with    

`CUDA_HOME=/usr/local/cuda ./configure --with-cuda --with-gpu-arch='60 70 80' --prefix /usr/local --enable-shared --enable-device-memory-pool  --disable-static  --enable-unified-memory`

When  initializing hypre, device utils asserts that my actual architecture doesnt match the compiled architecture.  Shouldn't the device downgrade when running a lower architecture than what it states?

actual=610
compiled=600

Why assert in this case?  

Thanks
Joe

**Comment by victorapm** [comment]
@jtristano it seems `--with-gpu-arch='61 70 80'` would work for your machine

**Comment by jtristano** [comment]
It would but 60 should still run on 61, correct?

**Comment by victorapm** [comment]
@jtristano Correct, however hypre currently doesn't support that. Is there a particular reason why you would like this feature? Note it's recommended to compile device code for the newest compute architecture supported by a given card.

**Comment by jtristano** [comment]
As we containerize we have multiple cards to support on various machines.  It would be nice to compile to the major version and drop back to that

**Comment by victorapm** [comment]
@jtristano thanks! We will work on supporting that

**Comment by liruipeng** [comment]
> Hello, I am building hypre for multiple architectures, Quadro, Volta, and Ampere with
> 
> `CUDA_HOME=/usr/local/cuda ./configure --with-cuda --with-gpu-arch='60 70 80' --prefix /usr/local --enable-shared --enable-device-memory-pool --disable-static --enable-unified-memory`
> 
> When initializing hypre, device utils asserts that my actual architecture doesnt match the compiled architecture. Shouldn't the device downgrade when running a lower architecture than what it states?
> 
> actual=610 compiled=600
> 
> Why assert in this case?
> 
> Thanks Joe

This assertion is only for hypre's debug mode. Do you need to run it in the debug mode?
