### ISSUE TITLE
build under MSVC 2022 with MPI and windows 11 

### ISSUE THREAD

**Issue by jbensabat** [hypre-space/hypre#1004]
Hello 
I am trying to build hypre with MPI support under windows (11) and msvc 2022 using CMAKE 3.28 
I have msmpi and intel mpi installed and CMAKE does not seem to be happy 
mpi_c seems to be missing 
any help would really be appreciated.
best
jac

**Comment by ermore** [comment]
Two components of `MSMPI` need to be installed: `MSMPISDK.msi` and `MSMpisetup.exe`. The default installation will add msmpi to the path, which will be detected by cmake.

**Comment by jbensabat** [comment]
hi 
thanks for the help. that worked.
best 
jac
