### ISSUE TITLE
Umpire Memory Pool Usage

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#1008]
Is there any way to tell how much of an Umpire memory pool is being used at a given point in a Hypre solve?

-Paul

**Comment by victorapm** [comment]
Hi Paul, currently not. But that's something that could be implemented in hypre, see umpire's `getCurrentSize`:

https://github.com/LLNL/Umpire/blob/58be0db4455643893287a102d3f7409846e354b1/src/umpire/Allocator.hpp#L107-L115
 
I'm not sure though how this would work in the scenario where a GPU is being oversubscribed with multiple MPI ranks (if we want to compute overall memory utilization percentage)...

**Comment by PaulMullowney** [comment]
Thanks Victor. That's a helpful pointer.
-Paul

**Comment by victorapm** [comment]
This is the C interface for the function I mentioned (hypre uses umpire via its C interface): https://github.com/LLNL/Umpire/blob/58be0db4455643893287a102d3f7409846e354b1/src/umpire/interface/c_fortran/wrapAllocator.cpp#L97-L105C2

If you implement something, please let me know :)

**Comment by victorapm** [comment]
Paul, this seems to be resolved, so I'm closing. Thanks!
