### ISSUE TITLE
Unused variable 'suffix' build on Windows

### ISSUE THREAD

**Issue by adam-sim-dev** [hypre-space/hypre#1012]
hypre-2.30.0\src\utilities\utilities.c(160,20): : warning : unused variable 'suffix' [-Wunused-variable]
2>   HYPRE_Int       suffix;
2>                   ^
hypre-2.30.0\src\utilities\utilities.c(162,20): : warning : unused variable 'msg' [-Wunused-variable]
2>   char            msg[HYPRE_MAX_MSG_LEN];

**Comment by victorapm** [comment]
Thanks for reporting. We have a branch fixing this
