### ISSUE TITLE
Is it possible to use HYPRE_ParVector references without memory leaks?

### ISSUE THREAD

**Issue by thartland** [hypre-space/hypre#1015]
I want to work with `HYPRE_ParVector` references to `HYPRE_IJVector`'s. I would like to not have to invoke `HYPRE_IJVectorDestroy` but rather just use `HYPRE_ParVectorDestroy` on the `HYPRE_ParVector`. Unfortunately, after running a memory leak with valgrind I see that in the following code 
1. There are no memory leaks if I call `HYPRE_IJVectorDestroy`
2. If I only call `HYPRE_ParVectorDestroy` then just as much memory is _definitely lost_ as if I did not call any `VectorDestroy` method.

Is this behavior expected? I have added context below the attached code to better understand why I am focused on this problem.

```
#include "HYPRE.h"
#include "HYPRE_parcsr_ls.h"

int main (int argc, char *argv[])
{
  MPI_Init(&argc, &argv);
  /* Initialize HYPRE */
  HYPRE_Initialize();
  
  
  int myrank, nprocs; 
  MPI_Comm_rank(MPI_COMM_WORLD, &myrank);
  MPI_Comm_size(MPI_COMM_WORLD, &nprocs);

  int nGlb = 20; // global number of dofs
  
  /* partition nGlb among the given MPI processes */
  HYPRE_Int * dofOffsets = (HYPRE_Int *) calloc(2, sizeof(HYPRE_Int));
  for (int i = 0; i < 2; i++)
  {
    (dofOffsets)[i] = (HYPRE_Int) ((myrank + i ) * nGlb / nprocs);
  }
  dofOffsets[1] -= 1;
 

  int nLoc = 1 + (dofOffsets[1] - dofOffsets[0]); // number of dofs for given MPI process
  
  
  /* determine indicies owned by given process and assign values to these entries */
  int    * dofs =    (int    *) calloc(nLoc, sizeof(int));    // Vector indicies owned by given process
  double * valuesx = (double *) calloc(nLoc, sizeof(double)); // Vector entries
  for(int i = 0; i < nLoc; i++)
  {
    dofs[i] = dofOffsets[0] + i;
    valuesx[i] = 1.0;
  }

  /* create HYPRE_IJVec */
  HYPRE_IJVector xIJ;
  HYPRE_IJVectorCreate(MPI_COMM_WORLD, dofOffsets[0], dofOffsets[1], &xIJ);
  HYPRE_IJVectorSetObjectType(xIJ, HYPRE_PARCSR);
  HYPRE_IJVectorInitialize(xIJ);
  HYPRE_IJVectorSetValues(xIJ, nLoc, dofs, valuesx);
  HYPRE_IJVectorAssemble(xIJ);
  free(dofs); 
  free(valuesx);

  /* create a HYPRE_ParVec which references the HYPRE_IJVec */
  HYPRE_ParVector par_x;
  HYPRE_IJVectorGetObject(xIJ, (void **) &par_x);

  /* have been altering the destroys here to better understand how they work */
  //HYPRE_IJVectorDestroy(xIJ);
  HYPRE_ParVectorDestroy(par_x);
  
  free(dofOffsets); 
  HYPRE_Finalize();

  /* Finalize MPI*/
  MPI_Finalize();

  
  return 0;
}
```

Context: In a project that I am working on I am assuming that there is a means to compute a gradient (`IJ_grad`) of a function at a point `par_x`, where the gradient is a `HYPRE_IJVector`

`void grad_IJ (HYPRE_ParVector * par_x, HYPRE_IJVector * IJ_grad)`

I want to then use this as follows in order to compute a `HYPRE_ParVector` representation of the gradient.

```
void grad_par (HYPRE_ParVector * par_x, HYPRE_ParVector * par_grad)
{
  HYPRE_IJVector IJ_grad;
  grad_IJ (par_x, &IJ_grad);
  HYPRE_IJVectorGetObject(IJ_grad, (void **) par_grad);
}
```

but this seems prone to memory leaks due to the issue that is the focus of this issue.

**Comment by liruipeng** [comment]
Hi @thartland If you only call `HYPRE_ParVectorDestroy` to free the object of IJVecotr, it is expected to have memory leak from the other parts of IJVector. `HYPRE_IJVectorDestroy` free them as well. I don't see the reason why you can't call `HYPRE_IJVectorDestroy` on `IJ_grad`. Maybe I missed something. If you have to call `HYPRE_ParVectorDestroy` to free the parvector, the way I guess is to manipulate the IJ structure, after `HYPRE_IJVectorGetObject`, by setting 
```
hypre_IJVectorObject(vector) = NULL
```
or something like that, so you can call `HYPRE_IJVectorDestroy` to free the IJVector but keep the ParVector.

**Comment by rfalgout** [comment]
We have reference counters in some of the matrix/vector objects in hypre.  I wonder if we should expose this to users somehow so they can create persistent references to objects and better manage memory.  The simplest thing we could do for now is implement a `GetObjectRef` call for all matrices and vectors.  This would maintain backward compatibility and I think it would help Tucker out.  Basically, this call (instead of `GetObject`) would return an object that must be freed separately at some point.  So here both the IJDestroy and the ParDestroy would have to be called (in any order).

**Comment by thartland** [comment]
Thanks everyone for the quick responses! I am glad to know that it wasn't something obvious that I missed. Before your team invests the time into this effort let me communicate a bit more with my team to further clarify needs, I'll follow up in the next few days.

**Comment by thartland** [comment]
I did a slight redesign of my code to avoid memory leaks. Thank you for clarifying how these objects work, that information was useful to me.
