### ISSUE TITLE
I am using the finite element interface and encountered a missing file issue while compiling ex10. 

### ISSUE THREAD

**Issue by LiMuxing666** [hypre-space/hypre#1017]
I couldn’t find the missing file in the src directory.These files cannot be found.
#include "fei_defs.h"
#include "fei_Data.hpp"
#include "fei_Lookup.hpp"
#include "fei_LinearSystemCore.hpp"
in the file :LLNL_FEI_LSCore.h
![image](https://github.com/hypre-space/hypre/assets/103888790/4650c1ca-c6ef-400d-83e0-f31acfcc6dc6)

**Comment by LiMuxing666** [comment]
Also, I would like to know if it is feasible to use the finite element interface to solve the tetrahedral mesh problem. I hope to receive your assistance and guidance.

**Comment by rfalgout** [comment]
I would encourage you to avoid the FEI interface in hypre as our long-term plan is to stop supporting it.  The `SStruct` and `IJ` interfaces will continue to be fully supported, if that works for you.  You might also consider using MFEM (https://mfem.org/) as an alternative finite-element interface that also provides access to hypre.  Let us know if you have other questions.  Thanks!

**Comment by LiMuxing666** [comment]
Thank you very much for your suggestions. Unfortunately, we are unable to use the SStruct interface. I am currently trying the ij interface, but I cannot understand what the “×” in this table means
![image](https://github.com/hypre-space/hypre/assets/103888790/dd68a3e0-5757-41df-a26f-09460950a94a)
I hope you can help clarify it for me.

Additionally, it seems that some solvers were not used in the examples. I tried AME, but unfortunately, it failed. I was wondering if you have any previously built examples that I could refer to. Thank you very much.

This is the modified ex5 to obtain ex20.
[ex20.zip](https://github.com/hypre-space/hypre/files/13511336/ex20.zip)
