### ISSUE TITLE
configure can't find Intel icx compiler

### ISSUE THREAD

**Issue by adam-sim-dev** [hypre-space/hypre#1021]
[config.log](https://github.com/hypre-space/hypre/files/13536398/config.log)
This is not a real problem, because one could workaround by specifying CC=mpiicx. Since the classic icc compiler is removed from Intel oneAPI 2024.0, it would be better to support the new icx compiler.

**Comment by victorapm** [comment]
Thanks for reporting. We will add icx/mpiicx support

**Comment by victorapm** [comment]
@adam-sim-dev Can you try the `fix-icx` branch and let me know if it solves your problem?

**Comment by adam-sim-dev** [comment]
> @adam-sim-dev Can you try the `fix-icx` branch and let me know if it solves your problem?

configure works now and mpicc is used by default.

**Comment by xujiangping** [comment]
I encountered the aforementioned issue when using the command ./configure --disable-fortran in both hypre-master\src and hyper.2.30.0\src directories: /opt/intel/oneapi/mpi/2021.11/bin/mpiicx: 1: eval: icc: not found. Could you please advise on how to resolve this? Thank you. The log file is attached.
[config.txt](https://github.com/hypre-space/hypre/files/13669690/config.txt)

**Comment by xujiangping** [comment]
> > @adam-sim-dev Can you try the `fix-icx` branch and let me know if it solves your problem?
> 
> configure works now and mpicc is used by default.

I also tried this branch: hypre-fix-icx/src. got the log file like this:
[config-fix-icx.log](https://github.com/hypre-space/hypre/files/13670073/config-fix-icx.log)

**Comment by victorapm** [comment]
@xujiangping, for now you can do `./configure CC=mpiicx`. We are still working on the `fix-icx` branch

**Comment by xujiangping** [comment]
> @xujiangping, for now you can do `./configure CC=mpiicx`. We are still working on the `fix-icx` branch

Great! it works. Thanks a lot!
