### ISSUE TITLE
Red/Black multigrid

### ISSUE THREAD

**Issue by SIMAO75** [hypre-space/hypre#103]
Hello everybody,

Can i use the solver red/black multigrid in the struct interface ?

Cordially,

**Comment by victorapm** [comment]
Hi @SIMAO75,

Yes, this is possible. Red/Black Gauss-Seidel relaxation is available with the PFMG and SparseMSG solvers. See [HYPRE_StructPFMGSetRelaxType](https://hypre.readthedocs.io/en/latest/api-sol-struct.html#_CPPv428HYPRE_StructPFMGSetRelaxType18HYPRE_StructSolver9HYPRE_Int) to set up the relaxation type of PFMG and [HYPRE_StructSparseMSGSetRelaxType](https://hypre.readthedocs.io/en/latest/api-sol-struct.html?highlight=msgsetrelax#_CPPv433HYPRE_StructSparseMSGSetRelaxType18HYPRE_StructSolver9HYPRE_Int) for SparseMSG.

Best,
Victor

**Comment by SIMAO75** [comment]
Thank you for your answer, 

Cordialy, 

EL OUAFA, 


De: "Victor A. Paludetto Magri" <notifications@github.com> 
À: "hypre-space/hypre" <hypre@noreply.github.com> 
Cc: "Mohamed ELOUAFA" <mohamed.elouafa@u-pem.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Lundi 6 Avril 2020 22:00:33 
Objet: Re: [hypre-space/hypre] Red/Black multigrid (#103) 





Hi [ https://github.com/SIMAO75 | @SIMAO75 ] , 

Yes, this is possible. Red/Black Gauss-Seidel relaxation is available with the PFMG and SparseMSG solvers. See [ https://hypre.readthedocs.io/en/latest/api-sol-struct.html#_CPPv428HYPRE_StructPFMGSetRelaxType18HYPRE_StructSolver9HYPRE_Int | HYPRE_StructPFMGSetRelaxType ] to set up the relaxation type of PFMG and [ https://hypre.readthedocs.io/en/latest/api-sol-struct.html?highlight=msgsetrelax#_CPPv433HYPRE_StructSparseMSGSetRelaxType18HYPRE_StructSolver9HYPRE_Int | HYPRE_StructSparseMSGSetRelaxType ] for SparseMSG. 

Best, 
Victor
