### ISSUE TITLE
build against SuperLU_dist 6.3 fails

### ISSUE THREAD

**Issue by loveshack** [hypre-space/hypre#105]
The current release of SuperLU_dist has changed the API to introduce double and complex versions of things, so it looks as if assorted function and type names now need a "d" prefix. I don't know whether you want to support that, but it would at least be worth noting.

**Comment by oseikuffuor1** [comment]
Thanks @loveshack . We are aware of this and working out a solution for it.

**Comment by oseikuffuor1** [comment]
Fixed with PR #106 . Thanks.
