### ISSUE TITLE
tar files for previous releases (to track down the cause of increased iteration counts when upgrading from 2.0.0)

### ISSUE THREAD

**Issue by MatthiasHeilManchester** [hypre-space/hypre#1052]
[Not sure if this is the right way to get in touch; apologies if not!]

We're in the process of upgrading to a more recent version of hypre (from 2.0.0!) and while our code (within which we're mainly using your AMG as a preconditioner) works with the most recent version, the iteration counts are  noticeably higher, so something's changed under the hood). The github page only lists relatively recent releases (and they all behave the same) so we wanted to narrow things down a bit by checking older ones. Is there a repository for the older tar files somewhere? 

     Many thanks!

                Matthias

- I've found some here: https://src.fedoraproject.org/repo/pkgs/hypre but they only go back to hypre-2.11.1 (which already misbehaves)

- Hypre is used quite deep inside our code and is heavily wrapped, so I'll try to prepare a stand-alone minimum working example once we've established where things break. However, if any of these (vague!) symptoms ring a bell, any hints would be appreciated. It feels like some defaults have changed somewhere... The only API changes were the changes  
hypre_CTAlloc (additional argument) and hypre__global_error -->  hypre__global_error.error_flag.

**Comment by victorapm** [comment]
Hi @MatthiasHeilManchester ,

you can get a list of the old versions of hypre via:
```
git clone https://github.com/hypre-space/hypre.git hypre-git
cd hypre-git
git tag
```
Then, select a version, e.g.:
```
git checkout V1-9-0a
```
The default parameters of BoomerAMG have changed since then. However, if the input parameters used for BoomerAMG in the old hypre version match with the ones used for the new hypre version, you should be able to get the same convergence.

Hope this helps,
Victor

**Comment by MatthiasHeilManchester** [comment]
Brilliant! Many thanks for your quick reply -- that'll really help to figure out what's going on!

     Matthias

**Comment by MatthiasHeilManchester** [comment]
I'll close this for now. May have to get back to you (plural!) re the change of the default settings; had to park my  investigation and will open a new issue if I can't get to the bottom of it by myself.
