### ISSUE TITLE
How to use -fromparcsrfile or -fromonecsrfile?

### ISSUE THREAD

**Issue by TXTsky** [hypre-space/hypre#107]
Hi ,
     I want to use some matrix in suitsparse for testing. Should I use -formonecsrfile or -formparcsrfile? Is there any need to change the matrix downloaded from suitsparse?
    Can you give an example,like 
`mpirun -np 2 ./ij -fromfile A -nf 2  -rlx 6 -solver 1 -falgout -interptype 0 -Pmx 0`

Thanks，
-TXT

**Comment by victorapm** [comment]
Hi @TXTsky,

the most straightforward way is to convert the SuiteSparse matrix to CSR format with 1-based indices for row_index and cols. The file would look like:

    nrows
    row_index[0] ... row_index[nrows]
    cols[0] ... cols[nnz - 1]
    values[0] ... values[nnz - 1]

Then, use the "-fromonecsrfile" option to read it.

Best,
Victor
