### ISSUE TITLE
Deadlock in `HYPRE_StructSMGSetup` for some specific domain decompositions

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [hypre-space/hypre#108]
Hello,

One of our users reported a deadlock with his application that I tracked it down to `HYPRE_StructSMGSetup` and more specifically `hypre_FinalizeCommunication`.

I was able to reproduce with this small sample code: https://gist.github.com/RemiLacroix-IDRIS/ec88a1ab976454a675f42084e97a668f. To compile, just use `mpif90 -g -o test.exe test.f90 -lHYPRE -Lpath/to/hypre/lib` and run with `mpirun -np 12 ./test.exe` (the test case is hard coded for 12 MPI processes).

The problem occurs only with some specific domain decompositions. For example, I can reproduce on a 256x256x384 domain with a 2x2x3 MPI topology but not with a 256x384x256 domain with a 2x3x2 MPI topology.

I added some `printf` to the functions `hypre_InitializeCommunication` and `hypre_FinalizeCommunication` in the `struct_mv/struct_communication.c` file to see exactly what is going on.

Here is what I get for processes 0 and 4 with a 256x256x384 domain and a 2x2x3 MPI topology:
 * process 0
```
req 0 - irecv --> receiving 16389 elements from 1
req 1 - irecv --> receiving 16389 elements from 2
req 2 - irecv --> receiving 261 elements from 4
req 3 - irecv --> receiving 261 elements from 5
req 4 - irecv --> receiving 133 elements from 7
req 5 - irecv --> receiving 133 elements from 8
req 6 - irecv --> receiving 7 elements from 10
req 7 - irecv --> receiving 7 elements from 11
1/8 - wait req 2 ok
2/8 - wait req 6 ok
3/8 - wait req 0 ok
4/8 - wait req 4 ok
```
 * process 4
```
req 0 - irecv --> receiving 261 elements from 0
req 1 - irecv --> receiving 261 elements from 2
req 2 - irecv --> receiving 16389 elements from 3
req 3 - irecv --> receiving 16389 elements from 5
req 4 - irecv --> receiving 7 elements from 6
req 5 - irecv --> receiving 7 elements from 8
req 6 - irecv --> receiving 133 elements from 9
req 7 - irecv --> receiving 133 elements from 11
```

As you can see both are waiting for each other to send  261 elements, hence the deadlock.

Also note that if I change `#define DEBUG 0` to `#define DEBUG 1` in `struct_mv/struct_communication.c`, I get a segfault at line 567 `offset = hypre_CommEntryTypeOffset(comm_entry);`. I am not sure if it is another symptom for the same issue or if it is another issue.

Let me know if you can reproduce the problem with the provided sample code and if you need more information.

Best regards,
Rémi

**Comment by RemiLacroix-IDRIS** [comment]
Any thoughts regarding this issue? I forgot to mention that it's happen will all compilers and MPI libraries I tested (on multiple machines).

**Comment by victorapm** [comment]
Hi @RemiLacroix-IDRIS,

thank you for reporting this issue and providing an example problem. I will have a look at it this weekend. 

Best,
Victor

**Comment by victorapm** [comment]
Hi @RemiLacroix-IDRIS,

the code has been fixed and changes were merged to master. Thanks for reporting this issue once again.

Best,
Victor

**Comment by RemiLacroix-IDRIS** [comment]
Hi Victor,

No problem, thanks for fixing the issue!

Best,
Rémi

**Comment by RemiLacroix-IDRIS** [comment]
Hi,

Just wondering, do you know in which version of HYPRE this fix will be included and do you have any ETA for it?

Best,
Rémi

**Comment by victorapm** [comment]
Hi @RemiLacroix-IDRIS,

this fix will be present in the next release of Hypre, scheduled for the end of May. Note that you can already have access to it in the master branch.

Best,
Victor
