### ISSUE TITLE
bootstrap: provide path to update-release.sh

### ISSUE THREAD

**Issue by drew-parsons** [hypre-space/hypre#11]
src/config/bootstrap now invokes update-release.sh in the docs subdir.

Since it's fairly common to not include This Directory (.) in a user's PATH, the bootstrap script will be more robust with 
`(cd docs; ./update-release.sh)`
instead of
`(cd docs; update-release.sh)`

**Comment by rfalgout** [comment]
Fixed.  Thanks!
