### ISSUE TITLE
Hypre with Cuda on Windows

### ISSUE THREAD

**Issue by kiendangtor** [hypre-space/hypre#1118]
Hi,

I was trying to run Hypre (IJ) with Cuda on a Windows machine. There were a matrix that very ill conditioned (results from an unstructured mesh with many interfaces). I used the FGMREs with BoomerAMG, all the option failed except using Schwarz smoother (I test that with the build without CUDA). All other smoothers yielded very slow convergence no matter what options I tried. FSAI supposedly to work well but the size of kap gradient estimated was not enough and it crashed. I put a check in hypre_FindKapGrad() to prevent it but then the convergence rate is almost 1.  
Unfortunately, when I tried to use Schwarz with Cuda (Unified memory has to be on), it failed because prefetching from Cuda was not supported on windows.  So my question is is there anyway that I can use Schwarz on a window machine with cuda build?

Another question is that if we have any plan to support Multiple GPUs on a single node (or in sequential configuration).

The matrix can be downloaded from here: https://we.tl/t-Ox2PmK5uqD

Thanks,

**Comment by victorapm** [comment]
@kiendangtor, thank you for your interest in hypre.

The Schwarz smoother requires unified memory support to work on GPUs, and as you pointed out, [full unified memory support is not available on windows](https://docs.nvidia.com/cuda/wsl-user-guide/index.html). Therefore, at the moment, it is not possible to use the Schwarz smoother on GPUs on windows machines.

hypre currently supports multiple GPUs on a single node, as long as each GPU is assigned to a different MPI rank. There are no plans in extending support to multiple GPUs per MPI rank.

Hope this helps!

**Comment by kiendangtor** [comment]
@victorapm thank you for you response. Magically when I commented out that async it works but just very slow. Maybe I can try that with WSL, do you think it would improve the performance a lot comparing with windows when we can oversubscribe?

**Comment by victorapm** [comment]
Good, @kiendangtor! 

If I understand your question correctly, you are asking whether the ability of oversubscribing GPU memory improves performance. In general, the answer is no because that leads to frequent data transfers between CPU RAM and GPU RAM, which is costly.

**Comment by kiendangtor** [comment]
Thanks @victorapm. That confirmed the behaviors that i observed. Using the schwarz with unified memory was a lot slower than just use CPU alone. Cheers!
I acutally have a nother question, using precond FSAI on GPU is alot faster than GPU but ILU is slower actually. Is the behavior expected?

**Comment by victorapm** [comment]
@kiendangtor I think there was a typo in your previous message. Which backend did you observe ILU to be slower **G**PU (device) or **C**PU (host)? Which ILU type have you used?

**Comment by kiendangtor** [comment]
@victorapm My apology. It was slower on GPU (cuda) than on CPU. 

Here are the command line for ij.exe test. For CPU: (took 0.94s for setting up and 3.23s to solve) 51 iterations
"-frombinfile", "D:\\Matrix solver lib\\Matrix samples\\failedunknown.out.A","-rhsfromonefile","D:\\Matrix solver lib\\Matrix samples\\failedunknown.out.b.0","-solver","61","-th", "0.8","-tol","1e-3","-smlv","1","-mxl","25","-smtype","5","-sns","1","-k","128","-ilu_sm_max_iter","1","-ilu_droptol","1e-2","-ilu_tri_solve","1","-ilu_type","0","-ns","1","-max_iter","200","-mg_max_iter","200","-memory_host","-exec_host"


For GPU (0.47s for setting up and 4.2s for solving) 57 iterations
"-frombinfile", "D:\\Matrix solver lib\\Matrix samples\\failedunknown.out.A","-rhsfromonefile","D:\\Matrix solver lib\\Matrix samples\\failedunknown.out.b.0","-solver","61","-th", "0.8","-tol","1e-3","-smlv","1","-mxl","25","-smtype","5","-sns","1","-k","128","-ilu_sm_max_iter","1","-ilu_droptol","1e-2","-ilu_tri_solve","1","-ilu_type","0","-ns","1","-max_iter","200","-mg_max_iter","200","-memory_device","-exec_device" 

Changing ilu_type gave consistent ratio between CPU and GPU (GPU is slower)

using smtype = 4 (FSAI) i got the following:
CPU: set up: 0.42 solve: 0.995 with 33 iterations
GPU: setup: 0.81 solve: 0.235 with 34 iterations

You can download the matrix from here https://we.tl/t-YyWE7m7p3M

Many thanks.

**Comment by kiendangtor** [comment]
Just to follow up on the performance of ILU as smoother for GMRES AMG generally in both CPU and GPU. I could not find a setting that worked with my problem. Using FSAI smoother converged pretty fast in about 70 iterations. Using ILU it stagnates with convergence rate of 0.99. I would expect ILU should work in similar performance with FSAI if not better. I tried with all ILU types and had no luck. Is there any documents/papers that I can look at for more info of how to improve performance of ILU smoother?

**Comment by victorapm** [comment]
@kiendangtor glad FSAI worked for your problem. Regarding ILU, you can find its documentation [here](https://hypre.readthedocs.io/en/latest/solvers-ilu.html).

Please, let me know if this issue can be closed. Thanks!

**Comment by kiendangtor** [comment]
@victorapm yes, please close the issue
