### ISSUE TITLE
HYPRE_IJMatrixGetValues with GPU enabled

### ISSUE THREAD

**Issue by aescobed** [hypre-space/hypre#1123]
Hi,

I'm trying to use the function HYPRE_IJMatrixGetValues with GPU enabled. I've managed to set the values and printed them using:
            void *object;
            HYPRE_IJMatrixGetObject(peqn->hypreA, &object);
            hypre_ParCSRMatrix *par_csr = (hypre_ParCSRMatrix*) object;
            int ierr = hypre_ParCSRMatrixPrintIJ(par_csr, 0, 0, fileName);

So that is working and I'm trying to access any of the values and it doesn't seem to be working. It gives me a segmentation fault raised by petsc.
            I printed out the values that I am inputting here:
            HYPRE_Complex* hypreAValues;
            cudaMalloc((void**)&hypreAValues, total_values * sizeof(HYPRE_Complex));

            HYPRE_Int* h_ncols_new = (HYPRE_Int*)malloc(nRows2 * sizeof(HYPRE_Int));
            HYPRE_BigInt* h_rows_new = (HYPRE_BigInt*)malloc(nRows2 * sizeof(HYPRE_BigInt));
            HYPRE_BigInt* h_cols_new = (HYPRE_BigInt*)malloc(total_values * sizeof(HYPRE_BigInt));
            
            
            cudaMemcpy(h_ncols_new, d_ncols2, nRows2 * sizeof(HYPRE_Int), cudaMemcpyDeviceToHost);
            cudaMemcpy(h_rows_new, d_rows2, nRows2 * sizeof(HYPRE_BigInt), cudaMemcpyDeviceToHost);
            cudaMemcpy(h_cols_new, d_cols2, total_values * sizeof(HYPRE_BigInt), cudaMemcpyDeviceToHost);
            
            
            printf("ncols:\n");
            for (int i = 0; i < nRows2; i++) {
                printf("%d ", h_ncols_new[i]);
            }
            printf("\n");
            
            printf("rows:\n");
            for (int i = 0; i < nRows2; i++) {
                printf("%lld ", (long long)h_rows_new[i]); 
            }
            printf("\n");
            
            printf("cols:\n");
            for (int i = 0; i < total_values; i++) {
                printf("%lld ", (long long)h_cols_new[i]);
            }
            printf("\n");
            
            HYPRE_Int nRows2 = 1; 
            printf("nrows: %d\n", nRows2);
            
            ierr = HYPRE_IJMatrixGetValues(peqn->hypreA, nRows2, d_ncols2, d_rows2, d_cols2, hypreAValues);

and this is the output:
            nrows: 1, ncols: 1, rowInd: 0, colInd: 0, total values: 1
            ncols:
            1 
            rows:
            0 
            cols:
            0 
            nrows: 1

I know this value exists because when i printed it this is what i got:

            0 0 -3.38998230595350e-02

I'm using almost all the same values to access HYPRE_IJVectorGetValues and that works. Just not the matrix values. Could someone lend me a hand please?

**Comment by liruipeng** [comment]
I think a quick answer is we haven't implemented this function on GPUs.

**Comment by liruipeng** [comment]
But we do have `HYPRE_ParCSRMatrixGetRow` that may be useful for you, which is GPU-enabled.

**Comment by aescobed** [comment]
> But we do have `HYPRE_ParCSRMatrixGetRow` that may be useful for you, which is GPU-enabled.

Thanks, I'll use that.
