### ISSUE TITLE
HYPRE_BoomerAMGSolve generates an "INFs and/or NaNs" error

### ISSUE THREAD

**Issue by wangmin239** [hypre-space/hypre#1127]
Hi all, below text message is produced by using HYPRE_BoomerAMGSolve.
The matrix is 589940*589940, has 4141914 non-zero elements.

   
>      Num MPI tasks = 1
>     
>      Num OpenMP threads = 1
>     
>     
>     BoomerAMG SETUP PARAMETERS:
>     
>      Max levels = 25
>      Num levels = 5
>     
>      Strength Threshold = 0.250000
>      Interpolation Truncation Factor = 0.000000
>      Maximum Row Sum Threshold for Dependency Weakening = 0.900000
>     
>      Coarsening Type = HMIS
>      measures are determined locally
>     
>     
>      No global partition option chosen.
>     
>      Interpolation = extended+i interpolation
>     
>     Operator Matrix Information:
>     
>                  nonzero            entries/row          row sums
>     lev    rows  entries sparse   min  max     avg      min         max
>     ======================================================================
>       0  589940  4141914  0.000     4   19     7.0   4.685e-06   1.980e+05
>       1    1740     5734  0.002     1    7     3.3   7.206e-06   1.435e+00
>       2     386     1964  0.013     1   18     5.1   2.344e-05   6.854e-01
>       3      93      401  0.046     1    9     4.3   1.247e-04   1.342e-01
>       4       3        3  0.333     1    1     1.0   1.023e-02   7.075e-02
>     
>     
>     Interpolation Matrix Information:
>                           entries/row        min        max            row sums
>      lev   rows x cols   min  max  avgW     weight      weight       min         max
>      ==================================================================================
>       0 589940 x 1740     0    1   0.0   2.827e-01   5.856e-01   0.000e+00   1.000e+00
>       1   1740 x 386      0    4   0.4   1.798e-02   6.643e-01   0.000e+00   1.000e+00
>       2    386 x 93       0    3   0.5   7.937e-03   4.615e-01   0.000e+00   1.000e+00
>       3     93 x 3        0    1   0.0   2.419e-02   5.086e-02   0.000e+00   1.000e+00
>     
>     
>          Complexity:   grid = 1.003766
>                    operator = 1.001956
>                      memory = 1.002656
>     
>     
>     
>     
>     BoomerAMG SOLVER PARAMETERS:
>     
>       Maximum number of cycles:         1
>       Stopping Tolerance:               0.000000e+00
>       Cycle type (1 = V, 2 = W, etc.):  1
>     
>       Relaxation Parameters:
>        Visiting Grid:                     down   up  coarse
>                 Number of sweeps:            1    1     1
>        Type 0=Jac, 3=hGS, 6=hSGS, 9=GE:      6    6     9
>        Point types, partial sweeps (1=C, -1=F):
>                       Pre-CG relaxation (down):   0
>                        Post-CG relaxation (up):   0
>                                  Coarsest grid:   0
>     
>     <C*b,b>: -nan
>     
>     
>     ERROR detected by Hypre ...  BEGIN
>     ERROR -- hypre_PCGSolve: INFs and/or NaNs detected in input.
>     User probably placed non-numerics in supplied b.
>     Returning error flag += 101.  Program not terminated.
>     ERROR detected by Hypre ...  END
>   

Using GDB to debug the program, find out the code in 'hypre/src/seq_mv/vector.c:1057' accumulates the squre value of every elements in rhs.  in the case of  that the totol_size is 589940, the value of the result will reach to 470561633025073.94.
So the program report a 'NaN' error.

Unfortunately, the issue is unable to be fixed by myself.  It is greatly appriciated for any suggestions or help.

`1041 HYPRE_Real                                                                                ` 
`1042 hypre_SeqVectorInnerProdHost( hypre_Vector *x,                                            ` 
`1043                               hypre_Vector *y )                                           ` 
`1044 {                                                                                         ` 
`1045    HYPRE_Complex *x_data      = hypre_VectorData(x);                                      ` 
`1046    HYPRE_Complex *y_data      = hypre_VectorData(y);                                      ` 
`1047    HYPRE_Int      num_vectors = hypre_VectorNumVectors(x);                                ` 
`1048    HYPRE_Int      size        = hypre_VectorSize(x);                                      ` 
`1049    HYPRE_Int      total_size  = size * num_vectors;                                       ` 
`1050                                                                                           ` 
`1051    HYPRE_Real     result      = 0.0;                                                      ` 
`1052    HYPRE_Int      i;                                                                      ` 
`1053                                                                                           ` 
`1054 #if defined(HYPRE_USING_OPENMP)                                                           ` 
`1055    #pragma omp parallel for private(i) reduction(+:result) HYPRE_SMP_SCHEDULE             ` 
`1056 #endif                                                                                    ` 
`1057    for (i = 0; i < total_size; i++)                                                       ` 
`1058    {                                                                                      ` 
`1059       result += hypre_conj(y_data[i]) * x_data[i];                                        ` 
`1060    }                                                                                      ` 
`1061                                                                                           ` 
`1062    return result;                                                                         ` 
`1063 }                                                                                         ` 
`1064                                                                                           `

**Comment by victorapm** [comment]
@wangmin239 can you share your linear system as printed out via `HYPRE_IJMatrixPrint` and `HYPRE_IJVectorPrint`?

**Comment by wangmin239** [comment]
@victorapm Thanks your response, the root cause of the problem was found out. I misused the AMG algorithm.

**Comment by wangmin239** [comment]
@victorapm Thanks your response, the root cause of the problem was found out. The AMG algorithm was misused by me.
