### ISSUE TITLE
Compile hypre on AMD GPU

### ISSUE THREAD

**Issue by bssoriano** [hypre-space/hypre#1128]
I am trying to compile hypre on AMD GPU (OLCF Frontier) but the Makefile doesn't seem to find the mpi libraries. Here is how the configure command was executed: `./configure --with-hip --enable-gpu-aware-mpi --enable-rocsolver --with-MPI`. The configure step returns successfully and the checks for MPI can see the libraries: 
```
checking for MPI_Init... yes
checking for mpi.h... yes
```
However, `make install` returns the following error: `./HYPRE_utilities.h:20:10: fatal error: 'mpi.h' file not found`. It is likely that I am doing something wrong so it would be great if I could have suggestions/best practices to compile hypre on AMD GPU (OLCF Frontier).

**Comment by victorapm** [comment]
Hi Bruno,

Could you please include the following options to the configure line:

```
--with-MPI-include=${MPICH_DIR}/include --with-MPI-lib-dirs=${MPICH_DIR}/lib
```

I'm looking at removing this extra step in the build process for AMD GPUs.

**Comment by bssoriano** [comment]
Thanks Victor. It worked! 

Now I am having an issue with rocsparse: `error: undefined symbol: rocsparse_dcsrsv_buffer_size`. I noticed that rocsparse is turned on with HIP. Is this a library that should be precompiled or loaded?

**Comment by victorapm** [comment]
Great! rocsparse is distributed along with the rocm software stack and hypre should be able to find it as long as `$ROCM_PATH` is defined.

Did you have this issue when compiling hypre or when trying to link hypre to your application?

**Comment by bssoriano** [comment]
The issue is when linking hypre with my application so it seems that the problem is on my end.

**Comment by victorapm** [comment]
Ok! Make sure to add something like: `-L${ROCM_PATH}/lib -L${HYPRE_INSTALL}/lib -lHYPRE -lamdhip64 -lrocsparse -lrocblas -lrocsolver -lrocrand` to your application, besides other libraries you might need

**Comment by victorapm** [comment]
Hi Bruno, I'm closing this issue since it seems resolved. Please reach out if you have any other problems
