### ISSUE TITLE
FSAI algorithm type 3 (static) is no longer supported?

### ISSUE THREAD

**Issue by kiendangtor** [hypre-space/hypre#1130]
I was trying to use static algorithm for FSAI as shown in Hypre Documents:
HYPRE_Int HYPRE_FSAISetAlgoType(HYPRE_Solver solver, HYPRE_Int algo_type)[](https://hypre.readthedocs.io/en/latest/api-sol-parcsr.html#_CPPv421HYPRE_FSAISetAlgoType12HYPRE_Solver9HYPRE_Int)
(Optional) Sets the algorithm type used to compute the lower triangular factor G

 - 1: Adaptive (can use OpenMP with static scheduling)
 - 2: Adaptive OpenMP with dynamic scheduling
 - 3: Static - power pattern

But results was not any different than algorithm 1. When I look at the code in par_fsai_setup it may confirm that:

 switch (algo_type)
 {
    case 1:
       // TODO: Change name to hypre_FSAISetupAdaptive
       hypre_FSAISetupNative(fsai_vdata, A, f, u);
       break;

    case 2:
       // TODO: Change name to hypre_FSAISetupAdaptiveOMPDynamic
       hypre_FSAISetupOMPDyn(fsai_vdata, A, f, u);
       break;

    default:
       hypre_FSAISetupNative(fsai_vdata, A, f, u);
       break;
 }

Also there were no place that the parameters for static algorithm were used to do any calculation (threshold and max_nnz_row). Can you please confirm that or I was looking at wrong place?

Thanks,

**Comment by victorapm** [comment]
@kiendangtor I'm sorry for this issue. The static option is available only for GPUs for now. Options 1 and 2 should lead to same results while option 2 is optimized for MPI+OpenMP runs.

I will need update the documentation with the information I just shared above.

Does that answer all your questions?

**Comment by kiendangtor** [comment]
@victorapm yes. Thank you for clarification
