### ISSUE TITLE
usage of hypre_TAlloc in device code leads to lots of spurious findings of CUDA initchecker tool

### ISSUE THREAD

**Issue by horstsoft0815** [hypre-space/hypre#1134]
In almost all memory allocations on the device, the non-initializing hypre_TAlloc call is used - while in the regarding host code often hypre_CTAlloc is used, which is zero initializing.
This leads to many (most likely unimportant) findings of the CUDA toolkit initchecker tool, which is quite unpleasant when trying to find serious issues.
Even worse: I dont know whether some of these findings could be serious.

**Comment by victorapm** [comment]
Thank you for bringing this up!

Is there a particular issue you are trying to debug within hypre? If you can share a matrix and hypre options (hypre configuration and solver/preconditioner) for reproducing the issue, we can take a look

**Comment by liruipeng** [comment]
That was because there is no `calloc` for GPU so what we do is a `malloc` followed by a `memset`, which has substantial overhead compared to CPU `calloc`. So we want to use `TAlloc` if `CTAlloc` not needed. We have been careful with this to make sure that no uninitialized data was read.  It is true that CUDA checker can be confused, unfortunately.

**Comment by horstsoft0815** [comment]
Thanks for your responses :)
@victorapm: we have a rather larger software project, where HYPRE is used as a possible choice for solving linear systems. As always with big projects there is an abundance of bugs to fix, so using these tools is always helpful, at least to exclude code from my list. I shared a matrix with options to my other issue https://github.com/hypre-space/hypre/issues/1133 , maybe you find bugs there regarding the non-owning ptrs?

@liruipeng that's what I was expecting. So basically for debugging purposes I will add a memset to my local debug version.
