### ISSUE TITLE
Projection for multiple solves

### ISSUE THREAD

**Issue by kiendangtor** [hypre-space/hypre#1155]
Hi all,

I read on the manual that Hypre provide some kinds of help for getting the initial guest using projection  as described here: 
"Projection methods - For multiple solves that use the same matrix, previous solution vectors can sometimes be used to give a better initial guess for subsequent solves. Two projection schemes have been implemented in hypre - A-conjugate projection (for SPD matrices) and minimal residual projection (for both SPD and non-SPD matrices)."

I could not find any documents to show how I can use them. Lets say I have solution x0 from solving Ax0 = b0, for the second solve for Ax1 = b1. How can I provide better initial guest for x1 using hypre?

Thanks

**Comment by victorapm** [comment]
Hi @kiendangtor, the projection method feature that you referred to is part of the FEI package, which is not actively maintained by hypre anymore. However, hypre does allow the use of arbitrary initial guesses when solving linear systems. It is up to the user to decide how to compute a "good" initial guess. For a sequence of linear systems, the simplest choice is to use the previous solution as initial guess, however the efficacy of this strategy depends on your problem.

**Comment by kiendangtor** [comment]
Thanks @victorapm
