### ISSUE TITLE
Examples built with BIGINT cause MPI_ABORT

### ISSUE THREAD

**Issue by ParticleTruthSeeker** [hypre-space/hypre#1184]
I have built HYPRE with mpi 5.0.5 built with the -m64 flags however when I select BIGINT the examples fail to run. They work fine otherwise.

Any Ideas what may be causing this?
```
hypre/src/examples/ex1.c:122:43: warning: passing argument 2 of ‘HYPRE_StructGridSetExtents’ from incompatible pointer type [-Wincompatible-pointer-types]
  122 |          HYPRE_StructGridSetExtents(grid, ilower, iupper);
      |                                           ^~~~~~
      |                                           |
      |                                           int *

```

Cheers

This may be a function of these specific examples.

**Comment by victorapm** [comment]
@ParticleTruthSeeker when compiling hypre with `--enable-bigint`, the only example codes available are `ex5big` and `ex15big`. You can build them by running `make bigint` from the `examples` folder if using the autotools build.  You might want to look at `--enable-mixedint` as well (mixed 32/64-bit integers support), which works with all example drivers

**Comment by ParticleTruthSeeker** [comment]
> @ParticleTruthSeeker when compiling hypre with `--enable-bigint`, the only example codes available are `ex5big` and `ex15big`. You can build them by running `make bigint` from the `examples` folder if using the autotools build. You might want to look at `--enable-mixedint` as well (mixed 32/64-bit integers support), which works with all example drivers

Thank you for the explanation. I assumed it to be so given some examples running successfully.
