### ISSUE TITLE
Problem with building Hypre with Sycl (Are Intel CPUs using Sycl supported?)

### ISSUE THREAD

**Issue by lprc** [hypre-space/hypre#1191]
I just tried to build Hypre with Sycl support, but unfortunately, it does not compile.

I tried the following configure command `.configure --with-sycl --disable-fortran`, which gives the following output:

<details>
<summary>Output of configure</summary>
<pre><code>
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for mpxlc... no
checking for mpixlc... no
checking for mpiicx... mpiicx
checking for CC... no
checking for mpxlC... no
checking for mpixlcxx... no
checking for mpixlC... no
checking for mpiicpx... mpiicpx
checking for icpx... icpx
checking whether make sets $(MAKE)... yes
checking for ranlib... ranlib
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether mpiicx accepts -g... no
checking for mpiicx option to enable C11 features... none needed
checking whether the compiler supports GNU C++... yes
checking whether mpiicpx accepts -g... no
checking for mpiicpx option to enable C++11 features... none needed
checking for MPI_Init... yes
checking for mpi.h... yes
checking for MPI_Comm_f2c... no
checking how to run the C preprocessor... mpiicx -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether MPI_Comm_f2c is a macro... yes
checking for cabs in -lm... yes
checking for /opt/intel/oneapi/mkl/2025.0/include/mkl.h... yes
configure: ***********************************************************
configure: Configuring with --with-sycl=yes without unified memory.
configure: It only works for struct interface.
configure: Use --enable-unified-memory to compile with unified memory.
configure: ***********************************************************
checking the hostname... mx-precision-5550
checking the architecture... LINUX
configure: creating ./config.status
config.status: creating config/Makefile.config
config.status: creating HYPRE_config.h
</pre></code>
</details>

And started the build process using `make` with the following output:

<details>
<summary>Output of make</summary>
<pre><code>
make[1]: Verzeichnis „/home/simon/tmp/hypre/src/utilities“ wird betreten
icpx  -O3 -fsycl -fsycl-unnamed-lambda  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -qmkl -I/include -DMKL_ILP64 -I/opt/intel/oneapi/mkl/2025.0/include        -c general.c -o general.obj
icpx: warning: treating 'c' input as 'c++' when -fsycl is used [-Wexpected-file-type]
In file included from general.c:8:
In file included from ./_hypre_utilities.h:648:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/stl_wrappers/assert.h:20:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:27:
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_types.hpp:135:1: error: templates must have C++ linkage
  135 | template <typename T, std::size_t R, std::size_t C, MatrixLayout L,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  136 |           Scope::Flag S = Scope::Flag::Subgroup,
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  137 |           MatrixUse U = MatrixUse::MatrixA>
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./_hypre_utilities.h:14:1: note: extern "C" language linkage specification begins here
   14 | extern "C" {
      | ^
In file included from general.c:8:
In file included from ./_hypre_utilities.h:648:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/stl_wrappers/assert.h:20:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:27:
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_types.hpp:144:1: error: templates must have C++ linkage
  144 | template <typename dataT>
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
./_hypre_utilities.h:14:1: note: extern "C" language linkage specification begins here
   14 | extern "C" {
      | ^
In file included from general.c:8:
In file included from ./_hypre_utilities.h:648:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/stl_wrappers/assert.h:20:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:27:
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_types.hpp:146:1: error: templates must have C++ linkage
  146 | template <typename dataT>
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
./_hypre_utilities.h:14:1: note: extern "C" language linkage specification begins here
   14 | extern "C" {
      | ^
In file included from general.c:8:
In file included from ./_hypre_utilities.h:648:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/stl_wrappers/assert.h:20:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:27:
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_types.hpp:150:1: error: templates must have C++ linkage
  150 | template <typename dataT, int dims>
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./_hypre_utilities.h:14:1: note: extern "C" language linkage specification begins here
   14 | extern "C" {
      | ^
In file included from general.c:8:
In file included from ./_hypre_utilities.h:648:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/stl_wrappers/assert.h:20:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:27:
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_types.hpp:165:1: error: templates must have C++ linkage
  165 | template <int Bits> using ap_int = _BitInt(Bits);
      | ^~~~~~~~~~~~~~~~~~~
./_hypre_utilities.h:14:1: note: extern "C" language linkage specification begins here
   14 | extern "C" {
      | ^
In file included from general.c:8:
In file included from ./_hypre_utilities.h:648:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/stl_wrappers/assert.h:20:
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:88:24: error: no template named '__ocl_vec_t'
   88 | __SPIRV_VAR_QUALIFIERS __ocl_vec_t<uint32_t, 4> __spirv_BuiltInSubgroupEqMask;
      |                        ^
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:89:24: error: no template named '__ocl_vec_t'
   89 | __SPIRV_VAR_QUALIFIERS __ocl_vec_t<uint32_t, 4> __spirv_BuiltInSubgroupGeMask;
      |                        ^
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:90:24: error: no template named '__ocl_vec_t'
   90 | __SPIRV_VAR_QUALIFIERS __ocl_vec_t<uint32_t, 4> __spirv_BuiltInSubgroupGtMask;
      |                        ^
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:91:24: error: no template named '__ocl_vec_t'
   91 | __SPIRV_VAR_QUALIFIERS __ocl_vec_t<uint32_t, 4> __spirv_BuiltInSubgroupLeMask;
      |                        ^
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:92:24: error: no template named '__ocl_vec_t'
   92 | __SPIRV_VAR_QUALIFIERS __ocl_vec_t<uint32_t, 4> __spirv_BuiltInSubgroupLtMask;
      |                        ^
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:216:1: error: templates must have C++ linkage
  216 | __SPIRV_DEFINE_INIT_AND_GET_HELPERS(GlobalSize);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:191:3: note: expanded from macro '__SPIRV_DEFINE_INIT_AND_GET_HELPERS'
  191 |   template <int ID> static size_t get##POSTFIX();                              \
      |   ^~~~~~~~~~~~~~~~~
./_hypre_utilities.h:14:1: note: extern "C" language linkage specification begins here
   14 | extern "C" {
      | ^
In file included from general.c:8:
In file included from ./_hypre_utilities.h:648:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/stl_wrappers/assert.h:20:
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:216:1: error: templates must have C++ linkage
  216 | __SPIRV_DEFINE_INIT_AND_GET_HELPERS(GlobalSize);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:192:3: note: expanded from macro '__SPIRV_DEFINE_INIT_AND_GET_HELPERS'
  192 |   template <> size_t get##POSTFIX<0>() { return __spirv_##POSTFIX##_x(); }     \
      |   ^~~~~~~~~~~
./_hypre_utilities.h:14:1: note: extern "C" language linkage specification begins here
   14 | extern "C" {
      | ^
In file included from general.c:8:
In file included from ./_hypre_utilities.h:648:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/stl_wrappers/assert.h:20:
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:216:1: error: extraneous 'template<>' in declaration of variable 'getGlobalSize'
  216 | __SPIRV_DEFINE_INIT_AND_GET_HELPERS(GlobalSize);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:193:3: note: expanded from macro '__SPIRV_DEFINE_INIT_AND_GET_HELPERS'
  193 |   template <> size_t get##POSTFIX<1>() { return __spirv_##POSTFIX##_y(); }     \
      |   ^~~~~~~~~~~
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:216:1: error: redefinition of 'getGlobalSize' as different kind of symbol
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:193:22: note: expanded from macro '__SPIRV_DEFINE_INIT_AND_GET_HELPERS'
  193 |   template <> size_t get##POSTFIX<1>() { return __spirv_##POSTFIX##_y(); }     \
      |                      ^
<scratch space>:338:1: note: expanded from here
  338 | getGlobalSize
      | ^
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:216:1: note: previous definition is here
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:192:22: note: expanded from macro '__SPIRV_DEFINE_INIT_AND_GET_HELPERS'
  192 |   template <> size_t get##POSTFIX<0>() { return __spirv_##POSTFIX##_x(); }     \
      |                      ^
<scratch space>:335:1: note: expanded from here
  335 | getGlobalSize
      | ^
In file included from general.c:8:
In file included from ./_hypre_utilities.h:648:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/stl_wrappers/assert.h:20:
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:216:1: error: expected ';' after top level declarator
  216 | __SPIRV_DEFINE_INIT_AND_GET_HELPERS(GlobalSize);
      | ^
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:193:34: note: expanded from macro '__SPIRV_DEFINE_INIT_AND_GET_HELPERS'
  193 |   template <> size_t get##POSTFIX<1>() { return __spirv_##POSTFIX##_y(); }     \
      |                                  ^
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:216:1: error: extraneous 'template<>' in declaration of variable 'getGlobalSize'
  216 | __SPIRV_DEFINE_INIT_AND_GET_HELPERS(GlobalSize);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:194:3: note: expanded from macro '__SPIRV_DEFINE_INIT_AND_GET_HELPERS'
  194 |   template <> size_t get##POSTFIX<2>() { return __spirv_##POSTFIX##_z(); }     \
      |   ^~~~~~~~~~~
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:216:1: error: redefinition of 'getGlobalSize'
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:194:22: note: expanded from macro '__SPIRV_DEFINE_INIT_AND_GET_HELPERS'
  194 |   template <> size_t get##POSTFIX<2>() { return __spirv_##POSTFIX##_z(); }     \
      |                      ^
<scratch space>:341:1: note: expanded from here
  341 | getGlobalSize
      | ^
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:216:1: note: previous definition is here
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:193:22: note: expanded from macro '__SPIRV_DEFINE_INIT_AND_GET_HELPERS'
  193 |   template <> size_t get##POSTFIX<1>() { return __spirv_##POSTFIX##_y(); }     \
      |                      ^
<scratch space>:338:1: note: expanded from here
  338 | getGlobalSize
      | ^
In file included from general.c:8:
In file included from ./_hypre_utilities.h:648:
In file included from /opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/stl_wrappers/assert.h:20:
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:216:1: error: expected ';' after top level declarator
  216 | __SPIRV_DEFINE_INIT_AND_GET_HELPERS(GlobalSize);
      | ^
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:194:34: note: expanded from macro '__SPIRV_DEFINE_INIT_AND_GET_HELPERS'
  194 |   template <> size_t get##POSTFIX<2>() { return __spirv_##POSTFIX##_z(); }     \
      |                                  ^
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:216:1: error: templates must have C++ linkage
  216 | __SPIRV_DEFINE_INIT_AND_GET_HELPERS(GlobalSize);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/intel/oneapi/compiler/2025.0/bin/compiler/../../include/sycl/CL/__spirv/spirv_vars.hpp:196:3: note: expanded from macro '__SPIRV_DEFINE_INIT_AND_GET_HELPERS'
  196 |   template <int Dim, class DstT> struct InitSizesST##POSTFIX;                  \
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./_hypre_utilities.h:14:1: note: extern "C" language linkage specification begins here
   14 | extern "C" {
      | ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [../config/Makefile.config:66: general.obj] Fehler 1
make[1]: Verzeichnis „/home/simon/tmp/hypre/src/utilities“ wird verlassen
make: *** [Makefile:91: all] Fehler 1
</pre></code>
</details>

Running clinfo shows that I have the backend for an Intel CPU installed:

```
Platform #0: Intel(R) OpenCL
 `-- Device #0: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
```

I guess when using Sycl, targeting an Intel ~~GPU~~ CPU should work, right? Or is it really only Intel GPUs?

If it should work, do you have an idea what's going wrong here? Compiling some examples from [the oneapi examples repo](https://github.com/oneapi-src/oneAPI-samples/tree/master/DirectProgramming/C%2B%2BSYCL/DenseLinearAlgebra/vector-add) works.

Thank you in advance.

**Comment by waynemitchell** [comment]
I've not seen this particular issue when compiling with sycl. I notice from your `make` output that the included `assert.h` is grabbing a header file from `sycl/stl_wrappers`, which I don't seem to have on the Intel systems that I'm running on. The error seems to indicate that this `assert.h` implementation is including some C++ templating stuff under the hood, but we have this included inside an extern C block. You could try wrapping `#include <assert.h>` statement with an extern C++ block and see if that fixes the issue.

I would expect you to be able to compile the code with sycl if you have oneAPI available, but if you have no GPU available, I'm not sure the code will run. The purpose of the sycl backend is really to target Intel GPUs. You can see that we explicitly look for a GPU device for the sycl code to run on:
https://github.com/hypre-space/hypre/blob/master/src/utilities/general.c#L102
I think that modifying the code to run on CPU would be very straightforward (in fact I have some debugging functionality implemented in the code that allows running sycl calls on the host CPU).

**Comment by lprc** [comment]
Thanks for your quick response and your insights!

You mean I can try wrapping `#include <assert.h>` of the file `src/utilities/_hypre_utilities.h` in an extern C++ block, like so?

```C
extern "C" {
#include <assert.h>
}
``` 

If I do that, the compiler errors with the following message:

```
mpiicx -O2  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -qmkl -I/include -DMKL_ILP64 -I/opt/intel/oneapi/mkl/2025.0/include        -c F90_HYPRE_error.c
In file included from F90_HYPRE_error.c:8:
./_hypre_utilities.h:697:8: error: expected identifier or '('
  697 | extern "C" {
      |        ^
1 error generated.
make: *** [../config/Makefile.config:54: F90_HYPRE_error.o] Fehler 1
``` 

[Here](https://stackoverflow.com/a/16192947/4108363) I learned that extern "C" or extern "C++" is C++-specific, so the C compiler does not understand it.

> I notice from your make output that the included assert.h is grabbing a header file from sycl/stl_wrappers, which I don't seem to have on the Intel systems that I'm running on.

I saw [here](https://github.com/hypre-space/hypre/wiki/Requirements), that Hypre with Sycl was tested only for oneapi 2024, so I tested that version using a Docker image. It indeed compiles fine (without adding external C++), so there must be some change in the 2025 version, that breaks it (probably the templating stuff you mentioned).

I'll see if I can also compile and run some examples (on the Intel CPU) and will ping back again. If that does not work and I have the time, I'll try to install the backend for the integrated Intel GPU (I did before but it messed with my system... Maybe I can do it in a container).

**Comment by lprc** [comment]
Compiling the examples work, but as you've guessed, running them does not work.

I couldn't manage to install the backend for the integrated GPU in a reasonable time either. `sycl-ls` only shows the Intel CPU and FPGA emulation device.

However, I'll close this issue for now, as apparently it's a problem with oneapi (v2025.0.0) and not with hypre.
