### ISSUE TITLE
Unable to find reachable pairing between local and remote interfaces

### ISSUE THREAD

**Issue by sanvila** [hypre-space/hypre#1194]
Hello. As reported in Debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1087784

On AWS machines of different types, we noticed that the test suite outputs lots of messages like this:

`[the-hostname][[59479,1],7][../../../../../../opal/mca/btl/tcp/btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces`

As a workaround, we have added two lines to the list of "misleading error messages":

https://salsa.debian.org/science-team/hypre/-/commit/41ec7a9da9336f755df4c0a7ceee332ad8b851ad

Unfortunately, this does not seem to be enough. The build fails randomly. Sometimes with a message like this:
```
FAILED : TEST_ij/solvers.err  (4)

h]
```
and sometimes with a message like this:
```
FAILED : TEST_ij/solvers.err  (129)

[the-hostname][[20559,1],4][../../../../../../opal/mca/btl/tcp/btl_tcp_proc.c:266:mca_btl_tcp_pr
oc_create_interface_grap
```
Note the missing `h]` at the end, apparently the messages are cut in pieces, which makes filtering with egrep not to be effective.

Ideally, we would like those messages not to be shown, or at least have an effective way to disable them.

Thanks.

**Comment by victorapm** [comment]
Thanks for reporting! This seem related to OpenMPI, are there other packages depending on OpenMPI showing this issue?

**Comment by sanvila** [comment]
Good question! I can actually see such messages in the build logs for the following Debian source packages:

```
dolfin
lammps
liggghts
mpi4py
mumps
opm-grid
opm-simulators
petsc
scalapack
superlu-dist
```
but in none of those cases the warnings make the tests to fail. Maybe hypre could look at the outcome of the tests themselves and ignore the warnings. I don't know.

Thanks.

**Comment by sanvila** [comment]
Hi. I managed the messages not to be shown by doing this:

`export OMPI_MCA_btl_tcp_if_include=lo
`

Because each Debian package is always built on a single machine (not in an OpenMPI network of several machines), this fits well in `debian/rules` (the Makefile which controls how the package is built) for the built-in tests which are part of the build.

At this point, I don't know if this could still be considered a bug in hypre or not, so please do what you consider appropriate.

Thanks a lot.

Edit: The error comes from `opal/mca/btl/tcp/btl_tcp_proc.c` in the openmpi source code:

```
if (0 == num_edges) {
    BTL_ERROR(("Unable to find reachable pairing between local and remote interfaces"));
    rc = OPAL_ERR_UNREACH;
}
```

**Comment by victorapm** [comment]
Hi @sanvila, thanks for the looking into this! Since the issue comes from OpenMPI, I'm closing this for now. Thanks!
