### ISSUE TITLE
Cuda compute capability requirements?

### ISSUE THREAD

**Issue by stefanozampini** [hypre-space/hypre#125]
I could not find any documentation about the current compute capability requirements of the 2.19 version. It seems sm_37 is not supported, by judging from the below compilation error. We are trying to finally integrate HYPRE GPU capabilities into PETSc. (A comment aside: it is not clear to me if BoomerAMG solve phase will still perform on the GPU when cuda-unified-memory is not used)
Thanks

Making seq_mv ...
make[1]: Entering directory '/home/zampins/hypre/src/seq_mv'
nvcc -O2 -lineinfo -ccbin=mpicxx -gencode arch=compute_37,"code=sm_37" -expt-extended-lambda -dc -std=c++11 --x cu -Xcompiler "-fstack-protector -g3 -O2 -fPIC " -Xcompiler "-fPIC" -DHAVE_CONFIG_H -I.. -I. -I./.. -I./../utilities -I/opt/ecrc/cuda/10.2/include   -c csr_spgemm_device_attempt.c 
csr_spgemm_device_attempt.c(52): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (HYPRE_Complex *, HYPRE_Complex)
          detected during:
            instantiation of "HYPRE_Int csr_spmm_compute_row_attempt<attempt,HashType>(HYPRE_Int, HYPRE_Int, HYPRE_Int *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int, volatile HYPRE_Int *, volatile HYPRE_Complex *, HYPRE_Int, HYPRE_Int *, HYPRE_Complex *, char &, volatile char *) [with attempt=1, HashType='L']" 
(251): here
            instantiation of "void csr_spmm_attempt<NUM_WARPS_PER_BLOCK,SHMEM_HASH_SIZE,attempt,HashType>(HYPRE_Int, HYPRE_Int *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int *, HYPRE_Int *) [with NUM_WARPS_PER_BLOCK=20, SHMEM_HASH_SIZE=128, attempt=1, HashType='L']" 
(463): here

csr_spgemm_device_attempt.c(62): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (HYPRE_Complex *, HYPRE_Complex)
          detected during:
            instantiation of "HYPRE_Int csr_spmm_compute_row_attempt<attempt,HashType>(HYPRE_Int, HYPRE_Int, HYPRE_Int *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int, volatile HYPRE_Int *, volatile HYPRE_Complex *, HYPRE_Int, HYPRE_Int *, HYPRE_Complex *, char &, volatile char *) [with attempt=1, HashType='L']" 
(251): here
            instantiation of "void csr_spmm_attempt<NUM_WARPS_PER_BLOCK,SHMEM_HASH_SIZE,attempt,HashType>(HYPRE_Int, HYPRE_Int *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int *, HYPRE_Int *, HYPRE_Complex *, HYPRE_Int *, HYPRE_Int *) [with NUM_WARPS_PER_BLOCK=20, SHMEM_HASH_SIZE=128, attempt=1, HashType='L']" 
(463): here

2 errors detected in the compilation of "/tmp/tmpxft_000018a4_00000000-6_csr_spgemm_device_attempt.cpp1.ii".
../config/Makefile.config:42: recipe for target 'csr_spgemm_device_attempt.o' failed
make[1]: *** [csr_spgemm_device_attempt.o] Error 1
make[1]: Leaving directory '/home/zampins/hypre/src/seq_mv'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by liruipeng** [comment]
@stefanozampini We generally suggest sm >= 60. Can you please checkout branch `RL-FIX` (https://github.com/hypre-space/hypre/tree/RL_FIX) and see if it compiles with `sm_37`? I don't have a sm_37 GPU at hand. Can you please test if it can run? Thanks!

**Comment by stefanozampini** [comment]
The code compiles fine now. thanks

**Comment by liruipeng** [comment]
@stefanozampini  Great! Have you tried to run some test on sm_37 GPUs?
