### ISSUE TITLE
hypre_IJMatrixSetValuesParCSR bug?

### ISSUE THREAD

**Issue by bobby-philip** [hypre-space/hypre#13]
Hi:

There might be a bug around line 1032 of IJMatrix_parcscr.c. If it's a bug the same bug exists in the release version also.         
           
                    if (not_found)
                     {
                        if (cnt_diag < diag_space)
                        {
                           diag_j[cnt_diag] = col_j;
                           diag_data[cnt_diag++] = values[indx];
                        }
                        else
                        {
                           hypre_error(HYPRE_ERROR_GENERIC);
                           if (print_level)
                           {
                              hypre_printf("Error in row %b ! Too many elements !\n",
                                           row);
                           }
                           /* return 1; */
                           return hypre_error_flag;
                        }
                     }

col_j is not initialized for this if condition. I believe line 1032 should be 
diag_j[cnt_diag] = (HYPRE_Int)(cols[indx]-col_0);

**Comment by ulrikeyang** [comment]
Col_j should be defined in the loop before in line 1020. Did you run into a situation where it didn’t go through that loop?

**Comment by bobby-philip** [comment]
Yes I did. It seems to skip that loop for me.

**Comment by ulrikeyang** [comment]
If you move the assignment out and before the loop will it work for you?

**Comment by bobby-philip** [comment]
It would, but wouldn't it introduce a bug for the loop? I just modified it as shown. As an aside the OMP version explicitly assigns.

**Comment by bobby-philip** [comment]
Hi guys, just wanted to ask if you had a chance to look at this and the related bug that the PETSc folks were seeing. 

Also, as I had mentioned when we last talked we are seeing a OOM memory when running BiCGSTAB with BoomerAMG. Let me know if I need to file a separate issue for that.

**Comment by ulrikeyang** [comment]
I believe the PETSc folk's issue was connected to our mixed-int changes and caused by them using hypre under the hood. They have fixed their issues and it's working for them now. 
The change I gave you won't cause a bug for the loop because the loop does not affect col. 
Can you tell me more about the OOM issue?
Thanks

**Comment by bobby-philip** [comment]
This appears to be fixed in 2.18.1
