### ISSUE TITLE
IJ interface in Hypre

### ISSUE THREAD

**Issue by siamak1984** [hypre-space/hypre#131]
Hi, 

I'm trying to link my code, which is written in Fortran, with HYPRE. The code itself is serial, and I intend to parallelize the linear system solves. The code is successfully linked with HYPRE. However, the solution to the linear system is incorrect (even with one processor). 

I think the problem is coming from the part of code that I define my matrix. I've tried to follow the test4f.f from examples folder to build the IJ interface. I have read the manual but still have not understood it fully.

What I'm currently doing is using "HYPRE_IJMatrixSetValues" to set non-zero values at each row of the matrix. Something like the following loop:

k=0
       do i = ilower,iupper
         nnz=ia(i+2)-ia(i+1)
         values(1:nnz)=a(k+1:k+nnz)
         cols(1:nnz)=ja(k+1:k+nnz)-1
         k=k+nnz
         call HYPRE_IJMatrixSetValues(A,1,nnz,i,cols,values,ierr)
       enddo

Your guidance on this would be very much appreciated. 

All the best
Siamak

**Comment by victorapm** [comment]
Hi @siamak1984,

the code snippet seems correct. Have you tried to print matrix A to a file and check if the entries are as you expected? You can do this with a call to [HYPRE_IJMatrixPrint](https://hypre.readthedocs.io/en/latest/api-int-ij.html?highlight=HYPRE_IJMatrixPrint#_CPPv419HYPRE_IJMatrixPrint14HYPRE_IJMatrixPKc) after you have assembled the matrix.

Best,
Victor

**Comment by liruipeng** [comment]
> Hi,
> 
> I'm trying to link my code, which is written in Fortran, with HYPRE. The code itself is serial, and I intend to parallelize the linear system solves. The code is successfully linked with HYPRE. However, the solution to the linear system is incorrect (even with one processor).
> 
> I think the problem is coming from the part of code that I define my matrix. I've tried to follow the test4f.f from examples folder to build the IJ interface. I have read the manual but still have not understood it fully.
> 
> What I'm currently doing is using "HYPRE_IJMatrixSetValues" to set non-zero values at each row of the matrix. Something like the following loop:
> 
> k=0
> do i = ilower,iupper
> nnz=ia(i+2)-ia(i+1)
> values(1:nnz)=a(k+1:k+nnz)
> cols(1:nnz)=ja(k+1:k+nnz)-1
> k=k+nnz
> call HYPRE_IJMatrixSetValues(A,1,nnz,i,cols,values,ierr)
> enddo
> 
> Your guidance on this would be very much appreciated.
> 
> All the best
> Siamak

Make sure `cols` contains the global column indices. You may not pass by value: don't give `1` but declare a variable `one=1` and give `one` instead.

**Comment by siamak1984** [comment]
Hi,

Thank you both for the comments.

The matrix and vector printing helped to see where the problem is coming from. The values were not correct for rhs.  

All the best
Siamak
