### ISSUE TITLE
Small optimization in hypre_CSRMatrixBigJtoJ()

### ISSUE THREAD

**Issue by v-dobrev** [hypre-space/hypre#132]
In the following code:
https://github.com/hypre-space/hypre/blob/3d1a441674c06aa7fd29ed1136dc06eecb888fac/src/seq_mv/csr_matrix.c#L178-L185

it seems that the re-allocation and copy are unnecessary when `HYPRE_Int` and `HYPRE_BigInt` are the same -- one can just move the pointer.

**Comment by liruipeng** [comment]
@v-dobrev Good point! Will fix it and have it in master soon and in the next release. Thanks!

**Comment by liruipeng** [comment]
This issue seems to have been resolved.
