### ISSUE TITLE
Is there a reason to keep so version as 2.8.2?

### ISSUE THREAD

**Issue by andrecbarros** [hypre-space/hypre#137]
On subdir src/config, there is Makefile.config.in file with sover hard set as 2.8.2. Because of this, on linux, the dynamic library generated is libHYPRE.so.2.8.2. It, doesn't seem to be coherent with the source version.

Perhaps, shouldn't the library version be guessed from a file on source root dir, like it is done on some other projects?

**Comment by rfalgout** [comment]
I don't see the problem you are talking about.  See:

  https://github.com/hypre-space/hypre/blob/master/src/config/Makefile.config.in

Can you clarify?  Thanks!

**Comment by andrecbarros** [comment]
Sorry, the problem had its origin on a script I used to build it automatically.
