### ISSUE TITLE
Calling AIR through petsc

### ISSUE THREAD

**Issue by tangqi** [hypre-space/hypre#139]
Hi,

Is it possible to call AIR through Petsc now? I have an application implemented in MFEM. I use SNES as my nonlinear solver coupled with my own preconditioner (through petsc's shell interface). The preconditioner contains inversions of a few matrices for which I call hypre as my preconditioner. One of the small matrices can be dominated by the convection term as time evolves. This becomes problematic since boomeramg can be very inefficient. So that motivates me to try AIR through petsc. Therefore, I am wondering if there is any update on porting it into petsc. 

An alternative approach I can think of would be building another shell preconditioner back to mfem so that I call AIR directly there, but it seems unnecessary as I expect there may be a better solution here. So please let me know if you have any suggestions. 

Thanks,
Qi

**Comment by jthano** [comment]
i am not a member of the hypre team, but I did create a PETSc interface for AIR so that I could use it in MOOSE. I will work to get my PETSc interface merged into the main PETSc repo shortly

**Comment by tangqi** [comment]
Awesome! I will be very interested to try it out as soon as you commit the change. Please keep me posted. -Qi
