### ISSUE TITLE
Making in path with whitespace fails under macOS

### ISSUE THREAD

**Issue by FelixKratz** [hypre-space/hypre#140]
If the directory where hypre is cloned contains whitespaces an error occurs because 
the targets of the copy commands are not escaped properly.

`Making utilities ...
cp -fR ./HYPRE_*.h /.../folder with white spaces/hypre/src/hypre/include
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
make[1]: *** [all] Error 64
make: *** [all] Error 1
`

**Comment by rfalgout** [comment]
I don't think this is something we ever supported.  Can you try cmake instead?  Another option is to create a soft link (that doesn't have whitespace in it) to the directory that has the whitespace in its path, and use that instead.

**Comment by FelixKratz** [comment]
The soft link trick works just fine, thanks.
