### ISSUE TITLE
New Parallel ILU

### ISSUE THREAD

**Issue by jehicken** [hypre-space/hypre#146]
Hi,

I am very interested in the new parallel ILU preconditioner.  Thank you for implementing this!

I was wondering where I could find more information, both about the implementation and the algorithm(s) (Is it related to this [paper](https://doi.org/10.1137/S1064827597328996) by any chance?).  I read the `readthedocs` documentation, but it directs me to the [reference manual](https://computing.llnl.gov/sites/default/files/public/hypre-2.11.2_ref_manual.pdf) which appears to be out of date, at least as far as the ILU solver is concerned.

If there is no online or pdf documentation yet, I would appreciate it if you could briefly answer the following questions:

- Which of the parallel version of ILU would you recommend for Newton-Krylov, where the Schur complement does not need to be solved as accurately?
- I see some arrays in the code that suggest that row and column reordering is possible.  How can I choose different reordering schemes?
- Is there a block-based version available, or scalar only?  If there is only a scalar version, is it possible to reorder based on sets of variables in a PDE system?  (e.g. keep the variables at a FEM node together)

Thanks in advance.

**Comment by oseikuffuor1** [comment]
Hi Jason,
Thanks for your interest. The new parallel ILU preconditioner follows a two-level domain decomposition strategy similar to the paper you referenced. Local factorizations are done on the diagonal (local) blocks, and an approximate Schur complement strategy is used to account for the global coupling between the processors. We have implemented multiple strategies for this global solve. The reference manual information can be found in here: https://hypre.readthedocs.io/en/latest/api-sol-parcsr.html . Just search for "HYPRE_ILU". I agree the documentation is pretty thin on details, and we will be updating it to provide more information soon. In the mean time, to answer your questions:

1. The choice for Newton-Krylov will depend on the type of problem being solved. Without knowing anymore information about the type of problem being solved, and the fact that you are considering an ILU preconditioner, I am assuming AMG is not ideal here? In this case, I would recommend trying a block Jacobi preconditioner with ILUk (see HYPRE_ILUSetType(...) with ilu_type=0). You may also try ilu_type=10 or ilu_type=30 for GMRES or restricted additive Schwarz respectively. These are more robust than block Jacobi.

2. We support local RCM reordering. This is done by default, but you can turn this off. See HYPRE_ILUSetLocalReordering(...).

3. The current implementation is only a scalar ILU. We do not support reordering by the unknowns, however the user is free to provide the system matrix in whichever ordering. Nonetheless, the factorization will still treat it as a scalar matrix. If you are interested in dealing with different physical variables at a node (with perhaps different preconditioners), then you can take a look at the multigrid reduction (MGR) solver in hypre.

Hope this is helpful.
-Daniel

**Comment by jehicken** [comment]
Hi Daniel,

Thank you for the quick response to my questions.

- Sorry I missed the online API documentation, which answers many of my questions.
- We're solving steady, high Reynolds number CFD problems, for which AMG is definitely not ideal.  I have experience implementing an approximate Schur ILU preconditioner for my phd (based on the paper I referenced), and I found that preconditioner worked well for these applications (hence my interest in Hypre's ILU).
- We will try RCM, or see if it is possible to change the ordering on mfem's end.  Unfortunately, the stability of the ILU factorization for these types of CFD problems is highly sensitive to the ordering.

Thanks again,
Jason

**Comment by oseikuffuor1** [comment]
Hi Jason, If you are interested in the ILUT variants of the ilu_type options I gave you earlier, then simply replace '0' with '1' to get the ILUT variants. There are two other options that I did not mention earlier. But for completeness, we also have ilu_type options 20/21 for Newton-Schultz-Hotelling (NSH) with iluk and ilut respectively; and 40/41 for GMRES with ddPQ ordering and iluk/ilut respectively. The NSH algorithm is an approximate inverse algorithm, and the ddPQ strategy implements a nonsymmetric ordering based on diagonal dominance.

Again the RCM ordering done here is local, and typically leads to better convergence. If stability becomes an issue, then perhaps a global reordering prior to the factorization may help. RCM typically does fine, but you might also consider the ddPQ option.

Let us know if you have any additional questions.
-Daniel

**Comment by jehicken** [comment]
Hi Daniel,
Thank you for the additional information.  Is there some literature you can recommend for NSH and ddPQ?  Also, if we end up using Hypre's new parallel ILU preconditioner, are there specific papers you would prefer we cite?
-Jason
