### ISSUE TITLE
toward integrating HYPRE GPU into PETSc

### ISSUE THREAD

**Issue by stefanozampini** [hypre-space/hypre#151]
I'm opening this issue to keep track of the status of integrating HYPRE GPU capabilities from PETSc.
Following Ruipeng's advice via personal email, I have checked out the latest master branch and configure HYPRE

```
./configure --prefix=/home/zampins/Devel/hypre/myinstall CC=mpicc CFLAGS='-fPIC -fstack-protector -g3 -O2' CXX=mpicxx CXXFLAGS='-fstack-protector -g3 -O2 -fPIC' F90=mpif90 F90FLAGS='-fPIC -ffree-line-length-0 -g3 -O2' FFLAGS='-fPIC -ffree-line-length-0 -g3 -O2' FC=mpif90 F77=mpif90 FCFLAGS='-fPIC -ffree-line-length-0 -g3 -O2' --enable-shared --with-MPI-lib-dirs= --with-MPI-libs= --with-blas-lib='-Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/mkl/lib/intel64 -L/opt/ecrc/intel/2018/compilers_and_libraries/linux/mkl/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_gnu_thread -lgomp -ldl -lpthread -lm' --with-lapack-lib=  --with-blas=no --with-lapack=no --with-fmangle-blas=one-underscore --with-fmangle-lapack=one-underscore --without-mli --without-superlu --with-cuda CUDA_HOME=/opt/ecrc/cuda/10.2 --enable-unified-memory HYPRE_CUDA_SM=70
```

It seems compilation is broken, since SHARED_COMPILE_FLAG is used (instead of SHARED_BUILD_FLAG) is used to compile C code?

```
zampins@vulture:~/Devel/hypre/src$ make -j1
Making blas ...
make[1]: Entering directory '/home/zampins/Devel/hypre/src/blas'
mpicc -fstack-protector -g3 -O2 -fPIC  -Xcompiler "-fPIC" -DHAVE_CONFIG_H -I/opt/ecrc/cuda/10.2/include  -I.. -I../utilities -c dasum.c
gcc-5: error: unrecognized command line option ‘-Xcompiler’
../config/Makefile.config:54: recipe for target 'dasum.o' failed
make[1]: *** [dasum.o] Error 1
make[1]: Leaving directory '/home/zampins/Devel/hypre/src/blas'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by stefanozampini** [comment]
Yet another issue

```
nvcc fatal   : Unknown option '-Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/mkl/lib/intel64'
Makefile:101: recipe for target 'libHYPRE.so' failed
make[1]: *** [libHYPRE.so] Error 1
make[1]: Leaving directory '/home/zampins/Devel/hypre/src/lib'
Makefile:86: recipe for target 'all' failed
```

Do you really need `nvcc` to link the final libHYPRE.so?

**Comment by liruipeng** [comment]
> Yet another issue
> 
> ```
> nvcc fatal   : Unknown option '-Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/mkl/lib/intel64'
> Makefile:101: recipe for target 'libHYPRE.so' failed
> make[1]: *** [libHYPRE.so] Error 1
> make[1]: Leaving directory '/home/zampins/Devel/hypre/src/lib'
> Makefile:86: recipe for target 'all' failed
> ```
> 
> Do you really need `nvcc` to link the final libHYPRE.so?

@stefanozampini
It seems that linking with host linker needs a two pass compile (see https://stackoverflow.com/questions/17278932/cuda-shared-library-linking-undefined-reference-to-cudaregisterlinkedbinary). I am not an expert on this, so we just use `nvcc` to link. Do you have ideas on it? We would like to change to host linker but the two-pass approach seems too complicated. Thanks!

**Comment by stefanozampini** [comment]
I always thought that resolving symbols from the various cuda libraries was enough.

**Comment by stefanozampini** [comment]
@liruipeng Can you please summarize the various options that HYPRE currently has to run on GPU? Is there up-to-date documentation I can read?

We are deciding (cc  @BarrySmith) on how to best access the HYPRE solvers on GPU from PETSc. Is unified memory mandatory or not? Are there alternatives for HYPRE supporting the "copy-to-GPU-when-needed" approach?
We can chat separately if you think it is better.

**Comment by stefanozampini** [comment]
@liruipeng FYI here is the makefile rules details we use in PETSc for CUDA code 
https://gitlab.com/petsc/petsc/-/blob/master/gmakefile#L168
https://gitlab.com/petsc/petsc/-/blob/master/gmakefile.test#L103

Just in case you want to give it a try to avoid nvcc for linking

**Comment by liruipeng** [comment]
> @liruipeng FYI here is the makefile rules details we use in PETSc for CUDA code
> https://gitlab.com/petsc/petsc/-/blob/master/gmakefile#L168
> https://gitlab.com/petsc/petsc/-/blob/master/gmakefile.test#L103
> 
> Just in case you want to give it a try to avoid nvcc for linking

@stefanozampini 

Thank you for the information.

My impression is one needs to have a second "device link" step (`nvcc -dlink`, https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-specifying-compilation-phase-device-link). I did not recognize it in your makefiles:

Is the following meant to be the two-step compile?

```
$(OBJDIR)/%.o : src/%.cu | $$(@D)/.DIR
	$(PETSC_COMPILE.cu) $(abspath $<) -o $@ # Compile first so that if there is an error, it comes from a normal compile
	@$(PETSC_GENDEPS.cu) $(abspath $<) -o $(@:%.o=%.d) # Generate the dependencies for later
```

**Comment by stefanozampini** [comment]
No, I guess it is used for generating the .d file used by the makefile to decide whether or not we need to recompile

**Comment by stefanozampini** [comment]
I was able to use HYPRE GPU from PETSc. I only have a couple of tests failures. One coming from using pfmg, and another when doing matrix-matrix product. I'm investigating those failures and  report some detailed information later.
Can you please tell me if HYPRE_Init() is mandatory to be called when using these advanced HYPRE features?

**Comment by stefanozampini** [comment]
@liruipeng I have a couple of test failures, see https://gitlab.com/petsc/petsc/-/commit/db70fb71493071008f476bf4a2373c714190ba4b

One is from a matrix-matrix multiplication using HYPRE_ParMul. The input matrices are 1 x 12 and 12 x 1, split on 3 processes. Note that the same test works fine when not using the GPU version of HYPRE

Another test is related with pfmg (same test runs fine with the CPU version). I don't know what is going on there, I'm not an expert of these methods. I have tried running cuda-memcheck, and got tons of errors (below I report only the first one) 

```
$ cd src/ksp/ksp/tutorials/
$ make ex34
$ cuda-memcheck ./ex34 -ksp_type gmres -pc_type pfmg -dm_mat_type hyprestruct -ksp_monitor #only report first error
========= CUDA-MEMCHECK
========= Invalid __global__ read of size 8
=========     at 0x00000700 in /home/zampins/Devel/hypre/src/struct_mv/_hypre_struct_mv.hpp:782:_Z13forall_kernelIZ30hypre_StructVectorSetBoxValuesEUliE0_EvT_i
=========     by thread (127,0,0) in block (3,0,0)
=========     Address 0x7fbe42216a58 is out of bounds
=========     Device Frame:/home/zampins/Devel/hypre/src/struct_mv/_hypre_struct_mv.hpp:782:_Z13forall_kernelIZ30hypre_StructVectorSetBoxValuesEUliE0_EvT_i (_Z13forall_kernelIZ30hypre_StructVectorSetBoxValuesEUliE0_EvT_i : 0x700)
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 (cuLaunchKernel + 0x346) [0x297db6]
=========     Host Frame:/opt/ecrc/cuda/10.2/lib64/libcudart.so.10.2 [0x1a547]
=========     Host Frame:/opt/ecrc/cuda/10.2/lib64/libcudart.so.10.2 [0x1a5d7]
=========     Host Frame:/opt/ecrc/cuda/10.2/lib64/libcudart.so.10.2 (cudaLaunchKernel + 0x225) [0x51885]
=========     Host Frame:/home/zampins/Devel/hypre/myinstall/lib/libHYPRE-2.19.0.so [0x3ffc4c]
=========     Host Frame:/home/zampins/Devel/hypre/myinstall/lib/libHYPRE-2.19.0.so (_Z13BoxLoopforallI18__nv_hdl_wrapper_tILb0ELb0E11__nv_dl_tagIPFiP25hypre_StructVector_structP16hypre_Box_structS5_PdiiiEXadL_Z30hypre_StructVectorSetBoxValuesEELj2EEFviEI20hypre_Boxloop_structSB_S6_S6_EEEv22_HYPRE_ExecutionPolicyiT_ + 0x158) [0x4041a8]
=========     Host Frame:/home/zampins/Devel/hypre/myinstall/lib/libHYPRE-2.19.0.so (hypre_StructVectorSetBoxValues + 0x8ba) [0x401daa]
=========     Host Frame:/home/zampins/Devel/hypre/myinstall/lib/libHYPRE-2.19.0.so (HYPRE_StructVectorSetBoxValues2 + 0x9d) [0x3ca6fd]
=========     Host Frame:/home/zampins/Devel/hypre/myinstall/lib/libHYPRE-2.19.0.so (HYPRE_StructVectorSetBoxValues + 0x12) [0x3ca742]
=========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 [0x1a62a67]
=========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 (PCApply + 0xab8) [0x1adb05e]
=========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 [0x1b8fea2]
=========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 (KSPInitialResidual + 0xca5) [0x1b90e26]
=========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 [0x1c91451]
=========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 [0x1b60609]
=========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 (KSPSolve + 0x54d) [0x1b624fe]
=========     Host Frame:./ex34 [0x1f75]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20840]
=========     Host Frame:./ex34 [0x1909]
```

**Comment by liruipeng** [comment]
> I was able to use HYPRE GPU from PETSc. I only have a couple of tests failures. One coming from using pfmg, and another when doing matrix-matrix product. I'm investigating those failures and report some detailed information later.
> Can you please tell me if HYPRE_Init() is mandatory to be called when using these advanced HYPRE features?

@stefanozampini
It is suggested that `HYPRE_Init()` is called first, but it should also work without.

**Comment by liruipeng** [comment]
> > I was able to use HYPRE GPU from PETSc. I only have a couple of tests failures. One coming from using pfmg, and another when doing matrix-matrix product. I'm investigating those failures and report some detailed information later.
> > Can you please tell me if HYPRE_Init() is mandatory to be called when using these advanced HYPRE features?
> 
> It is suggested that `HYPRE_Init()` is called first, but it should also work without.

**Comment by liruipeng** [comment]
> @liruipeng I have a couple of test failures, see https://gitlab.com/petsc/petsc/-/commit/db70fb71493071008f476bf4a2373c714190ba4b
> 
> One is from a matrix-matrix multiplication using HYPRE_ParMul. The input matrices are 1 x 12 and 12 x 1, split on 3 processes. Note that the same test works fine when not using the GPU version of HYPRE
> 
> Another test is related with pfmg (same test runs fine with the CPU version). I don't know what is going on there, I'm not an expert of these methods. I have tried running cuda-memcheck, and got tons of errors (below I report only the first one)
> 
> ```
> $ cd src/ksp/ksp/tutorials/
> $ make ex34
> $ cuda-memcheck ./ex34 -ksp_type gmres -pc_type pfmg -dm_mat_type hyprestruct -ksp_monitor #only report first error
> ========= CUDA-MEMCHECK
> ========= Invalid __global__ read of size 8
> =========     at 0x00000700 in /home/zampins/Devel/hypre/src/struct_mv/_hypre_struct_mv.hpp:782:_Z13forall_kernelIZ30hypre_StructVectorSetBoxValuesEUliE0_EvT_i
> =========     by thread (127,0,0) in block (3,0,0)
> =========     Address 0x7fbe42216a58 is out of bounds
> =========     Device Frame:/home/zampins/Devel/hypre/src/struct_mv/_hypre_struct_mv.hpp:782:_Z13forall_kernelIZ30hypre_StructVectorSetBoxValuesEUliE0_EvT_i (_Z13forall_kernelIZ30hypre_StructVectorSetBoxValuesEUliE0_EvT_i : 0x700)
> =========     Saved host backtrace up to driver entry point at kernel launch time
> =========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 (cuLaunchKernel + 0x346) [0x297db6]
> =========     Host Frame:/opt/ecrc/cuda/10.2/lib64/libcudart.so.10.2 [0x1a547]
> =========     Host Frame:/opt/ecrc/cuda/10.2/lib64/libcudart.so.10.2 [0x1a5d7]
> =========     Host Frame:/opt/ecrc/cuda/10.2/lib64/libcudart.so.10.2 (cudaLaunchKernel + 0x225) [0x51885]
> =========     Host Frame:/home/zampins/Devel/hypre/myinstall/lib/libHYPRE-2.19.0.so [0x3ffc4c]
> =========     Host Frame:/home/zampins/Devel/hypre/myinstall/lib/libHYPRE-2.19.0.so (_Z13BoxLoopforallI18__nv_hdl_wrapper_tILb0ELb0E11__nv_dl_tagIPFiP25hypre_StructVector_structP16hypre_Box_structS5_PdiiiEXadL_Z30hypre_StructVectorSetBoxValuesEELj2EEFviEI20hypre_Boxloop_structSB_S6_S6_EEEv22_HYPRE_ExecutionPolicyiT_ + 0x158) [0x4041a8]
> =========     Host Frame:/home/zampins/Devel/hypre/myinstall/lib/libHYPRE-2.19.0.so (hypre_StructVectorSetBoxValues + 0x8ba) [0x401daa]
> =========     Host Frame:/home/zampins/Devel/hypre/myinstall/lib/libHYPRE-2.19.0.so (HYPRE_StructVectorSetBoxValues2 + 0x9d) [0x3ca6fd]
> =========     Host Frame:/home/zampins/Devel/hypre/myinstall/lib/libHYPRE-2.19.0.so (HYPRE_StructVectorSetBoxValues + 0x12) [0x3ca742]
> =========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 [0x1a62a67]
> =========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 (PCApply + 0xab8) [0x1adb05e]
> =========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 [0x1b8fea2]
> =========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 (KSPInitialResidual + 0xca5) [0x1b90e26]
> =========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 [0x1c91451]
> =========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 [0x1b60609]
> =========     Host Frame:/home/zampins/Devel/petsc/arch-gpu-double-dbg-hypre/lib/libpetsc.so.3.013 (KSPSolve + 0x54d) [0x1b624fe]
> =========     Host Frame:./ex34 [0x1f75]
> =========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20840]
> =========     Host Frame:./ex34 [0x1909]
> ```

@stefanozampini 

1. `HYPRE_ParMul` is a CPU only function, but it should work with CUDA UVM.
2. Is it possible for me to run the test? Please advise how to configure and compile PETSc with CUDA and run.

Thanks!

**Comment by stefanozampini** [comment]
Assuming you have HYPRE GPU installed in some location,  you can checkout `stefanozampini/hypre-cuda-rebased-v3` of PETSc and build PETSc 

``` 
export PETSC_DIR=$PWD
export PETSC_ARCH=arch-test
./configure --with-hypre-dir=/path/to/hypre/install/dir --with-cc=/path/to/mpicc/compiler --with-cxx=/path/to/mpic++/compiler --with-fortran-bindings=0 --with-cuda=1 --with-cuda-unifiedmemory=1
make
```

Then, after you compile PETSc, you can run all the hypre related tests using

`make -f gmakefile.test test query='requires' queryval='hypre'`

This will not run the broken tests (since are flagged as broken).

To run the broken tests: here is for the ParMul tests

```
cd src/mat/tests
make ex115
mpiexec -n 3 ./ex115 -M 1 -N 12 -test_offproc
mpiexec -n 3 ./ex115 -M 1 -N 2 -test_offproc
```

Instead, for `pfmg`, you can run

```
cd src/ksp/ksp/tutorials/
make ex34
./ex34 -ksp_type gmres -pc_type pfmg -dm_mat_type hyprestruct -ksp_monitor -ksp_converged_reason
```

This test converges in few Krylov iterations with CPU only builds, but fails for GPU builds

**Comment by stefanozampini** [comment]
Oh, forgot to say that you must provide PETSc the Blas/lapack symbols (if not in system locations)

either with

```
--with-blaslapack-lib=[comma-separated-list-of-libraries]
```

or with

```
--download-fblaslapack=1
```

or 

```
--download-openblas=1
```

there are few configuration examples in `config/examples`

**Comment by liruipeng** [comment]
@stefanozampini 

There was some error in running configure

```
