### ISSUE TITLE
Installation help requested

### ISSUE THREAD

**Issue by cbjuju** [hypre-space/hypre#153]
This is to request help with the hypre installation process. I was unable to install hypre by running the following two commands in the top-level source directory hypre/src :

./configure
make

I am trying to install hypre version v2.19.0. The following are the details relevant to the system I am trying to install on :

Machine : CPU/GPU workstation (Dual Xeon Gold 6140 with Nvidia Tesla V100 GPU)
OS: Ubuntu 18.04.4 LTS
MPI: openmpi 20.10.0
compiler: Intel fortran/c++ parallel studio 2016.5, Intel fortran/c++ parallel studio 2019.3

It seems that the configure tool is not able to locate the MPI installation. Also, make errors out saying that the recipe for target 'all' failed.

**Comment by liruipeng** [comment]
It appears your system failed to find MPI. You can provide MPI path to hypre by add the following options to `configure`

```
 --with-MPI-include=DIR  User specifies that mpi.h is in DIR. The options
                          --with-MPI-include --with-MPI-libs and
                          --with-MPI-lib-dirs must be used together.
  --with-MPI-libs=LIBS    LIBS is space-separated list (enclosed in quotes) of
                          library names needed for MPI, e.g. "nsl socket mpi".
                          The options --with-MPI-include --with-MPI-libs and
                          --with-MPI-lib-dirs must be used together.
  --with-MPI-lib-dirs=DIRS
                          DIRS is space-separated list (enclosed in quotes) of
                          directories containing the libraries specified by
                          --with-MPI-libs, e.g "usr/lib /usr/local/mpi/lib".
                          The options --with-MPI-include --with-MPI-libs and
                          --with-MPI-lib-dirs must be used together.
```
