### ISSUE TITLE
In StructGrid solver, can a matrix uses multiple stencils for each cell?

### ISSUE THREAD

**Issue by thecasterian** [hypre-space/hypre#154]
I'm working on solving 2-D Poisson equation with the _immersed boundary method_ (IBM). I used 5-point stencil for discretization of Poisson equation but, in the IBM, the value of boundary cells are determined by an interpolation of that of inner cells so some cells require the informations of cells outside the 5-point stencil.

Can I apply different stencils for a specific cell, or is there any simple implementation of IBM in HYPRE StructGrid solver?

**Comment by rfalgout** [comment]
Hi @thecasterian .  The stencil is fixed in `Struct`.  You can use `SStruct` to add stencil entries in different places of the grid.  The only  multigrid solver you will have in this case currently is BoomerAMG.  Hope this help!  -Rob
