### ISSUE TITLE
Hide hardcoded "warp size" in bit-shift operators

### ISSUE THREAD

**Issue by pbauman** [hypre-space/hypre#158]
In several places in the code, specifically the GPU parts, there are statements like `HYPRE_Int wid  = threadIdx.x >> 5`. These are effectively hardcoding in warp size and will limit portability. I would like to hide the value behind a macro similar to `HYPRE_WARP_SIZE`. So there are two questions:

1. Do you agree in principle?
2. What is a good name for the macro? My kneejerk is `HYPRE_WARP_BIT_SHIFT`, but I'm not sure that's very clear.

I'm happy to cook up a PR to address this if there is agreement both on the strategy and the marco name. Thank you.

**Comment by rfalgout** [comment]
Hi @pbauman .  Thanks for being mindful of portability!  Regarding your questions, I do agree in principle that the `>> 5` should not be hardcoded.  I also don't really like the macro name idea you throw out.  However, I think there is more to this than defining the number 5 with a macro.  This line effectively multiplies by 32, and the number 32 is important in related code, such as this code in `utilities/hypre_cuda_reducer.h`

      __shared__ T shared[32];        // Shared mem for 32 partial sums

So, we would either need another companion macro for the number 32 or use a different approach here.  Just my 2 cents.

**Comment by pbauman** [comment]
Hi @rfalgout Agreed, I'm not super keen on the macro idea either. However, I was trying to follow precedence in the library. See #157 where I address exactly the the case you list, as well as a few others. I'm definitely open to suggestions.

**Comment by rfalgout** [comment]
@pbauman .  Yep.  I wasn't paying attention.  Should have looked more carefully at your pull request first.

Anyway, why not change `>> 5` to `* HYPRE_WARP_SIZE`?  Is there a performance reason for the bit shift?

**Comment by pbauman** [comment]
Hi @rfalgout, no worries, sorry for firing off all this at once.

My understanding is that `>> 5` would be equivalent to `/ HYPRE_WARP_SIZE`, not `* HYPRE_WARP_SIZE`?

@liruipeng may have a better idea, but I believe the `>> 5` would be more performant than the `/ 5`. I can say I would expect there could be a significant performance penalty for using `/` in the device code on AMD devices (in the cases where the resulting value can't be determined at compile time), so my preference would be to preserve the `>>` for performance reasons when thinking ahead to supporting AMD devices. But I definitely could be missing something. I admit to not yet canvasing for cases that can be deduced at compile time, but the case I posted in the opening of this issue is at least one case that can't be determined at compile time.

**Comment by rfalgout** [comment]
You are correct @pbauman , it's `/ 5`.  Whatever you and @liruipeng decide is fine with me.  Thanks again!

**Comment by liruipeng** [comment]
@pbauman @rfalgout 

`>> 5 == / 32` but `>> 5` is more efficient. Having another macro as `HYPRE_WARP_BIT_SHIFT` is fine to me. We just need it to make sure it is consistent with `HYPRE_WARP_SIZE` such as `5` for `32`. I was thinking of a way to take log2 of `HYPRE_WARP_SIZE` and define a macro for it. But it seems too hard to do. That might be the reason I left `5` explicitly in many places. But it is definitely not portable, and should be fixed.

**Comment by pbauman** [comment]
> We just need it to make sure it is consistent with HYPRE_WARP_SIZE such as 5 for 32

Agreed. The way I'm handling this with HIP is `#if defined`. At least with these macros, they will be in one place, right next to each other.

> Having another macro as HYPRE_WARP_BIT_SHIFT is fine to me. 

OK, I'll cook up a PR for this. (I'll build it on #157 but have it be a separate PR.)
