### ISSUE TITLE
Error building on Mac with mixedint

### ISSUE THREAD

**Issue by v-dobrev** [hypre-space/hypre#159]
I noticed that building hypre fails on Mac when using the `--enable-mixedint` option. All versions after 2.16.0 seem to be affected.

I tracked down the issue to the following 3 lines which have empty file lists in this case:
https://github.com/hypre-space/hypre/blob/b075d642550c9947b758201f41f5d38dabfe7a51/src/lib/Makefile#L82-L84

and `ar` on Mac does not like that:
```console
ar -rcu libHYPRE.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
```

One possible solution is to combine these lines with one of the lines that always has some files.

**Comment by v-dobrev** [comment]
This came up in https://github.com/mfem/mfem/pull/1583#issuecomment-663914143.

**Comment by rfalgout** [comment]
Hi @v-dobrev .  If you combine these three lines with the DISTMATRIXFILES line as follows, does it fix the issue?

    ${AR} $@ $(EUCLIDFILES) $(PARASAILSFILES) $(PILUTFILES) $(DISTMATRIXFILES)

If so, we'll go ahead and make that change (with an appropriate comment to avoid accidentally breaking it up again in the future).  Let us know.   Thanks!

**Comment by v-dobrev** [comment]
> Hi @v-dobrev . If you combine these three lines with the DISTMATRIXFILES line as follows, does it fix the issue?
> 
> ```
> ${AR} $@ $(EUCLIDFILES) $(PARASAILSFILES) $(PILUTFILES) $(DISTMATRIXFILES)
> ```
> 
> If so, we'll go ahead and make that change (with an appropriate comment to avoid accidentally breaking it up again in the future). Let us know. Thanks!

Yes, this change fixes the issue.

**Comment by rfalgout** [comment]
Thanks @v-dobrev .  I just pushed the change.
