### ISSUE TITLE
Issue with big partitions in HYPRE_MIXEDINT mode

### ISSUE THREAD

**Issue by v-dobrev** [hypre-space/hypre#162]
While debugging an issue with a "big" problem (~5e9 unknowns) in https://github.com/mfem/mfem/pull/1583, I traced it to the following function:
https://github.com/hypre-space/hypre/blob/6846fc28da5f27308f7fa8ea2f832886db8a7ce7/src/parcsr_mv/par_csr_assumed_part.c#L308-L312

Switching the `HYPRE_Int` parameters to `HYPRE_BigInt` seems to resolve the problem we were seeing.

**Comment by ulrikeyang** [comment]
You are right. We missed that one. Thanks


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On July 28, 2020 at 12:51:53 PM PDT, Veselin Dobrev <notifications@github.com> wrote:

While debugging an issue with a "big" problem (~5e9 unknowns) in mfem/mfem#1583<https://github.com/mfem/mfem/pull/1583>, I traced it to the following function:
https://github.com/hypre-space/hypre/blob/6846fc28da5f27308f7fa8ea2f832886db8a7ce7/src/parcsr_mv/par_csr_assumed_part.c#L308-L312

Switching the HYPRE_Int parameters to HYPRE_BigInt seems to resolve the problem we were seeing.

**Comment by ulrikeyang** [comment]
It's now fixed. Thanks
