### ISSUE TITLE
Hotfix release -- missing hypre_AuxParCSRMatrixInitialize in 2.19.0

### ISSUE THREAD

**Issue by zerothi** [hypre-space/hypre#164]
Release 2.19.0 does not contain the code for the function mentioned in the title.

This has been added later in a commit.

This is rather unfortunate since the hypre headers define the methods, and thus linking will not work. I.e. I can't compile slepc due to this inconsistency.

Would you consider a 2.19.1 release with this cherry-pick, or release a new version?

**Comment by liruipeng** [comment]
It was added in the master branch, and will be included in the next release. Thanks!

**Comment by zerothi** [comment]
Yes I know, but I was asking whether you could soonish make a release to make it public?

The 2.19.0 releases was 2 months ago :)
E.g. When is the next release ;)

**Comment by rfalgout** [comment]
Hi @zerothi .  Out of curiosity, why do you need to have an actual release?  Note that we do make an effort to keep the master "clean", so it is usually pretty safe to point to that.  We don't currently have a specific date set for a new release.  Let us know.  Thanks!

**Comment by zerothi** [comment]
Thanks, it just seemed weird to me since the latest release is in a somewhat non-usable form. 

But you are correct, I will take a prior release. I was just updating packages for our HPC software stack for our scientist. And they typically request lastest and shining ;)

Thanks for your time, I'll close.

**Comment by rfalgout** [comment]
Hi @zerothi .  The issue you are having is specifically related to using PETSc.  The PETSc guys are using internal hypre routines (lower-case 'hypre_' indicates an internal routine), and we did not catch the fact that our changes in 2.19.0 broke what they were doing.  We are starting to work more closely with the PETSc team now as part of our release process and regular testing, so hopefully this kind of thing won't happen again.

**Comment by zerothi** [comment]
Hi, thanks for the info, and sorry for the blurp ;)
