### ISSUE TITLE
Is hypre_ParCSRMatrixReadIJ() intended to read output from hypre_ParCSRMatrixPrintIJ()?

### ISSUE THREAD

**Issue by barker29** [hypre-space/hypre#168]
In `hypre_ParCSRMatrixPrintIJ()`, the first values printed are `ilower, iupper, jlower, jupper`, ie, the limits of the local portion of the matrix. But in `hypre_ParCSRMatrixReadIJ()`, the first values read in are expected to be `global_num_rows` and `global_num_cols`. In particular, this means if I print a matrix on one processor and then read it in using these routines, the reader will assign it a `global_num_rows` of 0 which leads to a segfault later in the reading procedure.

How should I print and read a `hypre_ParCSRMatrix` from disk?

**Comment by liruipeng** [comment]
@barker29 There indeed exists inconsistency between `hypre_ParCSRMatrixPrintIJ()` and `hypre_ParCSRMatrixReadIJ()`.

As of now, one can resort to the IJ interface, i.e, `HYPRE_IJMatrixRead` and `HYPRE_IJMatrixPrint` should work.
