### ISSUE TITLE
BoomerAMG with rigid body modes

### ISSUE THREAD

**Issue by andrea-franceschini** [hypre-space/hypre#182]
I am trying to use `hypre` BoomerAMG for a 3D elasticity problem, providing the rigid body modes as near null kernel, but I think that the function [par_sv_interp_ln.c](https://github.com/hypre-space/hypre/blob/master/src/parcsr_ls/par_sv_interp_ln.c) has a small error.

This function takes as input parameter _num_smooth_vecs_, the number of smooth vectors. In my case, this is 6.
But in the function body, we have
https://github.com/hypre-space/hypre/blob/5da38fea68c6825ecc47a5b20f900fd5b873263b/src/parcsr_ls/par_sv_interp_ln.c#L881-L884

where _adj_ and _r_extra_ are arrays of fixed size 3.
https://github.com/hypre-space/hypre/blob/5da38fea68c6825ecc47a5b20f900fd5b873263b/src/parcsr_ls/par_sv_interp_ln.c#L142

As a temporary solution, I changed 3 to 6, avoiding the segmentation fault and computing the proper BoomerAMG + rigid body modes and everything works fine.
I think the best solution would be a dynamic allocation of size _num_smooth_vecs_.

Also, in the same function there is (I think) another small problem. For each prolongation row, to compute the average value of a given quantity to be equally distributed among all coarse nodes, this is the code:
https://github.com/hypre-space/hypre/blob/5da38fea68c6825ecc47a5b20f900fd5b873263b/src/parcsr_ls/par_sv_interp_ln.c#L1134

but there is the possibility of a prolongation row with zero entries. This means that both _p_num_diag_elements_ and  _p_num_offd_elements_ will be zero and the code (when floating point exceptions are catch) will crash. The value _aw_ is not used for these particular rows, so its computation can be skipped, adding something like:

```
if( P_diag_i[i+1] > P_diag_i[i] )
{
   aw =  a_ij/( p_num_diag_elements + p_num_offd_elements);
}
```

The same happens several other times in this routine.

**Comment by oseikuffuor1** [comment]
Hi @af1990 thanks again for the info. It looks like the function in par_sv_interp_ln.c assumes up to 3 rigid body modes for 3D. There does seem to be an issue with this since the number of vectors passed as input is not checked either. We will look into this further. Regarding the second issue, are you implying that the matrix would have a zero row?  ( p_num_diag_elements + p_num_offd_elements) should give the sum of the nonzero entries in the row. Are you encountering cases where this value is zero?

**Comment by liruipeng** [comment]
Hi, @af1990, Nice to hear from you. The reason why it assumes RBM has dimension 3 is that it only considers the ration modes but the translation modes are automatically handled by the unknown-based interpolation approach.

-Ruipeng

**Comment by andrea-franceschini** [comment]
> 
> 
> Hi, @af1990, Nice to hear from you. The reason why it assumes RBM has dimension 3 is that it only considers the ration modes but the translation modes are automatically handled by the unknown-based interpolation approach.
> 
> -Ruipeng

Oh ... this clarify the 3! Thanks Ruipeng.

**Comment by andrea-franceschini** [comment]
> Regarding the second issue, are you implying that the matrix would have a zero row? ( p_num_diag_elements + p_num_offd_elements) should give the sum of the nonzero entries in the row. Are you encountering cases where this value is zero?

I noticed that in correspondence of a Dirichlet dof, i.e. a row of `A` with only the diagonal value, the prolongation has no entries.
The matrix `A` is regular, with well-defined rows. I am referring to the prolongation when I am saying that it has zero rows.

**Comment by oseikuffuor1** [comment]
Thanks @liruipeng. I think we should still make this clearer so a user does not pass more vectors. I believe the HYPRE_BoomerAMGSetInterpVectors() function does not specify up to 3 vectors for 3D, which can lead to issues such as this one. @af1990 you should get similar result when using only the rotation modes for the vectors. Can you confirm this works fine?

**Comment by andrea-franceschini** [comment]
Yes @oseikuffuor1, I can confirm that the results are practically the same. Everything works fine with just the three rotations.
