### ISSUE TITLE
build error after hopscotch fix

### ISSUE THREAD

**Issue by suguanting** [hypre-space/hypre#183]
Dear HYPRE developers,

I am setting up HYPRE on a new WIN10 machine using CMAKE, which return the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0020	identifier "ffs" is undefined	HYPRE	E:\hypre\hypre-master\src\utilities\hypre_hopscotch_hash.h	135	
```

It seems it concerns the new hopscotch fix, after which the code becomes:

```
// Small Utilities ..........................................................
static inline HYPRE_Int
first_lsb_bit_indx( hypre_uint x )
{
  return ffs(x) - 1;
}
```

whose original version that worked fine for me was

```
// Small Utilities ..........................................................
#ifdef HYPRE_CONCURRENT_HOPSCOTCH
static inline HYPRE_Int first_lsb_bit_indx(hypre_uint x) 
{
  return ffs(x) - 1;
}
#endif
```

So any suggestions? Thanks in advance for your help!

Guanting

**Comment by liruipeng** [comment]
@suguanting @victorapm 

It seems that `ffs` is available for Linux only.

**Comment by victorapm** [comment]
@suguanting, thanks for reporting this problem. We fixed it and merged the changes into master.

**Comment by suguanting** [comment]
Hi @victorapm @liruipeng , it is working fine this time, thank you for the fix!
