### ISSUE TITLE
"-vis" flag is not saving .mesh, .sol and .data file in /vis directory

### ISSUE THREAD

**Issue by Huq2090** [hypre-space/hypre#185]
`-vis` flag is not saving .mesh, .sol and .data file in /vis directory for any example. 

So I can't visualize any figure. 
Any suggestion?
Thanks.

**Comment by rfalgout** [comment]
Hi @Huq2090 .  To turn on the vis stuff, you need to define HYPRE_EXVIS.  With make, just modify the `examples/Makefile` in the following way (using diff notation):

    -#CDEFS     = -DHYPRE_EXVIS
    -CDEFS     =
    +CDEFS     = -DHYPRE_EXVIS
    +#CDEFS     =

This was done to allow us to write a header file usage regression test.  Hope this helps!

**Comment by Huq2090** [comment]
I have installed `glvis` with `mfem`. But, it's showing `glvis` is not found. Then checked `echo $PATH` and I didn't see `glvis`. 
I think that's the reason why I'm not getting those files and can't visualize. 
Any way out or suggestions. 
Thanks

**Comment by Huq2090** [comment]
Thanks.
Now I can plot. 
`glvis` is working.
