### ISSUE TITLE
deprecated cuda calls

### ISSUE THREAD

**Issue by akhaneles** [hypre-space/hypre#186]
Hello,

I tried to configure hypre 2.19.0 with cuda 11 and got errors:

csr_matvec_device.c(68): error: identifier "cusparseDcsr2csc" is undefined
csr_matvec_device.c(72): error: identifier "cusparseDcsrmv" is undefined
csr_matvec_device.c(84): error: identifier "cusparseDcsrmv" is undefined

it seems hypre is using cuda calls that have been deprecated quite a while ago (https://docs.nvidia.com/cuda/archive/10.1/pdf/CUSPARSE_Library.pdf).

Is it correct? If yes, any plans to upgrade?

For now I rolled everything back to cuda-10.2, etc.

Thank you,
Alex

**Comment by tpowis** [comment]
I also observe the same issue, although @akhaneles and I use the same system (a Power 9 architecture with V100 GPUs), we may be using different configurations so I will provide some more details:

I attempt to compile on the Hypre master branch using GCC 8.3.1, OpenMPI 4.04 (which is CUDA-aware), as well as CudaToolKit 11.0.

The configuration I use is
```bash
./configure HYPRE_CUDA_SM=70 --with-cuda --disable-fortran --enable-gpu-aware-mpi
```

I then build using `make`.

I have attached the output from the config and make steps.

Thanks in advance for your help!

Tasman

Config output:
[hypre-config-cuda11.txt](https://github.com/hypre-space/hypre/files/5166856/hypre-config-cuda11.txt)

Make output:
[hypre-make-cuda11.txt](https://github.com/hypre-space/hypre/files/5166858/hypre-make-cuda11.txt)

**Comment by liruipeng** [comment]
@tpowis @akhaneles We are working on supporting CUDA-11 (see work-in-progress PR #163), and will have it in master soon. Thanks for reporting the issue.

-Ruipeng

**Comment by liruipeng** [comment]
@tpowis @akhaneles we have CUDA11 support merged into the master. Please let us know if it works for you. Thanks!

**Comment by tpowis** [comment]
@liruipeng thank you for the update. I just installed it and it runs fine, better than fine actually. On a single GPU I see a remarkable speedup of 600x for PFMG using the Struct interface! Initial checks seem to verify that the solution is still accurate, however I'll run further checks to make sure this is real and also explore the scaling performance across multiple GPUs.

FYI we compiled on the Traverse cluster, a POWER9 system with NVIDIA V100 GPUs. I used the following packages:
- GCC 8.3.1
- OpenMPI 4.0.4 which is CUDA-aware for CUDA-11.0
- CudaToolkit 11.0

I configured using:
`./configure --with-cuda --disable-fortran --enable-gpu-aware-mpi`

I'll update with further results when they become available.

**Comment by liruipeng** [comment]
@tpowis Thank you for keeping us updated. We are glad to see it works for you, although 600x speedup is likely a too-good-to-be-true. But anyways, we would like to see further results. I am closing this issue since it seems to have been resolved. Please feel free to open another one when needed. Thanks! -Ruipeng
