### ISSUE TITLE
Employing boundary conditions while using the constant entries option of the Struct interface

### ISSUE THREAD

**Issue by p-costa** [hypre-space/hypre#197]
Hello everyone,

I tried to simplify the solution of a Poisson equation using HYPRE in the case of constant grid spacing using the Struct interface, where the entries of the stencil are constant. Does HYPRE support the case where the entries are constant except for the boundary coefficients that should be set to zero (e.g. for Dirichlet/Neumann boundary conditions)?

I am trying to get the solver to work for a Neumann/Dirichlet B.C. using `HYPRE_StructMatrixSetConstantEntries` and `HYPRE_StructMatrixSetConstantValues` for the off-diagonal elements (while the diagonal is set with `HYPRE_StructMatrixSetBoxValues` since it is not constant due to the B.C.), but I am getting wrong results. So I wonder if I am missing something, or perhaps these options will only work for a case where all the stencil entries are truly constant, like for periodic boundary conditions?

Edit: I forgot to mention that I use `HYPRE_StructMatrixSetValues` to set to zero the off-diagonal elements at the boundaries. When I do not do not change the stencil elements at the boundaries the solution error is smaller but still incorrect.

Thanks in advance!
Pedro

**Comment by rfalgout** [comment]
Hi @p-costa .  You can use constant stencils for Dirichlet problems and constant-with-variable-diagonal stencils for Neumann (or Dirichlet).  You don't need to set the off-diagonal entries to zero at boundaries in this case.  If you use an all-constant stencil, then you will have some limitations if you want to use PFMG.  I would recommend using the variable diagonal approach.

You can run these cases in our driver `test/struct`, if you are interested.  For example, do

    struct -d 2 -n 20 20 1 -solver 4 -print

to run a 20x20 2D Laplacian problem with Dirichlet BCs (the results are printed to `struct.out.x.00000`).  Change the solver value to 1 to get the variable coefficient version.  Use `struct -help` to see all of the available options (you can run 3D as well).

Hope this helps!

**Comment by p-costa** [comment]
Thank you very much for the prompt response @rfalgout ! The cases in the nice test/struct driver seem to run fine. 

Unfortunately I'm getting wrong results with PFMG and SMG (did not test others) in my (Fortran) implementation. It is a bit strange, since it is a simple modification of a solver which works correctly using an all-variable stencil (i.e. one call of `HYPRE_StructMatrixSetBoxValues` filling all the matrix entries).

I will make a minimal working example and post it here (perhaps in the meantime I realize what went wrong).

Thanks again!

**Comment by p-costa** [comment]
Hi again @rfalgout and all,

I write below a minimal example for the solution of a Poisson equation in Fortran, using the SMG solver and Dirichlet BCs. When I run it, I do not get the right solution. The relevant lines where I setup the matrix are shown in the snippet below, and I also add the full program later in case someone wants to test it. Perhaps I am missing something obvious, but this is how I would write it based on my understanding of the API.

Thanks in advance for your feedback!

```fortran
  call HYPRE_StructMatrixSetConstantEn(mat,nstencil-1,[1,2,3,4,5,6],ierr)
  call HYPRE_StructMatrixSetConstantVa(mat,nstencil-1,[1,2,3,4,5,6],1._rp*[1,1,1,1,1,1],ierr)
  q = 0
  do k=1,n
    do j=1,n
      do i=1,n
        q = q + 1
        cc  = -6._rp
        if(any(i==[1,n])) then
          cc = cc - 1._rp
        endif
        if(any(j==[1,n])) then
          cc = cc - 1._rp
        endif
        if(any(k==[1,n])) then
          cc = cc - 1._rp
        endif
        matvalues(q) = cc
      enddo
    enddo
  enddo
  call HYPRE_StructMatrixSetBoxValues(mat,lo,hi,1,[0],matvalues,ierr)
  call HYPRE_StructMatrixAssemble(mat,ierr)
```

```fortran
program poi2d
  use mpi
  implicit none
  integer , parameter                    :: rp = KIND(0.0D0)
  integer , parameter                    :: n = 4
  integer , parameter                    :: nstencil = 7
  integer                                :: ierr
  integer(8)                             :: comm_hypre,grid,stencil,mat,rhs,sol,solver
  integer , dimension(3)                 :: lo,hi
  integer , dimension(3,nstencil)        :: offsets
  real(rp), dimension(n**3)              :: matvalues,rhsvalues,solvalues
  real(rp), dimension(0:n+1,0:n+1,0:n+1) :: sol_3d
  integer                                :: i,j,k,q,qq
  real(rp)                               :: cc,rn,lap
  !
  call MPI_INIT(ierr)
  comm_hypre = MPI_COMM_WORLD
  !
  lo(:) = [1,1,1]
  hi(:) = [n,n,n]
  call HYPRE_StructGridCreate(comm_hypre,3,grid,ierr)
  call HYPRE_StructGridSetExtents(grid,lo,hi,ierr)
  call HYPRE_StructGridAssemble(grid,ierr)
  !
  call HYPRE_StructStencilCreate(3,nstencil,stencil,ierr)
  offsets = reshape([ 0, 0, 0, &
                     -1, 0, 0, &
                      1, 0, 0, &
                      0,-1, 0, &
                      0, 1, 0, &
                      0, 0,-1, &
                      0, 0, 1 ],shape(offsets))
  do q=1,nstencil
    call HYPRE_StructStencilSetElement(stencil,q-1,offsets(:,q),ierr)
  enddo
  !
  call HYPRE_StructMatrixCreate(comm_hypre,grid,stencil,mat,ierr)
  call HYPRE_StructMatrixInitialize(mat,ierr)
  call HYPRE_StructVectorCreate(comm_hypre,grid,sol,ierr)
  call HYPRE_StructVectorInitialize(sol,ierr)
  call HYPRE_StructVectorCreate(comm_hypre,grid,rhs,ierr)
  call HYPRE_StructVectorInitialize(rhs,ierr)
  !
  call HYPRE_StructMatrixSetConstantEn(mat,nstencil-1,[1,2,3,4,5,6],ierr)
  call HYPRE_StructMatrixSetConstantVa(mat,nstencil-1,[1,2,3,4,5,6],1._rp*[1,1,1,1,1,1],ierr)
  q = 0
  do k=1,n
    do j=1,n
      do i=1,n
        q = q + 1
        cc  = -6._rp
        if(any(i==[1,n])) then
          cc = cc - 1._rp
        endif
        if(any(j==[1,n])) then
          cc = cc - 1._rp
        endif
        if(any(k==[1,n])) then
          cc = cc - 1._rp
        endif
        matvalues(q) = cc
        call random_number(rn)
        rhsvalues(q) = rn
        solvalues(q) = 0._rp
      enddo
    enddo
  enddo
  call HYPRE_StructMatrixSetBoxValues(mat,lo,hi,1,[0],matvalues,ierr)
  call HYPRE_StructMatrixAssemble(mat,ierr)
  !
  call HYPRE_StructVectorSetBoxValues(rhs,lo,hi,rhsvalues,ierr)
  call HYPRE_StructVectorAssemble(rhs,ierr)
  call HYPRE_StructVectorSetBoxValues(sol,lo,hi,solvalues,ierr)
  call HYPRE_StructVectorAssemble(sol,ierr)
  !
  call HYPRE_StructSMGCreate(comm_hypre,solver,ierr)
  call HYPRE_StructSMGSetMaxIter(solver,10,ierr)
  call HYPRE_StructSMGSetTol(solver,1.e-10,ierr)
  call HYPRE_StructSMGSetup(solver,mat,rhs,sol,ierr)
  call HYPRE_StructSMGSolve(solver,mat,rhs,sol,ierr)
  !
  call HYPRE_StructVectorGetBoxValues(sol,lo,hi,solvalues,ierr)
  q = 0
  do k=1,n
    do j=1,n
      do i=1,n
        q = q + 1
        sol_3d(i,j,k) = solvalues(q)
      enddo
    enddo
  enddo
  sol_3d(0  ,:,:) = -sol_3d(1,:,:)
  sol_3d(n+1,:,:) = -sol_3d(n,:,:)
  sol_3d(:,0  ,:) = -sol_3d(:,1,:)
  sol_3d(:,n+1,:) = -sol_3d(:,n,:)
  sol_3d(:,:,0  ) = -sol_3d(:,:,1)
  sol_3d(:,:,n+1) = -sol_3d(:,:,n)
  q = 0
  do k=1,n
    do j=1,n
      do i=1,n
        q = q + 1
        lap = (sol_3d(i-1,j,k) -2._rp*sol_3d(i,j,k) + sol_3d(i+1,j,k) + &
               sol_3d(i,j-1,k) -2._rp*sol_3d(i,j,k) + sol_3d(i,j+1,k) + &
               sol_3d(i,j,k-1) -2._rp*sol_3d(i,j,k) + sol_3d(i,j,k+1) ) 
        print*,'right-hand-side = '      , rhsvalues(q), &
               'laplacian of solution = ', lap,          &
               'difference  = '          , lap-rhsvalues(q)
      enddo
    enddo
  enddo
  call MPI_FINALIZE(ierr)
  stop
end program poi2d
```

**Comment by p-costa** [comment]
PS: I left out a very important piece of information that I see now that caused confusion. I should have mentioned that I want to impose a *staggered* BC. For instance, for a zero-valued Dirichlet BC at x = 0, the BC would be (p_0 + p_1)/2 = 0 -> p_0 = - p_1.

So I guess this is not possible to do with the `HYPRE_StructMatrixSetConstantEntries` and `HYPRE_StructMatrixSetConstantValues`?

Pedro

**Comment by p-costa** [comment]
hello again, @rfalgout and all,

I hope that my last comment was clear. In other words, I want to prescribe the BC on the center of a grid cell, instead of on the face. This is not possible to do with `HYPRE_StructMatrixSetConstantEntries` and `HYPRE_StructMatrixSetConstantValues`, right? I can leave the issue open if you feel like this is something worth supporting in the future; otherwise, I can close it.

Thank you!
Pedro

**Comment by rfalgout** [comment]
Hi @p-costa .  I wasn't clear about what p_0 and p_1 were in your earlier comment.  However, if your discretization requires the off-diagonal stencil couplings to change near the boundary, then you cannot use `SetConstantEntries`.  If it's only the diagonal that changes, then there is an option you can use.  Hope this helps!

**Comment by p-costa** [comment]
Exactly, it requires that the boundary values of off-diagonal coefficients are changed near the boundary (which as you probably know is a very common requirement). Thank you, I'm going to close this.
