### ISSUE TITLE
"Mixed" Filename Mangling Issue

### ISSUE THREAD

**Issue by tmpnemophd** [hypre-space/hypre#20]
Hi,

I have been trying to compile **ex5f.f** with the Hypre library (MPI option ENABLED), and I suspect that my Fortran compiler is running into a situation where a single mangling macro cannot take care of all subroutine name formats. 

When I try to compile **ex5f.f** with the Hypre library built with the default options, I get the following error messages:

________________________________________________________________________________________________
Error	1	 error LNK2019: unresolved external symbol MPI_INIT referenced in function MAIN__	ex5f.obj	
Error	2	 error LNK2019: unresolved external symbol MPI_COMM_RANK referenced in function MAIN__	ex5f.obj	
Error	3	 error LNK2019: unresolved external symbol MPI_COMM_SIZE referenced in function MAIN__	ex5f.obj	
Error	4	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXCREATE referenced in function MAIN__	ex5f.obj	
Error	5	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXSETOBJECTTYPE referenced in function MAIN__	ex5f.obj	
Error	6	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXINITIALIZE referenced in function MAIN__	ex5f.obj	
Error	7	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXSETVALUES referenced in function MAIN__	ex5f.obj	
Error	8	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXASSEMBLE referenced in function MAIN__	ex5f.obj	
Error	9	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXGETOBJECT referenced in function MAIN__	ex5f.obj	
Error	10	 error LNK2019: unresolved external symbol HYPRE_IJVECTORCREATE referenced in function MAIN__	ex5f.obj	
Error	11	 error LNK2019: unresolved external symbol HYPRE_IJVECTORSETOBJECTTYPE referenced in function MAIN__	ex5f.obj	
Error	12	 error LNK2019: unresolved external symbol HYPRE_IJVECTORINITIALIZE referenced in function MAIN__	ex5f.obj	
Error	13	 error LNK2019: unresolved external symbol HYPRE_IJVECTORSETVALUES referenced in function MAIN__	ex5f.obj	
Error	14	 error LNK2019: unresolved external symbol HYPRE_IJVECTORASSEMBLE referenced in function MAIN__	ex5f.obj	
Error	15	 error LNK2019: unresolved external symbol HYPRE_IJVECTORGETOBJECT referenced in function MAIN__	ex5f.obj	
Error	16	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGCREATE referenced in function MAIN__	ex5f.obj	
Error	17	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETPRINTLEVEL referenced in function MAIN__	ex5f.obj	
Error	18	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETOLDDEFAULT referenced in function MAIN__	ex5f.obj	
Error	19	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETRELAXTYPE referenced in function MAIN__	ex5f.obj	
Error	20	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETRELAXORDER referenced in function MAIN__	ex5f.obj	
Error	21	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETNUMSWEEPS referenced in function MAIN__	ex5f.obj	
Error	22	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETMAXLEVELS referenced in function MAIN__	ex5f.obj	
Error	23	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETTOL referenced in function MAIN__	ex5f.obj	
Error	24	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETUP referenced in function MAIN__	ex5f.obj	
Error	25	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSOLVE referenced in function MAIN__	ex5f.obj	
Error	26	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGGETNUMITERATIONS referenced in function MAIN__	ex5f.obj	
Error	27	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGGETFINALRELTVRES referenced in function MAIN__	ex5f.obj	
Error	28	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGDESTROY referenced in function MAIN__	ex5f.obj	
Error	29	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXDESTROY referenced in function MAIN__	ex5f.obj	
Error	30	 error LNK2019: unresolved external symbol HYPRE_IJVECTORDESTROY referenced in function MAIN__	ex5f.obj	
Error	31	 error LNK2019: unresolved external symbol MPI_FINALIZE referenced in function MAIN__	ex5f.obj	
Error	32	 error LNK2001: unresolved external symbol MPI_DUP_FN	ex5f.obj	
Error	33	 error LNK2001: unresolved external symbol MPI_NULL_DELETE_FN	ex5f.obj	
Error	34	 error LNK2001: unresolved external symbol MPI_NULL_COPY_FN	ex5f.obj	
Error	35	 error LNK2001: unresolved external symbol MPI_COMM_DUP_FN	ex5f.obj	
Error	36	 error LNK2001: unresolved external symbol MPI_COMM_NULL_DELETE_FN	ex5f.obj	
Error	37	 error LNK2001: unresolved external symbol MPI_COMM_NULL_COPY_FN	ex5f.obj	
Error	38	 error LNK2001: unresolved external symbol MPI_WIN_DUP_FN	ex5f.obj	
Error	39	 error LNK2001: unresolved external symbol MPI_WIN_NULL_DELETE_FN	ex5f.obj	
Error	40	 error LNK2001: unresolved external symbol MPI_WIN_NULL_COPY_FN	ex5f.obj	
Error	41	 error LNK2001: unresolved external symbol MPI_TYPE_DUP_FN	ex5f.obj	
Error	42	 error LNK2001: unresolved external symbol MPI_TYPE_NULL_DELETE_FN	ex5f.obj	
Error	43	 error LNK2001: unresolved external symbol MPI_TYPE_NULL_COPY_FN	ex5f.obj	
Error	44	 error LNK2001: unresolved external symbol MPI_CONVERSION_FN_NULL	ex5f.obj	
Error	45	 fatal error LNK1120: 44 unresolved externals	x64\Release\Test_MPI.exe
________________________________________________________________________________________________

Based on my previous correspondence in this forum (thank you for the help again), I modified the **fortran.h** file to capitalize the subroutine names by inserting

"#define HYPRE_FMANGLE 4"

right before

/*-------------------------------------------------------
Define hypre_F90_NAME and hypre_F90_IFACE
 *-------------------------------------------------------*/

However, when I try to compile **ex5f.f** again after re-building the Hypre library, I get the following errors:

________________________________________________________________________________________________
Error	1	 error LNK2019: unresolved external symbol MPI_INIT referenced in function MAIN__	ex5f.obj	
Error	2	 error LNK2019: unresolved external symbol MPI_COMM_RANK referenced in function MAIN__	ex5f.obj	
Error	3	 error LNK2019: unresolved external symbol MPI_COMM_SIZE referenced in function MAIN__	ex5f.obj	
Error	4	 error LNK2019: unresolved external symbol MPI_FINALIZE referenced in function MAIN__	ex5f.obj	
Error	5	 error LNK2001: unresolved external symbol MPI_DUP_FN	ex5f.obj	
Error	6	 error LNK2001: unresolved external symbol MPI_NULL_DELETE_FN	ex5f.obj	
Error	7	 error LNK2001: unresolved external symbol MPI_NULL_COPY_FN	ex5f.obj	
Error	8	 error LNK2001: unresolved external symbol MPI_COMM_DUP_FN	ex5f.obj	
Error	9	 error LNK2001: unresolved external symbol MPI_COMM_NULL_DELETE_FN	ex5f.obj	
Error	10	 error LNK2001: unresolved external symbol MPI_COMM_NULL_COPY_FN	ex5f.obj	
Error	11	 error LNK2001: unresolved external symbol MPI_WIN_DUP_FN	ex5f.obj	
Error	12	 error LNK2001: unresolved external symbol MPI_WIN_NULL_DELETE_FN	ex5f.obj	
Error	13	 error LNK2001: unresolved external symbol MPI_WIN_NULL_COPY_FN	ex5f.obj	
Error	14	 error LNK2001: unresolved external symbol MPI_TYPE_DUP_FN	ex5f.obj	
Error	15	 error LNK2001: unresolved external symbol MPI_TYPE_NULL_DELETE_FN	ex5f.obj	
Error	16	 error LNK2001: unresolved external symbol MPI_TYPE_NULL_COPY_FN	ex5f.obj	
Error	17	 error LNK2001: unresolved external symbol MPI_CONVERSION_FN_NULL	ex5f.obj	
Error	18	 error LNK2019: unresolved external symbol MPI_Send referenced in function hypre_MPI_Send	HYPRE.lib(mpistubs.obj)	
Error	19	 error LNK2019: unresolved external symbol MPI_Recv referenced in function hypre_MPI_Recv	HYPRE.lib(mpistubs.obj)	
Error	20	 error LNK2019: unresolved external symbol MPI_Get_count referenced in function hypre_MPI_Get_count	HYPRE.lib(mpistubs.obj)	
Error	21	 error LNK2019: unresolved external symbol MPI_Isend referenced in function hypre_MPI_Isend	HYPRE.lib(mpistubs.obj)	
Error	22	 error LNK2019: unresolved external symbol MPI_Irsend referenced in function hypre_MPI_Irsend	HYPRE.lib(mpistubs.obj)	
Error	23	 error LNK2019: unresolved external symbol MPI_Irecv referenced in function hypre_MPI_Irecv	HYPRE.lib(mpistubs.obj)	
Error	24	 error LNK2019: unresolved external symbol MPI_Wait referenced in function hypre_MPI_Wait	HYPRE.lib(mpistubs.obj)	
Error	25	 error LNK2019: unresolved external symbol MPI_Test referenced in function hypre_MPI_Test	HYPRE.lib(mpistubs.obj)	
Error	26	 error LNK2019: unresolved external symbol MPI_Request_free referenced in function hypre_MPI_Request_free	HYPRE.lib(mpistubs.obj)	
Error	27	 error LNK2019: unresolved external symbol MPI_Waitany referenced in function hypre_MPI_Waitany	HYPRE.lib(mpistubs.obj)	
Error	28	 error LNK2019: unresolved external symbol MPI_Waitall referenced in function hypre_MPI_Waitall	HYPRE.lib(mpistubs.obj)	
Error	29	 error LNK2019: unresolved external symbol MPI_Testall referenced in function hypre_MPI_Testall	HYPRE.lib(mpistubs.obj)	
Error	30	 error LNK2019: unresolved external symbol MPI_Iprobe referenced in function hypre_MPI_Iprobe	HYPRE.lib(mpistubs.obj)	
Error	31	 error LNK2019: unresolved external symbol MPI_Probe referenced in function hypre_MPI_Probe	HYPRE.lib(mpistubs.obj)	
Error	32	 error LNK2019: unresolved external symbol MPI_Send_init referenced in function hypre_MPI_Send_init	HYPRE.lib(mpistubs.obj)	
Error	33	 error LNK2019: unresolved external symbol MPI_Recv_init referenced in function hypre_MPI_Recv_init	HYPRE.lib(mpistubs.obj)	
Error	34	 error LNK2019: unresolved external symbol MPI_Startall referenced in function hypre_MPI_Startall	HYPRE.lib(mpistubs.obj)	
Error	35	 error LNK2019: unresolved external symbol MPI_Type_contiguous referenced in function hypre_MPI_Type_contiguous	HYPRE.lib(mpistubs.obj)	
Error	36	 error LNK2019: unresolved external symbol MPI_Type_vector referenced in function hypre_MPI_Type_vector	HYPRE.lib(mpistubs.obj)	
Error	37	 error LNK2019: unresolved external symbol MPI_Type_create_hvector referenced in function hypre_MPI_Type_hvector	HYPRE.lib(mpistubs.obj)	
Error	38	 error LNK2019: unresolved external symbol MPI_Type_create_struct referenced in function hypre_MPI_Type_struct	HYPRE.lib(mpistubs.obj)	
Error	39	 error LNK2019: unresolved external symbol MPI_Get_address referenced in function hypre_MPI_Address	HYPRE.lib(mpistubs.obj)	
Error	40	 error LNK2019: unresolved external symbol MPI_Type_commit referenced in function hypre_MPI_Type_commit	HYPRE.lib(mpistubs.obj)	
Error	41	 error LNK2019: unresolved external symbol MPI_Type_free referenced in function hypre_MPI_Type_free	HYPRE.lib(mpistubs.obj)	
Error	42	 error LNK2019: unresolved external symbol MPI_Barrier referenced in function hypre_MPI_Barrier	HYPRE.lib(mpistubs.obj)	
Error	43	 error LNK2019: unresolved external symbol MPI_Bcast referenced in function hypre_MPI_Bcast	HYPRE.lib(mpistubs.obj)	
Error	44	 error LNK2019: unresolved external symbol MPI_Gather referenced in function hypre_MPI_Gather	HYPRE.lib(mpistubs.obj)	
Error	45	 error LNK2019: unresolved external symbol MPI_Gatherv referenced in function hypre_MPI_Gatherv	HYPRE.lib(mpistubs.obj)	
Error	46	 error LNK2019: unresolved external symbol MPI_Scatter referenced in function hypre_MPI_Scatter	HYPRE.lib(mpistubs.obj)	
Error	47	 error LNK2019: unresolved external symbol MPI_Scatterv referenced in function hypre_MPI_Scatterv	HYPRE.lib(mpistubs.obj)	
Error	48	 error LNK2019: unresolved external symbol MPI_Allgather referenced in function hypre_MPI_Allgather	HYPRE.lib(mpistubs.obj)	
Error	49	 error LNK2019: unresolved external symbol MPI_Allgatherv referenced in function hypre_MPI_Allgatherv	HYPRE.lib(mpistubs.obj)	
Error	50	 error LNK2019: unresolved external symbol MPI_Alltoall referenced in function hypre_MPI_Alltoall	HYPRE.lib(mpistubs.obj)	
Error	51	 error LNK2019: unresolved external symbol MPI_Op_create referenced in function hypre_MPI_Op_create	HYPRE.lib(mpistubs.obj)	
Error	52	 error LNK2019: unresolved external symbol MPI_Op_free referenced in function hypre_MPI_Op_free	HYPRE.lib(mpistubs.obj)	
Error	53	 error LNK2019: unresolved external symbol MPI_Reduce referenced in function hypre_MPI_Reduce	HYPRE.lib(mpistubs.obj)	
Error	54	 error LNK2019: unresolved external symbol MPI_Allreduce referenced in function hypre_MPI_Allreduce	HYPRE.lib(mpistubs.obj)	
Error	55	 error LNK2019: unresolved external symbol MPI_Scan referenced in function hypre_MPI_Scan	HYPRE.lib(mpistubs.obj)	
Error	56	 error LNK2019: unresolved external symbol MPI_Comm_group referenced in function hypre_MPI_Comm_group	HYPRE.lib(mpistubs.obj)	
Error	57	 error LNK2019: unresolved external symbol MPI_Group_incl referenced in function hypre_MPI_Group_incl	HYPRE.lib(mpistubs.obj)	
Error	58	 error LNK2019: unresolved external symbol MPI_Group_free referenced in function hypre_MPI_Group_free	HYPRE.lib(mpistubs.obj)	
Error	59	 error LNK2019: unresolved external symbol MPI_Comm_size referenced in function hypre_MPI_Allgatherv	HYPRE.lib(mpistubs.obj)	
Error	60	 error LNK2019: unresolved external symbol MPI_Comm_rank referenced in function hypre_MPI_Comm_rank	HYPRE.lib(mpistubs.obj)	
Error	61	 error LNK2019: unresolved external symbol MPI_Comm_dup referenced in function hypre_MPI_Comm_dup	HYPRE.lib(mpistubs.obj)	
Error	62	 error LNK2019: unresolved external symbol MPI_Comm_create referenced in function hypre_MPI_Comm_create	HYPRE.lib(mpistubs.obj)	
Error	63	 error LNK2019: unresolved external symbol MPI_Comm_split referenced in function hypre_MPI_Comm_split	HYPRE.lib(mpistubs.obj)	
Error	64	 error LNK2019: unresolved external symbol MPI_Comm_free referenced in function hypre_MPI_Comm_free	HYPRE.lib(mpistubs.obj)	
Error	65	 error LNK2019: unresolved external symbol MPI_Wtime referenced in function hypre_MPI_Wtime	HYPRE.lib(mpistubs.obj)	
Error	66	 error LNK2019: unresolved external symbol MPI_Wtick referenced in function hypre_MPI_Wtick	HYPRE.lib(mpistubs.obj)	
Error	67	 error LNK2019: unresolved external symbol MPI_Init referenced in function hypre_MPI_Init	HYPRE.lib(mpistubs.obj)	
Error	68	 error LNK2019: unresolved external symbol MPI_Finalize referenced in function hypre_MPI_Finalize	HYPRE.lib(mpistubs.obj)	
Error	69	 error LNK2019: unresolved external symbol MPI_Abort referenced in function hypre_MPI_Abort	HYPRE.lib(mpistubs.obj)	
Error	70	 fatal error LNK1120: 69 unresolved externals	x64\Release\Test_MPI.exe	
________________________________________________________________________________________________

As can be seen, the compiler now has trouble finding subroutines whose names are made up of both lower case and capital letters.
 
Would there be anything I can do to resolve this issue? For your info, the MPI is provided by Microsoft MPI and I am using Visual Studio.

Thank you.

**Comment by rfalgout** [comment]
These are MPI issues that don't have anything to do with name mangling in hypre (as far as I can see).  The hypre library is looking for the C MPI routines while your main program is looking for the Fortran MPI routines, but it's finding neither.  My guess is that you probably don't have the MPI library on your link line.  You might try looking at some forums that discuss how to use MPI with Visual Studio.

Hope this help!  Sorry I couldn't provide a fix.
