### ISSUE TITLE
Question on Hypre GPU Assembly

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#202]
Hi,
I compiled Hypre with CUDA and UVM.  Can the Hypre APIs:
HYPRE_IJMatrixSetValues
HYPRE_IJMatrixAddToValues
HYPRE_IJVectorSetValues
HYPRE_IJVectorAddToValues
 
accept pointers to GPU memory for the rows, columns, and values?
-Paul

**Comment by liruipeng** [comment]
@PaulMullowney They all accept GPU pointers (even non-UVM). Please let us know if it works.

**Comment by PaulMullowney** [comment]
If the memory is strictly on the GPU and Hypre is compiled for GPU and UVM, then these APIs do not work.  GDB shows:
#0     hypre_PrefixSumInt (nvals=208109, vals=0x2000d5ae4280, sums=0x838bb100) at HYPRE_IJMatrix.c:386
386	            sums[i] = sums[i-1] + vals[i-1];
