### ISSUE TITLE
Does Struct Stencil support the stencil in spectral method.

### ISSUE THREAD

**Issue by ztdepztdep** [hypre-space/hypre#205]
Dear sir, in my spectral code, the neighbors of (I,j) is all the nodes along the x and y direction. How to set the Struct Stencil in this situation?

**Comment by rfalgout** [comment]
Hi @ztdepztdep .  The hypre library isn't designed for non-sparse settings such as with spectral methods.  Sorry we can't be of more help.  Thanks!
