### ISSUE TITLE
Cannot build/install shared libraries

### ISSUE THREAD

**Issue by vdilecce** [hypre-space/hypre#208]
In HYPRE 2.20.0, the CMake project fails to build shared libraries (and install them, on Windows).

**Build**

In `src/CMakeLists.txt`, variable `BUILD_SHARED_LIBS` must be set before calling `add_library(HYPRE)`, otherwise it will not have any effect. This could be worked around by specifying both `-DBUILD_SHARED_LIBS=ON` and `-DHYPRE_ENABLED_SHARED=ON` from command-line to CMake.

**Install**

Even if shared libraries are built, the `install(TARGETS)` command does not install the DLLs on Windows, which are identified by the [`RUNTIME`](https://cmake.org/cmake/help/latest/command/install.html#targets) keyword (missing). The following would need added to the `install(TARGETS)` command:

`RUNTIME DESTINATION "${CMAKE_INSTALL_LIBDIR}"`
or (to place them in the `bin` subdirectory):
`RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"`

**Comment by vitlav** [comment]
Can you send a pull request?
