### ISSUE TITLE
Integer Overflow in HYPRE_EuclidSetup

### ISSUE THREAD

**Issue by ryagal** [hypre-space/hypre#210]
Hello,

The preconditioner setup for Euclid occasionally crashes for matrices with about 1 to 5 million unknowns. For example, it will successfully setup the preconditioner for a matrix with 1, 2, 4, 8, 32, 64 processes but crash with 16. The problem occurs due to integer overflow in either Hash_i_dhLookup or Hash_i_dhInsert. The problem is that

    idx = (start + i*inc) % size;

can overflow when performing i*inc and produce a negative value for idx which is supposed to be a positive. Casting to 64 bit integers for these operations fixes the problem (when not building with BigInts), but I'm not sure how this should be handled in the case where HYPRE is built with BigInts.

**Comment by liruipeng** [comment]
> Hello,
> 
> The preconditioner setup for Euclid occasionally crashes for matrices with about 1 to 5 million unknowns. For example, it will successfully setup the preconditioner for a matrix with 1, 2, 4, 8, 32, 64 processes but crash with 16. The problem occurs due to integer overflow in either Hash_i_dhLookup or Hash_i_dhInsert. The problem is that
> 
> ```
> idx = (start + i*inc) % size;
> ```
> 
> can overflow when performing i*inc and produce a negative value for idx which is supposed to be a positive. Casting to 64 bit integers for these operations fixes the problem (when not building with BigInts), but I'm not sure how this should be handled in the case where HYPRE is built with BigInts.

@ryagal Can you please checkout branch https://github.com/hypre-space/hypre/tree/Euclid-FIX, and let us know if it fixes the problem? Thanks!

-Ruipeng

**Comment by ryagal** [comment]
@liruipeng Hi Ruipeng, sorry about the delayed response. I've verified that the Euclid-FIX branch fixed the problem for the matrices I was encountering this issue with. I see that you merged the changes today, and will close this issue. Thanks for your help!
