### ISSUE TITLE
How to solve a AX=B with multiple righ hand vectors?

### ISSUE THREAD

**Issue by ztdepztdep** [hypre-space/hypre#211]
Dear friends:
    I am working in IJ interface with flexgmres solver. and I want to know How to solve a AX=B with multiple righ hand vectors?

**Comment by liruipeng** [comment]
@ztdepztdep We don't have the option of solving with multiple right-hand sides simultaneously. So you have to solve them one after another. If you use preconditioner, you can setup it once for all.
