### ISSUE TITLE
Fortran interface for Hypre-ILU

### ISSUE THREAD

**Issue by CZHU20** [hypre-space/hypre#212]
Hi Hypre team,

Thanks for the wonderful software.

We solve our problem with GMRES and am experimenting with different preconditioners (mostly different flavors of ILU). The code is in Fortran. After checking the Hypre source code,  I saw that the Fortran interface of GMRES currently supports four preconditioners (ds, amg, pilut, parasails and euclid). I was wondering why Hypre-ILU is not supported in Fortran. It seems to be a very interesting choice. While we are at it, I would also greatly appreciate it if you could provide some insights on the following issues:

1) Is thre any build-in reordering in Euclid? And, what is its strategy in dealing with zero pivots in Hypre-ILU and Euclid?
2) I know this can be problem specific, but is there a rule of thumb in choosing between Euclid and Hypre-ILU?

Many thanks!

**Comment by oseikuffuor1** [comment]
Hi @CZHU20, as you noted, hypre_ILU is not currently supported in the Fortran interface. It is on our to-do list and will be addressed soon. To answer your remaining questions:
1.  Euclid only assumes the natural ordering passed in by the user. It does not do any explicit reordering of the matrix prior to the factorization, if that is what you mean. hypre_ILU does support RCM (local) reordering. 
1b. Nothing special is done to take care of zero pivots in Euclid, as far as I know. hypre_ILU sets small (near zero) diagonals to 1.0e-6.
2. Both Euclid and hypre_ILU should give similar convergence behavior for the ilu(k) variants of ILU. However, hypre_ILU also supports parallel ILUT (Euclid's ILUT is sequential only), multiple flavors of parallel ILU (including 2-level ILU), and faster setup time than Euclid.

Hope these answer your questions.

**Comment by CZHU20** [comment]
Hi Daniel, thanks for the quick response! They are very helpful.
