### ISSUE TITLE
HYPRE produces different results using different numbers of processors when Neumann boundary condition is enforced

### ISSUE THREAD

**Issue by suguanting** [hypre-space/hypre#213]
Dear HYPRE developers,

I am trying to solve a Poisson equation using GMRES solver with SMG preconditioners in Struct interface. And surprisingly HYPRE produces different results using different numbers of processors. More specifically, this problem only occur when Neumann boundary conditions are enforced on a boundary that is to be partitioned and assigned to different processors. When Dirichlet conditions are used on such boundaries, HYPRE will work as expected.

For example, for a model problem I am dealing with, when I uses Neumann conditions on the bottom boundary and assign grid points with I<IM/2 (IM=363 in this case) to processor 0 and I>=IM/2 to processor 1, the produced results differs from the one in which only one processor is used as shown below (PHI2-1 indicates the difference), which is well beyond the convergence criteria.
![image](https://user-images.githubusercontent.com/14161266/94888214-f4074280-04aa-11eb-828a-ba9e2188af0a.png)

Right now in my program, the grid points on the boundary layer are not included in the domain that is provided to HYPRE, which is consistent with ex3. I adjust the stencil entry of grid points adjacent to the boundary layer and their RHS according to the boundary condition.  Different type of boundary conditions are enforced using a unified Robin type format as PHI_1=a*PHI_0+b (e.g., a=0,b=0 for Dirichlet; a=1,b=0 for homogenous Neumann). 

I think the problem is probably due to that the current boundary condition enforcement, which should be correct as it worked before using other solvers, does not suit HYPRE. Could you provide some examples on how to implement Neumann type boundary conditions in Struct interface? Besides any comment on the boundary conditions, please also let me know if you think the real problem lies elsewhere.

Thank you in advance,

Guanting

**Comment by rfalgout** [comment]
Hi @suguanting .  Try using the `HYPRE_StructMatrixPrint()` and `HYPRE_StructVectorPrint()` routines on both 1 and multiple processes to verify that you are getting the same system for the parallel runs.  If you are converging in both cases, but getting different results, your system is probably not set up correctly (probably along the bottom boundary).  Hope this helps!

**Comment by suguanting** [comment]
Hi @rfalgout , thanks for the tip! Now the problem is solved.
