### ISSUE TITLE
MPI_Abort and insufficient virtual memory

### ISSUE THREAD

**Issue by suguanting** [hypre-space/hypre#214]
Dear HYPRE developers,

I am using HYPRE in WIN 10. The compiler is Intel Fortran for Visual Studio 2019. Recently, I often encountered errors that involve `MPI_Abort `and `insufficient virtual memory` as follows,
```
 Hello right before HYPRE from process:            1 of            2
 Hello right before HYPRE from process:            0 of            2

 Iterations =            8
 Final Relative Residual Norm =   9.329738133153583E-007
 -----------------------------------------------------
 Hello right before HYPRE from process:            0 of            2
 Hello right before HYPRE from process:            1 of            2
Abort(-1) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
```
and
```
 Hello right before HYPRE from process:            0 of            2
 Hello right before HYPRE from process:            1 of            2

 Iterations =           11
 Final Relative Residual Norm =   2.324650022168671E-007
 -----------------------------------------------------
forrtl: severe (41): insufficient virtual memory
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FF9F85F06FB  Unknown               Unknown  Unknown
STD18_FORTRAN_HYP  00007FF69C5C45CB  Unknown               Unknown  Unknown
STD18_FORTRAN_HYP  00007FF69C5A40EA  Unknown               Unknown  Unknown
STD18_FORTRAN_HYP  00007FF69C5A8351  Unknown               Unknown  Unknown
STD18_FORTRAN_HYP  00007FF69C5E77FE  Unknown               Unknown  Unknown
STD18_FORTRAN_HYP  00007FF69C696DC4  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFA264F7BD4  Unknown               Unknown  Unknown
ntdll.dll          00007FFA266ECE51  Unknown               Unknown  Unknown

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 25300 RUNNING AT DESKTOP-9EBQMSS
=   EXIT STATUS: -1 (ffffffff)
===================================================================================
```

I would be very happy to provide more specific details or narrow the problem down as much as I could before bring it to you. However, this problem is annoying in the way that it cannot be reproduced. When running a same exe on the same PC using the same input, I could end up getting different types of errors that occured at different time steps, i.e., sometimes MPI_Abort is called, sometimes insufficient virtual memory occured, and the time step at which they occurred is not fixed.  I tried using `HYPRE_ClearAllErrors` at the end of each iteration as suggested in https://github.com/hypre-space/hypre/issues/94. However, I can still get `MPI_Abort ` type error.

The reason I think HYPRE is involved is that both error occurred only when HYPRE functions were called. It would be of great help if you could give me some general idea on what could possibly cause these errors for HYPRE. 

Below is the code for the solver configuration:
```
            ! Create an empty GMRES Struct solver
            CALL HYPRE_StructGMRESCreate(MPI_COMM_F, SOLVER_MG, IERR)

            ! Set some parameters
            CALL HYPRE_StructGMRESSetMaxIter(SOLVER_MG, 50, IERR)
            CALL HYPRE_StructGMRESSetTol(SOLVER_MG, 1.0D-6, IERR)
            !CALL HYPRE_StructGMRESSetPrintLevel(SOLVER_MG, 2, IERR)!/* PRINT EACH CG ITERATION */
            !CALL HYPRE_StructGMRESSetLogging(SOLVER_MG, 1, IERR)

            ! Use symmetric SMG as preconditioner
            CALL HYPRE_StructSMGCreate(MPI_COMM_F, PRECOND_MG, IERR)
            CALL HYPRE_StructSMGSetMemoryUse(PRECOND_MG, 0, IERR)
            CALL HYPRE_StructSMGSetMaxIter(PRECOND_MG, 1, IERR)
            CALL HYPRE_StructSMGSetTol(PRECOND_MG, 0.0, IERR)
            CALL HYPRE_StructSMGSetZeroGuess(PRECOND_MG, IERR)
            CALL HYPRE_StructSMGSetNumPreRelax(PRECOND_MG, 1, IERR)
            CALL HYPRE_StructSMGSetNumPostRelax(PRECOND_MG, 1, IERR)

            ! Setup and solve
            CALL HYPRE_StructGMRESSetPrecond(SOLVER_MG, 0, PRECOND_MG, IERR)
            CALL HYPRE_StructGMRESSetup(SOLVER_MG, A_MG, B_MG, X_MG, IERR)
            CALL HYPRE_StructGMRESSolve(SOLVER_MG, A_MG, B_MG, X_MG, IERR)

            ! Get some info on the run
            CALL HYPRE_StructGMRESGetNumIteratio(SOLVER_MG,NUM_ITERATIONS_MG,IERR)
            CALL HYPRE_StructGMRESGetFinalRelati(SOLVER_MG,FINAL_RES_NORM_MG,IERR)
```

Thanks in advance,
Guanting

**Comment by rfalgout** [comment]
Hi @suguanting .  This sounds like a classic memory problem, possibly a memory leak in this case (are you destroying hypre objects between time steps?).  The easiest way to track down these sorts of errors is to use a memory checking tool.  Unfortunately, I don't know what to suggest for your Windows platform.  Does Visual Studio provide something?  We run our code through a tool called valgrind nightly to check for memory issues.  This is a tool that is available on Linux platforms.

Hope this helps!  Sorry I can't be more specific about what to recommend here.

**Comment by suguanting** [comment]
Hi @rfalgout , thanks for your advice.  The problem is now solved by ensuring that global objects like Struct Matrix `A` are initialized only once.

One last thing to check, is it necessary to create and destroy a global solver object and a global preconditioner object each time when hypre is used to produce a solution? For my problem, Struct Matrix `A` stays the same, only RHS `b` change every time when hypre is used. Can I do things like below, and will it make any difference in terms of efficiency by using the same global solver object and global preconditioner object the whole time?
```
    !Create and configure the solver
    HYPRE_StructGMRESCreate...
    ...

    !Create and configure the preconditioner
    HYPRE_StructSMGCreate...
    ...

    Loop begin
    =====================
    !b is changed
    HYPRE_StructVectorSetBoxValues...
    !Setup and solve
    HYPRE_StructGMRESSetPrecond...
    HYPRE_StructGMRESSetup...
    HYPRE_StructGMRESSolve...
    =====================
    Loop end

    !Destroy the solver and the preconditioner
    HYPRE_StructSMGDestroy...
    HYPRE_StructGMRESDestroy...
```

Thanks in advance,

Guanting

**Comment by rfalgout** [comment]
Hi @suguanting .  It is often a good idea to reuse the solver object for several solves to amortize the cost of setup.  For example, if you've only got different right-hand-sides, then you only need to do setup once.  If you are in a time-dependent loop where the matrix is changing at each time step but not by too much, then you may be able to get away with using the same setup for some number of solves.  In your example loop, you should not call `GMRESSetup` inside the loop, just once before the loop.  Hope this helps!

**Comment by suguanting** [comment]
Hi @rfalgout , thanks for the reply. So below should be the most efficient outline for my problem where only RHS `b` changes at each time step :

```
1.Create and configure the solver and preconditioner
2.Set up the solver and preconditioner (HYPRE_StructGMRESSetPrecond...HYPRE_StructGMRESSetup...)
3.change b
4.solve (HYPRE_StructGMRESSolve...)
5.if want to solve one more time, go to 3; if finished, destroy the solver and preconditioner
```
So, even though RHS `b` is an input for the HYPRE_StructGMRESSetup funtion, the process is actually not very sensitive on RHS `b`, am I understanding correctly? And what kind of change in RHS `b` could be considered as "not too much"?

Thanks in advance,

Guanting

**Comment by rfalgout** [comment]
Yes, this pseudocode is correct.  Also, you can change the RHS values as much as you like.  My earlier comments about "not too much" were about the system matrix A.  Thanks!

**Comment by suguanting** [comment]
Thanks for the clarification, that helps a lot!
