### ISSUE TITLE
Cannot find mpi.h

### ISSUE THREAD

**Issue by bensworth** [hypre-space/hypre#217]
Hi hypre team, I am trying to install MPI and hypre on a new Mac laptop. I installed the latest gcc via homebrew, and manually cloned Open-MPI and installed it into a local directory. I added this install directory, as well as the /bin, /include/ and /lib directories to my PATH variable. 

When I configure and make hypre, it finds the mpicc compiler, I make it to utilities, then get MPI errors
```
Making utilities ...
/usr/local/bin/gcc -O  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -c F90_HYPRE_error.c
/usr/local/bin/gcc -O  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -c F90_HYPRE_general.c
/usr/local/bin/gcc -O  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -c HYPRE_version.c
/usr/local/bin/gcc -O  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -c amg_linklist.c
/usr/local/bin/gcc -O  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -c binsearch.c
/usr/local/bin/gcc -O  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -c exchange_data.c
/usr/local/bin/gcc -O  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -c fortran_matrix.c
/usr/local/bin/gcc -O  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -c hypre_ap.c
/usr/local/bin/gcc -O  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -c hypre_complex.c
/usr/local/bin/gcc -O  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -c hypre_error.c
/usr/local/bin/gcc -O  -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.    -c hypre_hopscotch_hash.c
In file included from _hypre_utilities.h:7,
                 from F90_HYPRE_error.c:8:
HYPRE_utilities.h:20:10: fatal error: mpi.h: No such file or directory
   20 | #include "mpi.h"
      |          ^~~~~~~

```
However, if I make a simple hello world example with mpi.h, I can compile and run from the command line fine via `mpicxx -o test test.cpp' and `mpirun -n 4 ./test`. It seems my PATH is not being passed to the hypre makefile. I saw the configure flag to pass in MPI dir, inc, lib, but I have no idea what libraries are supposed to be linked.

**Comment by victorapm** [comment]
Hi @bensworth,

it seems that the configure script did not find the MPI C compiler, make is using `/usr/local/bin/gcc` instead. Can you look at the output of `config.log`? A possible fix is to pass manually CC=mpicc and `--with-MPI-include --with-MPI-libs` options to the configure script.

Hope this helps,
Victor

**Comment by bensworth** [comment]
Thanks Victor! CC has been exported specifically to be `/usr/local/bin/gcc`, I thought it would just have a different MPI compiler. Clearing that variable fixed things.
