### ISSUE TITLE
Bug report: build by mingw

### ISSUE THREAD

**Issue by rockydut** [hypre-space/hypre#219]
When I build hypre by mingw with OpenMP, it shows error in three files:  red_black_gs.h,  _hypre_struct_mv.h and include\_hypre_struct_mv.h.
I found the main error is the defination of Pragma(x):
#ifdef HYPRE_USING_OPENMP
#define HYPRE_BOX_REDUCTION
#ifdef WIN32
#define Pragma(x) __pragma(HYPRE_XSTR(x))
#else
#define Pragma(x) _Pragma(HYPRE_XSTR(x))
#endif
#define OMPRB1 Pragma(omp parallel for private(HYPRE_REDBLACK_PRIVATE) HYPRE_BOX_REDUCTION HYPRE_SMP_SCHEDULE)
#else
#define OMPRB1
#endif

For mingw in windows, the defination of #define Pragma(x) __pragma(HYPRE_XSTR(x)) is incorrect. It should be defined #define Pragma(x) _Pragma(HYPRE_XSTR(x)).

When I compile hypre, I change it to:
#ifdef HYPRE_USING_OPENMP
#define HYPRE_BOX_REDUCTION
//#ifdef WIN32
//#define Pragma(x) __pragma(HYPRE_XSTR(x))
//#else
#define Pragma(x) _Pragma(HYPRE_XSTR(x))
//#endif
#define OMPRB1 Pragma(omp parallel for private(HYPRE_REDBLACK_PRIVATE) HYPRE_BOX_REDUCTION HYPRE_SMP_SCHEDULE)
#else
#define OMPRB1
#endif

It compile correctly.

**Comment by liruipeng** [comment]
The fix has been merged. Thanks!
