### ISSUE TITLE
GPU BoomerAMG setup

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#220]
Hi,
I compiled Hypre with CUDA and UVM. Will Boomer AMG setup functions (or some parts of them) run on the GPU by default? Is there anything I need to do to to ensure this happens?

I've run an example through nvvp and It appears that only the GMRES solver and smoothers are running on device.
-Paul

**Comment by PaulMullowney** [comment]
As a follow up, I printed out the memory location of the matrices, just prior to 
hypre_BoomerAMGCoarsenPMISDevice/Host in par_coarsen.c
It always say either HOST or HOST_PINNED, and not UNIFIED as I would expect given how I compiled Hypre.

**Comment by liruipeng** [comment]
> Hi,
> I compiled Hypre with CUDA and UVM. Will Boomer AMG setup functions (or some parts of them) run on the GPU by default? Is there anything I need to do to to ensure this happens?
> 
> I've run an example through nvvp and It appears that only the GMRES solver and smoothers are running on device.
> -Paul

Please add `hypre_HandleDefaultExecPolicy(hypre_handle()) = HYPRE_EXEC_DEVICE`, after `HYPRE_Init();`

**Comment by PaulMullowney** [comment]
Ok. I've done that. The solvers converge successfully on 1 GPU, but not on 2. Is this expected?

**Comment by ulrikeyang** [comment]
No. Which problem are you trying to solve? And which settings are you using for BoomerAMG?

**Comment by PaulMullowney** [comment]
Pressure Equation in CFD. I could share matrix market files with the matrix and rhs if that would help.

Settings are:    
    bamg_max_levels: 7
    bamg_coarsen_type: 8
    bamg_interp_type: 6
    bamg_relax_type: 11
    bamg_num_sweeps: 2
    bamg_cycle_type: 1
    bamg_relax_order: 0

    bamg_trunc_factor: 0.1
    bamg_agg_num_levels: 2
    bamg_agg_interp_type: 4
    bamg_agg_pmax_elmts: 3
    bamg_pmax_elmts: 3
    bamg_strong_threshold: 0.25
    bamg_non_galerkin_tol: 0.05
    bamg_non_galerkin_level_tols:
       levels: [0, 1, 2]
       tolerances: [0.0, 0.01, 0.03 ]

**Comment by ulrikeyang** [comment]
Is 11 your smoother?
Is this converging when you use CPU for the setup phase?
You are using a lot of settings that will use CPU-only functions, so it is possible that there are some connections not working properly, although they should work, but I would expect it to be slow.

**Comment by PaulMullowney** [comment]
Yes, 11 is the Two Stage Gauss Seidel smoother. Solvers converge on the GPU (for setup on the CPU), on up to 144 GPUs.  What CPU settings should I remove?

**Comment by PaulMullowney** [comment]
One other point. The input to HYPRE_IJMatrixSet/AddToValues() (and similar for IJVector) are pointers to UVM memory.

**Comment by ulrikeyang** [comment]
The non Galerkin options will not work on the GPU, and agg_interp_type should now be 5 or 7.
Try this and see if this works.

**Comment by ulrikeyang** [comment]
It would be best if Ruipeng comments on the pointers to UVM question!

**Comment by liruipeng** [comment]
> One other point. The input to HYPRE_IJMatrixSet/AddToValues() (and similar for IJVector) are pointers to UVM memory.

UVM pointers should work fine with HYPRE_IJMatrix/VectorSet/AddToValues.

**Comment by PaulMullowney** [comment]
Settings are now. I also tried agg_interp_type: 5
    bamg_max_levels: 7
    bamg_coarsen_type: 8
    bamg_interp_type: 6
    bamg_relax_type: 11
    bamg_num_sweeps: 2
    bamg_cycle_type: 1
    bamg_relax_order: 0
    bamg_trunc_factor: 0.1
    bamg_agg_num_levels: 2
    bamg_agg_interp_type: 7
    bamg_agg_pmax_elmts: 3
    bamg_pmax_elmts: 3
    bamg_strong_threshold: 0.25

No luck.

**Comment by ulrikeyang** [comment]
Can you run setup on the CPU, but set bamg_interp_type to 17, to see if this converges?

**Comment by PaulMullowney** [comment]
Found it. It was a bug in my code. This small problem converges on 2GPUs and the performance looks good. Thanks!

**Comment by liruipeng** [comment]
This issue seems to have been resolved. So I close it.
