### ISSUE TITLE
Is it possible to only store the upper or lower triangle matrix for the symmetric matrix?

### ISSUE THREAD

**Issue by rockydut** [hypre-space/hypre#229]
For many problem, the matrix is symmetrical.
Is it possible to only store the upper or lower triangle matrix for the symmetric matrix?
Or any other package can deal with such problem to solve linear equation?

**Comment by rfalgout** [comment]
@rockydut .  This is only possible with StructMatrix, and partially so with SStructMatrix.  We considered the possibility of doing this in an unstructured matrix a long long time ago, but the advantages in the parallel setting were not obvious relative to the effort required (in serial, this is a good idea).
