### ISSUE TITLE
CF/FC Relax 18

### ISSUE THREAD

**Issue by liruipeng** [hypre-space/hypre#235]
@rfalgout @ulrikeyang 

This line doesn't seem correct to me,
https://github.com/hypre-space/hypre/blob/2bc4228eca313f0eeb4fdb6bf1baa81ad8a7e317/src/parcsr_ls/par_cycle.c#L462

What we want here is CF/FC relaxations, CF down and FC up. So, we should have `if (cycle_param < 2)` instead of `if (cycle_type < 2)`? `cycle_param` controls the down/up/coarsest cycle, whereas `cycle_type` is for V-/W-cycles.

Any ideas?

Thanks

-Ruipeng

**Comment by rfalgout** [comment]
@ulrikeyang is more familiar with this code than me, so I'll leave it to her to comment.

**Comment by ulrikeyang** [comment]
@liruipeng @rfalgout 
Ruipeng is right. This should be cycle_param. Thanks for catching this.
