### ISSUE TITLE
installation Hypre 2.14.0 into petsc 3.9.3 on Ubuntu 18.4

### ISSUE THREAD

**Issue by tarekhussein** [hypre-space/hypre#241]
i have a problem in installing Hypre 2.14.0 on Ubuntu 18.4, the following error appears:

************************************************************************                                                  UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):                                     -------------------------------------------------------------------------------                                         Error during download/extract/detection of HYPRE:                                                                       Unable to download hypre                                                                                                Could not execute "git clone https://github.com/LLNL/hypre /home/tarek/petsc-3.9.3/arch-linux2-c-opt/externalpackages/git.hypre":                                                                                                               Cloning into '/home/tarek/petsc-3.9.3/arch-linux2-c-opt/externalpackages/git.hypre'...                                  remote: Repository not found.                                                                                           fatal: repository 'https://github.com/LLNL/hypre/' not found                                                            Unable to download package HYPRE from: git://https://github.com/LLNL/hypre                                              * If URL specified manually - perhaps there is a typo?                                                                  * If your network is disconnected - please reconnect and rerun ./configure                                              * Or perhaps you have a firewall blocking the download                                                                  * You can run with --with-packages-dir=/adirectory and ./configure will instruct you what packages to download manually * or you can download the above URL manually, to /yourselectedlocation                                                    and use the configure option:                                                                                           --download-hypre=/yourselectedlocation                                                                                file could not be opened successfully                                                                                   Downloaded package HYPRE from: https://github.com/LLNL/hypre/archive/v2.14.0.tar.gz is not a tarball.                   [or installed python cannot process compressed files]                                                                   * If you are behind a firewall - please fix your proxy and rerun ./configure                                              For example at LANL you may need to set the environmental variable http_proxy (or HTTP_PROXY?) to  http://proxyout.lanl.gov                                                                                                                   * You can run with --with-packages-dir=/adirectory and ./configure will instruct you what packages to download manually * or you can download the above URL manually, to /yourselectedlocation/v2.14.0.tar.gz                                     and use the configure option:                                                                                           --download-hypre=/yourselectedlocation/v2.14.0.tar.gz                                                                 Unable to download hypre                                                                                                Could not execute "git clone https://github.com/LLNL/hypre /home/tarek/petsc-3.9.3/arch-linux2-c-opt/externalpackages/git.hypre":                                                                                                               Cloning into '/home/tarek/petsc-3.9.3/arch-linux2-c-opt/externalpackages/git.hypre'...                                  remote: Repository not found.                                                                                           fatal: repository 'https://github.com/LLNL/hypre/' not found                                                            Unable to download package HYPRE from: git://https://github.com/LLNL/hypre                                              * If URL specified manually - perhaps there is a typo?                                                                  * If your network is disconnected - please reconnect and rerun ./configure                                              * Or perhaps you have a firewall blocking the download                                                                  * You can run with --with-packages-dir=/adirectory and ./configure will instruct you what packages to download manually * or you can download the above URL manually, to /yourselectedlocation                                                    and use the configure option:                                                                                           --download-hypre=/yourselectedlocation

**Comment by liruipeng** [comment]
@tarekhussein this seems like a petsc issue. The download link is wrong, which should be https://github.com/hypre-space/hypre.git

**Comment by shijie68** [comment]
I have the same issue. did you @tarekhussein solve this probelm

**Comment by victorapm** [comment]
@shijie68, this issue is related to an old version of PETSc. It is trying to download hypre from an address that is not supported anymore. I see two solutions:

1. Upgrade to a newer version of PETSc (that points to the right address of hypre).
2. Download and compile your own version of hypre and tell PETSc where to find it.

I recommend the first one.

Thanks,
Victor

Edit: see PETSc's error message:

> You can run with --with-packages-dir=/adirectory and ./configure will instruct you what packages to download manually * or you can download the above URL manually, to /yourselectedlocation and use the configure option: --download-hypre=/yourselectedlocation

**Comment by shijie68** [comment]
Thank you @victorapm. I was wondering whether we could change the download address from PETSc.

**Comment by victorapm** [comment]
According to PETSc:

>you can download the above URL manually, to /yourselectedlocation and use the configure option: --download-hypre=/yourselectedlocation

**Comment by shijie68** [comment]
Thank you @victorapm. I really appreciate it
