### ISSUE TITLE
Help for ilu(k)

### ISSUE THREAD

**Issue by Leo9660** [hypre-space/hypre#244]
Hello,

    I'm a developer for some sparse libray, which involves ilu(k) preconditioner. Hypre is a amazing one for preconditioners and has been developed for years, so I think Hypre must offer a correct and complete implemetation for ilu(k). I want to use your library to verify my results, that is, given a sparse matrix A, do the level k ilu factorization and get the corresponding triangular matrix l & u, no need for reordering and dropout, just natural ordering is good.
    I notice in user manual there's a Euclid interface in 6.13 for ilu(k). When I do HYPRE_PCGSetup and HYPRE_PCGSolve, actually I do the factorization and the solver as a whole, I cannot get the l & u matrix I want. So is there any method or other interface for users to get the triangular matrix which satisfy a = lu in ilu(k)?
    Thanks a lot!

Leo

**Comment by liruipeng** [comment]
> Hello,
> 
> ```
> I'm a developer for some sparse libray, which involves ilu(k) preconditioner. Hypre is a amazing one for preconditioners and has been developed for years, so I think Hypre must offer a correct and complete implemetation for ilu(k). I want to use your library to verify my results, that is, given a sparse matrix A, do the level k ilu factorization and get the corresponding triangular matrix l & u, no need for reordering and dropout, just natural ordering is good.
> I notice in user manual there's a Euclid interface in 6.13 for ilu(k). When I do HYPRE_PCGSetup and HYPRE_PCGSolve, actually I do the factorization and the solver as a whole, I cannot get the l & u matrix I want. So is there any method or other interface for users to get the triangular matrix which satisfy a = lu in ilu(k)?
> Thanks a lot!
> ```
> 
> Leo

Hi, @Leo9660 ,

The L/U factors of ILU(K) are saved in `Factor_dh F`  of `struct _mpi_interface_dh`, see `Euclid_dh.h`.
In `struct _factor_dh` (see `distributed_ls/Euclid/Factor_dh.h`). What you want is in these 3 arrays
```
struct _factor_dh {
...
  HYPRE_Int *rp;       
  HYPRE_Int *cval;
  REAL_DH *aval;
...
```
which stores L/U in one CSR matrix as `L+U-I`. Note that it stores the **inverse** of the diagonal of `U`.

You can also print them to take a look by

```
   Euclid_dh eu = (Euclid_dh ) pcg_precond;
   Factor_dh F = eu->F;
   Factor_dhPrintTriples(F, "Euclid_F");
```


Please let us know if you have more questions on this.

Thanks

-Ruipeng

**Comment by Leo9660** [comment]
Hi, @liruipeng 
Thank you very much for your comments! Now I can find where the matrices are and compare them to my own results, that helps a lot! Sorry for taking so long to reply, and wish you guys a happy new year!

Thanks,

-Leo

**Comment by liruipeng** [comment]
@Leo9660 Great! Thanks! Happy new year to you, too.
