### ISSUE TITLE
Hypre minimum CUDA version requirements

### ISSUE THREAD

**Issue by sayerhs** [hypre-space/hypre#245]
As of 22f4d3f8c (#163) we are no longer able to build hypre with CUDA 9.2.88. Is this expected? What is the minimum CUDA version we should use for hypre?

**Error message:**

```
nvcc -O2 -lineinfo -ccbin=mpic++ -gencode arch=compute_70,"code=sm_70" -expt-extended-lambda -dc -std=c++11 --x cu -Xcompiler "-O2 " -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I. -I/nopt/nrel/apps/cuda/9.2.88/include    -c hypre_cuda_utils.c -o hypre_cuda_utils.obj
_hypre_utilities.hpp(754): error: identifier "cusparseIndexType_t" is undefined

hypre_cuda_utils.c(721): error: identifier "cusparseIndexType_t" is undefined

hypre_cuda_utils.c(737): error: identifier "CUSPARSE_INDEX_32I" is undefined

hypre_cuda_utils.c(830): error: identifier "cusparseGetErrorString" is undefined

hypre_cuda_utils.c(832): error: identifier "cusparseGetErrorString" is undefined

hypre_cuda_utils.c(848): error: identifier "cusparseGetErrorString" is undefined

hypre_cuda_utils.c(849): error: identifier "cusparseGetErrorString" is undefined

hypre_cuda_utils.c(850): error: identifier "cusparseGetErrorString" is undefined

hypre_cuda_utils.c(921): error: identifier "cusparseGetErrorString" is undefined

hypre_cuda_utils.c(926): error: identifier "cusparseGetErrorString" is undefined

10 errors detected in the compilation of "/tmp/tmpxft_00002401_00000000-6_hypre_cuda_utils.cpp1.ii".
make[1]: *** [hypre_cuda_utils.obj] Error 1
```

**Configure**
```
$ ./configure --with-cuda --enable-unified-memory --without-openmp --disable-bigint --enable-curand --disable-cub --without-superlu

$ mpic++ -show
/nopt/nrel/ecom/hpacf/compilers/2019-05-08/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.4.0-srw2azby5tn7wozbchryvj5ak3zlfz3r/bin/g++ -I/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/openmpi-3.1.4-kuzrpughgfurzixeep7le673td4jjwq5/include -fexceptions -pthread -L/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/hwloc-1.11.11-vlwsr53rwi2kxtflx626o3k7ek4i4qhr/lib -L/nopt/slurm/current/lib -L/usr/lib64 -Wl,-rpath,/nopt/nrel/ecom/hpacf/compilers/2019-05-08/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.4.0-srw2azby5tn7wozbchryvj5ak3zlfz3r/lib64 -Wl,-rpath -Wl,/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/hwloc-1.11.11-vlwsr53rwi2kxtflx626o3k7ek4i4qhr/lib -Wl,-rpath -Wl,/nopt/slurm/current/lib -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/openmpi-3.1.4-kuzrpughgfurzixeep7le673td4jjwq5/lib -L/lustre/eaglefs/projects/hfm/exawind/nalu-wind-testing/spack/opt/spack/linux-centos7-x86_64/gcc-7.4.0/openmpi-3.1.4-kuzrpughgfurzixeep7le673td4jjwq5/lib -lmpi_cxx -lmpi
```

@paulmullowney

**Comment by liruipeng** [comment]
> cusparseGetErrorString

Hi @sayerhs ,

So far, we don't have an official minimum supported CUDA version. We tested hypre with CUDA 10.2 or 11.x. These errors were from adding stuff that need at least CUDA 10.2. It's not hard to fix in this case. But we need to have some consensus from the users what's the minimal CUDA version we should support. We don't want support too out-of-date CUDA. Do you actually need support CUDA 9 in Exawind? Thanks!

**Comment by sayerhs** [comment]
Hi @liruipeng. We have been using CUDA 10.2.89 on most systems. There is one nightly test machine that is still using CUDA 9.2.88 and caught this. We will work to upgrade the test machine to start using CUDA 10.2.89. I opened an issue because I didn't see any errors in configure step about minimum version checks, so wanted to ensure that this was an intentional change and not a regression.

I think it would be good if hypre officially required a certain minimum CUDA version. Similarly, is there a minimum CUDA arch that you support? Or is that just based on what architectures the CUDA version supports?

**Comment by liruipeng** [comment]
> Hi @liruipeng. We have been using CUDA 10.2.89 on most systems. There is one nightly test machine that is still using CUDA 9.2.88 and caught this. We will work to upgrade the test machine to start using CUDA 10.2.89. I opened an issue because I didn't see any errors in configure step about minimum version checks, so wanted to ensure that this was an intentional change and not a regression.
> 
> I think it would be good if hypre officially required a certain minimum CUDA version. Similarly, is there a minimum CUDA arch that you support? Or is that just based on what architectures the CUDA version supports?

Sure. We indeed need to add minimum CUDA version and CUDA arch (SM). About the latter one, we basically tested on P100 and V100. SM are just based on arch, i.e., SM_60 and SM_70 respectively. I am not sure if it makes sense to look at SMs lower than those, such as 50, for these two GPUs. Thoughts? Thanks again @sayerhs

**Comment by sayerhs** [comment]
@liruipeng For ExaWind we have only been using on `sm_60, sm_70`, so that won't affect us. 

Currently, if we are using CUDA 10.2.x, I assume the user can set `HYPRE_CUDA_SM=50` and attempt to build hypre and it would build successfully. In this situation, do we expect the compiled library to work correctly upon execution? If not, I was just wondering if hypre should be explicit about this and require `HYPRE_CUDA_SM >= 60`.

**Comment by cessenat** [comment]
I succesfully compiled Hypre Master (2021/01/29) using CUDA 11.1.0, PGI 20.4 and OpenMPI 4.0.3 with
./configure --enable-shared --with-cuda --enable-unified-memory --enable-cublas --with-MPI-include=$MPI_INCDIR --with-MPI-lib-dirs=$MPI_LIBDIR --prefix=/opt/hypre_cuda
Is there somewhere an example I could compile and check it works correctly ?
Thanks.
Olivier Cessenat.
