### ISSUE TITLE
Multivectors

### ISSUE THREAD

**Issue by kswirydo** [hypre-space/hypre#25]
By default, the Krylov space in GMRES is stored as an array of ParVectors. This is very inefficient esp if the orthogonalization is performed "in bulk" and on the GPU (either one-sycnh modified Gram Schmidt or Classical Gram Schmidt with reorthogonalization), because data access is very scattered. 
I implemented this instead storing the space as one long multivector in which the data is stored columnwise as one long contiguous chunk of memory. I was wandering if this can be changed in the main hypre branch.

Thanks

**Comment by ulrikeyang** [comment]
This is the way the vector data array is allocated. The first vector contains all data. See CreateVectorArray in parcsr_ls/pcg_par.c
