### ISSUE TITLE
Add saved-file feature to runtest.sh script

### ISSUE THREAD

**Issue by rfalgout** [hypre-space/hypre#255]
Having one set of saved output files for regression testing creates issues on different architectures that produce slightly different numerical results.  The `runcheck.sh` script allows some flexibility here, but sometimes requires the use of loose tolerances, which has become a problem on the GPU machines in particular.

We should extend the regression testing to allow for additional sets of "saved files".  To do this requires adding a saved-file-extension feature to the `runtest.sh` script (similar to -rtol and -atol), modifying the `TEST*/*.sh` scripts to use the extension, and creating the new saved files.

**Comment by liruipeng** [comment]
@rfalgout is it easy to add additional arguments to all tests for GPUs, something like `./ij .... -exec_gpu`? Thanks!

**Comment by rfalgout** [comment]
Hi @liruipeng .  Not currently.  It would not be difficult to add a feature that allows us to append something to every run string, if that's what you are asking.  So, if the normal run string is something like

    mpirun -np 8 struct -n 20 20 20 -solver 11 -rap 1 ...

it would be easy to update `runtest.sh` to add options at the very end of this.
