### ISSUE TITLE
Remove struct_mv header files in utilities memory code

### ISSUE THREAD

**Issue by rfalgout** [hypre-space/hypre#276]
In https://github.com/hypre-space/hypre/blob/master/src/utilities/hypre_memory.c , the following two includes should be removed

    #include "_hypre_struct_mv.h"
    #include "_hypre_struct_mv.hpp"

This does not break the default compile, but I'm not sure about the GPU stuff.  Would you mind looking into this @liruipeng ?  Thanks!

**Comment by liruipeng** [comment]
@rfalgout Will do. Thanks!

**Comment by liruipeng** [comment]
@rfalgout I know why we need them in `hypre_memory.c`, at least the `.hpp`. It's because we use boxloops to do memset for device-openmp build.

**Comment by rfalgout** [comment]
Okay.  I looked briefly, and I don't completely see what's going on here, but it looks like the `hypre_Loop` stuff doesn't depend on any notion of boxes, so it probably should be moved to `utilities` instead.  In any case, this somehow this needs to be reorganized, because it doesn't make sense for `utilities` to depend on `struct_mv`.  Maybe we can chat at some point?  This is not urgent.

**Comment by liruipeng** [comment]
> Okay. I looked briefly, and I don't completely see what's going on here, but it looks like the `hypre_Loop` stuff doesn't depend on any notion of boxes, so it probably should be moved to `utilities` instead. In any case, this somehow this needs to be reorganized, because it doesn't make sense for `utilities` to depend on `struct_mv`. Maybe we can chat at some point? This is not urgent.

Yes, @rfalgout I agree. `hypre_LoopBegin(num, k)` is just a plain for-loop `for (k=0; k<num; k++)`, no notion of boxes involved. I think we were just lazy there to use it since `hypre_LoopBegin` is portable to GPUs. Moving `hypre_LoopBegin` to `utilities` is fine to me.

**Comment by liruipeng** [comment]
@rfalgout I think this issue has been resolved. We may close it if you also think so.

**Comment by rfalgout** [comment]
Sounds good.  Thanks!
