### ISSUE TITLE
Pre and post sweeps different (settings)

### ISSUE THREAD

**Issue by sthomas61** [hypre-space/hypre#287]
Does Hypre BoomerAMG CSR interface support different values for pre and post sweeps.
If not could this option be added.

**Comment by ulrikeyang** [comment]
What do you mean? Different smoothers? You can set different smoothers for up than for down sweeps using HYPRE_BoomerAMGSetCycleRelaxType. You can also vary the number of sweeps with HYPRE_BoomerAMGSetCycleNumSweeps. 1 is down, 2 is up, 3 is coarse level.

**Comment by sthomas61** [comment]
by different pre versus post sweeps, for example, would like to use 2 relaxation sweeps in the pre-smoothing
on the way from fine to coarse level - whereas use 1 relaxation sweep in the post-smoothing
leads to greatly improved performance and better scaling

**Comment by sthomas61** [comment]
can see how to use - thanks !
