### ISSUE TITLE
Clang-11 + openmp offload fails with Hypre-2.18.2 on rzansel

### ISSUE THREAD

**Issue by lee-busby** [hypre-space/hypre#289]
Good morning, Hypre team -
Building miranda against the given version of hypre on rzansel at LLNL, I observe the following error:

In file included from .../miranda/src/solvers/diffusion_amr/amr_solver_m2s.cpp:2:
In file included from .../amr_solver_m2s.hpp:4:
In file included from .../hypre-2.18.2/include/HYPRE_sstruct_ls.h:15:
In file included from .../hypre-2.18.2/include/HYPRE_struct_ls.h:1107:
In file included from .../hypre-2.18.2/include/_hypre_struct_mv.h:10:
In file included from /usr/tce/packages/clang/clang-11.0.0/release/lib/clang/11.0.0/include/openmp_wrappers/math.h:20:
In file included from /usr/tce/packages/clang/clang-11.0.0/release/lib/clang/11.0.0/include/openmp_wrappers/cmath:17:
In file included from /usr/tce/packages/gcc/gcc-4.9.3/lib64/gcc/powerpc64le-unknown-linux-gnu/4.9.3/../../../../include/c++/4.9.3/cmath:42:
/usr/tce/packages/gcc/gcc-4.9.3/lib64/gcc/powerpc64le-unknown-linux-gnu/4.9.3/../../../../include/c++/4.9.3/bits/cpp_type_traits.h:72:3: error: templates must have C++ linkage
  template<typename _Iterator, typename _Container>
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../hypre-2.18.2/include/HYPRE_struct_ls.h:15:1: note: extern "C" language linkage specification begins here
extern "C" {
^

The error appears to be related to some usage of "extern C" in the several Hypre files seen above.  I believe you can reproduce this error using a simple helloworld.cpp file, and including the HYPRE_sstruct_ls.h file:

#include <iostream>
using namespace std;
#include "HYPRE_sstruct_ls.h"
int main() { cout << "Hello, World!\n"; return 0; }

Compile line is (you'll need to supply your own Hypre library to find that include file):

mpiclang++ -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -I.../hypre-2.18.2/include -c helloworld.cpp

The key compiler option seems to be "-fopenmp-targets=nvptx64-nvidia-cuda".  That's what causes Clang to drag in the openmp_wrappers around what is usually a simple "#include <math.h>" in the Hypre reference.

Thank you,
Lee Busby

**Comment by liruipeng** [comment]
Hi @lee-busby I tried compiling your "helloworld.cpp" with the latest master, which seemed fine.

```
 mpiclang++ -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -I/g/g92/li50/workspace/hypre/master/src/hypre/include/ -c hello.cpp
```

Are you still having this problem?

Thanks

-Ruipeng

**Comment by lee-busby** [comment]
Thank you for the followup.  I can also reproduce your results: fail with hypre-2.18.0, pass with current hypre-master.  So I believe we can close this issue.

**Comment by liruipeng** [comment]
> Thank you for the followup. I can also reproduce your results: fail with hypre-2.18.0, pass with current hypre-master. So I believe we can close this issue.

Thanks @lee-busby . I am not 100% sure what we did made it work. There have been so many changes in recent releases. But I am glad it works. So, closing this issue.
