### ISSUE TITLE
Bug for large number of d.o.f./MPI task?

### ISSUE THREAD

**Issue by jeanlucf22** [hypre-space/hypre#29]
As I am running tests on Summit, I got a segfault running the 'struct' driver:

[g04n11:54194] *** Process received signal ***
[g04n11:54194] Signal: Segmentation fault (11)
[g04n11:54194] Signal code: Address not mapped (1)
[g04n11:54194] Failing at address: (nil)
[g04n11:54194] [ 0] [0x2000000504d8]
[g04n11:54194] [ 1] /ccs/home/jeanluc/GIT/hypre-space/hypre/src/hypre/lib/libHYPRE-2.16.0.so(+0x549e84)[0x200000639e84]
[g04n11:54194] [ 2] /ccs/home/jeanluc/GIT/hypre-space/hypre/src/hypre/lib/libHYPRE-2.16.0.so(+0x54f384)[0x20000063f384]
[g04n11:54194] [ 3] /ccs/home/jeanluc/GIT/hypre-space/hypre/src/hypre/lib/libHYPRE-2.16.0.so(hypre_PFMGSetup+0xab4)[0x2000005470c4]
[g04n11:54194] [ 4] /ccs/home/jeanluc/GIT/hypre-space/hypre/src/hypre/lib/libHYPRE-2.16.0.so(HYPRE_StructPFMGSetup+0x18)[0x200000500
7d4]
[g04n11:54194] [ 5] /ccs/home/jeanluc/hypre/bin/struct_gpu[0x1000b08c]
[g04n11:54194] [ 6] /lib64/libc.so.6(+0x25100)[0x20000b3b5100]
[g04n11:54194] [ 7] /lib64/libc.so.6(__libc_start_main+0xc4)[0x20000b3b52f4]

I am running the following command line:

jsrun -n 1 -g 1 -a 1 struct -n 512 512 512 -P 1 1 1 -c 2.0 3.0 4.0 -solver 1

that is, running 1 MPI task on a single GPU, for a mesh 512x512x512.
All my other (smaller) tests, using smaller meshes, or several MPI tasks, work.

Jean-Luc Fattebert

**Comment by victorapm** [comment]
Hi Jean-Luc,

I reproduced this error on summit and found that it occurs because the code is trying to allocate more memory on the GPU than what is available. To avoid this, you should try reducing the problem size on a single GPU. We are working on improving the error handling in hypre to help avoid segfaults like in this case.

Thanks,
Victor

**Comment by jeanlucf22** [comment]
Thanks for looking into it Victor.
I guess I had underestimated how much memory hypre is using. A Volta GPU on Summit has 16 GB, and a "solution" vector in double should use only about 1 GB of it. Of course you need at least 2 vectors and the diagonal of the matrix which already brings you up to 3 GB. I can imagine some extra internal "work" arrays eat up the rest...
I also tried "solver 4" which should use less memory with constant off-diagonal elements, but it also failed.

Jean-Luc
