### ISSUE TITLE
New hypre release 2.17.0 - license change to MIT/Apache-2.0

### ISSUE THREAD

**Issue by rfalgout** [hypre-space/hypre#30]
Hello @hypre-space/developers, 

We are in the process of doing a new hypre release, so please hold off on making changes to the master branch until it is done. I hope to have it completed by Wednesday, but I will let you know.

This release will incorporate a license change to dual MIT/Apache-2.0.  Please take a look at the new source in the 'relicense' branch at https://github.com/hypre-space/hypre/tree/relicense.

Thanks!

-Rob

**Comment by rfalgout** [comment]
Checklist:

- [ ] [MAJOR] Initial documentation review meeting.
- [x] [MAJOR.MINOR] Update user and reference manuals.
- [ ] [MAJOR] Final documentation review meeting.
- [x] Update `CHANGELOG` file with information regarding contents of this release.
- [x] Verify that all agreed-upon changes have been committed.
- [x] Update `config/configure.in` and `CMakeLists.txt` with release number and date, then run `config/bootstrap` and commit changes to the repository.
- [x] Check that the regression tests all run cleanly
  - [x] machine-tux
  - [x] machine-tux-exlibs
  - [x] machine-rztopaz
  - [x] machine-syrah
  - [x] machine-ray.sh
  - [x] machine-vs-pro.bat
- [x] Tag repository with release number: `git tag -a v2.11.0 -m "Release v2.11.0"` and push the tags to the central repository: `git push --tags`
- [x] On the CASC cluster, copy the GitHub release tar file to `/usr/casc/hypre`.
- [x] On the RZ, copy the GitHub tar file to `/usr/gapps/hypre` (for backup reasons).
- [x] Close the new release GitHub issue.

**Comment by rfalgout** [comment]
Hello @hypre-space/developers ,

Is there anything else to add to this release?  We probably need to get the superlu regression test issue resolved.  Anybody want to look into that?  Let me know.  Thanks!

-Rob

**Comment by victorapm** [comment]
Hi Rob,

I was looking at machine-tux-exlibs and realized that the config line https://github.com/hypre-space/hypre/blob/208fc8732130e4eff62d692229d1b682d38d7ee0/AUTOTEST/machine-tux-exlibs.sh#L59 uses files that are defined in your home folder. Maybe we should make it not dependent on the user by using an environment flag like SUPERLU_DIR instead? Then, this test could be ran in another machine as long as the flag is defined.

Thanks,
Victor

**Comment by rfalgout** [comment]
Hi @victorapm.  We might be able to find a better approach for this.  Agreed.

FYI, All.  Sarah is looking into the exlibs test, so we've got a volunteer.  :)  Thanks!

-Rob

**Comment by victorapm** [comment]
Thanks, @rfalgout! 

Another minor detail, we need to change the line: https://github.com/hypre-space/hypre/blob/568d5c3fe95231d1660d0d957e40ce87f02dca66/LICENSE-APACHE#L190 to something like: 

Copyright 2019 Lawrence Livermore National Security, LLC.

**Comment by rfalgout** [comment]
Hi @victorapm ,

That part of the license is just instructional.  I don't think we need to change it.  The Spack guys didn't either and I'm mostly copying them. :)

Thanks for looking over this so closely!  A lot of files have changed, so it's easy for me to miss something.

-Rob

**Comment by victorapm** [comment]
It makes sense! Now I realized that it is in the Appendix section of the file. 

Thanks!

**Comment by rfalgout** [comment]
The release and license change is done.  Closing this issue. :)
