### ISSUE TITLE
uninitialized variables in HYPRE_Init() : GPU/Cuda

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#307]
Here's some valgrind output from our application.

==82764== 
==82764== Conditional jump or move depends on uninitialised value(s)
==82764==    at 0x41125D0: cuCtxSetCurrent (in /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-7.4.0/spectrum-mpi-10.3.1.2-20200121-eu2wh5ypz6ipvokwbng2m5ihug6doysh/lib/libpami_cudahook.so.1.0)
==82764==    by 0x991D507: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcudart.so.10.2.89)
==82764==    by 0x995B8D3: cudaSetDevice (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcudart.so.10.2.89)
==82764==    by 0xE221D7F: hypre_SetDevice (in /gpfs/alpine/cfd116/scratch/mullowne/install/gpu/hypre-master-3-4-2021/lib/libHYPRE-2.20.0.so)
==82764==    by 0xE221EBB: HYPRE_Init (in /gpfs/alpine/cfd116/scratch/mullowne/install/gpu/hypre-master-3-4-2021/lib/libHYPRE-2.20.0.so)
==82764==    by 0x10104307: hypre_initialize (HypreNGP.h:31)
==82764==    by 0x10104307: main (nalu.C:82)
==82764== 
==82764== Conditional jump or move depends on uninitialised value(s)
==82764==    at 0x4116A38: cuDevicePrimaryCtxRetain (in /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-7.4.0/spectrum-mpi-10.3.1.2-20200121-eu2wh5ypz6ipvokwbng2m5ihug6doysh/lib/libpami_cudahook.so.1.0)
==82764==    by 0x2E5F815B: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcusparse.so.10.3.1.89)
==82764==    by 0x2E5F8453: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcusparse.so.10.3.1.89)
==82764==    by 0x2E5FCC37: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcusparse.so.10.3.1.89)
==82764==    by 0x2E5EBE2B: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcusparse.so.10.3.1.89)
==82764==    by 0x2E5CDDC3: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcusparse.so.10.3.1.89)
==82764==    by 0x2E611FF3: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcusparse.so.10.3.1.89)
==82764==    by 0x2E139E4F: cusparseCreate (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcusparse.so.10.3.1.89)
==82764==    by 0xE20CE1F: hypre_CudaDataCusparseHandle(hypre_CudaData*) (in /gpfs/alpine/cfd116/scratch/mullowne/install/gpu/hypre-master-3-4-2021/lib/libHYPRE-2.20.0.so)
==82764==    by 0xE221EDB: HYPRE_Init (in /gpfs/alpine/cfd116/scratch/mullowne/install/gpu/hypre-master-3-4-2021/lib/libHYPRE-2.20.0.so)
==82764==    by 0x10104307: hypre_initialize (HypreNGP.h:31)
==82764==    by 0x10104307: main (nalu.C:82)
==82764== 
==82764== Conditional jump or move depends on uninitialised value(s)
==82764==    at 0x41147F0: cuMemFree_v2 (in /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-7.4.0/spectrum-mpi-10.3.1.2-20200121-eu2wh5ypz6ipvokwbng2m5ihug6doysh/lib/libpami_cudahook.so.1.0)
==82764==    by 0x2E5CDDF3: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcusparse.so.10.3.1.89)
==82764==    by 0x2E611FF3: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcusparse.so.10.3.1.89)
==82764==    by 0x2E139E4F: cusparseCreate (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcusparse.so.10.3.1.89)
==82764==    by 0xE20CE1F: hypre_CudaDataCusparseHandle(hypre_CudaData*) (in /gpfs/alpine/cfd116/scratch/mullowne/install/gpu/hypre-master-3-4-2021/lib/libHYPRE-2.20.0.so)
==82764==    by 0xE221EDB: HYPRE_Init (in /gpfs/alpine/cfd116/scratch/mullowne/install/gpu/hypre-master-3-4-2021/lib/libHYPRE-2.20.0.so)
==82764==    by 0x10104307: hypre_initialize (HypreNGP.h:31)
==82764==    by 0x10104307: main (nalu.C:82)
==82764== 
==82764== Conditional jump or move depends on uninitialised value(s)
==82764==    at 0x4116A38: cuDevicePrimaryCtxRetain (in /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-7.4.0/spectrum-mpi-10.3.1.2-20200121-eu2wh5ypz6ipvokwbng2m5ihug6doysh/lib/libpami_cudahook.so.1.0)
==82764==    by 0x443737B: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcurand.so.10.1.2.89)
==82764==    by 0x4437673: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcurand.so.10.1.2.89)
==82764==    by 0x443BE57: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcurand.so.10.1.2.89)
==82764==    by 0x442B04B: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcurand.so.10.1.2.89)
==82764==    by 0x440CFE3: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcurand.so.10.1.2.89)
==82764==    by 0x4451213: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcurand.so.10.1.2.89)
==82764==    by 0x43AE287: curandCreateGenerator (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcurand.so.10.1.2.89)
==82764==    by 0xE20CC8F: hypre_CudaDataCurandGenerator(hypre_CudaData*) (in /gpfs/alpine/cfd116/scratch/mullowne/install/gpu/hypre-master-3-4-2021/lib/libHYPRE-2.20.0.so)
==82764==    by 0xE221EFB: HYPRE_Init (in /gpfs/alpine/cfd116/scratch/mullowne/install/gpu/hypre-master-3-4-2021/lib/libHYPRE-2.20.0.so)
==82764==    by 0x10104307: hypre_initialize (HypreNGP.h:31)
==82764==    by 0x10104307: main (nalu.C:82)
==82764== 
==82764== Conditional jump or move depends on uninitialised value(s)
==82764==    at 0x41147F0: cuMemFree_v2 (in /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-7.4.0/spectrum-mpi-10.3.1.2-20200121-eu2wh5ypz6ipvokwbng2m5ihug6doysh/lib/libpami_cudahook.so.1.0)
==82764==    by 0x440D013: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcurand.so.10.1.2.89)
==82764==    by 0x4451213: ??? (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcurand.so.10.1.2.89)
==82764==    by 0x43AE287: curandCreateGenerator (in /autofs/nccs-svm1_sw/summit/cuda/10.2.89/targets/ppc64le-linux/lib/libcurand.so.10.1.2.89)
==82764==    by 0xE20CC8F: hypre_CudaDataCurandGenerator(hypre_CudaData*) (in /gpfs/alpine/cfd116/scratch/mullowne/install/gpu/hypre-master-3-4-2021/lib/libHYPRE-2.20.0.so)
==82764==    by 0xE221EFB: HYPRE_Init (in /gpfs/alpine/cfd116/scratch/mullowne/install/gpu/hypre-master-3-4-2021/lib/libHYPRE-2.20.0.so)
==82764==    by 0x10104307: hypre_initialize (HypreNGP.h:31)
==82764==    by 0x10104307: main (nalu.C:82)

**Comment by liruipeng** [comment]
@PaulMullowney We usually don't run GPU hypre with valgrind. The error points inside CUDA. I am not sure if we are responsible for that. Any ideas? Thanks!

**Comment by PaulMullowney** [comment]
You're right. Ugh. Nothing to do here except hope they clean up their code.
