### ISSUE TITLE
Make GPU Matrix Descriptors Tied to Matrix

### ISSUE THREAD

**Issue by pbauman** [hypre-space/hypre#309]
I alluded to this in some code comments when adding rocSPARSE support in #304, but currently the matrix descriptors, i.e. `rocsparse_mat_descr` and `rocsparse_mat_info` for rocSPARSE and `cusparseMatDescr_t` for cuSPARSE, are treated as global variables and not tied to any specific matrix instance. This will need to change in order to add some performance optimizations for rocSPARSE. But I think it's also the more correct thing to do. I would propose moving those objects to be stored in `hypre_CSRMatrix` and appropriate accessor APIs added there. I can cook up a PR for this, but wanted to open up discussion here before doing so to make sure everyone is on the same page and to make sure there isn't something I'm missing.

**Comment by liruipeng** [comment]
@pbauman Thank you for checking with us. This is a correct thing to do; we actually wanted to do it too. If you don't mind, please make the change, and let us know if you need help on this. Thanks!

**Comment by liruipeng** [comment]
We have addressed this issue in #331. So, I close it.
