### ISSUE TITLE
Documentation about hypre_parcsr matrix

### ISSUE THREAD

**Issue by geyan3566** [hypre-space/hypre#311]
Hi,

I'm writing a parallel FEM solver that will use hypre_parcsr matrix, but I couldn't find relevant documentation about how to the API details.
Could you please let me know where can I find it?

Thanks,
Ge

**Comment by ulrikeyang** [comment]
Hello Ge,
Generally users should use the IJ interface to generate an IJ matrix, the object of which is a parcsr matrix.
The API is described in our documentation: Welcome to hypre’s documentation! — hypre 2.20.0 documentation<https://hypre.readthedocs.io/en/latest/>
The reference manual is in the last section entitled API.
Let us know if you have more questions
Ulrike

From: Ge Yan ***@***.***>
Sent: Monday, March 22, 2021 7:18 AM
To: hypre-space/hypre ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hypre-space/hypre] Documentation about hypre_parcsr matrix (#311)


Hi,

I'm writing a parallel FEM solver that will use hypre_parcsr matrix, but I couldn't find relevant documentation about how to the API details.
Could you please let me know where can I find it?

Thanks,
Ge

**Comment by geyan3566** [comment]
Hi,

I'm afraid that the `HYPRE_IJMATRIX` API might be inadequate for what I want to do.
Also, the `mfem` community highly suggests me to use hypre_parcsr matrix API. 
May I know where I can find the hypre_parcsr matrix API instruction?

Thanks,
Ge

**Comment by geyan3566** [comment]
Hi,

I used `HYPRE_IJMATRIX` interface to construct the `HYPRE_PARCSR` matrix.
Given that `mfem` has a `HypreParMatrix` class that the underhood class is `hypre_ParCSRMatrix` (the lower case),
is there a way to convert `HYPRE_PARCSRMatrix` to `hypre_ParCSRMatrix`?

Thanks,
Ge

**Comment by liruipeng** [comment]
`HYPRE_ParCSRMatrix` is just a pointer type of `hypre_ParCSRMatrix`. Doing pointer casting should be fine.

**Comment by liruipeng** [comment]
@geyan3566 I am not sure if we had written down documentations for `HYPRE_ParCSRMatrix`. You can find its definition in `par_csr_matrix.h` and basic API's in `par_csr_matrix.c` You can always ask specific questions on github or sending us emails.

**Comment by geyan3566** [comment]
Thank you very much @liruipeng !

**Comment by geyan3566** [comment]
Hi,

I have another question need to confirm with you.
Fot the `HYPRE_IJMatrixSetValues(ij_matrix, nrows, ncols, rows, cols, values)` function, is the `value` will be filled in the `HYPRE_PARCSRMatrix` in a row-by-row or colume-by-colume manner? 

Thanks,
Ge

**Comment by ulrikeyang** [comment]
Row-by-row

**Comment by geyan3566** [comment]
Hi,

I'm having a problem while using the `HYPRE_IJMatrix` interface to construct the `hypre_parcsrmatrix`.
Here is the pseudo-code:
```
 HYPRE_IJMatrixCreate(GetComm(), dof_start, dof_end,
                        el_start, el_end, &ij_matrix);
HYPRE_IJMatrixSetObjectType(ij_matrix, HYPRE_PARCSR);
HYPRE_IJMatrixInitialize(ij_matrix);
for (in i = 0; i < something; i++)
{
   // create relative dates and update them
   ......
   ......
   HYPRE_IJMatrixSetValues(ij_matrix, num_dofs, ncols.GetData(), row_index.GetData(),
                                                col_index.GetData(), local_mat.GetData());
}
HYPRE_IJMatrixAssemble(ij_matrix);
HYPRE_IJMatrixGetObject(ij_matrix, (void**)&hypre_parcsr);
```
In this code, I try to repetitively set up coefficient using `local_mat`, which is a dense matrix, and its row and column indices are described by`row_index` and `col_index`. The problem is that every time I call `HYPRE_IJMatrixSetValue`, only the column index for the first row is set up properly, and the other column indices are wrong.

Here is some output for a simple example where I'm constructing a `hypre_parcsrmatrix` of global size `84 x 12` on one processor (not fully filled, some coefficients are 0), and `local_mat` is always a `7 x 4` fully filled matrix for each loop.

Here: 1) the reconstruction matrix R is the `local_mat`.
          2) Element dofs and `Row` in assembling location are the `row_index`.
          3) Element id and `Col` in assembling location are the `col_index`.
          4) 'local_mat' size is 4 x 7 because it's transposed.

I'll post the index and coefficients in the final `hypre_csrmatrix` separately.
```
Element id in patch 0: 0 2 3 4
Local reconstruction matrix R:
[row +0]
+5.375575e-01 +2.586364e-01 -4.022571e-01 +6.060631e-01
[row +1]
+6.405314e-01 +2.681476e-01 +6.390189e-01 -5.476979e-01
[row +2]
+1.518576e+00 +2.988082e-01 -5.006191e-01 -3.167649e-01
[row +3]
+5.890444e-01 +2.633920e-01 +1.183809e-01 +2.918260e-02
[row +4]
+1.079554e+00 +2.834779e-01 +6.919992e-02 -4.322314e-01
[row +5]
+1.028067e+00 +2.787223e-01 -4.514381e-01 +1.446491e-01
[row +6]
+8.988882e-01 +2.751974e-01 -8.795243e-02 -8.613323e-02
number of dof is 7
Element dofs: 0 1 2 3 4 5 6
ncols is: 4 4 4 4 4 4 4
mat size is 4 x 7
        0 assemble location:
                Row:0 1 2 3 4 5 6
                Col:0 2 3 4
Element id in patch 1: 1 6 9 11
Local reconstruction matrix R:
[row +0]
+6.402714e-01 +2.682298e-01 -5.476238e-01 +6.391227e-01
[row +1]
+5.372336e-01 +2.587134e-01 +6.061674e-01 -4.021145e-01
[row +2]
+1.518777e+00 +2.991621e-01 -3.170195e-01 -5.009196e-01
[row +3]
+5.887525e-01 +2.634716e-01 +2.927178e-02 +1.185041e-01
[row +4]
+1.028005e+00 +2.789377e-01 +1.445739e-01 -4.515171e-01
[row +5]
+1.079524e+00 +2.836959e-01 -4.323217e-01 +6.910151e-02
[row +6]
+8.987607e-01 +2.753684e-01 -8.615866e-02 -8.797048e-02
number of dof is 7
Element dofs: 7 8 9 10 11 12 13
ncols is: 4 4 4 4 4 4 4
mat size is 4 x 7
        0 assemble location:
                Row:7 8 9 10 11 12 13
                Col:1 6 9 11
Element id in patch 2: 2 0 3 4
Local reconstruction matrix R:
[row +0]
+2.681476e-01 +6.405314e-01 +6.390189e-01 -5.476979e-01
[row +1]
+2.586364e-01 +5.375575e-01 -4.022571e-01 +6.060631e-01
[row +2]
+2.261891e-01 -3.524966e-01 +4.813824e-01 +6.449250e-01
[row +3]
+2.633920e-01 +5.890444e-01 +1.183809e-01 +2.918260e-02
[row +4]
+2.424128e-01 +9.253049e-02 +3.956266e-02 +6.254941e-01
[row +5]
+2.471684e-01 +1.440174e-01 +5.602007e-01 +4.861354e-02
[row +6]
+2.509911e-01 +2.751974e-01 +2.393814e-01 +2.344301e-01
number of dof is 7
Element dofs: 14 15 16 17 18 19 20
ncols is: 4 4 4 4 4 4 4
mat size is 4 x 7
        0 assemble location:
                Row:14 15 16 17 18 19 20
                Col:2 0 3 4
Element id in patch 3: 3 2 10
Local reconstruction matrix R:
[row +0]
-7.355436e-01 +9.005274e-01 +8.350163e-01
[row +1]
+1.891366e+00 -1.022236e+00 +1.308694e-01
[row +2]
+1.844177e+00 +1.217082e-01 -9.658857e-01
[row +3]
+5.779113e-01 -6.085412e-02 +4.829428e-01
[row +4]
+1.867772e+00 -4.502637e-01 -4.175081e-01
[row +5]
+5.543169e-01 +5.111178e-01 -6.543470e-02
[row +6]
+1.000000e+00 -1.150013e-16 +1.093289e-16
number of dof is 7
Element dofs: 21 22 23 24 25 26 27
ncols is: 3 3 3 3 3 3 3
mat size is 3 x 7
        0 assemble location:
                Row:21 22 23 24 25 26 27
                Col:3 2 10
....
....
```

**Comment by geyan3566** [comment]
Here are a few lines in the printed `hypre_parcsrmtrix`.
You can see that only the first row is set up properly for every `SetValue` call.
Please let me know if you need further information.
```
0 83 0 11
0 0 5.37557533763231e-01
0 2 2.58636446659176e-01
0 3 -4.02257113400038e-01
0 4 6.06063132977630e-01
1 1 -5.47697927448894e-01
1 -2008073599 6.40531363268714e-01
1 18743295 2.68147647692964e-01
1 1932 6.39018916487216e-01
2 1179403021 1.51857572843850e+00
2 1970561381 2.98808245924912e-01
2 1766614386 -5.00619084930978e-01
2 29811 -3.16764889432437e-01
3 0 5.89044448515973e-01
3 0 2.63392047176070e-01
3 0 1.18380901543589e-01
3 0 2.91826027643679e-02
4 0 6.91999157781190e-02
4 0 -4.32231408440666e-01
4 1321478624 1.07955354585361e+00
4 32669 2.83477946808938e-01
5 1 1.44649121772597e-01
5 -2008073599 1.02806663110087e+00
5 18743295 2.78722346292044e-01
5 1932 -4.51438099165508e-01
6 1212957459 8.98888208490149e-01
6 1332178529 2.75197446759018e-01
6 1345539182 -8.79524272812668e-02
6 1953067617 -8.61332279679005e-02
7 1 6.40271392340319e-01
7 6 2.68229780937912e-01
7 9 -5.47623843487967e-01
7 11 6.39122670209737e-01
8 0 6.06167409053394e-01
8 0 -4.02114479697826e-01
8 1801675074 5.37233631209495e-01
8 6581861 2.58713439434937e-01
```

**Comment by ulrikeyang** [comment]
It looks like you only provide the column indices for the first row and not the following rows.
If you have 7 rows with the same column numbers, you still need to repeat them for each row.

**Comment by geyan3566** [comment]
It seems not right. Now the `col_index` size is `7 x 4` and the `hypre_parcsrmatrix` looks like
```
0 83 0 11
0 -1852112945 5.37557533763231e-01
0 -1852112943 2.58636446659176e-01
0 -1852112942 -4.02257113400038e-01
0 -1852112941 6.06063132977630e-01
1 -1852112945 6.40531363268714e-01
1 -1852112943 2.68147647692964e-01
1 -1852112942 6.39018916487216e-01
1 -1852112941 -5.47697927448894e-01
2 -1852112945 1.51857572843850e+00
2 -1852112943 2.98808245924912e-01
2 -1852112942 -5.00619084930978e-01
2 -1852112941 -3.16764889432437e-01
3 -1852112945 5.89044448515973e-01
3 -1852112943 2.63392047176070e-01
3 -1852112942 1.18380901543589e-01
3 -1852112941 2.91826027643679e-02
4 -1852112945 1.07955354585361e+00
4 -1852112943 2.83477946808938e-01
4 -1852112942 6.91999157781190e-02
4 -1852112941 -4.32231408440666e-01
5 -1852112945 1.02806663110087e+00
5 -1852112943 2.78722346292044e-01
5 -1852112942 -4.51438099165508e-01
5 -1852112941 1.44649121772597e-01
```

And the data detail:
```
Element id in patch 0: 0 2 3 4
Local reconstruction matrix R:
[row +0]
+5.375575e-01 +2.586364e-01 -4.022571e-01 +6.060631e-01
[row +1]
+6.405314e-01 +2.681476e-01 +6.390189e-01 -5.476979e-01
[row +2]
+1.518576e+00 +2.988082e-01 -5.006191e-01 -3.167649e-01
[row +3]
+5.890444e-01 +2.633920e-01 +1.183809e-01 +2.918260e-02
[row +4]
+1.079554e+00 +2.834779e-01 +6.919992e-02 -4.322314e-01
[row +5]
+1.028067e+00 +2.787223e-01 -4.514381e-01 +1.446491e-01
[row +6]
+8.988882e-01 +2.751974e-01 -8.795243e-02 -8.613323e-02
number of dof is 7
Element dofs: 0 1 2 3 4 5 6
ncols is: 4 4 4 4 4 4 4
mat size is 4 x 7
col_index size is 28
        0 assemble location:
                Row:0 1 2 3 4 5 6
                Col:0 2 3 4 0 2 3 4 0 2 3 4 0 2 3 4 0 2 3 4 0 2 3 4 0 2 3 4
```
