### ISSUE TITLE
address sanitizer leak

### ISSUE THREAD

**Issue by ptsuji** [hypre-space/hypre#315]
Hello,

I noticed that in src/FEI_mv/fei-hypre/HYPRE_LinSysCore.cxx, there is a line which does a strcpy on line 4157:

   else if ( !strcmp(name, "dsuperlu") )
   {
      strcpy( HYSolverName_, name );
#ifdef HYPRE_USING_DSUPERLU
      HYSolverID_ = HYDSUPERLU;
#else
      printf("HYPRE_LinSysCore:: DSuperLU not available.\n");
      printf("                   default solver to be GMRES.\n");
      HYSolverID_ = HYGMRES;
#endif
   }

When we use dsuperlu as the solver, this shows up as a leak in address sanitizer (strcpy-param-overlap: memory ranges). When I remove this line, things run fine. Can it be removed? Is this part of the code tested regularly?

-Paul

**Comment by liruipeng** [comment]
`strcpy` doesn't like copying with overlapping. see https://www.cplusplus.com/reference/cstring/strcpy/. We should fix it with `memmove`. Before doing that, @rfalgout what's the plan for FEI? Should we still fix issues of it?

**Comment by rfalgout** [comment]
We have no way to test it, but should continue to make changes for our LLNL users (like Paul) until the FEI is phased out.  Thanks!

**Comment by liruipeng** [comment]
@rfalgout OK, Thanks! I will push a fix for that.

**Comment by liruipeng** [comment]
@ptsuji Can you please checkout this branch https://github.com/hypre-space/hypre/tree/strcpy and test if it fixes the issue? Thanks!
