### ISSUE TITLE
Compiling with CUDA and BigInt

### ISSUE THREAD

**Issue by wcdawn** [hypre-space/hypre#318]
Hello!

I'm trying to compile HYPRE with both CUDA and BigInt enabled. There are some minor changes necessary in `src/utilities/hypre_cuda_utils.c` [here](https://github.com/hypre-space/hypre/blob/366b80f89b1198305a7e0f5939dedc71582740de/src/utilities/hypre_cuda_utils.c#L361-L364) and [here](https://github.com/hypre-space/hypre/blob/366b80f89b1198305a7e0f5939dedc71582740de/src/utilities/hypre_cuda_utils.c#L731-L734).

However, there are many more problems in the CSR routines. For example, `src/seq_mv/csr_matvec_device.c` throws a precompiler error [here](https://github.com/hypre-space/hypre/blob/366b80f89b1198305a7e0f5939dedc71582740de/src/seq_mv/csr_matvec_device.c#L264-L266) when trying to compile CUDA with BigInt.

Is there any interest in supporting this combination of options? I can open a PR and start making changes but it seems like it may be a big undertaking.

Thanks!

**Comment by liruipeng** [comment]
@wcdawn We are working on supporting bigInt and mixedInt on GPUs. We will have them supported in the next release. Thanks!

**Comment by wcdawn** [comment]
Looking forward to it! Thank you!
