### ISSUE TITLE
find owner for idx = -1?

### ISSUE THREAD

**Issue by JBFahnline** [hypre-space/hypre#320]
I've used HYPRE in the past with good results, and I'm coming back to it again after not using it for several years.  Unfortunately, the clusters I used previously have all been decommissioned.  

I have been able to install HYPRE and run the ex5f.f example successfully on several different clusters, all of which use somewhat different set-ups.  When I try to run any of my own codes (including ones that have run successfully in the past), I get the following error:

============= error stack trace ====================
[32] ERROR: failed to find owner for idx = -1
       SubdomainGraph_dhFindOwner  file= SubdomainGraph_dh.c  line= 155

[32] called from: find_all_neighbors_unsym_private  file= SubdomainGraph_dh.c  line= 954
[32] called from: init_mpi_private  file= SubdomainGraph_dh.c  line= 515

This happens both using an older version of HYPRE (2.11.2) and the current version and on all the clusters.  I'm certainly using different versions of the Intel libraries than before, so that might be the issue.  

I would appreciate any ideas on how to fix the problem!

Thanks, John

**Comment by JBFahnline** [comment]
I figured out the problem.  I had forgotten that I needed to specify --enable-bigint when running configure.  For future reference, the errors listed in my original post are somehow related.

**Comment by victorapm** [comment]
That's good, @JBFahnline! I'm closing this issue since it has been solved.
