### ISSUE TITLE
HYPRE SMG solver: meaning of Grid Size

### ISSUE THREAD

**Issue by samratrao** [hypre-space/hypre#321]
For periodic conditions using HYPRE's SMG solver, the HYPRE documentation (https://hypre.readthedocs.io/_/downloads/en/latest/pdf/) says _For periodic problems, the **grid size** in periodic dimensions currently must be a power-of-two_. So i would like to know what is meant by grid size --- does it mean number of nodes or number of intervals (volumes) of the grid since the number of intervals is one less than the number of nodes.

**Comment by victorapm** [comment]
Hi @samratrao,

It refers to the number of cells (volumes). You might want to look at the PFMG solver as well since it can provide better performance than SMG.

**Comment by samratrao** [comment]
> Hi @samratrao,
> 
> It refers to the number of cells (volumes). You might want to look at the PFMG solver as well since it can provide better performance than SMG.

Thanks for the reply. I missed it and saw the reply when i got an alert that the issue has been closed a while ago.
