### ISSUE TITLE
Repackage with autoconf@2.70 or newer to use oneapi fortran

### ISSUE THREAD

**Issue by osborn9** [hypre-space/hypre#322]
From Jim Willenbring: You may see a request from the facilities to upgrade to use the latest version of Autoconf. If it is simple for your code, you may wish to simply do the update at your own convenience in anticipation of the request. For more info, you can contact Todd Munson. Thanks.

This came up as a spack issue this week and some details are explained in  https://github.com/spack/spack/issues/22643  (there's a workaround in spack, FYI). The recommended fix is updating to autoconf 2.70.

**Comment by osborn9** [comment]
Using the "assign" feature very loosely....this came up in the xSDK meeting today and wanted to let everyone know.

**Comment by rfalgout** [comment]
Version 2.69 seems to be the default installed on my tux box.  I didn't see a way to update it with the `yum` package manager.  I would prefer not to use a privately installed version, so maybe we should reach out to the sys admins?

What versions do you all have (do `autoconf --version`)?

**Comment by victorapm** [comment]
I also have version 2.69 on my tux box. The same on lassen and quartz. I see that the spack team implemented a hotfix for this issue in https://github.com/spack/spack/pull/22683

**Comment by victorapm** [comment]
Closing this issue since Rob has upgraded hypre to use autoconf 2.71
