### ISSUE TITLE
Parallelization of the code

### ISSUE THREAD

**Issue by Huq2090** [hypre-space/hypre#325]
I looked at example `ex3.c` and observed that, we can parallelized code considering fixed number of grid points per processor. Matrix and vectors are constructed based on that. But that restricts, total number of grid points along any axis to be multiple of number of processor.   

Can we go other way around, that is, can we have arbitrary number of grid points in x and y-axis? Can we then parallelize? 
If we can, then how will we construct matrix and vectors and move forward?  

Any insight is highly appreciated.

**Comment by victorapm** [comment]
Hi @Huq2090,

there's no restriction on the number of grid points held by each processor in each axis. However, if they are too different, this will result in load imbalance and degrade performance of the linear solver. Ideally, we want the same amount of work for each processor, thus, a similar size of unknowns for each of them.

**Comment by Huq2090** [comment]
Hello @victorapm,
Thank you for your reply.
I was wondering how can I allocate different number of grid points to different processor? Is there any example case which I can look at or follow?
Thank you.

**Comment by victorapm** [comment]
Hi @Huq2090,

you need to create a mapping function between the process id `myid` and the arrays `ilower`, `iupper`. Recall that each mpi rank will see its own values for `ilower` and `iupper`. In `ex3.c`, we have an example of such mapping for the case of equal grid points for each processor:
```
   N  = sqrt(num_procs);
   pj = myid / N;
   pi = myid - pj*N;

   ilower = {pi*n, pj*n};
   iupper = {ilower[0] + n-1, ilower[1] + n-1};
``` 
You need to create something like this for your case. There's no example code in hypre for this.
