### ISSUE TITLE
HYPRE works well with two processors but fails with one processor

### ISSUE THREAD

**Issue by RickGY** [hypre-space/hypre#327]
Hi! I have been running some experiments with Hypre and I ran into a problem. I tried to use the IJ interface to solve a system of linear equations using hypre/src/test/ij with flag -solver 1 and it worked well when running with 2 processors. However, when I switched to 1 processor, Hypre stalled immediately. The system of linear equations is defined by an SDD matrix arising from uniform coefficient Poisson problems on 3D grids.

To recreate the issue, please download the folder [hypre_issue.zip](https://github.com/hypre-space/hypre/files/6298542/hypre_issue.zip), change the variable hypre_dir in the Makefile, then run:

```bash
make run_proc1
make run_proc2
```

The following is the solver output when running with 1 processor from running the command:

```bash
mpirun -np 1 ~/hypre/src/test/ij --with-print-errors -solver 1 -fromonecsrfile uniform_grid_proc1.00000 -rhsfromonefile vec_proc1.00000 -print -tol 1e-8
```

>
    Running with these driver parameters:
    solver ID    = 1

    FromFile: uniform_grid_proc1.00000
    =============================================
    Generate Matrix:
    =============================================
    Spatial Operator:
    wall clock time = 0.000000 seconds
    wall MFLOPS     = 0.000000
    cpu clock time  = 0.002879 seconds
    cpu MFLOPS      = 0.000000

    Rhs FromFile: vec_proc1.00000
    Initial guess is 0
    =============================================
    IJ Vector Setup:
    =============================================
    RHS and Initial Guess:
    wall clock time = 0.000000 seconds
    wall MFLOPS     = 0.000000
    cpu clock time  = 0.000599 seconds
    cpu MFLOPS      = 0.000000

    Solver: AMG-PCG
    HYPRE_ParCSRPCGGetPrecond got good precond

    Num MPI tasks = 1

    Num OpenMP threads = 1

    BoomerAMG SETUP PARAMETERS:

    Max levels = 25
    Num levels = 8

    Strength Threshold = 0.250000
    Interpolation Truncation Factor = 0.000000
    Maximum Row Sum Threshold for Dependency Weakening = 1.000000

    Coarsening Type = HMIS 
    measures are determined locally

    No global partition option chosen.

    Interpolation = extended+i interpolation

    Operator Matrix Information:

                nonzero         entries per row        row sums
    lev   rows  entries  sparse  min  max   avg       min         max
    ===================================================================
    0     512     3200  0.012     4    7   6.2   0.000e+00   3.000e+00
    1     511     3199  0.012     4    7   6.3   0.000e+00   3.000e+00
    2     311     3919  0.041     6   18  12.6   0.000e+00   4.000e+00
    3     165     4559  0.167    12   46  27.6   5.115e-03   4.805e+00
    4      78     3020  0.496    22   65  38.7   3.188e-01   4.478e+00
    5      37     1237  0.904    28   37  33.4   1.035e+00   4.526e+00
    6      16      256  1.000    16   16  16.0   2.483e+00   4.674e+00
    7       6       36  1.000     6    6   6.0   3.990e+00   4.721e+00

    Interpolation Matrix Information:
                    entries/row    min     max         row sums
    lev  rows cols    min max     weight   weight     min       max 
    =================================================================
    0   512 x 511     1   3   1.667e-01 1.667e-01 5.000e-01 1.000e+00
    1   511 x 311     1   4   1.667e-01 2.500e-01 5.000e-01 1.000e+00
    2   311 x 165     1   4   2.146e-02 4.000e-01 2.480e-01 1.000e+00
    3   165 x 78      1   4   6.567e-03 4.555e-01 6.791e-02 1.000e+00
    4    78 x 37      1   4   9.732e-03 4.264e-01 1.402e-01 1.000e+00
    5    37 x 16      1   4   5.742e-03 2.366e-01 8.836e-02 1.000e+00
    6    16 x 6       1   4   2.094e-02 3.363e-01 1.322e-01 1.000e+00

        Complexity:    grid = 3.195312
                    operator = 6.070625
                    memory = 7.030938

    BoomerAMG SOLVER PARAMETERS:

    Maximum number of cycles:         1 
    Stopping Tolerance:               0.000000e+00 
    Cycle type (1 = V, 2 = W, etc.):  1

    Relaxation Parameters:
    Visiting Grid:                     down   up  coarse
                Number of sweeps:            1    1     1 
    Type 0=Jac, 3=hGS, 6=hSGS, 9=GE:     13   14     9 
    Point types, partial sweeps (1=C, -1=F):
                    Pre-CG relaxation (down):   0
                    Post-CG relaxation (up):   0
                                Coarsest grid:   0

    =============================================
    Setup phase times:
    =============================================
    PCG Setup:
    wall clock time = 0.010000 seconds
    wall MFLOPS     = 0.000000
    cpu clock time  = 0.002518 seconds
    cpu MFLOPS      = 0.000000

    <b,b>: 1.000000e+00

    Iters       ||r||_2     conv.rate  ||r||_2/||b||_2
    -----    ------------   ---------  ------------ 
        1    9.997558e-01    0.999756    9.997558e-01
        2    9.983957e-01    0.998640    9.983957e-01
        3    9.983834e-01    0.999988    9.983834e-01
        4    9.956677e-01    0.997280    9.956677e-01
        5    9.956676e-01    1.000000    9.956676e-01
        6    9.957078e-01    1.000040    9.957078e-01
        7    9.827902e-01    0.987027    9.827902e-01
        8    9.827975e-01    1.000007    9.827975e-01
        9    9.825688e-01    0.999767    9.825688e-01
    10    9.825692e-01    1.000000    9.825692e-01
    11    9.825691e-01    1.000000    9.825691e-01
    12    9.825757e-01    1.000007    9.825757e-01
    13    9.816778e-01    0.999086    9.816778e-01
    14    9.816778e-01    1.000000    9.816778e-01
    15    9.814156e-01    0.999733    9.814156e-01
    16    9.814161e-01    1.000001    9.814161e-01
    17    9.814159e-01    1.000000    9.814159e-01
    18    9.796562e-01    0.998207    9.796562e-01
    19    9.795565e-01    0.999898    9.795565e-01
    20    9.795602e-01    1.000004    9.795602e-01
    21    9.795311e-01    0.999970    9.795311e-01
    22    9.794540e-01    0.999921    9.794540e-01
    23    9.794538e-01    1.000000    9.794538e-01
    24    9.794528e-01    0.999999    9.794528e-01
    25    9.793476e-01    0.999893    9.793476e-01
    26    9.793476e-01    1.000000    9.793476e-01
    27    9.793476e-01    1.000000    9.793476e-01
    28    9.793472e-01    1.000000    9.793472e-01
    29    9.793439e-01    0.999997    9.793439e-01
    30    9.791652e-01    0.999817    9.791652e-01
    31    9.791689e-01    1.000004    9.791689e-01
    32    9.791689e-01    1.000000    9.791689e-01
    33    9.791687e-01    1.000000    9.791687e-01
    34    9.779934e-01    0.998800    9.779934e-01
    35    9.779928e-01    0.999999    9.779928e-01
    36    9.779869e-01    0.999994    9.779869e-01
    37    9.779871e-01    1.000000    9.779871e-01
    38    9.779878e-01    1.000001    9.779878e-01
    39    9.779895e-01    1.000002    9.779895e-01
    40    9.771468e-01    0.999138    9.771468e-01
    41    9.740101e-01    0.996790    9.740101e-01
    42    9.729349e-01    0.998896    9.729349e-01
    43    9.729349e-01    1.000000    9.729349e-01
    44    9.729356e-01    1.000001    9.729356e-01
    45    9.729349e-01    0.999999    9.729349e-01
    46    9.729356e-01    1.000001    9.729356e-01
    47    9.724527e-01    0.999504    9.724527e-01
    48    9.724648e-01    1.000012    9.724648e-01
    49    9.723871e-01    0.999920    9.723871e-01
    50    9.723823e-01    0.999995    9.723823e-01
    51    9.723766e-01    0.999994    9.723766e-01
    52    9.723701e-01    0.999993    9.723701e-01
    53    9.723709e-01    1.000001    9.723709e-01
    54    9.723709e-01    1.000000    9.723709e-01
    55    9.723506e-01    0.999979    9.723506e-01
    56    9.723506e-01    1.000000    9.723506e-01
    57    9.723506e-01    1.000000    9.723506e-01
    58    9.723491e-01    0.999998    9.723491e-01
    59    9.723479e-01    0.999999    9.723479e-01
    60    9.723480e-01    1.000000    9.723480e-01
    61    9.723497e-01    1.000002    9.723497e-01
    62    9.723706e-01    1.000021    9.723706e-01
    63    9.723599e-01    0.999989    9.723599e-01
    64    9.723600e-01    1.000000    9.723600e-01
    65    9.723598e-01    1.000000    9.723598e-01
    66    9.723598e-01    1.000000    9.723598e-01
    67    9.723597e-01    1.000000    9.723597e-01
    68    9.723598e-01    1.000000    9.723598e-01
    69    9.723598e-01    1.000000    9.723598e-01
    70    9.723641e-01    1.000004    9.723641e-01
    71    9.723641e-01    1.000000    9.723641e-01
    72    9.723641e-01    1.000000    9.723641e-01
    73    9.723643e-01    1.000000    9.723643e-01
    74    9.713352e-01    0.998942    9.713352e-01
    75    9.713499e-01    1.000015    9.713499e-01
    76    9.713048e-01    0.999954    9.713048e-01
    77    9.713048e-01    1.000000    9.713048e-01
    78    9.713047e-01    1.000000    9.713047e-01
    79    9.713047e-01    1.000000    9.713047e-01
    80    9.713047e-01    1.000000    9.713047e-01
    81    9.713046e-01    1.000000    9.713046e-01
    82    9.710928e-01    0.999782    9.710928e-01
    83    9.710607e-01    0.999967    9.710607e-01
    84    9.710542e-01    0.999993    9.710542e-01
    85    9.641676e-01    0.992908    9.641676e-01
    86    9.640748e-01    0.999904    9.640748e-01
    87    9.640675e-01    0.999993    9.640675e-01
    88    9.640676e-01    1.000000    9.640676e-01
    89    9.640648e-01    0.999997    9.640648e-01
    90    9.640647e-01    1.000000    9.640647e-01
    91    9.640647e-01    1.000000    9.640647e-01
    92    9.640620e-01    0.999997    9.640620e-01
    93    9.640630e-01    1.000001    9.640630e-01
    94    9.640630e-01    1.000000    9.640630e-01
    95    9.640641e-01    1.000001    9.640641e-01
    96    9.640640e-01    1.000000    9.640640e-01
    97    9.640649e-01    1.000001    9.640649e-01
    98    9.640656e-01    1.000001    9.640656e-01
    99    9.640658e-01    1.000000    9.640658e-01
    100    9.640679e-01    1.000002    9.640679e-01

    =============================================
    Solve phase times:
    =============================================
    PCG Solve:
    wall clock time = 0.010000 seconds
    wall MFLOPS     = 0.000000
    cpu clock time  = 0.011213 seconds
    cpu MFLOPS      = 0.000000

    Iterations = 100
    Final Relative Residual Norm = 9.640679e-01

**Comment by victorapm** [comment]
Hi @RickGY,

when using the option '-fromonecsrfile', hypre expects that the input matrix has the diagonal coeficient stored at the beggining of each row. Can you update your `uniform_grid_proc1.00000` file accordingly and run the code again? Moreover, the option `--with-print-errors` is not understood by the `ij` driver, you need to pass it to the configure script.

**Comment by RickGY** [comment]
Hi @victorapm, thanks for the reply. Do you mind elaborating a bit more on storing "the diagonal coefficient at the beginning of each row"? From reading the ij code, I thought that it only takes in the number of columns, then the pointer to the start of each row, column indices, and finally the non-zero values.

**Comment by victorapm** [comment]
Hi @RickGY,

if you pass a CSR matrix as input, the code expects the number of rows, row pointers, column indices and non-zero values. However, the column indices need to be in a specific order, i.e., the first column index for each row must be equal to the row index, that's what I meant with diagonal coefficient. Also, I see your column indices start from 1, but hypre works with 0-based CSR matrices, thus it expects that column indices start from zero. The same holds for the row pointers. So, to fix this, simply subtract 1 from the row pointer entries and column indices of your file.

To exemplify, in `uniform_grid_proc1.00000`, if you look at the data for the 9th row of the matrix (row number 8 in zero-based format), you have:
```
rowptr[8] = 39
rowptr[9] = 44
colidx = {1, 9, 10, 17, 73}
```
however, the correct would be:
```
rowptr[8] = 38
rowptr[9] = 43
colidx = {8, 0, 9, 16, 72}
```
Note: You can pass a matrix in COO format using the option `-fromfile` and avoid these restrictions.

**Comment by RickGY** [comment]
@victorapm thanks for the explanation, so the order of the non-zero values should be changed as well, as like the colidx?

**Comment by victorapm** [comment]
Yes, correct. I forgot to mention that

**Comment by RickGY** [comment]
@victorapm Got it, I try to see if this works.

**Comment by RickGY** [comment]
@victorapm Now the problem is fixed! Thank you so much!
