### ISSUE TITLE
Undefined references in hyper_BoomerAMGBuildExtPEInterpDevice

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#330]
Not sure if you're aware of this. Here's my configure line:

./configure CXX=/opt/hpe/hpc/mpt/mpt-2.22/bin/mpicxx CC=/opt/hpe/hpc/mpt/mpt-2.22/bin/mpicc FC=/opt/hpe/hpc/mpt/mpt-2.22/bin/mpif90 --prefix=/scratch/pmullown/install/gpu/hypre-master-4-12-2021/ --without-superlu --disable-bigint --without-openmp --with-cuda --enable-unified-memory --enable-curand --disable-cub --enable-shared

At the link step:

Making lib ...
make[1]: Entering directory `/lustre/eaglefs/scratch/pmullown/hypre/src/lib'
Building libHYPRE.so ...
nvcc -shared  -gencode arch=compute_70,"code=sm_70" -o libHYPRE-2.20.0.so   /scratch/pmullown/hypre/src/IJ_mv/*.o* /scratch/pmullown/hypre/src/distributed_ls/Euclid/*.o /scratch/pmullown/hypre/src/distributed_ls/ParaSails/*.o /scratch/pmullown/hypre/src/distributed_ls/pilut/*.o /scratch/pmullown/hypre/src/distributed_matrix/*.o* /scratch/pmullown/hypre/src/krylov/*.o* /scratch/pmullown/hypre/src/matrix_matrix/*.o* /scratch/pmullown/hypre/src/multivector/*.o* /scratch/pmullown/hypre/src/parcsr_ls/*.o* /scratch/pmullown/hypre/src/parcsr_mv/*.o* /scratch/pmullown/hypre/src/parcsr_block_mv/*.o* /scratch/pmullown/hypre/src/seq_mv/*.o* /scratch/pmullown/hypre/src/sstruct_ls/*.o* /scratch/pmullown/hypre/src/sstruct_mv/*.o* /scratch/pmullown/hypre/src/struct_ls/*.o* /scratch/pmullown/hypre/src/struct_mv/*.o* /scratch/pmullown/hypre/src/utilities/*.o* /scratch/pmullown/hypre/src/blas/*.o* /scratch/pmullown/hypre/src/lapack/*.o*        -lm  -L/nopt/nrel/ecom/hpacf/compilers/2020-07/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/cuda-10.2.89-rmccd4tpc5gxbbrjeeohphuuujb4cz2o/lib64 -lcudart -lcusparse -lcurand         -Xlinker=-soname,libHYPRE-2.20.0.so -Xlinker=-z,defs -ccbin=/opt/hpe/hpc/mpt/mpt-2.22/bin/mpicxx -gencode arch=compute_70,"code=sm_70" -Xcompiler ""
/nopt/nrel/ecom/hpacf/compilers/2020-07/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/binutils-2.34-2drppsfmkeudqr3ll7zz7pqxlsszuh4b/bin/ld: /scratch/pmullown/hypre/src/parcsr_ls/par_lr_interp.o: in function `hypre_BoomerAMGBuildExtInterp':
/scratch/pmullown/hypre/src/parcsr_ls/par_lr_interp.c:5304: undefined reference to `hypre_BoomerAMGBuildExtInterpDevice'
/nopt/nrel/ecom/hpacf/compilers/2020-07/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/binutils-2.34-2drppsfmkeudqr3ll7zz7pqxlsszuh4b/bin/ld: /scratch/pmullown/hypre/src/parcsr_ls/par_mod_lr_interp.o: in function `hypre_BoomerAMGBuildModExtInterp':
/scratch/pmullown/hypre/src/parcsr_ls/par_mod_lr_interp.c:541: undefined reference to `hypre_BoomerAMGBuildExtInterpDevice'
/nopt/nrel/ecom/hpacf/compilers/2020-07/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/binutils-2.34-2drppsfmkeudqr3ll7zz7pqxlsszuh4b/bin/ld: /scratch/pmullown/hypre/src/parcsr_ls/par_mod_lr_interp.o: in function `hypre_BoomerAMGBuildModExtPEInterp':
/scratch/pmullown/hypre/src/parcsr_ls/par_mod_lr_interp.c:1806: undefined reference to `hypre_BoomerAMGBuildExtPEInterpDevice'

-Paul

**Comment by pbauman** [comment]
I noticed this this morning as well. It happened with the latest commit to master (#312).

**Comment by liruipeng** [comment]
Thank you for letting us know. This problem should have been fixed in master.

**Comment by pbauman** [comment]
The compilation issue is fixed for me from the tip of master.

**Comment by liruipeng** [comment]
There seem to be seg-fault issues. We may have not run GPU regression tests for a previous PR merge. I am on that.

**Comment by liruipeng** [comment]
The problems should have been fixed. So I close this issue.

**Comment by PaulMullowney** [comment]
Are the seg faults resolved?

**Comment by ulrikeyang** [comment]
yes

**Comment by PaulMullowney** [comment]
Thanks!
