### ISSUE TITLE
Problem building hypre with XL compilers and CUDA on rzansel

### ISSUE THREAD

**Issue by lee-busby** [hypre-space/hypre#333]
Using either hypre-2.20.0 or current hypre-master.zip, I observe problems building on LLNL rzansel machine.  The first error is this:
```
/usr/tce/packages/cuda/cuda-11.0.2/include/thrust/type_traits/is_contiguous_iterator.h(74): error: "is_contiguous_iterator_v" is not a function or static data member
```

I attach a script ``build1`` and the output file from running it ``build1.out``.  I would be grateful for any advice on how to build hypre for this specific platform and compiler suite.

Thank you - Lee Busby
[build1.txt](https://github.com/hypre-space/hypre/files/6312315/build1.txt)
[build1.out.txt](https://github.com/hypre-space/hypre/files/6312316/build1.out.txt)

(P.S.: Had to add ``.txt`` to those file names in order to attach them here.)

**Comment by victorapm** [comment]
Hi @lee-busby,

thank you for reporting this. I see you are using `-std=c++14` for CXXFLAGS, however Hypre adds `-std=c++11` by default on the compiler flags for nvcc (CUFLAGS), see: https://github.com/hypre-space/hypre/blob/34b2f43ba8a2fe724ce11908525ae428c8fe2da2/src/configure#L8784

This mismatch between C++ dialects version used in CXXFLAGS and CUFLAGS is causing the issue. We should change the C++ dialect version properly in both flags if requested by the user. @liruipeng, any thoughts on how to do this? Should we create a `--with-cpp-dialect=` option for configure?

**Comment by lee-busby** [comment]
Thank you for the response.  My choice of ``-std-c++14`` was kind of accidental in the example given above.  The MARBL codes are currently at ``-std=c++11``.  That option gave different errors in building hypre, in a case where I was trying to use RAJA.  Our RAJA package uses an external CUB package (1.8.0, I think), which caused the CUDA-11 Thrust code to barf.  Anyway, I have been backing things out one by one.  We (MARBL) can probably live with either c++11 or c++14.  To be clear, changing ``-std=c++14`` to ``-std=c++11`` in the build1 script results in similar build errors, including, humorously:
```
 GCC warning "CUB requires C++14. Please pass -std=c++14 to your compile...
```
(And why is CUB even mentioned?  ``--enable-cub`` is off by default, according to ``configure --help``.)

**Comment by victorapm** [comment]
Hi @lee-busby,

this is a bit odd. I built hypre-master on Lassen with:
```
./configure --with-cuda=yes HYPRE_CUDA_SM=70 CUDA_HOME=/usr/tce/packages/cuda/cuda-11.0.2 AR='ar -rcu' RANLIB=ranlib CC=/usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-xl-2020.08.24-cuda-11.0.2/bin/mpicc CFLAGS='-O3 -qarch=auto -qtune=auto -qmaxmem=-1' CXX=/usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-xl-2020.08.24-cuda-11.0.2/bin/mpicxx CXXFLAGS='-O3 -qarch=auto -qtune=auto -qmaxmem=-1 -std=c++11 -qsourcetype=c++' FC=/usr/tce/packages/spectrum-mpi/spectrum-mpi-rolling-release-xl-2020.08.24-cuda-11.0.2/bin/mpixlf FCFLAGS='-O3 -qarch=auto -qtune=auto -qmaxmem=-1 -qsuppress=cmpmsg -qsuppress=1500-036 -qxlf2003=polymorphic -qnosave -qfree=f90 -qsuffix=cpp=f:f=f -qmaxmem=-1'
```

I'm attaching the configure and make outputs. Maybe your folder was not clean? Can you send your logs again?
[config.log](https://github.com/hypre-space/hypre/files/6314478/config.log)
[make.log](https://github.com/hypre-space/hypre/files/6314479/make.log)

Thanks!

**Comment by liruipeng** [comment]
Hi @lee-busby I just removed c++14 from your script. The build was fine on lassen. Unfortunately I don't have access to rz machines. Can you do `make distclean` in hypre and try again? Thanks!

**Comment by lee-busby** [comment]
Thank you both @liruipeng and @victorapm for check building.  I can build on both rzansel and lassen, and my build fails on both machines in essentially the exact same way.  It seems likely there is some difference in our user environments.  So I put together a new script ``build2``, attached, that displays its environment.  The only other difference is that I removed ``-std=c++14`` from the configure line.  I am building hypre-2.20.0.  Here is the md5sum for my hypre tar file and the two attached files:
```
: rzgenie2; md5sum hypre-2.20.0.tar.gz build2*
aba74c2f30fdb0188c4328e53b1929f2  hypre-2.20.0.tar.gz
6f5c0ac7de3f5006e941a10a32890446  build2
c3ca4106f09c2dd00c7be8c08109dbeb  build2.out
```
[build2.txt](https://github.com/hypre-space/hypre/files/6315289/build2.txt)
[build2.out.txt](https://github.com/hypre-space/hypre/files/6315291/build2.out.txt)
I ran ``build2`` as follows:
```
gunzip -c hypre-2.20.0.tar.gz | tar xf -
cd hypre-2.20.0/src
~/build2 > build2.out 2>&1
```
You should be able to do the same.  Please note I will not be working Thursday, should be back on Friday.

**Comment by victorapm** [comment]
Hi @lee-busby,

hypre-2.20.0 does not support CUDA-11. This is something added on master and will be shipped in the next release. The script `build2.sh` works fine for me with hypre-master on Lassen. Hope this helps!

Victor

**Comment by lee-busby** [comment]
Sorry for the long wait.  Thank you for the comment about hypre-2.20.0 and CUDA-11.  We (MARBL) have decided to move on ahead of the Hypre official releases.  We are currently using revision 25646da9, which was the HEAD of the Hypre master branch as of a few days ago, I think.  So if there is more to say about whether we should do that, or whether that revision is ok, now would be a good time to tell us.  I will note that I am now setting ``CUCC`` to the full pathname of ``nvcc`` as part of our Hypre configuration, which appears to resolve the apparent problems we previously saw with environment differences.  I would also like to control the value of ``CUFLAGS``, but the Hypre configuration sets that value internally, so it garbles the ultimate value.  It would be useful to add those variables to the output of ``./configure --help`` in setting up Hypre.

With that revision, and a CUB update, and a few other minor changes, I do have a Hypre build working in MARBL.  Nearly all of our test cases are failing with errors of the form:
```
CUDA ERROR (code = 2, out of memory) at hypre_memory.c:603
```
Sometimes ``invalid argument``, etc.  Those are presumably our fault.  So I think we can close this issue.

**Comment by liruipeng** [comment]
Hi, @lee-busby, we generally ask users to use the latest master if possible, but that revision should be fine. About `CUCC`, we will allow passing in full path in configure in the next release, something like `--with-cuda=path-to-cuda`. About `CUFLAGS`, hypre takes its existing value and append more stuff. Do you want hypre to not alter this variable at all if user has already set its value, which is fine.

About the `out-of-memory` issue, it seems line 603 is a memcpy (https://github.com/hypre-space/hypre/blob/25646da905fe56bf458f1fc00c2bb0188f61ebb6/src/utilities/hypre_memory.c#L603). It's strange to see an OOM error there.

**Comment by lee-busby** [comment]
Regarding the ``CUFLAGS`` question, I want the Hypre configuration to treat it the same as, say, ``CXXFLAGS``.  That is, if I pass in a value, then Hypre doesn't touch it, and uses (just) the given value.  Regarding the OOM matter, our test suite is failing roughly 170 jobs with variations of CUDA errors that all look about like that.  So it will probably turn out to be something pretty high level.  For example, I have unified-memory turned off for Hypre at the moment.  There are some other sort-of global things that MARBL does in setting up its automated test runs.  I will report back when we figure something out, if you like.
