### ISSUE TITLE
Cannot run `ij` example using Umpire on CUDA devices

### ISSUE THREAD

**Issue by pbauman** [hypre-space/hypre#339]
On a system with V100 and CUDA 10.2, I configured HYPRE as follows:

`HYPRE_CUDA_SM=70 ./configure --with-umpire --with-umpire-include=$UMPIRE_DIR/include --with-umpire-lib-dirs=$UMPIRE_DIR/lib --with-umpire-lib=-lumpire  --with-cuda=yes --without-MPI` `$UMPIRE_DIR` is the installation location of my Umpire build. HYPRE compiles successfully. I compile the `ij` test in the `test` directory using `make ij`. I run the `ij` using options that mimic the AMG benchmark, except I turn aggressive coarsening off since I did not compile with unified memory. I receive the following error at runtime:

<pre>
./ij -n 148 148 148 -pmis -keepT 1 -rlx 18 -exec_device -rap 1 -mod_rap2 1 -interptype 6 -solver 1 -agg_nl 0 -printallstats -27pt -mxrs 0.9 -ns 2 -Pmx 8
Running with these driver parameters:
  solver ID    = 1

=============================================
Hypre init times:
=============================================
Hypre init:
  wall clock time = 0.480000 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.453973 seconds
  cpu MFLOPS      = 0.000000

  Laplacian_27pt:
    (nx, ny, nz) = (148, 148, 148)
    (Px, Py, Pz) = (1, 1, 1)

=============================================
Generate Matrix:
=============================================
Spatial Operator:
  wall clock time = 0.590000 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.589990 seconds
  cpu MFLOPS      = 0.000000

  RHS vector has unit components
  Initial guess is 0
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  radix_sort: failed on 2nd step: cudaErrorInvalidValue: invalid argument
Aborted (core dumped)
</pre>

I saw in #243 that it specified with unified memory in the configure options of HYPRE, but I would have expected that using unified memory was not required. Am I mistaken? Thank you.

**Comment by liruipeng** [comment]
@pbauman No, you are right. UVM is not needed. 

I just ran it on lassen (V100, cuda-10.1), which worked fine, with the current `master`

```
mpirun -n 1 ./ij -n 148 148 148 -pmis -keepT 1 -rlx 18 -exec_device -rap 1 -mod_rap2 1 -interptype 6 -solver 1 -agg_nl 0 -print
allstats -27pt -mxrs 0.9 -ns 2 -Pmx 8
```
```
=============================================
Solve phase times:
=============================================
PCG Solve:
  wall clock time = 0.230000 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.230000 seconds
  cpu MFLOPS      = 0.000000


Iterations = 15
Final Relative Residual Norm = 3.439698e-09
```

Which version of Umpire do you use?

**Comment by pbauman** [comment]
Hi @liruipeng thanks for the quick reply. I built Umpire from yesterday's master, LLNL/Umpire@70c6b43f. I used the following to configure Umpire:

`cmake  -DENABLE_CUDA=On -DENABLE_C=On -DCMAKE_INSTALL_PREFIX=<install dir> ../Umpire`

**Comment by liruipeng** [comment]
Just updated to the latest `develop` of umpire. It still seems fine to me. 

I configure and install Umpire as

```
cmake3 -DCMAKE_INSTALL_PREFIX=../install_xlC_lassen -DENABLE_CUDA=On -DENABLE_OPENMP=Off -DCMAKE_CXX_COMPILER=xlC -DCMAKE_C_COMPILER=xlc -DENABLE_CUDA=On -DCMAKE_CUDA_FLAGS="-arch sm_70" -DENABLE_C=On ../
make
make install
```
But I am not an expert in cmake

**Comment by pbauman** [comment]
Ahhhhh, this was the critical part to my Umpire build: `-DCMAKE_CUDA_FLAGS="-arch sm_70"` I rebuilt Umpire with that option added and then rebuilt HYPRE and now the test works. Thanks for the quick reply. Closing.
