### ISSUE TITLE
Umpire, Cuda, and IJ interface

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#342]
Hi,

Should I expect Umpire memory pools to work when building with Cuda. I'm seeing crashes in thrust stable_sort_by_key methods in hypre_IJMatrixAssembleParCSRDevice. 

Is this something I should expect to work?

-Paul

**Comment by pbauman** [comment]
Hi @PaulMullowney, it worked for me yesterday, but I had to make sure and include the cuda arch when building umpire, see #339. Otherwise, I saw runtime failures in Thrust as you are indicating. Hopefully that helps.

**Comment by liruipeng** [comment]
@PaulMullowney Yes, this should work. As @pbauman mentioned, please check your Umpire build. Thanks!

**Comment by PaulMullowney** [comment]
Success. Thanks! I should have searched the issues first before posting.
