### ISSUE TITLE
HYPRE_IJVectorPrint on GPUs

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#343]
Hi,
I'm trying to dump a vector to file. I'm building with CUDA and UVM. Specifically I see segfaults at:

https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/par_vector_device.c#L28

MPT: #16 count_if<thrust::cuda_cub::execute_on_stream, int*, out_of_range<int> > (
MPT:     pred=..., last=0x7ffc2bfda5d4, first=0x7ffc2bfda5d0, exec=...)
MPT:     at /nopt/nrel/ecom/hpacf/compilers/2020-07/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/cuda-10.2.89-rmccd4tpc5gxbbrjeeohphuuujb4cz2o/include/thrust/detail/count.inl:51
MPT: #17 hypre_ParVectorGetValuesDevice () at par_vector_device.c:28
MPT: #18 0x00002acd4ee2ab95 in hypre_ParVectorGetValues (
MPT:     vector=vector@entry=0x1c0a6660, num_values=num_values@entry=1,
MPT:     indices=indices@entry=0x7ffc2bfda5d0, values=values@entry=0x7ffc2bfda5d8)
MPT:     at par_vector.c:1097
MPT: #19 0x00002acd4ec9cef8 in hypre_IJVectorGetValuesPar (vector=<optimized out>,
MPT:     num_values=1, indices=0x7ffc2bfda5d0, values=0x7ffc2bfda5d8)
MPT:     at IJVector_parcsr.c:727
MPT: #20 0x00002acd4ec7b6b3 in HYPRE_IJVectorPrint (vector=0x53df6a70,
MPT:     filename=<optimized out>) at HYPRE_IJVector.c:637

A host integer is used to initialize the indices vector. In none of these methods, does the indices get moved onto a device vector that can be used in the crashing thrust call, that I can see.

-Paul

**Comment by liruipeng** [comment]
> Hi,
> I'm trying to dump a vector to file. I'm building with CUDA and UVM. Specifically I see segfaults at:
> 
> https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/par_vector_device.c#L28
> 
> MPT: #16 count_if<thrust::cuda_cub::execute_on_stream, int*, out_of_range > (
> MPT: pred=..., last=0x7ffc2bfda5d4, first=0x7ffc2bfda5d0, exec=...)
> MPT: at /nopt/nrel/ecom/hpacf/compilers/2020-07/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.4.0/cuda-10.2.89-rmccd4tpc5gxbbrjeeohphuuujb4cz2o/include/thrust/detail/count.inl:51
> MPT: #17 hypre_ParVectorGetValuesDevice () at par_vector_device.c:28
> MPT: #18 0x00002acd4ee2ab95 in hypre_ParVectorGetValues (
> MPT: vector=vector@entry=0x1c0a6660, num_values=num_values@entry=1,
> MPT: indices=indices@entry=0x7ffc2bfda5d0, values=values@entry=0x7ffc2bfda5d8)
> MPT: at par_vector.c:1097
> MPT: #19 0x00002acd4ec9cef8 in hypre_IJVectorGetValuesPar (vector=,
> MPT: num_values=1, indices=0x7ffc2bfda5d0, values=0x7ffc2bfda5d8)
> MPT: at IJVector_parcsr.c:727
> MPT: #20 0x00002acd4ec7b6b3 in HYPRE_IJVectorPrint (vector=0x53df6a70,
> MPT: filename=) at HYPRE_IJVector.c:637
> 
> A host integer is used to initialize the indices vector. In none of these methods, does the indices get moved onto a device vector that can be used in the crashing thrust call, that I can see.
> 
> -Paul

@PaulMullowney  You are right. We need to fix this function on device, which is not used in our regression tests apparently. Thanks!

**Comment by PaulMullowney** [comment]
I've create a PR with a fix. Feel free to modify as you see fit.

https://github.com/hypre-space/hypre/pull/345

**Comment by liruipeng** [comment]
Fixed. And it will be in the next release.

**Comment by PaulMullowney** [comment]
Was this merged into master?

From: Ruipeng Li ***@***.***>
Reply-To: hypre-space/hypre ***@***.***>
Date: Thursday, May 6, 2021 at 11:41 PM
To: hypre-space/hypre ***@***.***>
Cc: "Mullowney, Paul" ***@***.***>, Mention ***@***.***>
Subject: Re: [hypre-space/hypre] HYPRE_IJVectorPrint on GPUs (#343)


CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Fixed. And it will be in the next release.

**Comment by liruipeng** [comment]
> Was this merged into master? From: Ruipeng Li ***@***.***> Reply-To: hypre-space/hypre ***@***.***> Date: Thursday, May 6, 2021 at 11:41 PM To: hypre-space/hypre ***@***.***> Cc: "Mullowney, Paul" ***@***.***>, Mention ***@***.***> Subject: Re: [hypre-space/hypre] HYPRE_IJVectorPrint on GPUs (#343) CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe. Fixed. And it will be in the next release. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhypre-space%2Fhypre%2Fissues%2F343%23issuecomment-834082893&data=04%7C01%7CPaul.Mullowney%40nrel.gov%7Ca55ef1b149a34932a77208d9111acf5f%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637559629117850547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2F%2F3dcBpTLqSkdiiP1rDRmQTgluk%2BI6ZF1DXmwW7tcPk%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAONG4MQ6LDDXNCWBSHPGW73TMN4RVANCNFSM43K4SWPA&data=04%7C01%7CPaul.Mullowney%40nrel.gov%7Ca55ef1b149a34932a77208d9111acf5f%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637559629117850547%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Hnl3fRuoRHV%2FTRgKqbo8MYLP%2BKqePqiG8gnSP6BX2js%3D&reserved=0>.

Not yet. It was merged to a GPU branch, which will be merged to master very soon. And we will have a new release after that.
