### ISSUE TITLE
Periodic BC for AMS

### ISSUE THREAD

**Issue by tangqi** [hypre-space/hypre#350]
Hi,

We are trying to use AMS preconditioner through petsc. We implemented a second-order mimetic finite difference scheme and their staggered grid interface (dmstag). We have a well defined curl curl problem on the edge dofs. I believe we need to provide two additional things: coordinates and gradient operator.

How can we incorporate the periodic BC when providing these two operators? Let's say if we have N grid points from [0, 2pi], should we provide the operator/coordinate to include both 0 and 2pi? Will AMS be confused by the jump of 0 to 2pi in the coordinate? (We are solving in the cylindrical coordinate.)

If there is any example for that (mfem, petsc or hypre), that would be certainly helpful. 

Thanks,
Qi

**Comment by tangqi** [comment]
@mlstowell Mark, do you happen to know by any chance? Or is there anyone we can reach out? Thanks

**Comment by tangqi** [comment]
Thanks a lot, Mark. That's going to be VERY helpful

**Comment by mlstowell** [comment]
Hi, @tangqi ,

I sent you a pair of test meshes and a modified version of ex3p.cpp which demonstrate that HypreAMS seems to work fine with periodic meshes and the results compare well with equivalent curved embedded meshes.

These two case are handled differently in the HypreAMS wrapper. See `HypreAMS::Init` in `linalg/hypre.cpp`. For standard meshes the vertices are extracted from the mesh and passed to HYPRE using the `HYPRE_AMSSetCoordinateVectors` function. For periodic meshes, or any meshes which use a `GridFunction` to define the coordinates, the vertices are not available so the wrapper defines interpolation matrices instead and passes these to HYPRE using the `HYPRE_AMSSetInterpolations` function.

If you're not using the `HypreAMS` wrapper from MFEM but using AMS through a PETSc interface I'm not sure exactly how to proceed but you should still have the option of creating interpolation operators and passing them to AMS. This may involve accessing the PETSc's pointer to the AMS solver struct and using the `HYPRE_AMSSetInterpolations` function directly. If this is the case you can probably copy code from our wrapper to help create these interpolation operators.

Best wishes,
Mark

**Comment by tangqi** [comment]
Hi @mlstowell 
Thanks again for your help. I have a look at `HypreAMS::Init`, now things become clear. It makes a lot of sense that we should provide an interpolation operator for periodic BC instead of just coordinates. I will explore the possibility of building such an operator in the petsc dmstag interface. 

Thanks a lot!

Best,
Qi
