### ISSUE TITLE
AMD/HIP compilation architecture

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#353]
What is the analog to HYPRE_CUDA_SM for HIP compilation? Do you specify through HIPCXXFLAGS? If so, can you provide an example.

-Paul

**Comment by pbauman** [comment]
Hi @PaulMullowney Currently there is not one. Are you running into issues?

The GPU on the node should be detected by the `hipcc` script (which is used in the compilation of the GPU parts of HYPRE when using the HIP backend). If you're compiling on a node without an AMD gpu, effectively cross-compiling, this has not been explicitly enabled yet. Outside of compiling on the node you wish to run on, you could set `HIPCXXFLAGS="--cuda-gpu-arch=gfx908"` to target MI100 (for example).

**Comment by PaulMullowney** [comment]
Should that flag be:
--offload-arch=gfx908
?

**Comment by liruipeng** [comment]
> Should that flag be:
> --offload-arch=gfx908
> ?

This is what I use `--amdgpu-target=gfx906,gfx908`
