### ISSUE TITLE
Invalid file HYPREConfig.cmake

### ISSUE THREAD

**Issue by grospelliergilles** [hypre-space/hypre#360]
The generated file HYPREConfig.cmake is invalid because it begins with invalid chars.

Using the simple CMakeLists.txt:

~~~{.cmake}
cmake_minimum_required(VERSION 3.12 FATAL_ERROR)
project(Test LANGUAGES CXX)
find_package(HYPRE)
~~~

You have the following error message:

~~~
CMake Error at /tmp/hypre_install/lib/cmake/HYPRE/HYPREConfig.cmake:1:
  Parse error.  Expected a command name, got unquoted argument with text
  "/******************************************************************************".
Call Stack (most recent call first):
  CMakeLists.txt:3 (find_package)


CMake Error at CMakeLists.txt:3 (find_package):
  find_package Error reading CMake code from
  "/tmp/hypre_install/lib/cmake/HYPRE/HYPREConfig.cmake".


-- Configuring incomplete, errors occurred!

~~~

I think this is because you use C++ comment style in the CMake file instead of '#'

**Comment by osborn9** [comment]
Hi @grospelliergilles, Yes, you are correct and this needs to be fixed. Thanks for pointing it out!

I've added this fix to the PR #349 where we're making other cmake updates (and will be merged to master soon).
