### ISSUE TITLE
"conflicting declaration" error when attempting to build against master on lassen

### ISSUE THREAD

**Issue by nDimensionalSpace** [hypre-space/hypre#373]
`/g/g22/hodge3/data/d_w_TLL/../libs/hypre/src/hypre/include/HYPRE_utilities.h:99:19: error: conflicting declaration 'typedef HYPRE_Int MPI_Comm'`

Any thoughts?

**Comment by rfalgout** [comment]
Hi @nDimensionalSpace .  When hypre is configured `--without-MPI`, we define `MPI_Comm` to be a `HYPRE_Int`.  I guess one of two things is happening here:
- You are (or another package is) also defining `MPI_Comm`
- You are actually using MPI in your code

Can you tell us more about what you are doing in your code and why you are configuring hypre without MPI?  We generally focus on running in parallel, so this may be a use case we have not really come across.  Other users have built hypre without MPI, but usually only when they don't have MPI installed on their platforms.

Thanks!

-Rob

**Comment by nDimensionalSpace** [comment]
Rob:

Right . . .  Just trying to run with the "easiest" case possible.  If it's easier to run with MPI enabled, I am good with that.  Thanks.

Neil
