### ISSUE TITLE
Question: How to run on Multiple GPUs ?

### ISSUE THREAD

**Issue by hansmitgans** [hypre-space/hypre#379]
I have access to a machine with 16 GPUs and I want to use them. If I use eg: mpirun -np 4  It seems that only 1GPU is used. What is the correct way to inform HYPRE about multiple GPUs. Can I run multithreaded and with multiple GPUs or do I have to have several processes ? I could not find anything in the user guide.

**Comment by liruipeng** [comment]
@hansmitgans You need to bind GPUs (`cudaSetDevice`) before calling `HYPRE_Init` (see https://github.com/hypre-space/hypre/blob/8a41a42c8dfc3d9b204ad6ee884d46da3cc432bf/src/test/ij.c#L2153 for example binding GPUs in a round-robin fashion https://github.com/hypre-space/hypre/blob/8a41a42c8dfc3d9b204ad6ee884d46da3cc432bf/src/utilities/hypre_cuda_utils.c#L1171), so each MPI process will use the device that has been set. Hypre is not thread safe. Please do not call hypre from a multi-threaded region.

**Comment by hansmitgans** [comment]
that works!
