### ISSUE TITLE
git filename collided

### ISSUE THREAD

**Issue by liruipeng** [hypre-space/hypre#384]
See mfem/mfem#2245

> git clone https://github.com/hypre-space/hypre hypre-2.21.0
Cloning into 'hypre-2.21.0'...
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:
  'src/utilities/HYPRE_handle.c'
  'src/utilities/hypre_handle.c'

I do remember this issue when I worked on my Mac where probably this issue originated. Any ideas how to fix?

**Comment by rfalgout** [comment]
I don't even understand it.  There is no file named `src/utilities/HYPRE_handle.c` that I can find.

**Comment by rfalgout** [comment]
Good point about Windows @tzanio !  I usually check this stuff on my linux box, but this time I looked at it on my laptop (Windows) and didn't see the file.  Of course.

@liruipeng .  The lower-case `hypre_` names really aren't needed.  For some reason the `utilities` directory has a bunch of these files, but we don't really do this in most other parts of hypre.  So, I recommend dropping the `hypre_` in the names.  I think we should do the same for the other files as well.

**Comment by liruipeng** [comment]
> @liruipeng . The lower-case `hypre_` names really aren't needed. For some reason the `utilities` directory has a bunch of these files, but we don't really do this in most other parts of hypre. So, I recommend dropping the `hypre_` in the names. I think we should do the same for the other files as well.

This works for me. I can rename `hypre_handle.c` to `handle.c`. Do we want to rename the others in this way, such as `hypre_printf.c` --> `printf.c`, `hypre_qsort.c` --> `qsort.c`, which are short names but should be fine.

**Comment by rfalgout** [comment]
Yes, probably.  Why don't you create a branch/PR with the changes in them so we can work on it and discuss as a team.  There are other places in hypre where we use this prefix that may require more thought.  Thanks!

**Comment by liruipeng** [comment]
Fixed.
