### ISSUE TITLE
QUESTION: example files

### ISSUE THREAD

**Issue by atsteich** [hypre-space/hypre#39]
I had a look on the example files, and found that running for e.g. `ex5` with BoomerAMG on a single core takes less time, than running it on all 4 cores of my processor, although all four of them are running at 100%. I stopped the time for Setup() and Solve(). 

I used standard settings, with a mesh-size of 2048x2048 on a core i7 7700.
Is there so much overhead that it is less efficient for this mesh size, or am I doing something wrong?

thanks, Chris

**Comment by rfalgout** [comment]
I just tested this myself and got a speedup of about 1.7.  However, the iteration count increased from 7 iterations to 11.  With AMG-CG, the speedup is about 2.2 and the iterations increase from 5 to 7. For either, the per-iteration speedup is around 3.

This is not unusual when going from one processor (no communication) to multiple processors.  Speedups are better when comparing two runs that both have communication, as long as the per-processor problem size is not too small.  The iteration count will also stabilize at larger processor counts.  Unfortunately, the convergence of AMG has a dependence on the parallel data distribution.

I turned optimization on and used MPI_Wtime() to do the timing.  The runs were on a Linux box, the specs of which I don't recall off the top of my head, but I think it has about 6 cores and enough memory that it shouldn't be swapping on these runs.
