### ISSUE TITLE
hypre with CUDA code compilation issue

### ISSUE THREAD

**Issue by babreu-ncsa** [hypre-space/hypre#391]
Hello,

I am trying to use Hypre to build a larger project in Fortran, but I'm failing miserably in compiling even the simplest of the codes.
I was able to compile Hypre with cuda apparently without a problem. My configuration is:

`./configure --enable-fortran --with-MPI --enable-debug --with-cuda --enable-unified-memory `

The output variables are:

AR='ar -rcu'
BLASLIBDIRS=''
BLASLIBS=''
BUILD_CC_SHARED=''
BUILD_CXX_SHARED=''
BUILD_FC_SHARED=''
BUILD_JAVA='0'
BUILD_PYTHON='0'
CALIPER_INCLUDE=''
CALIPER_LIBS=''
CC='mpicc'
CFLAGS='-g -Wall '
CPP='mpicc -E'
CPPFLAGS=''
CUCC='nvcc'
CUFLAGS='-g -O0 -lineinfo -ccbin=mpic++ -gencode arch=compute_70,"code=sm_70" -expt-extended-lambda -dc -std=c++11 --x cu -Xcompiler "-g -Wall "'
CXX='mpic++'
CXXFLAGS='-g -Wall '
DEFS='-DHAVE_CONFIG_H'
DSUPERLU_INCLUDE=''
DSUPERLU_LIBS=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP='/usr/bin/grep -E'
EXEEXT=''
FC='mpif77'
FCFLAGS='-g -O2'
FCLIBS=' -L/opt/packages/openmpi/gcc/4.0.2-gcc8.3.1/lib -L/usr/lib/gcc/x86_64-redhat-linux/8 -L/usr/lib/gcc/x86_64-redhat-linux/8/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/jet/packages/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/cuda-11.1.1-a6ajxenobex5bvpejykhtnfut4arfpwh/lib64 -L/usr/lib/gcc/x86_64-redhat-linux/8/../../.. -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lm -lquadmath -lpthread'
FFLAGS='-g -Wall'
FLIBS=''
GREP='/usr/bin/grep'
HIPCC=''
HOSTNAME='v002.ib.bridges2.psc.edu'
HYPRE_ARCH='LINUX'
HYPRE_BUGS='https://github.com/hypre-space/hypre/issues'
HYPRE_CUDA_INCLUDE='-I/jet/packages/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/cuda-11.1.1-a6ajxenobex5bvpejykhtnfut4arfpwh/include'
HYPRE_CUDA_LIBS='-L/jet/packages/spack/opt/spack/linux-centos8-zen/gcc-8.3.1/cuda-11.1.1-a6ajxenobex5bvpejykhtnfut4arfpwh/lib64 -lcudart -lcusparse -lcurand'
HYPRE_DATE='2020/09/24'
HYPRE_DISTRIBUTED_LS_DIR='/jet/home/babreu/hypre/hypre/src/distributed_ls'
HYPRE_EUCLID_FILES='/jet/home/babreu/hypre/hypre/src/distributed_ls/Euclid/*.o'
HYPRE_FEI_BASE_DIR=''
HYPRE_FEI_FEMLI_FILES=''
HYPRE_FEI_HYPRE_FILES=''
HYPRE_FEI_SRC_DIR=''
HYPRE_FEI_SUBDIRS=''
HYPRE_HIP_INCL=''
HYPRE_HIP_LIBS=''
HYPRE_INCINSTALL='${prefix}/include'
HYPRE_INSTALLDIR='/jet/home/babreu/hypre/gcc8.3'
HYPRE_KOKKOS_INCLUDE=''
HYPRE_KOKKOS_LIB=''
HYPRE_KOKKOS_LIB_DIR=''
HYPRE_KOKKOS_SRC_DIR=''
HYPRE_LIBINSTALL='${exec_prefix}/lib'
HYPRE_LIBSUFFIX='.a'
HYPRE_NAME='hypre'
HYPRE_NAP_INCLUDE=''
HYPRE_PARASAILS_FILES='/jet/home/babreu/hypre/hypre/src/distributed_ls/ParaSails/*.o'
HYPRE_PILUT_FILES='/jet/home/babreu/hypre/hypre/src/distributed_ls/pilut/*.o'
HYPRE_RAJA_INCLUDE=''
HYPRE_RAJA_LIB=''
HYPRE_RAJA_LIB_DIR=''
HYPRE_ROCM_PREFIX=''
HYPRE_SRCDIR='/jet/home/babreu/hypre/hypre/src'
HYPRE_TIME='00:00:00'
HYPRE_UMPIRE_INCLUDE=''
HYPRE_UMPIRE_LIB=''
HYPRE_UMPIRE_LIB_DIR=''
HYPRE_VERSION='2.20.0'
LAPACKLIBDIRS=''
LAPACKLIBS=''
LDFLAGS='-ccbin=mpic++ -gencode arch=compute_70,"code=sm_70" -Xcompiler ""'
LIBOBJS=''
LIBS='   -lm'
LINK_CC='nvcc'
LINK_CXX='nvcc'
LINK_FC='mpif77'
LTLIBOBJS=''
MPIFLAGS=''
MPIINCLUDE=''
MPILIBDIRS=''
MPILIBS=' '
OBJEXT='o'
PACKAGE_BUGREPORT=''
PACKAGE_NAME=''
PACKAGE_STRING=''
PACKAGE_TARNAME=''
PACKAGE_URL=''
PACKAGE_VERSION=''
PATH_SEPARATOR=':'
PYTHON=''
RANLIB='ranlib'
SET_MAKE=''
SHARED_BUILD_FLAG=''
SHARED_COMPILE_FLAG=''
SHARED_OPTIONS=''
SHARED_SET_SONAME=''
SHELL='/bin/sh'
SUPERLU_INCLUDE=''
SUPERLU_LIBS=''
ac_ct_CC=''
ac_ct_CXX=''
ac_ct_FC=''
bindir='${exec_prefix}/bin'
build='x86_64-pc-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='pc'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='${prefix}'
host='x86_64-pc-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='pc'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/jet/home/babreu/hypre/gcc8.3'
program_transform_name='s,x,x,'
psdir='${docdir}'
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

Here's the simple code (test.f90) I'm trying to compile:

_program main
use mpi
implicit none
integer :: ierr
integer*8 :: grid
call MPI_INIT(ierr)
call HYPRE_StructGridCreate(MPI_COMM_WORLD, 2, grid, ierr)
call MPI_FINALIZE(ierr)
end_

Then I compile with

`mpifort -c -I${CUDA_HOME}/include -I$HYPRE/include test.f90`

which of course goes alright, and then

`mpifort test.o -o test -L${CUDA_HOME}/lib64 -lcudart -lcurand -lcusparse -L$HYPRE/lib -lHYPRE -lstdc++`

which is when I get errors:

_/jet/home/babreu/hypre/gcc8.3/lib/libHYPRE.a(hypre_memory.obj): In function `__sti____cudaRegisterAll()':
/tmp/tmpxft_0023c50a_00000000-6_hypre_memory.cudafe1.stub.c:18: undefined reference to `__cudaRegisterLinkedBinary_47_tmpxft_0023c50a_00000000_7_hypre_memory_cpp1_ii_3f83de32'
/jet/home/babreu/hypre/gcc8.3/lib/libHYPRE.a(hypre_cuda_utils.obj): In function `__sti____cudaRegisterAll()':
/tmp/tmpxft_0023c4d0_00000000-6_hypre_cuda_utils.cudafe1.stub.c:287: undefined reference to `__cudaRegisterLinkedBinary_51_tmpxft_0023c4d0_00000000_7_hypre_cuda_utils_cpp1_ii_f19a05a8'
/jet/home/babreu/hypre/gcc8.3/lib/libHYPRE.a(hypre_general.obj): In function `__sti____cudaRegisterAll()':
/tmp/tmpxft_0023c4ef_00000000-6_hypre_general.cudafe1.stub.c:18: undefined reference to `__cudaRegisterLinkedBinary_48_tmpxft_0023c4ef_00000000_7_hypre_general_cpp1_ii_cf770a76'_

This is after a lot of digging. Really a lot. I have been trying to compile this for about a month now. Read pretty much everything that is available online regarding Hypre + CUDA. Any tips? Thank you so much!

**Comment by lacrymose** [comment]
@liruipeng Dear Ruipeng, I try to compile ex5 in the examples folder with CUDA 11.1 and gcc-9 supported and I get similar errors. Could you help me with this issue?

**Comment by babreu-ncsa** [comment]
This is still a mystery to me :/

**Comment by liruipeng** [comment]
@lacrymose @babreu-ncsa We are working on the Fortran examples with GPUs. Basically the issues are how to allocate GPU memory in  Fortran code as we do in the C examples. If you have your own working code, to link with hypre, try to use dynamic library linking for now (add `--enable-shared` in configure). It worked for me. 

```
mpifort -c ex5f.f
mpifort ex5f.o -o ex5f -L${CUDA_HOME}/lib64 -lcudart -lcurand -lcusparse -L../lib/ -lHYPRE -lstdc++
```
Again, this example doesn't run with CUDA yet due to the memory issue.

Hope this helps and we will fix the Fortran examples soon.

Thanks!

-Ruipeng

**Comment by babreu-ncsa** [comment]
@liruipeng Thanks for getting back to us! Unfortunately, I had already tried that. Note that, what I am trying to compile, is simply:

program main
use mpi
implicit none
integer :: ierr
integer*8 :: grid
call MPI_INIT(ierr)
call HYPRE_StructGridCreate(MPI_COMM_WORLD, 2, grid, ierr)
call MPI_FINALIZE(ierr)
end

**Comment by babreu-ncsa** [comment]
Just to report it, I tried to compile HYPRE without `--enable-fortran ` and compile the C version of this snippet:

#include <stdio.h>
#include "mpi.h"
int main(int argc, char *argv[])
{
	int ierr, grid;
	
	grid = 1;
	MPI_Init(&argc, &argv);
	ierr = hypre_StructGridCreate(MPI_COMM_WORLD, 2, grid);
	MPI_Finalize();
	return 0;
}

and I get exactly the same errors:
babreu@v002 test]$ mpiicc struct_test.o -o test -L${CUDA_HOME}/lib64 -lcudart -lcurand -lcusparse -L/jet/home/babreu/Libraries/hypre/intel_roberto_noF/lib/ -lHYPRE -lstdc++
/jet/home/babreu/Libraries/hypre/intel_roberto_noF/lib//libHYPRE.a(hypre_memory.obj): In function `_INTERNAL171b9e94::__sti____cudaRegisterAll()':
tmpxft_00017bd7_00000000-8_hypre_memory.cudafe1.cpp:(.text+0x1db5): undefined reference to `__cudaRegisterLinkedBinary_47_tmpxft_00017bd7_00000000_9_hypre_memory_cpp1_ii_3f83de32'
/jet/home/babreu/Libraries/hypre/intel_roberto_noF/lib//libHYPRE.a(hypre_cuda_utils.obj): In function `_INTERNAL8971c4d7::__sti____cudaRegisterAll()':
tmpxft_000179b1_00000000-8_hypre_cuda_utils.cudafe1.cpp:(.text+0x6515): undefined reference to `__cudaRegisterLinkedBinary_51_tmpxft_000179b1_00000000_9_hypre_cuda_utils_cpp1_ii_f19a05a8'
/jet/home/babreu/Libraries/hypre/intel_roberto_noF/lib//libHYPRE.a(hypre_general.obj): In function `_INTERNAL99bd38c1::__sti____cudaRegisterAll()':
tmpxft_00017bb2_00000000-8_hypre_general.cudafe1.cpp:(.text+0x8c5): undefined reference to `__cudaRegisterLinkedBinary_48_tmpxft_00017bb2_00000000_9_hypre_general_cpp1_ii_cf770a76'

**Comment by liruipeng** [comment]
@babreu-ncsa The problem is from linking using host linker (mpiicc) for GPU-hypre, so the device code cannot be linked. You can either use `nvcc -ccbin=mpiicc` to link, or wait for the changes we will make to allow linking using host linkers. Thanks again for reporting it!

**Comment by babreu-ncsa** [comment]
Hi again @liruipeng, and thanks for your quick response! I was indeed able to compile the C version with:

nvcc -ccbin=mpicc -c test.c
nvcc -ccbin=mpicc test.o -L../lib/ -lHYPRE -lstdc++ -lm  -L${CUDA_HOME}/lib64 -lcudart -lcurand -lcusparse

after having compiled Hypre with openmpi/4.0.5-gcc10.2.0. I am trying to figure out how to do the Fortran side of it now (should nvfortran work similarly?).
