### ISSUE TITLE
Missing MPI files when Installing Hypre on Windows with CMake for Visual Studio

### ISSUE THREAD

**Issue by tmpnemophd** [hypre-space/hypre#4]
Hello,

I am trying to install Hypre (ver. 2.11.2) on my Windows machine using CMake (ver. 3.14.0), but I am having some trouble due to missing mpi.h files. I was wondering if I could receive any help resolving this issue. I am new to Hypre and I am just trying to get any example code to run.

When I build the binaries (configured for Visual Studio 2011; x64) on CMake following the installation instruction, I receive the following messages:

----------
The C compiler identification is MSVC 17.0.50727.1
The CXX compiler identification is MSVC 17.0.50727.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/x86_amd64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/x86_amd64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/x86_amd64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 11.0/VC/bin/x86_amd64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND) 
Configuring done
----------

Then, as instructed, I generate the build files.

When I open up Visual Studio and try to build the "ALL_BUILD" target, I run into 395 errors, all of which say the following line:
"error C1083: Cannot open include file: 'mpi.h': No such file or directory"
The associated File is "HYPRE_utilities.h" and Line = 25.

Based on the error messages I get, both on CMake and Visual Studio, I think this issue has to do with MPI. Is there any way to bypass MPI? My ultimate intention is to utilize OpenMP-enabled Linear-Algebraic System Interface in Fortran, and I do NOT need MPI for my applications.

Thank you.

**Comment by tmpnemophd** [comment]
It worked! Thank you!

**Comment by rfalgout** [comment]
Excellent!
