### ISSUE TITLE
Hypre on Spock

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#401]
Has anyone successfully compiled and ran Hypre on Spock with HIP? Any suggestions on environment variables and build flags would be much appreciated.

-Paul

**Comment by PaulMullowney** [comment]
#!/bin/bash

module load craype-accel-amd-gfx908
module load PrgEnv-cray
module load rocm/4.2.0
module load cray-mpich

export rocm_version=4.2.0

export CFLAGS="-g -O2 -I$MPICH_DIR/include"
export CXXFLAGS="-g -O2 -I$MPICH_DIR/include" 
export HYPRE_INSTALL_PREFIX=/gpfs/alpine/cfd116/scratch/mullowne//install/gpu/hypre-rocm-${rocm_version}-$(date +%Y-%m-%d)/

export CXX=CC
export CC=CC

make distclean

./configure  --prefix=$HYPRE_INSTALL_PREFIX --with-gpu-arch=gfx908 --without-superlu --disable-bigint --without-openmp --with-hip --enable-rocsparse --enable-rocrand --enable-shared --with-MPI-lib-dirs="$MPICH_DIR/lib /opt/cray/pe/mpich/8.1.4/gtl/lib" --with-MPI-libs="mpi mpi_gtl_hsa" --with-MPI-include=$MPICH_DIR/include

make -j24

**Comment by liruipeng** [comment]
Thank you @PaulMullowney. This is useful!
