### ISSUE TITLE
Test with OpenMP

### ISSUE THREAD

**Issue by JulienLoiseau** [hypre-space/hypre#402]
Good afternoon, 

I am trying to run the simple test provided by Hypre "ij" and when I run this problem using different number of OpenMP threads I get a different result and number of iterations: 

OMP_NUM_THREADS=1: 
```
BoomerAMG Iterations = 11
Final Relative Residual Norm = 1.847551e-09
```

OMP_NUM_THREADS=8:
```
BoomerAMG Iterations = 14
Final Relative Residual Norm = 9.852263e-09
```

OMP_NUM_THREADS=16: 
```
BoomerAMG Iterations = 16
Final Relative Residual Norm = 9.272942e-09
```

OMP_NUM_THREADS=32: 
```
BoomerAMG Iterations = 18
Final Relative Residual Norm = 6.490803e-09
```

I compiled Hypre with the flag: 
`--with-openmp`

I also dont observe any scalability by using OpenMP.
Is there another flag to consider? Is that expected?

**Comment by liruipeng** [comment]
@JulienLoiseau It is expected, if you use default relaxation (hybrid Gauss-Seidel), since the algorithm depends on the number of threads.

**Comment by JulienLoiseau** [comment]
Thank you I close this issue.
