### ISSUE TITLE
How to Read Matrix Market file and solve it with BoomerAMG? 

### ISSUE THREAD

**Issue by lacrymose** [hypre-space/hypre#403]
Dear Developers,

I have a matrix marker file which contains the matrix and a text file which contains the right hand side vector. How can I read these two files through hypre and solve the linear algebraic system by calling Boomer AMG?

best

**Comment by liruipeng** [comment]
@lacrymose It is very easy to do it without MPI or with MPI and `np = 1`. You need to make modifications to the mtx files: remove all the banners (starting with `%`). Change line that contains `rows, columns, entries` to `1 rows 1 columns`. Suppose the mtx file is `A.mtx`, rename is as `A.mtx.00000`. Then, run `./ij -fromfile A.mtx`. You can check the saved files from `./ij -print` to check the matrix format hypre uses. Vectors need to be changed similarly.

For `np > 1`, you need to partition the files into `np` parts, each of which has a partition of rows.

**Comment by lacrymose** [comment]
@liruipeng  Many thanks for your quick reply. I have done as what you told. As of the rhs vector, in the hypre data file, one has to write down "1 rows" at the first line and "row_index  vector_value" at the rest lines, is this right? To be honest, I am a beginner at using HYPRE and have no idea what the data format of the hypre IJmatrix and IJvector are. I attempted to write the rhs vector file in the way I mentioned and run **./ij -fromfile A.mtx -rhsfromonefile b.rhs -solver 1**. Here below is what I get. Could you help me with this problem?
[localhost:259816] *** Process received signal ***
[localhost:259816] Signal: Segmentation fault (11)
[localhost:259816] Signal code: Address not mapped (1)
[localhost:259816] Failing at address: (nil)
[localhost:259816] [ 0] /lib64/libc.so.6(+0x36400)[0x7fb1ded44400]
[localhost:259816] [ 1] /lib64/libc.so.6(__isoc99_vfscanf+0xc)[0x7fb1ded7a4ec]
[localhost:259816] [ 2] ./ij[0x54df5e]
[localhost:259816] [ 3] ./ij[0x54785f]
[localhost:259816] [ 4] ./ij[0x41aecc]
[localhost:259816] [ 5] ./ij[0x406ff3]
[localhost:259816] [ 6] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7fb1ded30555]
[localhost:259816] [ 7] ./ij[0x4182e3]
[localhost:259816] *** End of error message ***
Segmentation fault (core dumped)

**Comment by lacrymose** [comment]
@liruipeng Many thanks for your quick reply. I have done as you told and succuceed in using BoomerAMG to solve the problem I am facing.
