### ISSUE TITLE
GPU Struct user questions

### ISSUE THREAD

**Issue by ibaned** [hypre-space/hypre#409]
Hello,

First, please let me know if this is an appropriate forum for the following: we are a GPU-accelerated code at SNL trying to solve a scalar conductivity problem on a structured mesh.

We'd like to do assembly directly on the GPU, which is the main question we'd like help with right now. It's not clear whether or how to use `HYPRE_StructMatrixSetBoxValues` if we want to assemble directly into GPU device memory.

In a forward-looking sense, we would also like to have HIP support for AMD GPUs in the near future.

Please let us know if this is the right place to ask these questions and any guidance you have on using HYPRE for this problem.

Thanks!
Dan

**Comment by liruipeng** [comment]
Hi, @ibaned 

This is the right place to ask questions about hypre.

`HYPRE_StructMatrixSetBoxValues` can be (and should be) used to set values for struct matrix on GPUs, where `values` should be a pointer to GPU memory. You can check `src/examples/ex1.c` for example.

We don't have HIP support so far for structure interface.

**Comment by ibaned** [comment]
@liruipeng Thank you for the fast response!

Are there plans to add HIP support to Struct or could we try to use a different interface that might provide HIP support sooner?

**Comment by liruipeng** [comment]
> @liruipeng Thank you for the fast response!
> 
> Are there plans to add HIP support to Struct or could we try to use a different interface that might provide HIP support sooner?

There is HIP support for IJ interface (AMG) but I assume that's not what you need for your structured solvers. We should be able to add HIP support to the structure interface soon, but we need to first discuss about it with the team @ulrikeyang.

**Comment by ibaned** [comment]
Thanks @liruipeng ! We'll move forward with Struct assuming that HIP will be added in the near future.

Another general support question: I think there is support for compiling and running on Windows, is that true? Is there any support for CUDA on Windows?

**Comment by liruipeng** [comment]
> Thanks @liruipeng ! We'll move forward with Struct assuming that HIP will be added in the near future.
> 
> Another general support question: I think there is support for compiling and running on Windows, is that true? Is there any support for CUDA on Windows?

I am not sure if our CMake build can work on Windows, for which it should. You can try something like

```
cmake -DCMAKE_C_COMPILER=$(which xlc) -DCMAKE_CXX_COMPILER=$(which xlc++) -DCMAKE_CUDA_COMPILER=$(which nvcc) -DMPI_C_COMPILER=$(which mpicc) -DMPI_CXX_COMPILER=$(which mpicxx) -DHYPRE_WITH_CUDA=ON -DHYPRE_ENABLE_UNIFIED_MEMORY=ON -DCMAKE_BUILD_TYPE=Debug -DHYPRE_CUDA_SM=70 ../
```

**Comment by ibaned** [comment]
Update: integration successful so far, getting correct answers on simple problems using the Struct interface on both CPUs and NVIDIA GPUs.

Next steps: try Windows, try "real" problems and choose best-performing solvers.

**Comment by ibaned** [comment]
We would definitely love to have HIP support in the Struct interface, if that is possible with your planning/funding. Thank you.

**Comment by ulrikeyang** [comment]
It is on our to do list for a release by October

**Comment by ibaned** [comment]
@ulrikeyang That is perfect timing for us, thank you for doing that.

**Comment by pbauman** [comment]
@liruipeng @ulrikeyang If it's implemented and functioning for CUDA, I'm curious what pieces are missing for HIP. I know sparse triangular solve needs to be added as well as rocRAND, but I'm unsure of other missing pieces. I can't help implement missing pieces in the immediate future, but if it's something simple I can at the very least provide some guidance. And happy to answer questions.

**Comment by ulrikeyang** [comment]
For the structured interface/solvers it mostly requires to enable the BoxLoops to run using hip. It's much less involved than the unstructured interface. The BoxLoops can also be run using Kokkos or RAJA, so the Intel folks were recently able to run the structured interface/solvers on Intel GPUs using SYCL and OpenMP Off load through Kokkos.

**Comment by liruipeng** [comment]
> @liruipeng @ulrikeyang If it's implemented and functioning for CUDA, I'm curious what pieces are missing for HIP. I know sparse triangular solve needs to be added as well as rocRAND, but I'm unsure of other missing pieces. I can't help implement missing pieces in the immediate future, but if it's something simple I can at the very least provide some guidance. And happy to answer questions.

@pbauman The structure interface uses different data structures from AMG, no matrix cusparse/curand libraries are needed there. Everything is abstracted in Boxloops. So, I think the porting from CUDA to HIP should be easier in some sense, as long as C++ lambda works correctly on AMD GPUs. I will let you know when I work on this and run into problems. Thank you!

**Comment by pbauman** [comment]
I took a quick glance and I do believe HIP is turned on for those box loops if you configure with HIP. I did a 
`srcgrep "HYPRE_USING_CUDA" | grep -v "HYPRE_USING_HIP"` to see where I didn't have HIP enabled with CUDA (HIP will be enabled with `HYPRE_USING_GPU`). I looked [here](https://github.com/hypre-space/hypre/blob/master/src/struct_mv/_hypre_struct_mv.hpp#L724) and it seems that HIP would be enabled there. Note this is not true for RAJA - I know RAJA has a HIP backend but I did not endeavor to try and enable that with HYPRE.

I did *not* try to update the tests for the struct interface though, so maybe those need to be updated? At any rate, I think it's worth just trying it out and seeing what breaks. Maybe it will "just work"? Certainly the library is compiling because that path is being walked by the compiler when HIP is on and I compiled HYPRE with HIP today. :)

**Comment by liruipeng** [comment]
> I took a quick glance and I do believe HIP is turned on for those box loops if you configure with HIP. I did a
> `srcgrep "HYPRE_USING_CUDA" | grep -v "HYPRE_USING_HIP"` to see where I didn't have HIP enabled with CUDA (HIP will be enabled with `HYPRE_USING_GPU`). I looked [here](https://github.com/hypre-space/hypre/blob/master/src/struct_mv/_hypre_struct_mv.hpp#L724) and it seems that HIP would be enabled there. Note this is not true for RAJA - I know RAJA has a HIP backend but I did not endeavor to try and enable that with HYPRE.
> 
> I did _not_ try to update the tests for the struct interface though, so maybe those need to be updated? At any rate, I think it's worth just trying it out and seeing what breaks. Maybe it will "just work"? Certainly the library is compiling because that path is being walked by the compiler when HIP is on and I compiled HYPRE with HIP today. :)

OK. I did not know struct code is actually compiled with HIP. Since it compiles fine, I think it is a good sign of being able to run it on AMD GPUs. It might "just work" :) There might be some cuda calls in the driver but it should be easy to fix. Thanks!

**Comment by ulrikeyang** [comment]
I just built hypre on Spock and ran PFMG-PCG on AMD GPUs. It works and is superfast.

**Comment by liruipeng** [comment]
> I just built hypre on Spock and ran PFMG-PCG on AMD GPUs. It works and is superfast.

Nice!

**Comment by liruipeng** [comment]
@ibaned I also successfully ran hypre's struct solvers on AMD GPUs, so I think the struct solvers of the current master should be fine with HIP. Sorry about the confusion before. Please let us know if it can work for you. Thanks!

**Comment by ibaned** [comment]
@liruipeng @ulrikeyang thanks for checking! This is great news! Thanks also @pbauman for noticing that this might already be in place.
