### ISSUE TITLE
builds internal BLAS and LAPACK regardless of --with-blas options

### ISSUE THREAD

**Issue by drew-parsons** [hypre-space/hypre#41]
The HYPRE source contains an internal copy of blas (also lapack) which it builds and uses in case blas is not already available.

If blas is available on the system then it can be identified at configure time with `--with-blas` and `--with-blas-lib` flags (also `--with-lapack --with-lapack-lib`).

But the problem is that even if `--with-blas` is used, the hypre build proceeds to build and link the internal copy of blas anyway.  You can see it with `nm -D libHYPRE-2.17.0.so  | less`, which shows symbols like hypre_dgemm, hypre_dtrmm etc.

The internal blas and lapack source should not be built and should not be linked, if configure flags have identified that a system BLAS and LAPACK is available.

**Comment by liruipeng** [comment]
> But the problem is that even if --with-blas is used, the hypre build proceeds to build and link the internal copy of blas anyway. You can see it with nm -D libHYPRE-2.17.0.so | less, which shows symbols like hypre_dgemm, hypre_dtrmm etc.

It is true that the internal blas and lapack are built even if --with-blas lapack is used,  but they are not linked. Hypre has an internal renaming (#def) mechanism to guarantee this. If external blas or lapack is given, hypre will be linked to the given blas/lapack
