### ISSUE TITLE
Controlling coarse level relaxation when restricting the number of levels

### ISSUE THREAD

**Issue by BarrySmith** [hypre-space/hypre#413]
Sorry for the delay in responding. 

   This seems to be a "feature" of hypre BoomerAMG.

   I set a max_levels smaller than what BoomerAMG would select and can reproduce the behavior you report. I ran in the debugger and verified that PETSc was passing the Gaussian-elimination (9) value to hypre and it was accepting it. 

  But in hypre_BoomerAMGSetup() line 2899 is the code

```
      if (coarse_size <= coarse_threshold)
      {
         hypre_GaussElimSetup(amg_data, level, grid_relax_type[3]);
      }
      else
      {
         grid_relax_type[3] = grid_relax_type[1];
      }
```

which is causing the coarse relaxation type to be ignored. 

I am cc:ing the hypre team, they may have a suggestion on exactly what options to select to achieve what you want.

Barry

On Jun 17, 2021, at 1:53 PM, Yu-hsuan Shih <yhs264@nyu.edu> wrote:

Hi,

I face a problem using BoomerAMG through Petsc. The situation is that I want to limit AMG with maximum number of levels 5 and use Gaussian Elimination as the coarse solver, where I used these two flags:
"pc_hypre_boomeramg_max_levels": 5,
"pc_hypre_boomeramg_relax_type_coarse": "Gaussian-elimination",  

I can see that the flags are correctly set in PETSc with

```
PC Object: (ns_) 56 MPI processes
  type: hypre
    HYPRE BoomerAMG preconditioning
      Cycle type W
      Maximum number of levels 5
      Maximum number of iterations PER hypre call 5
      Convergence tolerance PER hypre call 0.
      Threshold for strong coupling 0.25
      Interpolation truncation factor 0.
      Interpolation: max elements per row 0
      Number of levels of aggressive coarsening 0
      Number of paths for aggressive coarsening 1
      Maximum row sums 0.9
      Sweeps down         5
      Sweeps up           5
      Sweeps on coarse    1
      Relax down          symmetric-SOR/Jacobi
      Relax up            symmetric-SOR/Jacobi
      Relax on coarse     Gaussian-elimination
      Relax weight  (all)      1.
      Outer relax weight (all) 1.
      Using CF-relaxation
      Not using more complex smoothers.
      Measure type        local
      Coarsen type        Falgout
      Interpolation type  classical
  linear system matrix = precond matrix:
  Mat Object: (ns_) 56 MPI processes
    type: mpiaij
    rows=296450, cols=296450, bs=2
    total: nonzeros=14760964, allocated nonzeros=14760964
    total number of mallocs used during MatSetValues calls=0
      using I-node (on process 0) routines: found 1568 nodes, limit used is 5 
```

But from the statistic of BoomerAMG, it is using hSGS as the coarse grid solver:

```
BoomerAMG SOLVER PARAMETERS:  Maximum number of cycles:         5
  Stopping Tolerance:               0.000000e+00
  Cycle type (1 = V, 2 = W, etc.):  2  Relaxation Parameters:
   Visiting Grid:                     down   up  coarse
            Number of sweeps:            5    5     1
   Type 0=Jac, 3=hGS, 6=hSGS, 9=GE:      6    6     6
   Point types, partial sweeps (1=C, -1=F):
                  Pre-CG relaxation (down):   1  -1   1  -1   1  -1   1  -1   1  -1
                   Post-CG relaxation (up):  -1   1  -1   1  -1   1  -1   1  -1   1
                             Coarsest grid:   0
```

I am wondering if you know whether there is a situation that limits the usage of GE as the coarse grid solver in BoomerAMG? or are the options not passed to HYPRE correctly? 

Thanks in advance for any help.

Best regards,
Yu-hsuan

**Comment by liruipeng** [comment]
It is a "feature" of hypre BoomerAMG, which tries not to use direct solvers for "too large" coarsest grid. To force it to use Gaussian-elimination (9), set `HYPRE_BoomerAMGSetMaxCoarseSize` to a large enough number.
