### ISSUE TITLE
HYPRE with multiple GPUs

### ISSUE THREAD

**Issue by lacrymose** [hypre-space/hypre#417]
Dear Developers,

I have three GPUs, one Quadro M2000 and two Tesla K40c. CUDA toolkit 10.2, Nvidia driver for K40c and gcc-8 are installed on a workstation with Ubuntu 18.04 system. M2000 is for display, and K40c is for computation. Running nvidia-smi shows that GPU 0 is M2000 and GPU 1 and 2 are K40cs. Hypre is successfully compiled without MPI but with CUDA. Then I tried to make ij in the test folder. I get the following error: 

CUDA ERROR (code=101, invalid device ordinal) at memory.c: 131

What should I do to deal with this error? Is it because GPU 0 is the default device, however no drivers for it has been installed? How to choose which GPU device to be used?

Another question: I tried to compile with both MPI and CUDA, and then make ij. After ij is compiled, running ./ij produces:

segementation fault (11), 
signal code: address not mapped (1),
 failing at address 0x440000e8, 
[0] /lib/x86_64-linux-gnu/libc.so.6, 
[1] /usr/local/lib/libmpi/so/40(MPI_Comm_size+0x37), 
[2] ./ij

For your information, I have one workstation, not a cluster. Is it because in the case of one workstation, MPI and CUDA cannot be used simutaneously?

**Comment by liruipeng** [comment]
> Dear Developers,
> 
> I have three GPUs, one Quadro M2000 and two Tesla K40c. CUDA toolkit 10.2, Nvidia driver for K40c and gcc-8 are installed on a workstation with Ubuntu 18.04 system. M2000 is for display, and K40c is for computation. Running nvidia-smi shows that GPU 0 is M2000 and GPU 1 and 2 are K40cs. Hypre is successfully compiled without MPI but with CUDA. Then I tried to make ij in the test folder. I get the following error:
> 
> CUDA ERROR (code=101, invalid device ordinal) at memory.c: 131
> 
> What should I do to deal with this error? Is it because CPU 0 is the default device, however no drivers for it has been installed? How to choose which GPU device to be used?
> 

You probably need to call `cudaSetDevice(device_id);` before `HYPRE_Init`. see https://github.com/hypre-space/hypre/wiki/GPUs


> Another question: I tried to compile with both MPI and CUDA, and then make ij. After ij is compiled, running ./ij produces:
> 
> segementation fault (11),
> signal code: address not mapped (1),
> failing at address 0x440000e8,
> [0] /lib/x86_64-linux-gnu/libc.so.6,
> [1] /usr/local/lib/libmpi/so/40(MPI_Comm_size+0x37),
> [2] ./ij
> 
> For your information, I have one workstation, not a cluster. Is it because in the case of one workstation, MPI and CUDA cannot be used simutaneously?

MPI and CUDA should work on a single machine. Not sure what's the problem here. How did you configure/compile hypre and run `./ij`? Thanks @lacrymose

**Comment by lacrymose** [comment]
@liruipeng Thanks for your quick reply! 
For 1st problem, I try to call cudaSetDevice(2); before HYPRE_Init and it still gives the same error. This may indicate GPU 0 is not the cause. Here below is the configure:

./configure --with-cuda --enable-unified-memory CUDA_HOME=/usr/local/cuda CUDA_PATH=/usr/local/cuda HYPRE_CUDA_SM=35 --enable-device-memory-pool --enable-cublas --enable-gpu-profiling --with-print-errors --with-timing --enable-hopscotch --without-MPI CC=/usr/bin/gcc CFLAGS="-g -O3" CXX=/usr/bin/g++ CXXFLAGS="-g -O3" FC=/usr/bin/gfortran FCFLAGS="-g -O3"

As for 2nd problem, the configure is almost the same as the proceeding one except more infos about MPI is supplemented:

--with-MPI --with-MPI-include=/usr/local/include --with-MPI-lib=/usr/local/lib

For these two problems, I always use make and make install to compile hypre. With respect to ij, I cd into test folder and **make ij** and run **./ij** .

**Comment by liruipeng** [comment]
@lacrymose Thank you for providing the information. We haven't tested on K40 for a while, but we still expect hypre can still work on it, especially if the compile is fine.

On error `invalid device ordinal`, have you checked with `cudaGetDeviceCount`? See https://stackoverflow.com/questions/22175825/cuda-invalid-device-ordinal or https://stackoverflow.com/questions/13135459/i-get-runtime-api-error-invalid-device-ordinal-when-i-run-cuda-code-on-ubun.

I am not sure if this is a hypre problem per se. Have you tried running simple GPU program such as `deviceQuery`? see https://forums.developer.nvidia.com/t/cuda-invalid-device-ordinal/45720.

**Comment by lacrymose** [comment]
@liruipeng  Sorry for back to this issue so late! Possibly I find out the reason for this issue. cudaMemPrefetchAsync function in memory.c can only be used on GPUs with Pascal or newer arch, while my K40 is of Kepler arch. Check https://forums.developer.nvidia.com/t/cudamemprefetchasync-returns-cudaerrorinvaliddevice/46705/13. 
Are there any workarounds？
