### ISSUE TITLE
Building shared lib when CUDA is enabled

### ISSUE THREAD

**Issue by stefanozampini** [hypre-space/hypre#42]
I was experimenting building HYPRE (tag v.2.17.0) with CUDA support from within PETSc configure @BarrySmith @balay . PETSc  generates lots of -Wl,-rpath instructions needed for the creation of the so file.
nvcc, which is used by HYPRE when linking, does not tolerate this. Attached the error.

Building libHYPRE.so ... 
nvcc -shared -gencode arch=compute_60,"code=sm_60"  -o libHYPRE-2.17.0.so   /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/IJ_mv/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/distributed_ls/Euclid/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/distributed_ls/ParaSails/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/distributed_ls/pilut/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/distributed_matrix/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/krylov/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/matrix_matrix/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/multivector/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/parcsr_ls/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/parcsr_mv/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/parcsr_block_mv/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/seq_mv/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/sstruct_ls/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/sstruct_mv/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/struct_ls/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/struct_mv/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/utilities/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/blas/*.o /home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/lapack/*.o       -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/mkl/lib/intel64 -L/opt/ecrc/intel/2018/compilers_and_libraries/linux/mkl/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_intel_thread -liomp5 -ldl -lpthread -lstdc++ -ldl -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/mpi/intel64/lib/debug_mt -L/opt/ecrc/intel/2018/compilers_and_libraries/linux/mpi/intel64/lib/debug_mt -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/mpi/intel64/lib -L/opt/ecrc/intel/2018/compilers_and_libraries/linux/mpi/intel64/lib -lmpifort -lmpi -lmpigi -lrt -lpthread -Wl,-rpath,/opt/ecrc/cuda/10.0/lib64 -L/opt/ecrc/cuda/10.0/lib64 -Wl,-rpath,/opt/ecrc/cuda/10.0/lib -L/opt/ecrc/cuda/10.0/lib -Wl,-rpath,/opt/ecrc/valgrind/3.14.0-gcc-5.5.0/ub16/lib -L/opt/ecrc/valgrind/3.14.0-gcc-5.5.0/ub16/lib -Wl,-rpath,/opt/ecrc/valgrind/3.14.0-gcc-5.5.0/ub16/lib/valgrind -L/opt/ecrc/valgrind/3.14.0-gcc-5.5.0/ub16/lib/valgrind -Wl,-rpath,/opt/ecrc/cmake/3.11.1/ub16/lib -L/opt/ecrc/cmake/3.11.1/ub16/lib -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/lib/intel64 -L/opt/ecrc/intel/2018/compilers_and_libraries/linux/lib/intel64 -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/ipp/lib/intel64 -L/opt/ecrc/intel/2018/compilers_and_libraries/linux/ipp/lib/intel64 -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/mkl/lib/intel64 -L/opt/ecrc/intel/2018/compilers_and_libraries/linux/mkl/lib/intel64 -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/tbb/lib/intel64/gcc4.4 -L/opt/ecrc/intel/2018/compilers_and_libraries/linux/tbb/lib/intel64/gcc4.4 -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/daal/lib/intel64_lin -L/opt/ecrc/intel/2018/compilers_and_libraries/linux/daal/lib/intel64_lin -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/tbb/lib/intel64_lin/gcc4.4 -L/opt/ecrc/intel/2018/compilers_and_libraries/linux/tbb/lib/intel64_lin/gcc4.4 -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/lib/intel64_lin -L/opt/ecrc/intel/2018/compilers_and_libraries/linux/lib/intel64_lin -Wl,-rpath,/opt/ecrc/intel-it/2018/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin -L/opt/ecrc/intel-it/2018/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -Wl,-rpath,/lib/x86_64-linux-gnu -L/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib/i386-linux-gnu -L/usr/lib/i386-linux-gnu -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/mpi/intel64/lib/debug_mt -Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/mpi/intel64/lib -Wl,-rpath,/opt/intel/mpi-rt/2017.0.0/intel64/lib/debug_mt -Wl,-rpath,/opt/intel/mpi-rt/2017.0.0/intel64/lib -lifport -lifcoremt_pic -limf -lsvml -lm -lipgo -lirc -lgcc_s -lirc_s -lm  -L/opt/ecrc/cuda/10.0//lib64 -lcusparse -lcudart -lcublas -lnvToolsExt    -Xlinker=-soname,libHYPRE-2.17.0.so -Xlinker=-z,defs -ccbin=/opt/ecrc/intel/2018/compilers_and_libraries/linux/mpi/intel64/bin/mpiicpc -gencode arch=compute_60,"code=sm_60" -Xcompiler ""
nvcc fatal   : Unknown option 'Wl,-rpath,/opt/ecrc/intel/2018/compilers_and_libraries/linux/mkl/lib/intel64'
Makefile:101: recipe for target 'libHYPRE.so' failed
make[1]: *** [libHYPRE.so] Error 1
make[1]: Leaving directory '/home/zampins/petsc/arch-gpu-double/externalpackages/git.hypre/src/lib'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by rfalgout** [comment]
Has this issue been resolved?  Thanks!  -Rob
