### ISSUE TITLE
Problem while installation

### ISSUE THREAD

**Issue by Abuhegazy** [hypre-space/hypre#43]
I'm new user of Hypre. I downloaded a zip file then used unzip command to unzip the file.
Then I went to the src folder to install it.
I typed ./configure
then I typed make install 
that what I got,
Makefile:16: config/Makefile.config: No such file or directory
make: *** No rule to make target 'config/Makefile.config'.  Stop.

config.log file is attached

Could you please help me to figure out this problem?
Thank in advance.

[config.log](https://github.com/hypre-space/hypre/files/3560658/config.log)

**Comment by ulrikeyang** [comment]
Did you first type configure?



---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On August 30, 2019 at 8:57:40 AM PDT, Abuhegazy <notifications@github.com> wrote:

I'm new user of Hypre. I downloaded a zip file then used unzip command to unzip the file.
Then I went to the src folder to install it.
I typed ./configure
then I typed make install
that what I got,
Makefile:16: config/Makefile.config: No such file or directory
make: *** No rule to make target 'config/Makefile.config'. Stop.

config.log file is attached

Could you please help me to figure out this problem?
Thank in advance.

config.log<https://github.com/hypre-space/hypre/files/3560658/config.log>

**Comment by Abuhegazy** [comment]
Yes but didn't work. So I typed ./configure

**Comment by rfalgout** [comment]
Did configure create a file called 'config/Makefile.config'?  Would you also please send the command-line output that configure generates?  Thanks!

**Comment by Abuhegazy** [comment]
No it didn't.
this is the command line output: configure: command not found
then I typed ./configure and that's what i got. it  looks like I have a problem in openmpi but not sure

checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for mpxlc... no
checking for mpixlc... no
checking for mpiicc... no
checking for mpigcc... no
checking for mpicc... mpicc
checking for mpxlC... no
checking for mpixlcxx... no
checking for mpixlC... no
checking for mpiicpc... no
checking for mpig++... no
checking for mpic++... mpic++
checking for mpxlf... no
checking for mpixlf77... no
checking for mpiifort... no
checking for mpif77... mpif77
checking whether make sets $(MAKE)... yes
checking for ranlib... ranlib
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether mpicc accepts -g... yes
checking for mpicc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether mpic++ accepts -g... yes
checking whether we are using the GNU Fortran compiler... no
checking whether mpif77 accepts -g... no
checking how to get verbose linking output from mpif77... configure: WARNING: compilation failed

checking for Fortran libraries of mpif77... 
checking for dummy main to link with Fortran libraries... none
checking for Fortran name-mangling scheme... configure: error: in `/home/mohamed/hypre-master/src':
configure: error: cannot compile a simple Fortran program
See `config.log' for more details

**Comment by rfalgout** [comment]
You have a problem with your mpif77 compiler wrapper.  You don't need fortran to compile the hypre library, so add '--disable-fortran' to your configure line and see if that fixes the problem.

**Comment by Abuhegazy** [comment]
I did. it seems that that the installation is completed however, when running ex1 
by typing make ex1 
there is an error as follows,

mpicc -g -Wall -I../hypre/include -DHAVE_CONFIG_H -DHYPRE_TIMING -c ex1.c
ex1.c:25:10: fatal error: HYPRE_struct_ls.h: No such file or directory
 #include "HYPRE_struct_ls.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:48: recipe for target 'ex1.o' failed
make: *** [ex1.o] Error 1

**Comment by rfalgout** [comment]
Try going into 'src/test', typing 'make', and then running 'ij' or 'struct' or any of the other drivers.  If this works, then try the examples.

Actually, is there anything in 'src/hypre' after you finish the compile?  This is where the examples makefile is looking for headers and the library.

**Comment by Yanmyonaing53** [comment]
ar: *.o: No such file or directory
make[1]: *** [libHYPRE_utilities.a] Error 1
make[1]: Leaving directory `/root/Desktop/MFEM/hypre-2.16.0/src/utilities'
make: *** [all] Error 1
This is my error! Please give me your solution!
