### ISSUE TITLE
identifier '_Float128' is undefined

### ISSUE THREAD

**Issue by rl3418** [hypre-space/hypre#432]
I got the error message saying 'identifier Float_128 is undefined' while trying to run a problem with hypre 2.10.0b. Any idea what might have caused this? Is a different version of hypre required.

![1627522723(1)](https://user-images.githubusercontent.com/81304719/127418180-2048013d-83ce-4815-8c92-d1c46891bdb2.jpg)

**Comment by victorapm** [comment]
Hi @rl3418,

It looks like you are using an Intel compiler which does not support `__float128`. See this [related issue](https://community.intel.com/t5/Intel-C-Compiler/ICC-17-0-4-GCC-7-glibc-2-26-error-identifier-quot-Float128-quot/td-p/1170601). Can you try changing your compiler?

Thanks!
Victor
