### ISSUE TITLE
Parallel direct solvers

### ISSUE THREAD

**Issue by manauref** [hypre-space/hypre#445]
Dear Hypre team,
I'd like to raise a question or a feature request, not really an issue. Correct me if I'm wrong but my understanding is that the only direct solver available in Hypre is a serial one via SuperLU.
If that is the case, would it be possible to implement an interface to SuperLU_dist for parallel solvers? There are some applications in which one may wish to solve smaller problems with a direct solver in a subset of the dimensions of the whole simulation, and this would make it so that we can do those, and the bigger problems, with a single library or package (Hypre + interface to SuperLU).
Thank you.

**Comment by victorapm** [comment]
Hi @manauref,

the BoomerAMG solver/preconditioner supports SuperLU_dist as the solver for the coarsest level problem. To build hypre with SuperLU_dist support:
```
   ./configure  --with-dsuperlu \
                --with-dsuperlu-include="path-to-superlu_dist-include-dir" \
                --with-dsuperlu-lib="path-to-superlu_dist-lib"
```
Note that hypre must be configured with ``--enable-bigint`` or ``--enable-mixedint`` when linking to the 64-bit version of
SuperLU_DIST. To set the minimum problem size on the coarsest level, you can use the function:
```
/**
 * HYPRE_BoomerAMGSetDSLUThreshold
 *
 * Usage:
 *  Set slu_threshold >= max_coarse_size (from HYPRE_BoomerAMGSetMaxCoarseSize(...))
 *  to turn on use of superLU for the coarse grid solve. SuperLU is used if the
 *  coarse grid size > max_coarse_size and the grid level is < (max_num_levels - 1)
 *  (set with HYPRE_BoomerAMGSetMaxLevels(...)).
 **/

HYPRE_Int
HYPRE_BoomerAMGSetDSLUThreshold (HYPRE_Solver solver,
                                 HYPRE_Int    slu_threshold);
```

For the case you described, `slu_threshold` could be set to the original problem size, and this will reduce BoomerAMG to a two-level method with the coarse problem solved in parallel by SuperLU_dist. I can look at removing the limitation of having at least two levels in BoomerAMG for using SuperLU_dist if needed.

Hope this helps!
Victor
