### ISSUE TITLE
Printing Interpolation Matrix

### ISSUE THREAD

**Issue by acse-hep20** [hypre-space/hypre#446]
Is it possible to output the actual values of the Interpolation matrix used in the Hypre multigrid solver (BoomerAMG). I am trying to further investigate how Interpolation matrix of the l-AIR approach differs from more traditional multigrid methods. I was wondering if there is a method to dump this data to an output file for further examination. I can already see the summary of the interpolation / operator matrices that is included in the terminal output but I am looking to reconstruct the actual matrices themselves (for small sample problems).

**Comment by liruipeng** [comment]
@acse-hep20  You can `#define DEBUG_SAVE_ALL_OPS 1` at https://github.com/hypre-space/hypre/blob/224bab21afd37fa577870f4f2fbc06bc14e3c6d3/src/parcsr_ls/par_amg_setup.c#L15, to save the operators.

**Comment by acse-hep20** [comment]
Brilliant that works exactly for me, Thanks!
