### ISSUE TITLE
Building hypre with test drivers and external BLAS

### ISSUE THREAD

**Issue by jeanlucf22** [hypre-space/hypre#466]
Hi,
I am trying to build hypre with a vendor optimized BLAS library installed on my local Linux cluster. I want to evaluate solvers using the "ij" driver. So I am calling cmake with the following arguments (from the cmbuild directory):

cmake -DHYPRE_INSTALL_PREFIX=$HOME/hypre/install_gcc -DHYPRE_ENABLE_HYPRE_BLAS=OFF -DHYPRE_WITH_OPENMP=ON -DHYPRE_BUILD_TESTS=ON ..

cmake finds the external BLAS, but I am getting an error at link time, when the first test driver "struct" is being built:
../libHYPRE.a(ilaenv.c.o): In function `hypre_ilaenv':
ilaenv.c:(.text+0xb2): undefined reference to `hypre_s_copy'
ilaenv.c:(.text+0x248): undefined reference to `hypre_s_cmp'
../libHYPRE.a(dlamch.c.o): In function `hypre_dlamc2':
dlamch.c:(.text+0x786): undefined reference to `hypre_pow_di'
../libHYPRE.a(dsteqr.c.o): In function `hypre_dsteqr':
dsteqr.c:(.text+0xa7b): undefined reference to `hypre_d_sign'

Jean-Luc Fattebert, ORNL

**Comment by victorapm** [comment]
Hi @jeanlucf22, 

these cmake options will turn off the internal BLAS of hypre but will leave the internal LAPACK turned on. However, the internal LAPACK uses functions defined in the internal BLAS (`hypre_s_cmp`, `hypre_pow_di` and more), which gives the linking problem. Adding `-DHYPRE_ENABLE_HYPRE_LAPACK=OFF` to the cmake arguments should solve. 

Let me know if you have problems,
Victor

**Comment by jeanlucf22** [comment]
I see. In other words, you have to use blas and lapack either as both internal or both external. That works for me, and I am now able to build the drivers. Thanks!

Jean-Luc

**Comment by victorapm** [comment]
That's correct! Thanks for letting me know, Victor

**Comment by liruipeng** [comment]
> I see. In other words, you have to use blas and lapack either as both internal or both external. 

Maybe not necessary with autoconf (instead of Cmake)?

**Comment by victorapm** [comment]
Hi @liruipeng, I don't think so. I just tested:
```
./configure --with-blas --with-blas-lib="-lblas"
```
in my tuxbox and I have the same kind of issues with undefined references.
