### ISSUE TITLE
hypre_SeqVectorInnerProd(x,y) gives different results from run to run on the same number of openMP threads

### ISSUE THREAD

**Issue by tory3** [hypre-space/hypre#467]
This loop from the method hypre_SeqVectorInnerProd(x,y) seems to give different results from run to run even on the same number of openMP threads (HYPRE_SMP_SCHEDULE is defined as schedule(static)):

#pragma omp parallel for private(i) reduction(+:result) HYPRE_SMP_SCHEDULE
      for (i = 0; i < size; i++)
      {
         result += hypre_conj(y_data[i]) * x_data[i];
      }

It looks like it's the only source of differences for the solver we use: HYPRE_ParCSRPCGSolve. The solution became stable (for big number of linear systems) if I just replace the loop with the following one:

      static const HYPRE_Int numChunks = 128;
      const HYPRE_Int        chunkSize = (size / numChunks) + 1;
      HYPRE_Real             resultCH[numChunks];
      for (i = 0; i < numChunks; i++)
      {
         resultCH[i] = 0.;
      }
#pragma omp parallel for private(i) schedule(static, chunkSize)
      for (i = 0; i < size; i++)
      {
         resultCH[i/chunkSize] += hypre_conj(y_data[i]) * x_data[i];
      }
      for (i = 0; i < numChunks; i++)
      {
         result += resultCH[i];
      }

Maybe there is already a solution to the problem in the official sources that I missed?
Otherwise it would be nice to fix it.

**Comment by victorapm** [comment]
Hi @tory3,

thanks for your message. Can you attach an example of vectors `x` and `y` where you see different results for the inner product? Also, which compiler and optimization flags did you use to build hypre? Do you observe this issue with any number of threads or with particular ones? How different are the inner products computed with OpenMP turned on and off?

Thanks again!
Victor

**Comment by liruipeng** [comment]
I don't think OpenMP standard requires reproducibility in parallel reduction, even with the same number of threads.

**Comment by tory3** [comment]
Hello Victor,

I can reproduce the differences almost all the time with this code:
` 
        const int size = 100000;
        std::vector<double> a(size);
        std::vector<double> b(size);

        for (int i = 0; i < size; i++)
        {
            a[i] = drand48();
            b[i] = drand48();
        }

        for (int it = 0; it < 5; it++)
        {
            double result = 0;
#pragma omp parallel for reduction(+:result) schedule(static)
            for (int i = 0; i < size; i++)
            {
                result += a[i] * b[i];
            }
            std::cout << "result: " << result << std::endl;
        }
`
We are using gcc 7.4.0 and optimization flag -02.

The differences in results is quite small, I believe just a few last digits. Here are two results with 12 threads:
result: 24981.4645846216299105
result: 24981.4645846216262725

With one thread the result is very similar:
result: 24981.4645846216844802

I can reproduce the differences with the code above with any number of threads starting from 3. With 2 threads it seems to give the same results all the time. So I believe the source of the differences is the final summation that openMP does for the partial results computed by each thread.

I agree with Li:
> I don't think OpenMP standard requires reproducibility in parallel reduction, even with the same number of threads.

It would be nice if the final solution will give the same results when run on different number of threads (similar to the example in the first message).

Thanks for the quick reply!
Vladimir

**Comment by victorapm** [comment]
Hi Vladimir,

thanks for providing an example. The difference in the results is in the order of the machine precision for double data types (`O ~ 10^{-16}`), and this is acceptable since the order of floating point operations performed inside OpenMP regions will change. In other words, we can't expect the same results for up to machine precision when using OpenMP. If a difference of (`O ~ 10^{-16}`) is not acceptable in your application, I would suggest looking at a higher precision, e.g., `long double`.

Thanks,
Victor

**Comment by tory3** [comment]
The double precision is enough for our application. But we also need to maintain reproducibility. Even small changes in the solution could affect other parts of the code. And the final result (mesh generation in our case) could be relatively different from run to run.
We wanted to inform you about the issue because it's easier for us to have the fix in official sources. But we can use our internal fix. No problem.
Thanks for clarification!
