### ISSUE TITLE
Cuda compilation issue

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#468]
In csr_matop_device.c, the #if defined() are not properly enclosed. I think an #endif is missing above the definition of hypre_CSRMatrixTriLowerUpperSolveDevice. This leads to complaints of undefined methods during link. I think the method directly above and below are not wrapped correctly.

/gpfs/alpine/cfd116/scratch/mullowne/hypre/src/parcsr_ls/par_relax_device.obj: In function `hypre_BoomerAMGRelaxHybridGaussSeidelDevice':
/gpfs/alpine/cfd116/scratch/mullowne/hypre/src/parcsr_ls/par_relax_device.c:64: undefined reference to `hypre_CSRMatrixTriLowerUpperSolveDevice'
/gpfs/alpine/cfd116/scratch/mullowne/hypre/src/parcsr_ls/par_relax_device.c:40: undefined reference to `hypre_CSRMatrixTriLowerUpperSolveDevice'
/gpfs/alpine/cfd116/scratch/mullowne/hypre/src/parcsr_ls/par_relax_device.c:51: undefined reference to `hypre_CSRMatrixTriLowerUpperSolveDevice'

**Comment by liruipeng** [comment]
Will fix. Thanks!
