### ISSUE TITLE
Question about data distribution for asymmetric system (GMRES/AMG)

### ISSUE THREAD

**Issue by gkarpa** [hypre-space/hypre#471]
Hi all,

I'm using GMRES preconditioned with BoomerAMG to solve an asymmetric system of ~2 million rows, on 2 processors and a couple of questions arised. I notice that the distribution of the data seems to play some role to the quality of the solution x, e.g. when each processor has about half of the rows, the relative norm difference from the reference solution xr ( norm(x-xr)/norm(xr) ) is in the order of 1e-7. However when i give almost all the rows in one processor and leave a few in the other, then i get a much smaller relative difference (1e-13). And indeed, when running the example in serial execution, this difference is of the same order (1e-13). Is this to be expected or am I maybe using wrong parameters for my setup? Here are the settings i'm using:

Strong threshold = 0.9
Num functions for systems PDE = 3 (same behavior with = 1 as well though)
Coarsen type = 10
Interp type = 6
Aggressive coarsening levels = 1
Num sweeps = 1
PMaxElmts = 4
Max levels = 25
K dimension for GMRES = 30
Convergence tolerance = 1e-16

Besides that, when I am using very small convergence tolerance (e.g. 1e-16) I'm sometimes seeing the message "false convergence 2" in the output between the iterations, however the result seems to be correct. Should I ignore this message or set the tolerance a bit higher (e.g. with 1e-13 I don't see it)?

Finally, regardless of the solutions' correctness, in general I don't seem to be able to get parallel execution to run faster than the serial one, for a small number of processors (2-8). It's running much slower actually. Should I consider this normal and expect scaling only for large number of processors?

Any feedback around these issues is greatly appreciated. Thanks a lot in advance!

Regards,
George

**Comment by liruipeng** [comment]
What was the relaxation type hypre used? In general, with different distribution of equations, hypre does not give the same results.

**Comment by gkarpa** [comment]
Hi @liruipeng , thank you for the quick reply! I did not set anything explicitly for the relax_type so I'd say it is the default. In the output of the relaxation parameters it prints down: 13, up: 14, coarse: 9.

**Comment by liruipeng** [comment]
> Hi @liruipeng , thank you for the quick reply! I did not set anything explicitly for the relax_type so I'd say it is the default. In the output of the relaxation parameters it prints down: 13, up: 14, coarse: 9.

With 13/14, hybrid Gauss-Seidel, G-S is performed on local rows while Jacobi-type smoothing is on off-process rows. So, it is expected that "give almost all the rows in one processor and leave a few in the other" makes the smoother stronger, and so AMG gives smaller final residual.

Also, it is not normal that running in parallel is much slower than sequential. I am not sure why you are seeing this.

**Comment by gkarpa** [comment]
Thanks for the additional insight @liruipeng , it was very helpful. Regarding the performance, after running in a PC with more cores the behavior was as expected so no real problem there. I will close the issue.
