### ISSUE TITLE
Spock/Hip compilation help

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#475]
I tried adding -fPIC to my CXXFLAGS and CFLAGS and also to LDFLAGS but no luck.

Building libHYPRE_utilities.so ...
/opt/cray/pe/craype/2.7.8/bin/CC -shared  -o libHYPRE_utilities-2.22.1.so F90_HYPRE_error.o F90_HYPRE_general.o HYPRE_handle.o HYPRE_version.o amg_linklist.o binsearch.o exchange_data.o fortran_matrix.o ap.o log.o complex.o error.o hopscotch_hash.o merge_sort.o mpi_comm_f2c.o prefix_sum.o printf.o qsort.o utilities.o mpistubs.o qsplit.o random.o threading.o timer.o timing.o cuda_utils.obj general.obj handle.obj memory.obj omp_device.obj nvtx.obj -Wl,-soname,libHYPRE_utilities-2.22.1.so
ld.lld: error: can't create dynamic relocation R_X86_64_32 against symbol: __device_stub__hypreCUDAKernel_CompileFlagSafetyCheck(int*) in readonly segment; recompile object files with -fPIC or pass '-Wl,-z,notext' to allow text relocations in the output
>>> defined in cuda_utils.obj
>>> referenced by cuda_utils.c
>>>               cuda_utils.obj:(__device_stub__hypreCUDAKernel_CompileFlagSafetyCheck(int*))

**Comment by PaulMullowney** [comment]
Doing:
export HIPCXXFLAGS="-fPIC"
seems to work

**Comment by pbauman** [comment]
HI @PaulMullowney It looks like I haven't tried to build HIP in shared lib mode in awhile. I'll test it and submit a patch. As you've deduced, `HIPCXXFLAGS` is the configure variable you want to tickle to pass flags to HIP compilation. Sorry for the trouble.

**Comment by liruipeng** [comment]
> HI @PaulMullowney It looks like I haven't tried to build HIP in shared lib mode in awhile. I'll test it and submit a patch. As you've deduced, `HIPCXXFLAGS` is the configure variable you want to tickle to pass flags to HIP compilation. Sorry for the trouble.

Hi @pbauman, Thank you for fixing this problem. Shall we let HIP build use CXXFLAGS as well? We recently refactored autoconf build for CUDA for PETSc since they like to control CXXFLAGS.

**Comment by pbauman** [comment]
> Shall we let HIP build use CXXFLAGS as well? We recently refactored autoconf build for CUDA for PETSc since they like to control CXXFLAGS.

Hi @liruipeng I'll take a look, but my knee-jerk reaction is no. Or at the very least, CXXFLAGS needs to be a subset. We have to at least pass `-x hip` for the HIP compilation, which cannot be part of CXXFLAGS, unless you're guaranteeing CXXFLAGS is *only* used on GPU code files.

**Comment by liruipeng** [comment]
> > Shall we let HIP build use CXXFLAGS as well? We recently refactored autoconf build for CUDA for PETSc since they like to control CXXFLAGS.
> 
> Hi @liruipeng I'll take a look, but my knee-jerk reaction is no. Or at the very least, CXXFLAGS needs to be a subset. We have to at least pass `-x hip` for the HIP compilation, which cannot be part of CXXFLAGS, unless you're guaranteeing CXXFLAGS is _only_ used on GPU code files.

Hi @pbauman, we have similar stuff for CUDA as well such as `--x cu`. We put these directly in `CUFLAGS` if user has not predefined it. `CXXFLAGS` has the common C++ flags that be used for host and device code, like `-fPIC` if configured with share library. Just my 2 cents.

**Comment by pbauman** [comment]
OK,I see, I think I misunderstood you. I thought you meant use CXXFLAGS in place of HIPCXXFLAGS. I see now that you mean HIPCXXFLAGS uses CXXFLAGS. Yes, I agree that is the correct solution.
