### ISSUE TITLE
Create hyper_ParCSRMatrix

### ISSUE THREAD

**Issue by geyan3566** [hypre-space/hypre#483]
Hi,

I am writing an algorithm that constructs a parallel matrix (HypreParMatrix, in which the underhood object is hypre_ParCSRMatrix*), but the API and documentation are not that clear.

The entire matrix is constructed from the mesh, thus the hypreparmatrix is constructed from the parallel mesh.
The columns indices correspond to the element id and row indices correspond to the degrees of freedom, and the
parmatrix maps some value from the element to the quadrature points. `P u_{element} = u_{quad}`. Thus it's more
natural to distribute columns of the parallel matrix. 

For example, figure below shows the structure of a full size matris of 126 x 18, and I want the matrix divided into two parts:
1) processor 0 holds columns from 0 to 8, and all rows.
2) processor 1 holds columns form 9 to 18, and all rows.

On each processor, I already have the col/row indices of each local matrix, which is save in `mfem::SparseMatrix` format, so how should I use hypre API to construct hypre_ParCSRMatrix ?

![struct](https://user-images.githubusercontent.com/33760486/134542514-f7664721-3a41-4e9c-b3c9-df6becff3207.jpg)

Thanks,
Ge

**Comment by victorapm** [comment]
Hi Ge,

a hypre_ParCSRMatrix can be built through the IJ interface of hypre, see https://hypre.readthedocs.io/en/latest/ch-ij.html for a description of the process. Note that hypre assumes that such matrices are distributed by blocks of rows, instead of columns as you wanted. Alternatively, you could build the transpose of the matrix that you want.

**Comment by geyan3566** [comment]
Thank you.

Blocks of rows may also work. It came to my mind that because `u_{element}` are distributed among processors, so it looks more natural to distribute it by columns.

It seems hypre will take care of the communication even matrix is distributed by rows.

**Comment by victorapm** [comment]
Thanks, Ge! I will close this issue but feel free to reach out if you have more questions.
