### ISSUE TITLE
Issue installing Hypre on MacBook

### ISSUE THREAD

**Issue by kmoczuls** [hypre-space/hypre#506]
I am trying to install hyper 2.11.2 on my new MacBook Pro (A2141). I have installed mpi and am trying to install hypre using 

CC=mpicc CXX=mpicxx ./configure --prefix=/usr/local/hypre
and then 

sudo make install

The error that comes up is 

./../../utilities/version:1:2: error: invalid preprocessing directive

for a number of the utilities version.

**Comment by victorapm** [comment]
Closing this issue since it has been resolved with #731
