### ISSUE TITLE
Building hypre with cuda on target gpu arch sm_30 (kepler V1) fails to build due to instrinsic __ldg 

### ISSUE THREAD

**Issue by FCLC** [hypre-space/hypre#511]
Error returned by make is: 
```
../config/Makefile.config:66: recipe for target 'cuda_utils.obj' failed
make[1]: Leaving directory '/home/felix/petsc/arch-linux-c-opt/externalpackages/git.hypre/src/utilities'
Makefile:86: recipe for target 'all' failed_hypre_utilities.hpp(619): error: identifier "__ldg" is undefined
          detected during instantiation of "T read_only_load(const T *) [with T=HYPRE_Int]"
cuda_utils.c(131): here

_hypre_utilities.hpp(619): error: identifier "__ldg" is undefined
          detected during instantiation of "T read_only_load(const T *) [with T=HYPRE_Complex]"
cuda_utils.c(216): here

2 errors detected in the compilation of "/tmp/tmpxft_000029e6_00000000-6_cuda_utils.cpp1.ii".
make[1]: *** [cuda_utils.obj] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 1
```

I'm building Hypre with the following arguments: 

`./configure --with-MPI --with-extra-CFLAGS='-O3 -march=native -fopenmp' --with-extra-CXXFLAGS='-O3 -march=native -fopenmp' FOPTFLAGS='-O3 -march=native -qopenmp-stubs' --with-cuda-home=/usr/local/cuda-10.2  --with-gpu-arch=30 --enable-unified-memory --enable-fortran --enable-gpu-aware-mpi --enable-gpu-aware-mpi   --with-blas-libs=libmkl_blacs_intelmpi_lp64.so  --with-blas-lib-dirs=/opt/intel/oneapi/mkl/2021.4.0/lib/intel64/  --with-lapack-libs=libmkl_scalapack_ilp64.so   --with-lapack-lib-dirs=/opt/intel/oneapi/mkl/2021.4.0/lib/intel64/ --enable-cublas
 --with-hip=no`

host system is ubuntu 18.04 LTS with unmodified kernel, 

latest version of the cuda 10.2 tool kit (required for SM_30 devices) 

Seems this is similar in nature to an issue seen in py-thorch issue: https://github.com/pytorch/pytorch/issues/46644

As far as I can tell it has to do with Cuda versioning

Hypre is being build to integrate into PETSC as part of an accelerator for openFOAM. 

When called by petsc's configuration file, PETSC passes additional parameters based on it's on congif (petsc configures, makes and make installs  external packages during it's configure process, before building itself during it's own make step.)
The config passed to hyper by PETSC is below, but results in the same error: 

`./configure --prefix=/home/felix/OpenFOAM/felix-v2106/platforms/linux64GccDPInt32Opt/lib MAKE=/usr/bin/make --libdir=/home/felix/OpenFOAM/felix-v2106/platforms/linux64GccDPInt32Opt/lib/lib CC="/opt/intel/oneapi/mpi/latest/bin/mpiicc
" CFLAGS="-fPIC -wd1572 -O3" CXX="/opt/intel/oneapi/mpi/latest/bin/mpiicpc" CXXFLAGS="-wd1572 -O3 -fPIC -std=c++11" F90="/opt/intel/oneapi/mpi/latest/bin/mpiifort" F90FLAGS="-fPIC -O3" FFLAGS="-fPIC -O3" FC="/opt/intel/oneapi/mpi/latest/bin/mpiifort" F77="/opt/intel/oneapi/mpi/latest/bin/mpiifort" FCFLAGS="-fPIC -O3" --enable-shared --with-MPI-include="/opt/intel/oneapi/mpi/latest/include" --with-MPI-lib-dirs="" --with-MPI-libs="" --with-blas-lib="-Wl,-rpath,/opt/intel/oneapi/mkl/2
021.4.0/lib/intel64 -L/opt/intel/oneapi/mkl/2021.4.0/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lpthread -Wl,-rpath,/usr/local/cuda-10.2/lib -L/usr/local/cuda-10.2/lib -lcudart -lcufft -lcublas -lcusparse -lcusolver -lcurand -L/
usr/local/cuda-10.2/lib/stubs -lcuda -lstdc++ -ldl -Wl,-rpath,/opt/intel/oneapi/mpi/2021.4.0/lib/release -L/opt/intel/oneapi/mpi/2021.4.0/lib/release -Wl,-rpath,/opt/intel/oneapi/mpi/2021.4.0/lib -L/opt/intel/oneapi/mpi/2021.4.0/lib -lmpifort
-lmpi -lrt -lpthread -Wl,-rpath,/opt/intel/oneapi/tbb/2021.4.0/lib/intel64/gcc4.8 -L/opt/intel/oneapi/tbb/2021.4.0/lib/intel64/gcc4.8 -Wl,-rpath,/opt/intel/oneapi/mpi/2021.4.0/libfabric/lib -L/opt/intel/oneapi/mpi/2021.4.0/libfabric/lib -Wl,-r
path,/opt/intel/oneapi/mkl/2021.4.0/lib/intel64 -L/opt/intel/oneapi/mkl/2021.4.0/lib/intel64 -Wl,-rpath,/opt/intel/oneapi/compiler/2021.4.0/linux/compiler/lib/intel64_lin -L/opt/intel/oneapi/compiler/2021.4.0/linux/compiler/lib/intel64_lin -Wl
,-rpath,/opt/intel/oneapi/compiler/2021.4.0/linux/lib -L/opt/intel/oneapi/compiler/2021.4.0/linux/lib -Wl,-rpath,/usr/lib/gcc/x86_64-linux-gnu/7 -L/usr/lib/gcc/x86_64-linux-gnu/7 -Wl,-rpath,/opt/intel/oneapi/mpi/2021.4.0/lib/release -Wl,-rpath
,/opt/intel/oneapi/mpi/2021.4.0/lib -lifport -lifcoremt_pic -limf -lsvml -lm -lipgo -lirc -lgcc_s -lirc_s" --with-lapack-lib=" " --with-blas=no --with-lapack=no CUDA_HOME="/usr/local/cuda-10.2" --with-cuda --with-gpu-arch=30 CUCC="/usr/local/c
uda-10.2/bin/nvcc" CUFLAGS=" -expt-extended-lambda -std=c++11 --x cu  -Xcompiler -fPIC -O3 -std=c++11 -gencode arch=compute_30,code=sm_30  -Wno-deprecated-gpu-targets -Wno-deprecated-gpu-targets -I"/opt/intel/oneapi/mpi/2021.4.0/include" " --with-fmangle-blas=one-underscore --with-fmangle-lapack=one-underscore --without-mli --without-superlu AR="/usr/bin/ar cr" LDFLAGS="" --with-MPI --with-extra-CFLAGS='-O3 -march=native -fopenmp' --with-extra-CXXFLAGS='-O3 -march=native -fopenmp' FOPTFLAGS='-O3 -march=native -qopenmp-stubs' --with-cuda-home=/usr/local/cuda-10.2  --with-gpu-arch=30 --enable-unified-memory --enable-fortran --enable-gpu-aware-mpi --with-blas-libs=libmkl_blacs_intelmpi_lp64.so --with-blas-lib-dirs=/opt/intel/oneapi/mkl/2021.4.0/lib/intel64/ --with-lapack-libs=libmkl_scalapack_ilp64.so --with-lapack-lib-dirs=/opt/intel/oneapi/mkl/2021.4.0/lib/intel64/ --enable-cublas --with-hip=no`

Any suggestions?

**Comment by liruipeng** [comment]
@FCLC Can you please checkout this branch https://github.com/hypre-space/hypre/tree/sm30, and let us know if it works with sm 30? Thanks!

**Comment by FCLC** [comment]
> @FCLC Can you please checkout this branch https://github.com/hypre-space/hypre/tree/sm30, and let us know if it works with sm 30? Thanks!

Thanks for the reply! 

I'll try to build in a few days time, off LAN currently. 

Looks like gating around __ldg and then using a different method for sm30 and below?

**Comment by liruipeng** [comment]
`__ldg` is only for sm >= 35. For sm=30, it just simply returns the value. Btw, I have only tested building with sm=30, but I don't have a machine to run.
