### ISSUE TITLE
Crash when constructing MG hierarchy

### ISSUE THREAD

**Issue by bkrasnopolsky** [hypre-space/hypre#514]
Hello,
I'm experimenting with various options and solver configurations with hypre (BoomerAMG), and have faced with solver crash. It can be reproduced with the basic test application ij. An attempt to run the corresponding configuration (probably, rather exotic) leads to the solver failure:
mpirun -np 2 ./ij -laplacian -n 10 10 1 -agg_interp 2 -agg_nl 3 -mxrs 0.0
while the same run with np=1 finishes correctly. Logs for both runs are attached.

Tested on linux desktop (CentOS-8) with hypre-2.23.0 compiled with gcc-8.4.1 and OpenMPI-3.1.5.
[np1.log](https://github.com/hypre-space/hypre/files/7461932/np1.log)
[np2.log](https://github.com/hypre-space/hypre/files/7461933/np2.log)

**Comment by liruipeng** [comment]
@bkrasnopolsky ` -mxrs` is not supposed to be `<=0` or `> 1`. Are there reason you want max row sum to be 0? Even if so, you can try 
```
mpirun -np 2 ./ij -laplacian -n 10 10 1 -agg_interp 2 -agg_nl 3 -mxrs 1e-16
```
It should not crash.

Thanks!

**Comment by bkrasnopolsky** [comment]
@liruipeng That helps, thank you!

That is what was meant by rather exotic configuration. Actually - not, no practical reason this parameter to be equal to 0. That was an attempt to make automated search over the range of parameters. However, I didn't know this parameter should be strictly greater than 0. And different behavior for np=1 and 2 was also confusing.

Thank you for reply!

**Comment by liruipeng** [comment]
Excellent! Let me know if you find more issues. Close this now. Thanks!
