### ISSUE TITLE
Branch rebase and new style 

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#520]
Hi,
I have 3 branches keep up to date with Hypre master. I just rebased 1 of them. I want to keep these branches up to date with the newest style guidelines. In one of the directories where I modified files, I tried:

config/astyle-apply.sh parcsr_ls
Artistic Style Version 3.1 not found

What do I need to do to resolve this?

**Comment by rfalgout** [comment]
Hi Paul.  The input to the script is the `src` directory, so from the `src` directory, type `config/astyle-apply.sh .` .  See the hypre Wiki for more info on the new coding style:

https://github.com/hypre-space/hypre/wiki/Coding-Style

You will also need to have `astyle` installed and in your path.  If you don't want to worry about this, it's no problem.  We can take care of any indentation issues.

Thanks!
