### ISSUE TITLE
Error in HYPRE_IJMatrix?

### ISSUE THREAD

**Issue by craffael** [hypre-space/hypre#522]
I wonder if the following line is correct:

https://github.com/hypre-space/hypre/blob/66e1f2df45331ddc01a424586ad86716d8d75367/src/IJ_mv/HYPRE_IJMatrix.c#L261

I think it should read 
```
sums[j] = 0;
```
?

**Comment by liruipeng** [comment]
@craffael yes, I think you are right. Thank you!

**Comment by craffael** [comment]
I'm glad I could help :)

**Comment by craffael** [comment]
I guess you're going to fix it?

**Comment by rfalgout** [comment]
Yes, we will fix it.  Thanks for pointing this out!

**Comment by rfalgout** [comment]
This fix is now available on `master` and will be in future releases.  Thanks @craffael !
