### ISSUE TITLE
How to build with cuda when cuda is not all installed to one directory?

### ISSUE THREAD

**Issue by danielstone1943** [hypre-space/hypre#526]
Hi,

I've had some good success building hypre with cuda and running tests, when cuda-11 has been manually installed on my
machine. In that case everything cuda-related is found in /usr/local/cuda-11.4, with appropriate bin, include, lib64 directories
under that. Then I just set CUDA_HOME or use the --with-cuda-home=.. flag and hypre configures then compiles fine with cuda.

I've been trying to figure out how to do this on a different machine, where cuda has been installed by apt. In that case the cuda
includes, libraries, nvcc are not all in one place. For example cuda.h can be found in /usr/include/.

There doesn't seem to be a way to configure hypre for this situation. What would be ideal is flags analogous to --with-MPI-libs;
--with-MPI-include; etc. Is there something I'm missing?

I have noticed that variables HYPRE_CUDA_INCLUDE; HYPRE_CUDA_LIBS; are mentioned in the config.log file. However
setting them seems to make no difference. 

Is there a way of telling Hypre to look for cuda include files anywhere other than $CUDA_HOME/include?

**Comment by liruipeng** [comment]
Hi @danielstone1943 we do not support this for now, which can be improved later. For now, you may manually change `src/config/Makefile.config`. Thanks!

**Comment by danielstone1943** [comment]
Thanks for the clarification. 

So the way I can see around this now is:

1) Set cuda_home to "/usr", to trick the config file into finding cuda.h in /usr/include, so it doesn't error out on 
lines 8739...8774 of the configure script:

`./configure --with-cuda --enable-unified-memory -with-gpu-arch=61 CUDA_HOME=/usr`


2) Modify the autogenerated config/Makefile.config as follows:

```

##################################################################              
##  CUDA options                                                                
##################################################################              
HYPRE_CUDA_PATH    = /usr/                                                      
HYPRE_CUDA_INCLUDE = -I${HYPRE_CUDA_PATH}/include                               
#HYPRE_CUDA_LIBS    = -L${HYPRE_CUDA_PATH}/lib64 -lcudart -lcurand              
HYPRE_CUDA_LIBS    = -L/usr/lib/x86_64-linux-gnu/ -lcudart -lcusparse -lcurand  
CUDA_ARCH          = -gencode arch=compute_61,code=sm_61 

```
where I have determined that the files libcurart.so, etc, are located in /usr/lib/x86_64-linux-gnu.


When moving on to make I've come up with some problems in building, but I think this is related to cuda version:

```
/usr//bin/nvcc -ccbin=mpic++ -gencode arch=compute_61,code=sm_61  -O2 -lineinfo -expt-extended-lambda -std=c++11 --x cu -Xcompiler "-O2 " -DHAVE_CONFIG_H -I.. -I./.. -I./../struct_mv -I.  -I/usr//include        -c cuda_utils.c -o cuda_utils.obj
_hypre_utilities.hpp(991): error: identifier "cusparseIndexType_t" is undefined

cuda_utils.c(898): error: identifier "cusparseIndexType_t" is undefined

cuda_utils.c(914): error: identifier "CUSPARSE_INDEX_32I" is undefined

cuda_utils.c(1149): error: identifier "cusparseGetErrorString" is undefined

cuda_utils.c(1151): error: identifier "cusparseGetErrorString" is undefined

cuda_utils.c(1261): error: identifier "cusparseGetErrorString" is undefined


```
Right now I can only test this on an old ubuntu 18 install with cuda 9, which I think is too old
to contain these definitions - I think I've come across this problem before. A colleague may be able to 
test this procedure on an install of ubuntu 20 with cuda 10 installed. 

I note that re-configuring with 
```
--disable-cusparse
```
has no effect on these errors.

**Comment by liruipeng** [comment]
Your change of Makefile.config looks good. Yes, CUDA 9 is too old. `cusparseGetErrorString` was introduced in CUDA 10 I think. Also, hypre requires cusparse (for now) for AMG. Thanks for trying this!

**Comment by victorapm** [comment]
Closing this issue since it has been resolved
