### ISSUE TITLE
Deterministic CUDA solves?

### ISSUE THREAD

**Issue by ibaned** [hypre-space/hypre#541]
Hi! If I use PCG with SMG as a preconditioner, can I expect the setup and solve to be deterministic?

Meaning, if I give it the exact same linear system, will the solution be the same every time I run it?

Thanks!

**Comment by ibaned** [comment]
as the title states: with CUDA enabled, and the input being CUDA device memory arrays.

**Comment by liruipeng** [comment]
@ibaned I think so. Do you see nondeterministics with SMG? How big is the difference from run to run?

**Comment by ibaned** [comment]
@liruipeng Thanks! If it is expected to be deterministic, then I already feel better. I saw some non-determinism in overall application behavior and wanted to see if it could possibly be from HYPRE. I'll try to confirm that HYPRE is being deterministic in our runs, maybe hash the result vector somehow.

**Comment by liruipeng** [comment]
It should be. Please let us know if you can narrow down to hypre giving nondeterminism. Thanks!

**Comment by ibaned** [comment]
Thanks! I'll close for the answer and re-open if we actually confirm non-determinism.
