### ISSUE TITLE
Question about profiling Hypre.

### ISSUE THREAD

**Issue by hengjiew** [hypre-space/hypre#546]
Hello,

Is there a flag/option that enables hypre to print the time cost of each step/function it called? 
I hope to know how much time is spent on computation and communication in building matrices and solving the system at each level.
Thanks a lot!

**Comment by liruipeng** [comment]
The best way for profiling hypre is to configure `--with-caliper` (see `./configure --help`, need to install caliper https://github.com/LLNL/Caliper). If for GPU, you can use `--enable-gpu-profiling` instead, and view it by `Nsight` or `nvvp`. Hope this helps.
