### ISSUE TITLE
Illegal Address exception on Perlmutter

### ISSUE THREAD

**Issue by sjcrs** [hypre-space/hypre#551]
I'm trying to test an application that depends on hypre on the new NERSC Perlmutter nvidia80 system. hypre was configured with 

> export HYPRE_CUDA_SM=80
> _PREFIX="${_INSTALL}"
> ./configure \
>     --prefix="${_PREFIX}" \
>     --with-MPI \
>     --with-cuda 
> 

and successfully compiled with the supported PGI compiler. hypre is then linked to the application in question, and my application fails as soon as hypre calls are made.

I am no cuda debugging expert, so I simply ran the application under cuda-gdb to see the following exception:

> CUDA Exception: Warp Illegal Address
The exception was triggered at PC 0x64770c0 (struct_vector.c:423)
>Thread 1 "flash4" received signal CUDA_EXCEPTION_14, Warp Illegal Address.
[Switching focus to CUDA kernel 0, grid 7, block (0,0,0), thread (32,0,0), device 0, sm 0, warp 3, lane 0]
0x00000000064771e0 in void forall_kernel<hypre_StructVectorSetBoxValues::{lambda(int)#2}>(hypre_StructVectorSetBoxValues::{lambda(int)#2}, int)<<<(1,1,1),(512,1,1)>>> ()
    at /XXXX/hypre/src/struct_mv/struct_vector.c:423
423                    datap[datai] = values[dvali];

I'd appreciate any guidance here, as I'm sure there will be many new hypre users on Perlmutter once it opens up.

**Comment by liruipeng** [comment]
Hi @sjcrs we haven't tested on Perlmutter yet. But a quick run on A100 with sm=80 seemed fine. Can you please run the following two with `src/test/struct` and let us know if it fails?

```
mpirun -np 1  ./struct
mpirun -np 1  ./struct -solver 1
```
Thanks

**Comment by sjcrs** [comment]
Hi,
These executables did not fail. I saw the same output when I ran on a shared CPU node and when I submitted these commands to compute nodes via Slurm. I've attached the output from the both executables, respectively, below:


> sjcrs@login26:/global/u1/s/sjcrs/Perlmutter/hypre/src/test> ./struct
> Using HYPRE_DEVELOP_STRING: v2.23.0-0-ge8d142b63 (not main development branch)
>
> Running with these driver parameters:
>
>  (nx, ny, nz)    = (10, 10, 10)
  (istart[0],istart[1],istart[2]) = (-3, -3, -3)
  (Px, Py, Pz)    = (1, 1, 1)
  (bx, by, bz)    = (1, 1, 1)
  (px, py, pz)    = (0, 0, 0)
  (cx, cy, cz)    = (1.000000, 1.000000, 1.000000)
  (conx,cony,conz)= (0.000000, 0.000000, 0.000000)
  (n_pre, n_post) = (1, 1)
  dim             = 3
  skip            = 0
  sym             = 1
  rap             = 0
  relax           = 1
  jump            = 0
  solver ID       = 0
=============================================
Struct Interface:
=============================================
Struct Interface:
  wall clock time = 0.001058 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.001059 seconds
  cpu MFLOPS      = 0.000000
>
> =============================================
Setup phase times:
=============================================
SMG Setup:
  wall clock time = 0.026494 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.027232 seconds
  cpu MFLOPS      = 0.000000
>
>=============================================
Solve phase times:
=============================================
SMG Solve:
  wall clock time = 0.120779 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.120812 seconds
  cpu MFLOPS      = 0.000000
>
>
>Iterations = 5
>Final Relative Residual Norm = 1.375560e-07

>sjcrs@login26:/global/u1/s/sjcrs/Perlmutter/hypre/src/test> ./struct -solver 1
>
> Using HYPRE_DEVELOP_STRING: v2.23.0-0-ge8d142b63 (not main development branch)
>
> Running with these driver parameters:
> (nx, ny, nz)    = (10, 10, 10)
 >(istart[0],istart[1],istart[2]) = (-3, -3, -3)
  (Px, Py, Pz)    = (1, 1, 1)
  (bx, by, bz)    = (1, 1, 1)
  (px, py, pz)    = (0, 0, 0)
  (cx, cy, cz)    = (1.000000, 1.000000, 1.000000)
  (conx,cony,conz)= (0.000000, 0.000000, 0.000000)
  (n_pre, n_post) = (1, 1)
  dim             = 3
  skip            = 0
  sym             = 1
  rap             = 0
  relax           = 1
  jump            = 0
  solver ID       = 1
>
> =============================================
Struct Interface:
=============================================
Struct Interface:
  wall clock time = 0.001205 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.001206 seconds
  cpu MFLOPS      = 0.000000
>
> =============================================
Setup phase times:
=============================================
>PFMG Setup:
  wall clock time = 0.001383 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.001383 seconds
  cpu MFLOPS      = 0.000000
>
> =============================================
Solve phase times:
=============================================
PFMG Solve:
  wall clock time = 0.017586 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.017587 seconds
  cpu MFLOPS      = 0.000000
>
>
> Iterations = 16
>Final Relative Residual Norm = 5.185152e-07

**Comment by liruipeng** [comment]
Hi @sjcrs , the results of `struct` are the same as what we got on A100. Was it possible there were GPU errors outside hypre? Do you see these errors on V100 GPUs? Thanks

**Comment by sjcrs** [comment]
Sorry for the delay, it took some time to get access to our V100 GPU. The outputs for the `struct` and `struct -solver 1` are attached:

> Using HYPRE_DEVELOP_STRING: v2.24.0-7-g251cd3d26 (main development branch master)
>Running with these driver parameters:
  (nx, ny, nz)    = (10, 10, 10)
  (istart[0],istart[1],istart[2]) = (-3, -3, -3)
  (Px, Py, Pz)    = (1, 1, 1)
  (bx, by, bz)    = (1, 1, 1)
  (px, py, pz)    = (0, 0, 0)
  (cx, cy, cz)    = (1.000000, 1.000000, 1.000000)
  (conx,cony,conz)= (0.000000, 0.000000, 0.000000)
  (n_pre, n_post) = (1, 1)
  dim             = 3
  skip            = 0
  sym             = 1
  rap             = 0
  relax           = 1
  jump            = 0
  solver ID       = 0
=============================================
Struct Interface:
=============================================
Struct Interface:
  wall clock time = 0.000652 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.000651 seconds
  cpu MFLOPS      = 0.000000
>
>=============================================
Setup phase times:
=============================================
SMG Setup:
  wall clock time = 0.016525 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.016485 seconds
  cpu MFLOPS      = 0.000000
>
>=============================================
Solve phase times:
=============================================
SMG Solve:
  wall clock time = 0.054853 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.054774 seconds
  cpu MFLOPS      = 0.000000
>
>Iterations = 5
Final Relative Residual Norm = 1.375560e-07



>Using HYPRE_DEVELOP_STRING: v2.24.0-7-g251cd3d26 (main development branch master)
>
>Running with these driver parameters:
  (nx, ny, nz)    = (10, 10, 10)
  (istart[0],istart[1],istart[2]) = (-3, -3, -3)
  (Px, Py, Pz)    = (1, 1, 1)
  (bx, by, bz)    = (1, 1, 1)
  (px, py, pz)    = (0, 0, 0)
  (cx, cy, cz)    = (1.000000, 1.000000, 1.000000)
  (conx,cony,conz)= (0.000000, 0.000000, 0.000000)
  (n_pre, n_post) = (1, 1)
  dim             = 3
  skip            = 0
  sym             = 1
  rap             = 0
  relax           = 1
  jump            = 0
  solver ID       = 1
=============================================
Struct Interface:
=============================================
Struct Interface:
  wall clock time = 0.000583 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.000583 seconds
  cpu MFLOPS      = 0.000000
>
>=============================================
Setup phase times:
=============================================
PFMG Setup:
  wall clock time = 0.000763 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.000761 seconds
  cpu MFLOPS      = 0.000000
>
>=============================================
Solve phase times:
=============================================
PFMG Solve:
  wall clock time = 0.008916 seconds
  wall MFLOPS     = 0.000000
  cpu clock time  = 0.008894 seconds
  cpu MFLOPS      = 0.000000
>
>Iterations = 16
Final Relative Residual Norm = 5.185152e-07

**Comment by tangqi** [comment]
I have been testing hypre on Perlmutter and it has been working well as a single solver or in mfem. But thank you @sjcrs for providing the hypre installation configuration in another issue. It was very helpful

**Comment by victorapm** [comment]
Closing this issue since it has been resolved
