### ISSUE TITLE
Searching for .git... when cross compiling?

### ISSUE THREAD

**Issue by artv3** [hypre-space/hypre#556]
Hello, I've encountered an error I don't quite understand. 

When building on a blue_os system at LLNL I seem to hit the following build error with the latest hypre

```
src/../.git... configure: error: cannot check for file existence when cross compiling
```

Using hypre 2.22 built just fine. Has anyone seen this? Or have some insight on what might be going on?

**Comment by artv3** [comment]
The source of the error seems to come from here: 

https://github.com/hypre-space/hypre/blob/514c72be691b8698df7e7069d54458831cbc531e/src/configure#L2690-L2692

which was introduced in PR https://github.com/hypre-space/hypre/pull/472

**Comment by rfalgout** [comment]
Hi Arturo,

It looks like the autoconf macro `AC_CHECK_FILE` simply doesn't work in a cross-compile setting.  Can you say more about how we can replicate the problem?  Also, do you know if your build systems relies on having any of the `HYPRE_DEVELOP_*` variables?  Thanks!

-Rob

**Comment by victorapm** [comment]
Hi all,

sorry for getting into the conversation but I implemented a fix for this issue on branch [fix-cross-comp](https://github.com/hypre-space/hypre/tree/fix-cross-comp). @artv3, could you try it and confirm if it works? 

Thanks!

**Comment by rfalgout** [comment]
> sorry for getting into the conversation but I implemented a fix for this issue on branch [fix-cross-comp](https://github.com/hypre-space/hypre/tree/fix-cross-comp). @artv3, could you try it and confirm if it works?

That might just work, Victor!  Thanks!  Were you able to try it in a cross-compiling environment?

**Comment by victorapm** [comment]
I didn't, Rob. The login and compute nodes of the machines I have access share the same architecture :(

**Comment by victorapm** [comment]
Hi @artv3, I merged a fix for this issue on master. Let me know if you still have problems. 

Victor

**Comment by artv3** [comment]
Thanks! I'll give it a try by the end of the week.

**Comment by artv3** [comment]
Things are building now! Thanks!
