### ISSUE TITLE
Hypre failing to compile on Summit with Cuda 11

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#568]
csr_matvec_device.c(149): error: identifier "hypre_CSRMatrixToCusparseSpMat" is undefined
csr_matvec_device.c(153): error: identifier "hypre_CSRMatrixToCusparseSpMat" is undefined
csr_matvec_device.c(161): error: identifier "hypre_VectorToCusparseDnVec" is undefined

I've submitted a PR that fixes it, though I'm not sure if this is what you want (#567)

-Paul

**Comment by liruipeng** [comment]
This should be fixed after #569 . Thanks again @PaulMullowney
