### ISSUE TITLE
Changing/recompiling Issue on Summit

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#570]
On Summit, I'm trying to debug an assertion failure in par_csr_matvec.c. I make some changes to that file, and then build. I see:

2 errors found in build log:
     94     make[1]: Entering directory ‘/gpfs/alpine/cfd116/scratch/mullowne/spack-manager/environments/nalu-dev-debug_gcc-9.3.0_cuda-11.0.3/hypre/src/parcsr_mv’
     95     /sw/summit/cuda/11.0.3/bin/nvcc -ccbin=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/bin/mpicxx -gencode arch=compute_70,code=sm_70  -g -O0 -lineinfo -expt-extended-lambda -std=c++11 --x cu -Xcompiler “-g  -fPIC” -DHAVE_CONFIG_H -I.. -I. -I./.. -I./../blas -I./../lapack -I./../utilities -I./../seq_mv  -I/sw/summit/cuda/11.0.3/include        -c par_csr_matvec.c -o par_csr_matvec.obj
     96     Building libHYPRE_parcsr_mv.so ...
     97     /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/bin/mpicxx -shared  -o libHYPRE_parcsr_mv-2.23.0.so communicationT.o F90_HYPRE_parcsr_matrix.o F90_HYPRE_parcsr_vector.o F90_parcsr_matrix.o F90_par_vector.o HYPRE_parcsr_matrix.o HYPRE_parcsr_vector.o gen_fffc.o new_commpkg.o numbers.o par_csr_aat.o par_csr_assumed_part.o par_csr_bool_matop.o par_csr_bool_matrix.o par_csr_communication.o par_csr
            _matop.o par_csr_matrix.o par_csr_matop_marked.o par_csr_triplemat.o par_make_system.o par_vector.o par_vector_batched.o par_csr_matvec.obj par_csr_fffc_device.obj par_csr_matop_device.obj par_csr_triplemat_device.obj par_vector_device.obj -Wl,-soname,libHYPRE_parcsr_mv-2.23.0.so
     98     ln -s libHYPRE_parcsr_mv-2.23.0.so libHYPRE_parcsr_mv.so
     99     ln: failed to create symbolic link ‘libHYPRE_parcsr_mv.so’: File exists
     
Has anyone else seen anything like this?

To get things to build, I have to manually delete the symbolic link, or start from scratch and completely reconfigure/rebuild.
-Paul

**Comment by liruipeng** [comment]
@PaulMullowney I have seen this kind of errors. I am not an expert on this. But what I did was deleting the `.so` and `make` again. Hope it helps.

**Comment by PaulMullowney** [comment]
Could we add -f to the symbolic link creation?

I think this might work.

**Comment by liruipeng** [comment]
maybe. I am not very familiar with linking dynamic libraries . Thanks for your suggestion.

**Comment by PaulMullowney** [comment]
I added -f to ln -s commands in the parcsr_mv and lib subdirectory Makefiles. It seem to work

**Comment by PaulMullowney** [comment]
I just submitted a PR to address this. Maybe you can try it on your broader test system to see if this works generally.

https://github.com/hypre-space/hypre/pull/573

**Comment by liruipeng** [comment]
This should have been resolved.
