### ISSUE TITLE
hypre_TAlloc and hypre_TFree no backwards compatibility?

### ISSUE THREAD

**Issue by TheGermanGeologist** [hypre-space/hypre#590]
I'm currently trying to compile the [Uintah software](http://uintah-build.sci.utah.edu/) that uses hypre.
[Compilation fails](https://github.com/Uintah/Uintah/issues/13) because the hypre solvers in Uintah use the memory management functions hypre_TAlloc and hypre_TFree with two and one argument, respectively. The functions, however, expect three and two arguments. The missing argument in both cases seems to be of the type "hypre_MemoryLocation". The functions / macros are found in _hypre_utilities.h
Since I'm unfarmiliar with both softwares I wasn't able to find out what value I could pass to solve this issue.
The fact that the Uintah implementation has this deviation suggests that in a previous version of hypre, these calls were valid.
Is there an older version of hypre that allows calling these functions without the "hypre_MemoryLocation" argument? I couldn't find any hint in the changelog.

Appreciate any help!

**Comment by victorapm** [comment]
Hi @TheGermanGeologist,

the last version of hypre that supported memory allocation/deallocation functions without the `hypre_MemoryLocation` argument is [2.13.0](https://github.com/hypre-space/hypre/releases/tag/v2.13.0). 

I hope that using version 2.13 will solve your compilation issues,
Victor

**Comment by liruipeng** [comment]
Hi @TheGermanGeologist v2.13.0 is really old. I am not sure if you want to use that. Those functions are supposed for hypre internal use only, as all the other `hypre_*` functions. You may consider change them into `malloc`/`cudaMalloc`. Is there any reason that you cannot do it? Thanks!

**Comment by tharman-git** [comment]
We have successfully compiled Uinitah with hypre 2.23.0 and gcc 8.3.   Please paste the configure line you're using and describe the physical scenario you'd like to simulate.
