### ISSUE TITLE
error libHYPRE_utilities.a

### ISSUE THREAD

**Issue by KCCFD** [hypre-space/hypre#592]
I am getting the following error when I type "make" after I do the "./configure" in the "hypre-master/src" folder:

make[1]: O: Command not found
make[1]: [nvtx.obj] Error 127 (ignored)
Building libHYPRE_utilities.a ...
ar -rcu libHYPRE_utilities.a *.o
ar: *.o: No such file or directory
make[1]: *** [libHYPRE_utilities.a] Error 1

**Comment by liruipeng** [comment]
It seems to be compiler issues. You may check if the settings in `config/Makefile.config` look good.
