### ISSUE TITLE
ILU GPU reg/unit tests.

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#608]
Hi,
I need to refactor the ILU(0) GPU interface to be compatible with HIP/AMD
Is there a set of unit or regression tests that I can easily run to make sure I'm not breaking existing capabilities?
-Paul

**Comment by victorapm** [comment]
Hi @PaulMullowney,

you could run the regression tests defined on `src/test/TEST_ij/solvers.sh`. Particularly, the runs involving `hypre_ILU` start on line:  https://github.com/hypre-space/hypre/blob/5fe37b2286ded02dfc9089b8ae4e969b25624d49/src/test/TEST_ij/solvers.jobs#L126

Let me know if I can help you further,
Victor

**Comment by PaulMullowney** [comment]
Thanks Victor. I haven't forgotten about getting you some of our matrices.
