### ISSUE TITLE
Hypre on Crusher with ROCM 5

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#620]
Has anyone gotten Hypre to build with ROCM 5 on Crusher? I see the following configure error which I don't know how to resolve:

./conftest: error while loading shared libraries: libamdhip64.so.4: cannot open shared object file: No such file or directory

I use the following script to try to build (and this works for rocm 4.5.0):

#!/bin/bash
export rocm_version=5.0.2
module load craype-accel-amd-gfx90a
module load PrgEnv-cray
module load rocm/${rocm_version}
module load cray-mpich

export CFLAGS="-g -O2 -I$MPICH_DIR/include"
export CXXFLAGS="-g -O2 -I$MPICH_DIR/include"
export HYPRE_INSTALL_PREFIX=/ccs/home/mullowne/ilu_hypre_dev/install/gpu/hypre-IterTriSolve-crusher-$(date +%Y-%m-%d)/

export FC=$(which ftn)
export CXX=$(which CC)
export CC=$CXX

make distclean
./configure  --prefix=$HYPRE_INSTALL_PREFIX --with-gpu-arch=gfx90a --without-superlu --disable-bigint --without-openmp --with-hip --enable-rocsparse --enable-rocrand --enable-shared --with-MPI-lib-dirs="$MPICH_DIR/lib -L${CRAY_MPICH_ROOTDIR}/gtl/lib" --with-MPI-libs="mpi mpi_gtl_hsa" --with-MPI-include=$MPICH_DIR/include

make -j24

make install

**Comment by pbauman** [comment]
Hi @PaulMullowney, thanks for including your configure line. To confirm, you're *not* using GPU-aware MPI. This is critical as that is not playing nice with ROCm 5 on Crusher, yet. What you need to do is omit `-L${CRAY_MPICH_ROOTDIR}/gtl/lib"` from MPI-lib-dirs and `mpi_gtl_hsa` from MPI-libs. That is the GPU transport layer ("gtl") and it is only needed if you are using GPU-aware MPI. Indeed, this is the source of the incompatibility at present (and the source of your error message).

**Comment by PaulMullowney** [comment]
@pbauman This doesn't seem to resolve the issue. Is these the correct modules to use?
module load craype-accel-amd-gfx90a
module load PrgEnv-cray
module load rocm/5.1.0
module load cray-mpich

**Comment by pbauman** [comment]
I'm guessing you're using the Cray compiler? Likely it is still including the GTL library. I personally use module load `PrgEnv-gnu`, `CC=gcc CXX=g++` and then your configure line as is (except removing the gtl library inclusion).

**Comment by PaulMullowney** [comment]
Success. Thanks!
