### ISSUE TITLE
CUDA test error

### ISSUE THREAD

**Issue by Again-code** [hypre-space/hypre#64]
Hi,
I'm looking to use Hypre's GPU capabilities. But when I type `hypre/src/configure` to configure the package for my system, The CUDA test example in `hypre/src/test/` works fine. But the test example in `hypre/src/example/` will have error. In fact, the other software I use, PARFLOW, requires HYPRE. When I compiled PARFLOW, I encountered the same error as when I compiled the test example in `hypre/src/example/`. Here are some details：
`./configure --prefix=$HYPRE_DIR --with-MPI --with-cuda --enable-shared CC=mpicc CXX=mpicxx FC=mpif90 F77=mpif77`

```
hypre-2.18.2/src/examples$ make
mpicc -g -Wall -I../hypre/include -DHAVE_CONFIG_H -DHYPRE_TIMING -c ex1.c
In file included from /usr/local/cuda-9.2/include/thrust/execution_policy.h:24:0,
                 from ../hypre/include/_hypre_utilities.h:1129,
                 from ../hypre/include/interpreter.h:11,
                 from ../hypre/include/HYPRE_struct_ls.h:1105,
                 from ex1.c:32:
/usr/local/cuda-9.2/include/thrust/detail/execution_policy.h:21:1: error: unknown type name ‘namespace’
 namespace thrust
 ^
/usr/local/cuda-9.2/include/thrust/detail/execution_policy.h:22:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ tok
en {
 ^
。。。

In file included from /usr/local/cuda-9.2/include/thrust/detail/type_traits/pointer_traits.h:23:0,
                 from /usr/local/cuda-9.2/include/thrust/detail/raw_pointer_cast.h:20,
                 from /usr/local/cuda-9.2/include/thrust/detail/execute_with_allocator.h:20,
                 from /usr/local/cuda-9.2/include/thrust/execution_policy.h:25,
                 from ../hypre/include/_hypre_utilities.h:1129,
                 from ../hypre/include/interpreter.h:11,
                 from ../hypre/include/HYPRE_struct_ls.h:1105,
                 from ex1.c:32:
/usr/local/cuda-9.2/include/thrust/iterator/iterator_traits.h:34:20: fatal error: iterator: No such file or directory
compilation terminated.
Makefile:53: recipe for target 'ex1.o' failed
make: *** [ex1.o] Error 1
```
when I change ex1.c to ex1.cpp , it will report another error :
```
hypre-2.18.2/src/examples$ make
mpicxx -g -Wall -Wno-deprecated -I../hypre/include -I.. -DHAVE_CONFIG_H -DHYPRE_TIMING    -c -o ex1.o ex1.cpp
In file included from ../hypre/include/interpreter.h:11:0,
                 from ../hypre/include/HYPRE_struct_ls.h:1105,
                 from ex1.cpp:32:
../hypre/include/_hypre_utilities.h: In function ‘hypre_int hypre_cuda_get_num_threads()’:
../hypre/include/_hypre_utilities.h:1223:18: error: ‘blockDim’ was not declared in this scope
          return (blockDim.x);
                  ^
../hypre/include/_hypre_utilities.h: In function ‘hypre_int hypre_cuda_get_thread_id()’:
../hypre/include/_hypre_utilities.h:1241:18: error: ‘threadIdx’ was not declared in this scope
          return (threadIdx.x);
                  ^
../hypre/include/_hypre_utilities.h:1243:32: error: ‘blockDim’ was not declared in this scope
          return (threadIdx.y * blockDim.x + threadIdx.x);
```

**Comment by Again-code** [comment]
When I use cmake to build HYPRE,  the test example in `hypre/src/example/` works fine . But the 
 CUDA sample `hypre/src/test/` report an error like this :
```
/hypre-2.18.2/src/test$ make
Makefile:8: ../config/Makefile.config: No such file or directory
make: *** No rule to make target '../config/Makefile.config'.  Stop.

```
my order is:
`cmake -DHYPRE_ENABLE_SHARED=ON -DHYPRE_WITH_MPI=ON ../`

In addition，I didn't find any CUDA options in `CMakeLists.txt`
Can you point out my mistake and give some help?
Thanks!

**Comment by liruipeng** [comment]
Hi, @Again-code,

I believe it is a cuda (thrust) error. I had the same issue before. Can you try it with cuda-10.1.243 if possible?

Thanks

-Ruipeng

**Comment by Again-code** [comment]
Hi, @liruipeng
I have tried it, but it still get the same error. Is there any other solution?

Thanks

-Again-code

**Comment by liruipeng** [comment]
> Hi, @liruipeng
> I have tried it, but it still get the same error. Is there any other solution?
> 
> Thanks
> 
> -Again-code

Hi, @Again-code ,

There are several issues here. 1. Hopefully, after changing to `cuda-10.1.243`, the thrust errors are gone. 2. the makefile in `examples` does not carry the CUDA flags as in `test`, so you have to manually add them in compile. 3. the example code does not work on GPU anyway. So probably it is not useful even if you manage to compile

We have some example code made for GPU which, however, has not been pushed. If you feel it is useful, I can make a branch of hypre that includes it

Sorry for the confusion earlier

Thanks

-Ruipeng

**Comment by rfalgout** [comment]
Has this issue been resolved?  Thanks!  -Rob
