### ISSUE TITLE
Hypre lags when multiples CPU cores are used with mpirun 

### ISSUE THREAD

**Issue by KMountris** [hypre-space/hypre#640]
Hello, 

I am new user of the library and relatively new to MPI in general. I followed the ex5.c to incorporate Hypre in my software using the IJ interface. I get correct solutions when I run my program with mpirun -np 1 or mpirun -np 2.

However, when I choose a larger number of processors the program lags. The same behaviour has been observed during the execution of the examples. I wonder if this is a hardware problem or a configuration problem.

Could you let me if there is a way to debug it?

I am running on a Dell Alienware laptop with 12th gen Intel Core i9-12900H

Thank you in advance.

Kind regards,
Konstantinos

**Comment by victorapm** [comment]
Hi @KMountris,

What is the minimum number of MPI processes that you observe this unwanted behavior?
Have you configured hypre with OpenMP support?
Does your program hang at some point and do not complete execution or does it complete execution after a longer time than the case when `np = 1` or `np = 2`?

Thanks!

**Comment by KMountris** [comment]
Hello @victorapm,

Thank you for your fast reply. The problems appears for np >= 3. The program eventually completes but hang out for a long time. However, from your response I understand that OpenMP may create some issues. I checked and I had it enabled.

After disabling it and rebuilding Hypre, the program executes without any hanging out for up to np = 14 (number of my parallel processors). 

Is the odd behaviour when the OpenMP is enabled expected?

Thank you for your support.

**Comment by ulrikeyang** [comment]
That would depend on how many threats you are actually using. Imagine it uses the maximum number of cores and now also tries to use that in each MPI task, so the threads would inhibit each other.
You can avoid this by setting the number of threads per MPI task.

**Comment by victorapm** [comment]
Just adding to Ulrike's response: you can set the number of threads per MPI process via the environment variable `OMP_NUM_THREADS`.

**Comment by KMountris** [comment]
Dear @ulrikeyang and @victorapm,

Thank you for your feedback. Indeed, some parts of my existing code are using multithreading and this appears to be the reason for the hanging of the execution. I was able to resolve the issue thanks to your support.

I deeply appreciate it.
