### ISSUE TITLE
Question with hypre memory use

### ISSUE THREAD

**Issue by zqm1992** [hypre-space/hypre#65]
Dear hypre developers,

I am a using hypre for preconditioning (AMG) of homogenization problem. The problem I find is that the memory requirement for AMG is high so the system would crash because it cannot allocate enough memory. I would assume the total memory is scalable for hypre. I am just wondering whether the local memory would differ too much between different processors? Another question is that is there any way to reduce the memory requirement by change the parameters in preconditioner? The parameter I use is as followed (default setting for boomeramg):

        PETScOptions::set("ksp_view");
        PETScOptions::set("ksp_monitor_true_residual");
        PETScOptions::set("ksp_pc_side", "right");
        PETScOptions::set("pc_type", "hypre");
        PETScOptions::set("pc_hypre_type", "boomeramg");

Thank you for your help all the time. Hope you reply soon.

Yours sincerely,
Qiming

**Comment by liruipeng** [comment]
Hi, @zqm1992 , How big is your system to solve and how many nodes did you try to use? What are the parameters you gave to boomeramg (through PETSc)?

**Comment by zqm1992** [comment]
> Hi, @zqm1992 , How big is your system to solve and how many nodes did you try to use? What are the parameters you gave to boomeramg (through PETSc)?

Dear Liruipeng,

Thank you for your attentions. The current problem is not big (200x200x100 hex mesh). I am using 192 processors (4 nodes) in Stampede2. The parameters I gave to bommeramg is just default setting. Thank you for your help all the time.

Yours sincerely,
Qiming

**Comment by liruipeng** [comment]
@zqm1992 With the number of processors  and the problem size you mentioned, it should have been OK to solve with hypre. You said local memory differ too much, so did you see some process require enormous memory compared with the others. Was your problem equally partitioned before given to hypre?
