### ISSUE TITLE
HYPRE_BoomerAMGSolve produces NaNs

### ISSUE THREAD

**Issue by stgeke** [hypre-space/hypre#656]
We're facing an issue using newer HYPRE versions > 2.18.2 (older version are not affected):

```
BoomerAMG SETUP PARAMETERS:

 Max levels = 25
 Num levels = 6

 Strength Threshold = 0.250000
 Interpolation Truncation Factor = 0.000000
 Maximum Row Sum Threshold for Dependency Weakening = 0.900000

 Coarsening Type = PMIS 
 measures are determined locally


 No global partition option chosen.

 Interpolation = extended+i interpolation

Operator Matrix Information:

             nonzero            entries/row          row sums
lev    rows  entries sparse   min  max     avg      min         max
======================================================================
  0    8435    89145  0.001     8   11    10.6  -3.758e-14   3.758e-14
  1    3390    73158  0.006     8   74    21.6  -1.376e-14   1.166e-14
  2    1427    64405  0.032     6  192    45.1  -9.748e-15   8.171e-15
  3     414    33560  0.196    28  153    81.1  -9.533e-15   9.550e-15
  4      66     2348  0.539    30   45    35.6  -1.417e-14   8.665e-15
  5       7       49  1.000     7    7     7.0  -3.686e-14   1.485e-14


Interpolation Matrix Information:
                    entries/row        min        max            row sums
lev  rows x cols  min  max  avgW     weight      weight       min         max
================================================================================
  0  8435 x 3390    1    4   2.6   2.755e-02   1.000e+00   1.000e+00   1.000e+00
  1  3390 x 1427    1    4   2.2   1.812e-02   1.000e+00   1.000e+00   1.000e+00
  2  1427 x 414     1    4   3.6   1.772e-02   1.000e+00   1.000e+00   1.000e+00
  3   414 x 66      1    4   3.9  -1.086e-01   9.480e-01   1.000e+00   1.000e+00
  4    66 x 7       1    4   3.6   1.199e-02   7.384e-01   1.000e+00   1.000e+00


BoomerAMG SOLVER PARAMETERS:

  Maximum number of cycles:         1 
  Stopping Tolerance:               0.000000e+00 
  Cycle type (1 = V, 2 = W, etc.):  1

  Relaxation Parameters:
   Visiting Grid:                     down   up  coarse
            Number of sweeps:            1    1     1 
   Type 0=Jac, 3=hGS, 6=hSGS, 9=GE:     16   16    16 
   Point types, partial sweeps (1=C, -1=F):
                  Pre-CG relaxation (down):   0
                   Post-CG relaxation (up):   0
                             Coarsest grid:   0

 Output flag (print_level): 3 
                                            relative
               residual        factor       residual
               --------        ------       --------
    Initial    5.471123e-02                 1.000000e+00
    Cycle  1   -nan    -nan     -nan 
```

Matrix file: [matrix.txt](https://github.com/hypre-space/hypre/files/8947872/matrix.txt)

Somehow it seems to be related to the smoother (Chebychev) i.e. using Jacobi works fine.

**Comment by victorapm** [comment]
Hi @stgeke,

thank you for reporting this. This test case leads to a coarse level matrix in AMG that is rank deficient which causes problems to Chebyshev. I'll talk to the team about ways of treating the limitation with Chebyshev

Thanks

**Comment by stgeke** [comment]
Any idea why this worked with older HYPRE version e.g. 2.18.2?

**Comment by victorapm** [comment]
Can you double check if it really worked with 2.18.2? In this version and assuming the same BoomerAMG settings, hypre does not throw a NaN, however the solver doesn't converge to a relative residual norm smaller than 1e-8. You might want to double check your solution.

**Comment by stgeke** [comment]
It worked at least for our usecase. We use boomerAMG just in the preconditioner using a single V-cycle, so the residual norm is always larger > 1e-8.

**Comment by stgeke** [comment]
Does Gaussian elimination really work if there is a non-trivial nullspace? I thought in this case you want to use an iterative solver.

**Comment by victorapm** [comment]
> I thought in this case you want to use an iterative solver.

Correct, I thought this switch was being done internally at the code with our default coarsest level solver option, but I double checked now and that's not the case. Sorry for the confusion.

Can you provide more details on the linear system you're trying to solve (initial guess, where does the matrix come from, RHS)? I see the input matrix is singular, is there a way to make it full rank?

**Comment by stgeke** [comment]
The matrix comes from a FEM discretization of a Poisson equation. The boundary conditions are all Neumann. In the past we have just used iterative solvers to avoid null space issues.  What has changed that newer HYPRE version don't work anymore? As I said using 2.18.2 works just fine.

**Comment by victorapm** [comment]
@stgeke, which initial guess and RHS vectors are you using for this problem? I need this information to track down the difference between the behaviors you are seeing with hypre 2.25.0 and 2.18.2.

**Comment by ulrikeyang** [comment]
What are the settings you used that worked with 2.18.2, but no longer works? Generally we try to keep hypre backward compatible. I don’t think we changed any defaults since then.

**Comment by stgeke** [comment]
Attached x and b. 
[x.txt](https://github.com/hypre-space/hypre/files/8951486/x.txt)
[b.txt](https://github.com/hypre-space/hypre/files/8951487/b.txt)

All other relevant settings should be in this thread. Is there anything missing?

**Comment by victorapm** [comment]
@stgeke, thanks for providing the additional info. I implemented a fix on the [cheby-fix](https://github.com/hypre-space/hypre/tree/cheby-fix) branch and I'm able to solve your problem. Can you try using that branch and let me know if it works for you?

**Comment by victorapm** [comment]
@stgeke, the fix has been merged into master. Let me know if you have problems
