### ISSUE TITLE
HYPRE fails to build with `-DHYPRE_ENABLE_CUSPARSE=OFF`

### ISSUE THREAD

**Issue by stgeke** [hypre-space/hypre#662]
```
.../hypre/src/parcsr_ls/par_ilu.c(3069): error: identifier "hypre_DeviceDataCusparseHandle" is undefined
```
If this is expected why is it an optional flag?

**Comment by liruipeng** [comment]
Currently, we need  to have `-DHYPRE_ENABLE_CUSPARSE=ON` for GPUs, which can be changed in the future. Thanks!
