### ISSUE TITLE
Include contents of ams.h in _hypre_parcsr_ls.h

### ISSUE THREAD

**Issue by tuckerbabcock** [hypre-space/hypre#667]
I'd like to modify the build process so that the contents of `ams.h` get added to `_hypre_parcsr_ls.h` (just as `par_amg.h`) appears got be copied over. My real goal is to be able to read properties of the AMS solver (either through the macros like `hypre_AMSDataDimension` or just by direct accessing the fields of the struct). An alternative would be to write proper `HYPRE_AMSGet*` functions (like those that exist for BoomerAMG).

Would a Hypre dev be able to help me with the build system changes? Or in adding the `HYPRE_AMSGet*` functions?

Thanks,
Tucker Babcock

**Comment by tuckerbabcock** [comment]
The real goal is to address a memory leak in MFEM caused by calling `HYPRE_AMSSetup` on the same solver multiple times. I've proposed an implementation that fixes the memory leak (https://github.com/mfem/mfem/pull/3096), but if I could read the solver's settings/properties I'd be able to reset the solver to whatever it was before, instead of resorting to some default set of settings.

**Comment by tzanio** [comment]
@rfalgout, having access to the AMS data structure entries will indeed be useful for us in MFEM, as @tuckerbabcock pointed out.

I can propose a PR that updates `parcsr_ls/_hypre_parcsr_ls.h` accordingly if you are OK with it.

**Comment by rfalgout** [comment]
Hi @tzanio .  A PR would be fine with me.  Note that you should not modify `parcsr_ls/_hypre_parcsr_ls.h` directly, but instead add `ams.h` to the `headers` script.  Also, the `HYPRE_*Get` routines would be manually added to `parcsr_ls/HYPRE_parcsr_ls.h`.  Thanks!

**Comment by tzanio** [comment]
How does #730 look?

**Comment by rfalgout** [comment]
Looks good @tzanio.  I've added some reviewers and made @tuckerbabcock a hypre Contributor in case he needs to push changes to the branch/PR.

**Comment by rfalgout** [comment]
Note that it is preferable to use the `HYPRE_*Get()` functions when possible, so adding some might also be a good idea.  Usually these exist symmetrically with `HYPRE_*Set()` functions and make sense from a user interface perspective and is independent from the underlying data structure details.  Thanks!

**Comment by tzanio** [comment]
I think we have the `HYPRE_AMSGet*` functions we want already in `HYPRE_parcsr_ls.h` (similarly to what `BoomerAMG` exposes). Am I missing something?

**Comment by rfalgout** [comment]
@tzanio .  My comment about `Get` functions was intended to be general in nature.  You may well have everything you really want here already for AMS.  Thanks!

**Comment by tzanio** [comment]
Thanks Rob!
