### ISSUE TITLE
ex5.c erro:  cannot convert ‘double*’ to ‘HYPRE_Real* {aka long double*}’ for argument ‘2’ to ‘HYPRE_Int HYPRE_PCGGetFinalRelativeResidualNorm(HYPRE_Solver, HYPRE_Real*)’

### ISSUE THREAD

**Issue by ztdepztdep** [hypre-space/hypre#68]
Dear sir:
    I compile ex5 with kdevelop, but i met the following error.
cannot convert ‘double*’ to ‘HYPRE_Real* {aka long double*}’ for argument ‘2’ to ‘HYPRE_Int HYPRE_PCGGetFinalRelativeResidualNorm(HYPRE_Solver, HYPRE_Real*)’
 How to resolve this problem.

**Comment by liruipeng** [comment]
@ztdepztdep Did you configure hypre with  `--enable-longdouble`?
