### ISSUE TITLE
HYPRE_Int -> HYPRE_BigInt in hypre_ParcsrGetExternalRowsDeviceInit?

### ISSUE THREAD

**Issue by pbauman** [hypre-space/hypre#681]
Line in question:

https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/par_csr_matop_device.c#L714

Shouldn't this be a `HYPRE_BigInt`? 

@liruipeng @ulrikeyang 

Thanks!

**Comment by liruipeng** [comment]
Yes, @pbauman . This should be BigInt. Thanks for catching it.

**Comment by liruipeng** [comment]
Fixed. Thanks!
