### ISSUE TITLE
CUDA Status and Documentation

### ISSUE THREAD

**Issue by ian-bertolacci** [hypre-space/hypre#69]
Can someone tell me what the status of CUDA support is, and maybe what are common changes necessary to make existing Hypre using code compatible with the CUDA version of the library?

I've been tasked with incorporating the CUDA enabled version of Hypre into an application already using Hypre.
While there seems to be a small number of people using and discussing using CUDA-hypre in github issues, there isn't any documentation (as far as I can tell).

Thanks!

**Comment by rfalgout** [comment]
We have added some documentation for using GPUs and improved our GPU code overall.  Hopefully that helps.  Thanks!
