### ISSUE TITLE
AoT compiling for non-default target

### ISSUE THREAD

**Issue by mrogowsx** [hypre-space/hypre#697]
Following commit introduced target devices setting for aot compilation:
[Sycl interp (#638) · hypre-space/hypre@6f3bccb (github.com)](https://github.com/hypre-space/hypre/commit/6f3bccb92c3eb7bcee06d9f3a2560978731dcef9)
To be more specific:
https://github.com/hypre-space/hypre/blob/6f3bccb92c3eb7bcee06d9f3a2560978731dcef9/src/configure#L9331
https://github.com/hypre-space/hypre/blob/6f3bccb92c3eb7bcee06d9f3a2560978731dcef9/src/config/configure.in#L2414

The problem arises when the HYPRE build process is run for some other device, on a system which does not recognize versions 12.1.0/12.4.0. To make it build successfully the hardcoded values have to be changed. Is there a possibility to introduce providing target device values via some kind of parameter (and thus avoiding source code modifications)?

**Comment by waynemitchell** [comment]
@mrogowsx, sorry for the inconvenience. The sycl backend is still in somewhat early development, and I had hardcoded this just for my own ease of use on the system I use for development. I will put together a PR to make this easily modifiable from the configure command as you suggest. Stay tuned.

**Comment by waynemitchell** [comment]
I've opened PR [701](https://github.com/hypre-space/hypre/pull/701) to address this issue. Let me know if whether this is a good fix or if you have further suggestions. Thanks!

**Comment by mrogowsx** [comment]
After testing, it works as expected. Thank you very much!

**Comment by victorapm** [comment]
Closing this since the issue has been resolved.
