### ISSUE TITLE
Compiling ex5f.f without MPI

### ISSUE THREAD

**Issue by tmpnemophd** [hypre-space/hypre#7]
Hi,

I am trying to compile one of the Fortran examples (ex5f.f) without the MPI implementation, but I can't figure out how to tweak the code to safely ignore the MPI-related subroutines.

Just so you know, I have installed Hypre on my Windows machine with CMake, with the following configuration options in CMakeLists.txt:

---
option(HYPRE_SHARED               "Build a shared library" OFF)
option(HYPRE_BIGINT               "Use long long int for HYPRE_Int" OFF)
option(HYPRE_SEQUENTIAL           "Compile without MPI" ON)
option(HYPRE_TIMING               "Use HYPRE timing routines" OFF)
option(HYPRE_USING_HYPRE_BLAS     "Use internal BLAS library" ON)
option(HYPRE_USING_HYPRE_LAPACK   "Use internal LAPACK library" ON)
option(HYPRE_NO_GLOBAL_PARTITION  "Use assumed partition" ON)
option(HYPRE_PRINT_ERRORS         "Print HYPRE errors" OFF)
option(HYPRE_USING_OPENMP         "Use OpenMP" ON)
option(HYPRE_USING_FEI            "Use FEI" ON)
option(HYPRE_USING_CALIPER        "Use Caliper" OFF)
---

Now, before compiling ex5f.f (which comes with the Hypre distribution) in Visual Studio, I noticed that it makes use of "mpif.h". Because I turned off MPI, I do not have mpif.h (please let me know if I am wrong here or anywhere else). As a work-around, I commented out the **include 'mpif.h'** line and other calls to the subroutines that begin with "MPI..". 

When I try to build the solution with these edits, as you probably have guessed, I get error messages due to unresolved external symbols (e.g., _HYPRE_IJMATRIXCREATE, _HYPRE_IJMATRIXSETOBJECTTYPE, etc.).

Is there anything I can do to build this example file without MPI? Any help will be greatly appreciated.

Thank you.

**Comment by rfalgout** [comment]
Hi,

The problem you are having is not with MPI, but with Fortran name mangling.  It looks like your Fortran compiler prepends an underscore and capitalizes everything (I have never seen this particular scheme, BTW, so we don’t have it readily available in hypre).  If that is indeed the case, then I think you will need to modify the ‘src/utilities/fortran.h’ file by adding the following line just before the ‘#define hypre_F90_IFACE’ line (line 68):

  #define hypre_F90_NAME_5(name,NAME) _##NAME

Once you’ve done that, then do a clean build of hypre again before trying to compile/link the fortran example driver.  Let me know how this works.

Thanks!

-Rob

**Comment by tmpnemophd** [comment]
Thank you very much for quick reply. I followed your instruction but I think I am missing a critical link here. 

**Simply put, how do I compile ex5f.f ?**

I know the instruction says "Compile with: make ex5f" but I am not sure how to compile it in Windows with Visual Studio. The clean build still did not generate mpif.h. Could you tell me which source files to add to Visual Studio when compiling ex5f.f ?

Thank you.

**Comment by rfalgout** [comment]
Unfortunately, I am not a Visual Studio guru, so I don’t think I can help you compile and link the example driver.  Maybe some reading of VS user manuals would help?  You just need to understand how to compile a Fortran file that requires a link to an external library (in this case, the hypre library, which our CMake system builds for you).

One approach you might consider is to mimic the CMakeLists.txt file in the ‘src/test’ directory, but put it in the ‘src/examples’ directory instead.  With the appropriate modifications, you should be able to use CMake and VS to build the example file you are interested in.  You might try building the hypre drivers in ‘src/test’ first just to make sure everything is working for you with our drivers.

You can continue to comment out the ‘mpif.h’ and ‘MPI_*’ calls in the example code, since you are not using MPI.

Hope this helps!

-Rob

**Comment by tmpnemophd** [comment]
Thank you for your help. I will give it a try!

**Comment by rfalgout** [comment]
FYI, I just realized that my earlier message had a copy/paste typo.  The 'fortran.h' line should be:

    #define hypre_F90_NAME(name,NAME) _##NAME

So, no '_5'.

**Comment by tmpnemophd** [comment]
Thank you for clarification.

Also, just to confirm, is the "hypre library" you mentioned the "HYPRE.lib" file ?

Thank you.

**Comment by rfalgout** [comment]
Yes, that should be it.  -Rob

**Comment by tmpnemophd** [comment]
So the way to link libraries in Visual Studio is: [Project]->[Project Properties]->[Linker]->[Input]->[Additional Dependencies].

However, I still get error messages, which are:
---
Error	1	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXCREATE referenced in function MAIN__	ex5f.obj	
Error	2	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXSETOBJECTTYPE referenced in function MAIN__	ex5f.obj	
Error	3	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXINITIALIZE referenced in function MAIN__	ex5f.obj	
Error	4	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXSETVALUES referenced in function MAIN__	ex5f.obj	
Error	5	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXASSEMBLE referenced in function MAIN__	ex5f.obj	
Error	6	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXGETOBJECT referenced in function MAIN__	ex5f.obj	
Error	7	 error LNK2019: unresolved external symbol HYPRE_IJVECTORCREATE referenced in function MAIN__	ex5f.obj	
Error	8	 error LNK2019: unresolved external symbol HYPRE_IJVECTORSETOBJECTTYPE referenced in function MAIN__	ex5f.obj	
Error	9	 error LNK2019: unresolved external symbol HYPRE_IJVECTORINITIALIZE referenced in function MAIN__	ex5f.obj	
Error	10	 error LNK2019: unresolved external symbol HYPRE_IJVECTORSETVALUES referenced in function MAIN__	ex5f.obj	
Error	11	 error LNK2019: unresolved external symbol HYPRE_IJVECTORASSEMBLE referenced in function MAIN__	ex5f.obj	
Error	12	 error LNK2019: unresolved external symbol HYPRE_IJVECTORGETOBJECT referenced in function MAIN__	ex5f.obj	
Error	13	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGCREATE referenced in function MAIN__	ex5f.obj	
Error	14	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETPRINTLEVEL referenced in function MAIN__	ex5f.obj	
Error	15	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETOLDDEFAULT referenced in function MAIN__	ex5f.obj	
Error	16	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETRELAXTYPE referenced in function MAIN__	ex5f.obj	
Error	17	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETRELAXORDER referenced in function MAIN__	ex5f.obj	
Error	18	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETNUMSWEEPS referenced in function MAIN__	ex5f.obj	
Error	19	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETMAXLEVELS referenced in function MAIN__	ex5f.obj	
Error	20	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETTOL referenced in function MAIN__	ex5f.obj	
Error	21	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSETUP referenced in function MAIN__	ex5f.obj	
Error	22	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGSOLVE referenced in function MAIN__	ex5f.obj	
Error	23	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGGETNUMITERATIONS referenced in function MAIN__	ex5f.obj	
Error	24	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGGETFINALRELTVRES referenced in function MAIN__	ex5f.obj	
Error	25	 error LNK2019: unresolved external symbol HYPRE_BOOMERAMGDESTROY referenced in function MAIN__	ex5f.obj	
Error	26	 error LNK2019: unresolved external symbol HYPRE_IJMATRIXDESTROY referenced in function MAIN__	ex5f.obj	
Error	27	 error LNK2019: unresolved external symbol HYPRE_IJVECTORDESTROY referenced in function MAIN__	ex5f.obj	
Error	28	 error LNK2019: unresolved external symbol MPI_FINALIZE referenced in function MAIN__	ex5f.obj	
Error	29	 fatal error LNK1120: 28 unresolved externals	x64\Release\Test_Fortran.exe	
---

There are two underscores (__) after MAIN in the error messages above. I am suspecting (and hoping) that the issue has to do with the Fortran name mangling. Is there anything I can do? 

Thank you.

**Comment by rfalgout** [comment]
Based on these errors, it looks like the name mangling scheme is one I am familiar with: all caps.  You can either modify the 'fortran.h' line I gave you earlier to this:

  #define hypre_F90_NAME(name,NAME) NAME

or start from the original 'fortran.h' file and add this line just before the '#if   (HYPRE_FMANGLE == 1)' block of code:

  #define HYPRE_FMANGLE 4

Don't forget to do a clean rebuild of hypre too!

**Comment by tmpnemophd** [comment]
Thank you very much. I was able to compile and run this example successfully.
