### ISSUE TITLE
Convergence tolerance defaults

### ISSUE THREAD

**Issue by rfalgout** [hypre-space/hypre#70]
Hi @hypre-space/developers,

It looks like we have some inconsistencies with our convergence tolerance defaults.  In most cases, the default is 1.0e-6, but there are a couple that are 1.0e-7 (par_amg.c, par_mgr.c).  I think we should make them all 1.0e-6 and ensure that the header file comments also match.  Any concerns about making these changes?

Thanks!

-Rob

**Comment by liruipeng** [comment]
@rfalgout Agreed on making all the same, like 1e-6

**Comment by ulrikeyang** [comment]
I have no concerns
Ulrike

**Comment by oseikuffuor1** [comment]
That's fine with me too. I have not checked this yet, but I'm wondering if this may cause some of the regression tests to fail? That is, if the test drivers are not explicitly setting the convergence tolerance (default). I think ij.c does, so it should not be an issue.

-Daniel

**Comment by rfalgout** [comment]
Resolved with #206
