### ISSUE TITLE
Regression on lassen

### ISSUE THREAD

**Issue by liruipeng** [hypre-space/hypre#703]
I think PR #693 broke the regression test (TEST_ij/solvers.jobs, 118) on lassen, i.e.,
```
lrun -n 8 mpibind ./ij -n 20 20 20 -P 2 2 2 -agg_nl 1 -solver 3 -mult_add 0 -add_Pmx 5 -add_end 2
...
GMRES Iterations = 28
Final GMRES Relative Residual Norm = 5.665841e-09
```
for which the `.saved.lassen` is
```
# Output file: solvers.out.118
GMRES Iterations = 27
Final GMRES Relative Residual Norm = 5.532387e-09
```

**Comment by victorapm** [comment]
I'll take a look at this

It's weird that I ran the regression tests on [lassen](https://github.com/hypre-space/hypre/wiki/files/lassen.sh) before merging and `machine-lassen.err` was empty
