### ISSUE TITLE
What is the dimension order of the Grid for the Struct Interface?

### ISSUE THREAD

**Issue by GhislainViguier** [hypre-space/hypre#712]
Hello,
I try to understand how the Structured Interface works.
In [ex1.c](https://github.com/hypre-space/hypre/blob/71cdcc89f75853fac7d39673324a333c5f5822a4/src/examples/ex1.c) example, there is a 2D grid with 6 cells (2 rows and 3 columns) for the first process : 
https://github.com/hypre-space/hypre/blob/71cdcc89f75853fac7d39673324a333c5f5822a4/src/examples/ex1.c#L118-L123

Then we define the Struct Matrix with a linear index :
https://github.com/hypre-space/hypre/blob/71cdcc89f75853fac7d39673324a333c5f5822a4/src/examples/ex1.c#L179-L187

To which cell would the linear index `int idx = i / nentries;` correspond in the 2D grid? What's the fast dimension?

**Comment by GhislainViguier** [comment]
I think grid is row-major order.

**Comment by GhislainViguier** [comment]
I think grid is row-major order.

**Comment by rfalgout** [comment]
Hi @GhislainViguier .  See the reference manual for the ordering of the data:

https://hypre.readthedocs.io/en/latest/api-int-struct.html#:~:text=HYPRE_Int%20HYPRE_StructMatrixSetBoxValues(,%2B%2B%3B%0A%20%20%20%20%20%20%20%20%20%7D

Hope this helps!

**Comment by GhislainViguier** [comment]
> Hi @GhislainViguier . See the reference manual for the ordering of the data:
> 
> https://hypre.readthedocs.io/en/latest/api-int-struct.html#:~:text=HYPRE_Int%20HYPRE_StructMatrixSetBoxValues(,%2B%2B%3B%0A%20%20%20%20%20%20%20%20%20%7D
> 
> Hope this helps!

Yes, thank you.
