### ISSUE TITLE
Question about block matrix vector multiplication

### ISSUE THREAD

**Issue by akshay9594** [hypre-space/hypre#715]
The main computational loop nest under "hypre_CSRBlockMatrixMatvecT( )" within csr_block_matvec.c has been manually parallelized. I am struggling to understand how the outermost i-loop is parallelizable. Array "A_j[ ]" has repeating values.

I am using the IJ interface. Running the test - ./ij -interptype 22

Are there other parameter values I should be setting or any other interface i need to use?

**Comment by victorapm** [comment]
@akshay9594, there's a race condition in that code when OpenMP is turned on. I'll work on the fix, thanks for pointing it out.

> Are there other parameter values I should be setting or any other interface i need to use?

Can you say more about the linear system you are trying to solve?

**Comment by akshay9594** [comment]
Thanks for the acknowledgement. I am just analyzing the kernels for subscripted subscript patterns - a[b[i]] with a possible true or output dependence. If such loops have been manually parallelized, I am trying to understand why.
