### ISSUE TITLE
New hypre release 2.26.0

### ISSUE THREAD

**Issue by liruipeng** [hypre-space/hypre#749]
Hello @hypre-space/developers ,

We are doing a new hypre release, so please hold off on making changes to the master branch until it is done.

Thanks!

-Rui Peng

**Comment by liruipeng** [comment]
- [ ] [MAJOR] Initial documentation review meeting.
- [ ] [MAJOR.MINOR] Update user and reference manuals.
- [ ] [MAJOR] Final documentation review meeting.
- [x] Update `CHANGELOG` file with information regarding contents of this release.
- [x] Verify that all agreed-upon changes have been committed.
- [x] Update `config/version.sh` with release number and date, then run `config/update.sh` and commit changes to the repository.
- [x] Check that the regression tests all run cleanly
  - [x] machine-tux
  - [x] machine-tux-spack
  - [x] machine-rztopaz
  - [x] machine-syrah
  - [x] machine-lassen
  - [ ] machine-vs-pro (not able to test)
- [x] Tag repository with release number: `git tag -a v2.26.0 -m "Release v2.26.0"` and push the tags to the central repository: `git push --tags`
- [x] On the CASC cluster, copy the GitHub release tar file to `/usr/casc/hypre`.
- [x] On the RZ, copy the GitHub tar file to `/usr/gapps/hypre` (for backup reasons).
- [x] Update Spack Package and create Spack pull request.
- [x] Close the new release GitHub issue.

**Comment by rfalgout** [comment]
Hi @liruipeng .  Let me know when the code is tagged and ready to be tested so I can help out with RZ.  If you do it soon, I can launch it tonight and you'll also get tux and tux-spack results from the standard regression testing.  Thanks!

**Comment by liruipeng** [comment]
> Hi @liruipeng . Let me know when the code is tagged and ready to be tested so I can help out with RZ. If you do it soon, I can launch it tonight and you'll also get tux and tux-spack results from the standard regression testing. Thanks!

Hi Rob, the code is ready to be tested on RZ. Can you please do it? I will probably `git tag` after the regression boxes are checked. Thanks!

**Comment by rfalgout** [comment]
Hi @liruipeng .  I have started the rztopaz tests.  The results should show up in tomorrow's regression test email.

**Comment by liruipeng** [comment]
> Hi @liruipeng . I have started the rztopaz tests. The results should show up in tomorrow's regression test email.

Thank you @rfalgout

**Comment by rfalgout** [comment]
> Hi @liruipeng . I have started the rztopaz tests. The results should show up in tomorrow's regression test email.

FYI, I messed up the rztopaz runs somehow, so I have started them up again.  Turns out they were scheduled to run last night anyway and I shouldn't have done anything.  Anyway, I'll let you know when they are done.

**Comment by liruipeng** [comment]
@rfalgout How about `machine-syrah`? It passed on 10/12. Shall we test again? Thanks!

**Comment by rfalgout** [comment]
> @rfalgout How about `machine-syrah`? It passed on 10/12. Shall we test again? Thanks!

Oh, I forgot that you needed help on that one too.  I'll start it up.  The rztopaz runs are still going, but slowly. :(

**Comment by rfalgout** [comment]
Syrah is clean.  Rztopaz is still running, but so far so good.

**Comment by rfalgout** [comment]
Rztopaz is finished and clean.  We should see the reports for both syrah and rztopaz in the morning email.

**Comment by liruipeng** [comment]
the code has been tagged and pushed

**Comment by liruipeng** [comment]
The Spack PR was created https://github.com/spack/spack/pull/33299

**Comment by liruipeng** [comment]
Hi @rfalgout Can you help do `On the RZ, copy the GitHub tar file to /usr/gapps/hypre (for backup reasons).`? Once it's done, I think we can close the release issue. Thanks!

**Comment by rfalgout** [comment]
> Hi @rfalgout Can you help do `On the RZ, copy the GitHub tar file to /usr/gapps/hypre (for backup reasons).`? Once it's done, I think we can close the release issue. Thanks!

Hi @liruipeng .  All copied.  Would you also change the permissions on the file you copied to /usr/casc/hypre by running `chmod 664 hypre-2.26.0.tar.gz`?  Thanks!

**Comment by liruipeng** [comment]
> > Hi @rfalgout Can you help do `On the RZ, copy the GitHub tar file to /usr/gapps/hypre (for backup reasons).`? Once it's done, I think we can close the release issue. Thanks!
> 
> Hi @liruipeng . All copied. Would you also change the permissions on the file you copied to /usr/casc/hypre by running `chmod 664 hypre-2.26.0.tar.gz`? Thanks!

Yes, the permission of the file has been changed.
