### ISSUE TITLE
hypre_CSRMatrixToParCSRMatrix(...) some problem

### ISSUE THREAD

**Issue by GSRLW** [hypre-space/hypre#76]
Fatal error in PMPI_Type_create_struct: invalid argument ,error stack:
      PMPI_Type_create_struct(185):MPI_Type_create_struct(count=3 ,array_of_blocklengths=0x10c94f0,array_of_displacements=0x7ffc88c1f730,array_of_types=0x7ffc88c1f700,newtype=0x10a6794) failed

      PMPI_Type_create_struct(148): Invalid value for blocken ,must be non-negative but is -449

**Comment by ulrikeyang** [comment]
Do you have some more information on what you were doing when you got this message?

**Comment by GSRLW** [comment]
I use :
    HYPRE_ParCSRMatrix parcsr_A;
    hypre_hypre_CSRMatrix * csr_A = CSRMatrixRead("./matrixfile");
    HYPRE_BigInt * row_starts = NULL;
    parcsr_A = hypre_CSRMatrixToParCSRMatrix( MPI_CoOMM_WORLD ,csr_A ,row_starts ,col_starts );

then get this problem.

**Comment by GSRLW** [comment]
when i install hypre 2.18.2 , i changed it to 64bit version by
./configure --with-MPI --with-openmp --enable-bigint
then i found this problem .
maybe different size of index cause the crash in MPI...

**Comment by ulrikeyang** [comment]
There are various typos in the code you posted yesterday. I assume you don't have those in your actual code, do you? ( typos: hypre_hypre_CSRMatrix, MPI_CoOMM_WORLD )
Does it work for you when you use the default version?

**Comment by ulrikeyang** [comment]
You can build it by configuring with –enable-bigint as you apparently did. Does your code run if you configure without –enable-bigint?

**Comment by GSRLW** [comment]
... I really tried hypre 32bit version and 64 bit version ,both get same crash ( happend  in same func )...
I feel so sad...

**Comment by GSRLW** [comment]
I changed my strategy to skip this .
when I get a matrix ,I get its data .
 then I fill it to IJMATRIX by my hand ( by  HYPRE_IJMatrixSetValues() ) .
 then get ParCSRMatrix object from IJMatrix . 
finally i got it ....
