### ISSUE TITLE
Hypre, Umpire and hipMemGetInfo

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#777]
Hi All,
I'm using Hypre with Umpire enabled for AMD GPUs (rocm 5.1.0). In my application, I query the amount of free memory available with hipMemGetInfo after key steps (matrix creation, vector creation, preconditioner setup, ...). The results of these calls when not using Umpire are:

Before BuildMatrix : rank 0 of 8, free memory=63.98 GB, total memory=63.98 GB
Before hypre_CSRMatrixGpuRawSpMVAnalysis : rank 0 of 8, free memory=55.32 GB, total memory=63.98 GB
Before RHS IJVectorCreate : rank 0 of 8, free memory=54.90 GB, total memory=63.98 GB
After Preconditioner Setup : rank 0 of 8, free memory=43.68 GB, total memory=63.98 GB

This seems reasonable to me given the size of the problem. Once I build with Hypre with Umpire and a 4GB Device Memory Pool, I see:

Before BuildMatrix : rank 0 of 8, free memory=63.98 GB, total memory=63.98 GB
Before hypre_CSRMatrixGpuRawSpMVAnalysis : rank 0 of 8, free memory=.8517 GB, total memory=63.98 GB
Before RHS IJVectorCreate : rank 0 of 8, free memory=.8517 GB, total memory=63.98 GB
After Preconditioner Setup : rank 0 of 8, free memory=17.73 GB, total memory=63.98 GB

My question is, should I expect hipMemGetInfo to work properly when using device memory pools?
Thanks
-Paul

**Comment by PaulMullowney** [comment]
Anyone have any insight on this?

As a follow up, should I expect device memory pools larger than 4GB to work?

**Comment by victorapm** [comment]
Hi Paul, sorry for the delay. I was working on a similar topic and just noticed your issue.

> should I expect hipMemGetInfo to work properly when using device memory pools?

Yes, the free memory reported by `hipMemGetInfo` accounts for the umpire memory pool used by hypre

> should I expect device memory pools larger than 4GB to work?

Yes, you can change the device memory pool size via `HYPRE_SetUmpireDevicePoolSize`, which accepts values in bytes. Documentation has been added here: https://github.com/hypre-space/hypre/blob/15c63abb4eb1dfe03f66071ef353515729998cfa/src/utilities/HYPRE_utilities.h#L370-L404
