### ISSUE TITLE
fix hypre build with CUDA12

### ISSUE THREAD

**Issue by liruipeng** [hypre-space/hypre#795]
WIP.

**Comment by jedbrown** [comment]
Is this likely to be fixed in the next week? PETSc's cuda-12 support will merge for the upcoming release and many people `--download-hypre` with their PETSc so we need to either notify the user that cuda-12 won't work or point at a version that does work.

**Comment by liruipeng** [comment]
> Is this likely to be fixed in the next week? PETSc's cuda-12 support will merge for the upcoming release and many people `--download-hypre` with their PETSc so we need to either notify the user that cuda-12 won't work or point at a version that does work.

We are still working on this. hypre builds with CUDA 12 now, but has issues with the cusparseSpSV API (wrong results). This may take a while to appear in the master branch. Sorry.

**Comment by jczhang07** [comment]
@liruipeng Check if you do `cusparseSpSV_analysis()` in the numeric phase of factorization.  That was a gotcha I met before. The name looks like a symbolic routine, but in reality it needs latest matrix values.
