### ISSUE TITLE
Issue with configure

### ISSUE THREAD

**Issue by mrauseo** [hypre-space/hypre#8]
Hi
I'm encountering the following issue when I run configure in the src folder:

checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for mpxlc... no
checking for mpixlc... no
checking for mpiicc... mpiicc
checking for mpxlC... no
checking for mpixlcxx... no
checking for mpixlC... no
checking for mpiicpc... mpiicpc
checking for mpxlf... no
checking for mpixlf77... no
checking for mpiifort... mpiifort
checking whether make sets $(MAKE)... yes
checking for ranlib... ranlib
checking whether the C compiler works... no
configure: error: in `/****/****/hypre/src':
configure: error: C compiler cannot create executables
See `config.log' for more details

I'm wondering if all the mp compilers are needed or I have to comment some of them out?
I'm fairly new to complex codes so I can't really figure this out by myself for now and I'd really appreciate some help
Thank you

**Comment by rfalgout** [comment]
If you want to run with MPI, make sure you have an MPI C compiler (e.g., mpicc) in your path.  If you want to run in serial without MPI, make sure you have a serial C compiler (e.g., gcc) in your path and run 'configure --without-MPI'.  Hope this helps!

**Comment by mrauseo** [comment]
I managed to compile for serial run, but unfortunately even though I have intel module loaded (hence mpicc, mpiifort) it won't compile for parallel.
Thank you very much for your quick answer. Serial will do just fine for me to understand how the code works
