### ISSUE TITLE
CUDA API differences?

### ISSUE THREAD

**Issue by ian-bertolacci** [hypre-space/hypre#81]
We are experimentally exploring the use of the CUDA enabled version of Hypre in an application already using it.

Because there is no documentation readily available (#69), we are not sure what (if any) API changes have been made, and (if so) what changes we need make on our end to use it.

Is that something someone can help us with?
Thanks.

**Comment by rfalgout** [comment]
We have added some documentation for using GPUs and improved our GPU code overall. Hopefully that helps. Thanks!
