### ISSUE TITLE
Potential Bug in Vector Device Assembly

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#813]
This looks wrong to me. The entry on line L250 should not have +N0. I don't understand how this could work.

https://github.com/hypre-space/hypre/blob/master/src/IJ_mv/IJVector_parcsr_device.c#L249
https://github.com/hypre-space/hypre/blob/master/src/IJ_mv/IJVector_parcsr_device.c#L250

**Comment by PaulMullowney** [comment]
Nvermind. I think the code is correct.

**Comment by victorapm** [comment]
Yes, that's a reverse iterator
