### ISSUE TITLE
HYPRE_SStructStencilSetEntry on Fortran

### ISSUE THREAD

**Issue by simonedigiorgio1412208** [hypre-space/hypre#818]
Hi,
I am trying to switch from Struct framework to SStruct, but I am encountering the following error with this function :
...
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

    allocate(offsets(ndim,nstencil), stat=ierr) ! define the geometry of the stencil
    offsets(:,1) = (/ 0, 0, 0/)
    offsets(:,2) = (/-1, 0, 0, 0/)
    offsets(:,3) = (/ 1, 0, 0/)
    offsets(:,4) = (/ 0,-1, 0/)
    offsets(:,5) = (/ 0, 1, 0/)
    offsets(:,6) = (/ 0, 0,-1/)
    offsets(:,7) = (/ 0, 0, 1/)
    do i = 1, nstencil
      call HYPRE_SStructStencilSetEntry(stencil, i-1, offsets(1,i),var, ierr)
    enddo
....
I don't understand what I should enter in offsets whether a scalar or a vector, the examples in C or Fortran look different to me 
(ex6.c and ex12f.f),  however in both cases it returns me the same error.

thanks for the help

Simone

**Comment by rfalgout** [comment]
Hi Simone,

How does this code compare to your Struct code (which presumably works)?  The only thing I see that seems wrong is the second offset array which has 4 entries.

-Rob

**Comment by simonedigiorgio1412208** [comment]
Hi Rob,

Thank you for the help,
 I wrong to paste in this forum there aren't the 4 entries,

the struct version is:

   allocate(offsets(ndim,nstencil), stat=ierr) ! define the geometry of the stencil
    offsets(:,1) = (/ 0, 0, 0/)
    offsets(:,2) = (/-1, 0, 0/)
    offsets(:,3) = (/ 1, 0, 0/)
    offsets(:,4) = (/ 0,-1, 0/)
    offsets(:,5) = (/ 0, 1, 0/)
    offsets(:,6) = (/ 0, 0,-1/)
    offsets(:,7) = (/ 0, 0, 1/)
    do i = 1, nstencil
      stencil_indices(i) = i-1
      call HYPRE_StructStencilSetElement(stencil, stencil_indices(i), offsets(:,i), ierr)
    enddo

and this work, but I use this function :StructStencilSetElement.
In this case i put the vector in the third entry of the function.

Simone

**Comment by rfalgout** [comment]
I don't see anything wrong with this.  The `SStruct` call should look exactly like the `Struct` call except for the function name and the extra `var` argument.  What does the rest of your `SStructStencil` code look like?

**Comment by simonedigiorgio1412208** [comment]
I report some parts of the code,
I have some doubts about the variable type declaration (HYPRE_SSTRUCT_VARIABLE_CELL)
[subroutine.zip](https://github.com/hypre-space/hypre/files/10403519/subroutine.zip)

!========================================
....
  integer :: nstencil
  integer :: object_type, vartypes(1), ent
  integer :: nparts,nvars,part,var
  integer    HYPRE_SSTRUCT_VARIABLE_CELL
  parameter( HYPRE_SSTRUCT_VARIABLE_CELL = 1 )

  integer (kind = 8) :: grid_obj, stencil, Amat, Bvec, Xvec, solver, precond
  integer (kind = 8) :: graph_obj, sA, sb, sx

    nparts = 1
    nvars =  1
    part =   0
    var =    0
....

    call HYPRE_SStructGridCreate(mpi_comm_poi, ndim, nparts, grid_obj, ierr)    ! create a 3d grid object
    call HYPRE_SStructGridSetExtents(grid_obj,part, ilower, iupper, ierr)    ! add a box to the grid
    call HYPRE_SStructGridSetPeriodic(grid_obj,part, periodic_array, ierr)   ! set periodic
    vartypes(1) = HYPRE_SSTRUCT_VARIABLE_CELL
    call HYPRE_SStructGridSetVariables(grid_obj, part, nvars, vartypes, ierr)
    call HYPRE_SStructGridAssemble(grid_obj, ierr)                      ! assemble the grid
    call HYPRE_StructStencilCreate(ndim, nstencil, stencil, ierr)      ! create a 3d 7-pt stencil

    allocate(offsets(ndim,nstencil), stat=ierr) ! define the geometry of the stencil
    offsets(:,1) = (/ 0, 0, 0/)
    offsets(:,2) = (/-1, 0, 0/)
    offsets(:,3) = (/ 1, 0, 0/)
    offsets(:,4) = (/ 0,-1, 0/)
    offsets(:,5) = (/ 0, 1, 0/)
    offsets(:,6) = (/ 0, 0,-1/)
    offsets(:,7) = (/ 0, 0, 1/)
    do i = 1, nstencil
      call HYPRE_SStructStencilSetEntry(stencil, i-1, offsets(1,i),var, ierr)
    enddo
!
......
!=================================================

**Comment by simonedigiorgio1412208** [comment]
I solved the problem I had a "Struct" instead "SStruct" in one of the previous calls, sorry for the disturb and 
thanks so much for the help.

I still don't quite understand how the vartype works, so far I don't assign it and it seems to work.
Thanks again.

**Comment by rfalgout** [comment]
Excellent.  I'm glad you found the problem.

Regarding the vartype, since you are using a cell-centered type (which is equivalent to what `Struct` does), you should have your parameter statement set `HYPRE_SSTRUCT_VARIABLE_CELL` to `0`.  The hypre code should set these values for you, but we unfortunately don't do that currently in the Fortran interface.  To see what the values should be, you can look at the header file `sstruct_mv/HYPRE_sstruct_mv.h`.  Hope this helps!

**Comment by simonedigiorgio1412208** [comment]
Thank you, 

I test in Fortran,  works either by assigning nothing (default value) or by assigning 0
