### ISSUE TITLE
Building error with MinGW64

### ISSUE THREAD

**Issue by EvgeniyMist** [hypre-space/hypre#823]
Hello!

I am having problem with building this library on Windows 10 system with MinGW64.
Here is some information about my system:
```
gfortran --version
GNU Fortran (Rev1, Built by MSYS2 project) 12.2.0
```
```
make --version
GNU Make 4.3
Built for Windows32
```

I configure the project with this options:
```./configure --without-MPI --with-openmp --enable-fortran FC=gfortran ```
Then I execute the ```make``` command and after compiling a lot of things I get the error:
```
Making lib ...
make[1]: Entering directory 'C:/Users/User/Documents/Evgenii/hypre-master/src/lib'
make[1]: *** No rule to make target '/c/Users/User/Documents/Evgenii/hypre-master/src/IJ_mv/*.o', needed by 'libHYPRE.a'.  Stop.
make[1]: Leaving directory 'C:/Users/User/Documents/Evgenii/hypre-master/src/lib'
make: *** [Makefile:86: all] Error 1
```
I have tried  this order on two different PC and get the same behavior.
And on my Linux system everything is fine, so i don't understand what's the problem...

**Comment by rfalgout** [comment]
Hi @EvgeniyMist .  What are the compilers chosen by `configure` (you can look in `src/config/Makefile.config` to see what they are)?  Also, are there any '.o' files in the `src/IJ_mv` directory?  Thanks!

**Comment by EvgeniyMist** [comment]
> Hi @EvgeniyMist . What are the compilers chosen by `configure` (you can look in `src/config/Makefile.config` to see what they are)? Also, are there any '.o' files in the `src/IJ_mv` directory? Thanks!

There is such information about compilers in `src/config/Makefile.config`:
```
FC        = gfortran
FFLAGS    = -O2 -fopenmp -g -O2 $(FC_COMPILE_FLAGS)

CC        = gcc
CFLAGS    = -O2 -fopenmp  -DHAVE_CONFIG_H $(C_COMPILE_FLAGS)

CXX       = g++
CXXFLAGS  = -O2 -fopenmp  -DHAVE_CONFIG_H $(CXX_COMPILE_FLAGS)
```
As for your second question, yes. In `src/IJ_mv` directory there is `.o` file for each `.c` file.
I also want to note that there are some messages from the `ar` command during the build of `.a` libraries:
`ar: 'u' modifier ignored since 'D' is the default (see 'U')`

**Comment by rfalgout** [comment]
To figure this out, I'll probably need to see more details, including the files `src/config.log`, `src/config/Makefile.config`, and all of the output from your `make` command.  The problem could be the `ar` command, but I would expect to see that before the "No rule to make target" line or not at all.

An alternative that may work is to use `cmake` to build the library.  You would have to install cmake on your system, but that's straightforward.  Then look at the `INSTALLmd` file for pointers on how to use it.

**Comment by EvgeniyMist** [comment]
Here are the files:
[config.log](https://github.com/hypre-space/hypre/files/10457607/config.log)
[Makefile_config.txt](https://github.com/hypre-space/hypre/files/10457628/Makefile_config.txt)
[make_out.txt](https://github.com/hypre-space/hypre/files/10457639/make_out.txt)

For now I will try with the `cmake`

**Comment by rfalgout** [comment]
Okay, this looks like some subtle issue with `make` and possibly the shell.  I think the following might work, though it's a hack.  Manually edit the file `src/lib/Makefile` and just below the "Rules" section on the line that starts with `libHYPRE.a:`, delete `${FILES_HYPRE}`.  Then try `make` again from the `src` directory.

**Comment by EvgeniyMist** [comment]
Thank you very much, now everything is building!

But now I have two more questions...
First question is related with building the library with the `ifort` compiler on Windows system. Due to certain features of this compiler on this system, I could not build in a similar way (I launched `MinGW64` shell from `intel ONE API` command propmt for setting the necessary environment). Have you had any such attempts?. It is worth noting that on Linux there are no problems.
In order to understand the library a little, I decided to write a small program for solving an easy system of two equations. But in the end, I get error 256, indicating that convergence was not achieved. The whole problem is in the chosen solver (I just took the first one that came across from `ex5f.f`) or is it still in the program?
```
      program test

      implicit none

      include 'HYPREf.h'

      integer :: ierr
      integer :: ilower, iupper, i
      integer :: num_iterations
      double precision :: final_res_norm

      integer*8 :: parcsr_A
      integer*8 :: A
      integer*8 :: b
      integer*8 :: x
      integer*8 :: par_b
      integer*8 :: par_x
      integer*8 :: solver
      integer*8 :: precond

      call HYPRE_Init(ierr)
      call HYPRE_SetMemoryLocation(HYPRE_MEMORY_DEVICE, ierr)
      call HYPRE_SetExecutionPolicy(HYPRE_EXEC_DEVICE, ierr)
      call HYPRE_SetSpGemmUseVendor(0, ierr)

      ilower = 0
      iupper = 1

!     MATRIX
      call HYPRE_IJMatrixCreate(0, ilower, iupper, ilower, iupper, A, ierr)
      call HYPRE_IJMatrixSetObjectType(A, HYPRE_PARCSR, ierr)
      call HYPRE_IJMatrixInitialize(A, ierr)
      call HYPRE_IJMatrixSetValues(A, 1, 2, 0, [0, 1], [1.0d0,  1.0d0], ierr)
      call HYPRE_IJMatrixSetValues(A, 1, 2, 1, [0, 1], [1.0d0, -1.0d0], ierr)
      call HYPRE_IJMatrixAssemble(A, ierr)
      call HYPRE_IJMatrixGetObject(A, parcsr_A, ierr)
      !call HYPRE_IJMatrixPrint(A, 'try.out', ierr)

!     RIGHT VECTOR
      call HYPRE_IJVectorCreate(0, ilower, iupper, b, ierr)
      call HYPRE_IJVectorSetObjectType(b, HYPRE_PARCSR, ierr)
      call HYPRE_IJVectorInitialize(b, ierr)
      call HYPRE_IJVectorSetValues(b, 2, [0, 1], [2.0d0, 0.0d0], ierr)
      call HYPRE_IJVectorAssemble(b, ierr)
      call HYPRE_IJVectorGetObject(b, par_b, ierr)
      !call HYPRE_IJVectorPrint(b, 'try.out', ierr)

!     VARIABLE VECTOR
      call HYPRE_IJVectorCreate(0, ilower, iupper, x, ierr)
      call HYPRE_IJVectorSetObjectType(x, HYPRE_PARCSR, ierr)
      call HYPRE_IJVectorInitialize(x, ierr)
      call HYPRE_IJVectorSetValues(x, 2, [0, 1], [10.0d0, 10.0d0], ierr)
      call HYPRE_IJVectorAssemble(x, ierr)
      call HYPRE_IJVectorGetObject(x, par_x, ierr)
      !call HYPRE_IJVectorPrint(x, 'try.out', ierr)

      print *, 'After initialization', ierr

!     SOLVER
      call HYPRE_BoomerAMGCreate(solver, ierr)


!     Set some parameters (See Reference Manual for more parameters)

!     print solve info + parameters
      call HYPRE_BoomerAMGSetPrintLevel(solver, 3, ierr)
!     old defaults, Falgout coarsening, mod. class. interpolation
      call HYPRE_BoomerAMGSetOldDefault(solver, ierr)
!     G-S/Jacobi hybrid relaxation
      call HYPRE_BoomerAMGSetRelaxType(solver, 3, ierr)
!     C/F relaxation
      call HYPRE_BoomerAMGSetRelaxOrder(solver, 1, ierr)
!     Sweeeps on each level
      call HYPRE_BoomerAMGSetNumSweeps(solver, 1, ierr)
!     maximum number of levels
      call HYPRE_BoomerAMGSetMaxLevels(solver, 20, ierr)
!     conv. tolerance
      call HYPRE_BoomerAMGSetTol(solver, 1.0d-7, ierr)
!     Keep local transposes
      call HYPRE_BoomerAMGSetKeepTransp(solver, 1, ierr)

!     Now setup and solve!
      call HYPRE_BoomerAMGSetup(solver, parcsr_A, par_b, par_x, ierr)
      print *, 'After setup', ierr
      call HYPRE_BoomerAMGSolve(solver, parcsr_A, par_b, par_x, ierr)
      print *, 'After solving', ierr

!     Run info - needed logging turned on
      call HYPRE_BoomerAMGGetNumIterations(solver, num_iterations,ierr)
      call HYPRE_BoomerAMGGetFinalReltvRes(solver, final_res_norm,ierr)

      print *
      print *, 'Iterations = ', num_iterations
      print *, 'Final Relative Residual Norm = ', final_res_norm
      print *
      call HYPRE_IJVectorPrint(x, 'try.out', ierr)

!     Destroy solver
      call HYPRE_BoomerAMGDestroy(solver, ierr)

      end program test
```

**Comment by rfalgout** [comment]
Great to hear things are compiling now!  Did you use cmake or the "hack" I suggested?  Just curious.

Regarding your questions:
1. Can you be more specific about the issue you are having with `ifort`?  The hypre library doesn't actually require a fortran compiler.  Only a few example codes are in fortran.  So, for fortran users, the main issue is getting the name mangling set correctly to link successfully to hypre.  Are you having trouble linking?
2. The system in your example code is not positive definite (you have a 1 and a -1 on the diagonal).  The BoomerAMG solver is designed with symmetric positive definite systems in mind, so either change the system to something like [2, -1; -1, 2] or try the GMRES solver.

Hope this helps!

**Comment by EvgeniyMist** [comment]
Sorry for the long answer.

Regarding building - I used your hack.

Regarding linking - with `gfortran` compiler I use this command (from root repository directory) for building my application:
`gfortran try.f90 -fopenmp -I src/hypre/include -L src/hypre/lib -lHYPRE`
And everything works correctly. And with `ifort` compiler I am trying to use this command:
`ifort try.f90 /Qopenmp /I:"src\hypre\include" "src\hypre\lib\libHYPRE.a"`
But I am getting the linking error:
```
try.obj : error LNK2019: unresolved external symbol HYPRE_INIT referenced in function MAIN__.
...
try.exe : fatal error LNK1120: 25 unresolved externals
```

Thanks for the advice on choosing a solver. I should devote more time to studying the documentation, namely the areas of application of the provided solvers.

**Comment by rfalgout** [comment]
Hi @EvgeniyMist .  It looks like you are having a name-mangling issue with the `ifort` compiler expecting to find names in all caps.  To fix this, add `--with-fmangle=caps-no-underscores` to your configure line, and rebuild the library (`make clean; make`).  Let me know if that works.  Thanks!

**Comment by EvgeniyMist** [comment]
Hi @rfalgout. Is it possible to add option`--with-fmangle=caps-no-underscores`, if I configure with the help of `cmake`?

**Comment by rfalgout** [comment]
> Hi @rfalgout. Is it possible to add option`--with-fmangle=caps-no-underscores`, if I configure with the help of `cmake`?

Well, one way to do it is to first run `cmake` like you normally do, then manually edit the `HYPRE_config.h` file and change `HYPRE_FMANGLE` to `4` before compiling.  There may be a smarter way to do this when running `cmake`, but I'll have to defer to @osborn9 on that one.  Hope this helps!

**Comment by EvgeniyMist** [comment]
Thank you very much for the great amount of help you provided!
Now everything works well.
It remains only to study the features of the provided solvers :)
