### ISSUE TITLE
Fortran include  file for call requiring SMGSolve and SMGSetup definitions

### ISSUE THREAD

**Issue by kellerdek** [hypre-space/hypre#828]
hypregrid_hypre_solver.f90(239): error #6404: This name does not have a type, and must have an explicit type.   [HYPRE_STRUCTSMGSOLVE]
      Call HYPRE_StructPCGSetPrecond(solver,HYPRE_StructSMGSolve, &
--------------------------------------------^
/g1/ssd/kellerd/aster_hyp/t1_16cp_new1_7steps/aster/src/radtrans/multigrid_hypre_solver.f90(240): error #6404: This name does not have a type, and must have an explicit type.   [HYPRE_STRUCTSMGSETUP]
         HYPRE_StructSMGSetup, precond)

I am trying to setup a preconditioner for a PCG solve.  Compiling with intel/2020.1 F90 compiler.   Using HYPRE 2.8.0b.
I cannot find a fortran include file to help satisfy these referances.

**Comment by victorapm** [comment]
Hi @kellerdek , I recommend using a newer hypre version. Also, the current function prototype for `HYPRE_StructPCGSetPrecond` looks a bit different, e.g.:
https://github.com/hypre-space/hypre/blob/b08a962924e2c446c7ccd2153a1bceb798a91ad7/src/examples/ex12f.f#L450

Note: 1 means the PFMG preconditioner, use 0 for SMG

**Comment by kellerdek** [comment]
Thanks!
