### ISSUE TITLE
hypre_structstencilcreate routine is inconsistent with header and F90 wrapper

### ISSUE THREAD

**Issue by johannjc** [hypre-space/hypre#839]
The hypre_structstencilcreate routine defined in struct_stencil.c has 3 arguments - the first two are HYPRE_INT's, but the third is a hypre_index instead of a HYPRE_StructStencil.  I believe hypre_index is 3 ints - or 12 bytes, while the hypre_structstencil is just an 8 byte integer.  This would explain the invalid writing to the 4 byte integer stored in memory following the hypre_structstencil.  

I noticed this by having a derived type containing

  type hypreStructStencil
     integer :: nEntries
     integer, allocatable, dimension(:,:) :: offsets
     integer(8) :: stencil
     integer :: nDim
  end type hypreStructStencil

and if I set the nDim=2 and nEntries=5 members of the derived type - and then call

CALL HYPRE_StructStencilCreate(stencil%nDim, stencil%nEntries, stencil%stencil, ierr)

the stencil%nDim is reset to 0...  The same thing happens when I use

CALL HYPRE_StructStencilCreate(2, stencil%nEntries, stencil%stencil, ierr)

But it works ok - if I re-order the components of hypreStructStencil so that the stencil pointer is at the end

  type hypreStructStencil
     integer :: nEntries
     integer, allocatable, dimension(:,:) :: offsets
     integer :: nDim
     integer(8) :: stencil
  end type hypreStructStencil

though I suspect there is still an invalid write occurring within HYPRE - it's just not breaking my toy program.

**Comment by rfalgout** [comment]
Hi @johannjc .  The function your fortran code is linking to is actually in `struct_mv/F90_HYPRE_struct_stencil.c` and calls the create function defined in `HYPRE_struct_stencil.c`.  In looking at the above, I think the issue may be that you are defining the `stencil` component of your derived type to be `integer(8)` instead of `integer*8`.  The first is an array of integers, right?  Anyway, that's my best guess.  Hope this helps!

**Comment by johannjc** [comment]
Hi @rfalgout, my understanding is that integer(8) is short for integer(kind=8) which is effectively the same as integer*8.  However, in trying to make a reproducer - I discovered an error that I had made...  I thought selected_int_kind(8) was also an 8 byte integer - but it was only 4 bytes... I'm still a little confused by the differences in the argument and parameter lists - but I can live with that...  Thanks for looking into this.
