### ISSUE TITLE
CUDA Error 700, Illegal Memory Access, for a trivial example using Struct interface

### ISSUE THREAD

**Issue by lprc** [hypre-space/hypre#845]
Hi,

after some hurdles I successfully compiled HYPRE using CMake enabling CUDA and linked it against a small test program which essentially just partly resembles [the struct interface example in the docs](https://hypre.readthedocs.io/en/latest/ch-struct.html), minimal working example (mwe) below.

However when executing the program it crashes with the message `CUDA ERROR (code = 700, an illegal memory access was encountered) at <path-to-hypre>/hypre/src/utilities/memory.c:508`.

When I comment out the call of `HYPRE_StructMatrixSetBoxValues` the program does not crash.

After seeing comments in e.g. example `ex1` like `/* double values[30]; OK to use constant-length arrays for CPUs */` I replaced all the static arrays with dynamic ones, hoping it would make any difference. It didn't.

The example program works fine when HYPRE is compiled without CUDA support.

I'm using CUDA 11.8.0 (with CUDA 12.0, HYPRE did not compile at all, even on the cuda12 branch) on MX Linux 21.3 (based on Debian 11). GPU is Quadro T2000, CMake configure arguments are:

```
-DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/openmpi
-DHYPRE_WITH_CUDA=ON
-DHYPRE_CUDA_SM=75
-DHYPRE_ENABLE_UNIFIED_MEMORY=ON
-DHYPRE_BUILD_EXAMPLES=ON
```

And the mwe example program:
<details>
<summary>MWE example program</summary>

```
#include "HYPRE_struct_ls.h"
#include "mpi.h"

int main(int argc, char *argv[])
{
    int myid, num_procs;

    /* Initialize MPI */
    MPI_Init(&argc, &argv);
    MPI_Comm_rank(MPI_COMM_WORLD, &myid);
    MPI_Comm_size(MPI_COMM_WORLD, &num_procs);

    /* Initialize HYPRE */
    HYPRE_Init();

    HYPRE_StructGrid grid;
    int ndim = 2;
    int **ilower = (int **)calloc(2, sizeof(int *));
    int **iupper = (int **)calloc(2, sizeof(int *));
    ilower[0] = (int *)calloc(2, sizeof(int));
    ilower[1] = (int *)calloc(2, sizeof(int));
    iupper[0] = (int *)calloc(2, sizeof(int));
    iupper[1] = (int *)calloc(2, sizeof(int));

    // int ilower[2][2] = {{-3, 1}, {0, 1}};
    // int iupper[2][2] = {{-1, 2}, {2, 4}};

    /* Create the grid object */
    HYPRE_StructGridCreate(MPI_COMM_WORLD, ndim, &grid);

    /* Set grid extents for the first box */
    HYPRE_StructGridSetExtents(grid, ilower[0], iupper[0]);

    /* Set grid extents for the second box */
    HYPRE_StructGridSetExtents(grid, ilower[1], iupper[1]);

    /* Assemble the grid */
    HYPRE_StructGridAssemble(grid);

    HYPRE_StructStencil stencil;
    // int ndim = 2;
    int size = 5;
    int entry;
    int **offsets = (int **)calloc(5, sizeof(int *));
    for (int i = 0; i < size; i++)
        offsets[i] = (int *)calloc(2, sizeof(int));

    offsets[0][0] = 0;
    offsets[0][1] = 0;
    offsets[1][0] = -1;
    offsets[1][1] = 0;
    offsets[2][0] = 1;
    offsets[2][1] = 0;
    offsets[3][0] = 0;
    offsets[3][1] = -1;
    offsets[4][0] = 0;
    offsets[4][1] = 1;
    // int offsets[5][2] = {{0, 0}, {-1, 0}, {1, 0}, {0, -1}, {0, 1}};

    /* Create the stencil object */
    HYPRE_StructStencilCreate(ndim, size, &stencil);

    /* Set stencil entries */
    for (entry = 0; entry < size; entry++)
    {
        HYPRE_StructStencilSetElement(stencil, entry, offsets[entry]);
    }

    /* Thats it!  There is no assemble routine */

    HYPRE_StructMatrix A;
    // double values[36];
    double *values = (double *)calloc(36, sizeof(double));
    // int stencil_indices[2] = {0, 3};
    int *stencil_indices = (int *)calloc(2, sizeof(int));
    stencil_indices[0] = 0;
    stencil_indices[0] = 3;
    int i;

    HYPRE_StructMatrixCreate(MPI_COMM_WORLD, grid, stencil, &A);
    HYPRE_StructMatrixInitialize(A);

    for (i = 0; i < 36; i += 2)
    {
        values[i] = 4.0;
        values[i + 1] = -1.0;
    }

    // If this is commented out the programs finishes without errors.
    HYPRE_StructMatrixSetBoxValues(A, ilower[0], iupper[0], 2,
                                   stencil_indices, values);
    HYPRE_StructMatrixSetBoxValues(A, ilower[1], iupper[1], 2,
                                   stencil_indices, values);

    /* set boundary conditions */
    // not done here

    HYPRE_StructMatrixAssemble(A);

    // HYPRE_StructVector b;
    // double values_b[18];
    // // int i;

    // HYPRE_StructVectorCreate(MPI_COMM_WORLD, grid, &b);
    // HYPRE_StructVectorInitialize(b);

    // for (i = 0; i < 18; i++)
    // {
    //     values_b[i] = 0.0;
    // }

    // HYPRE_StructVectorSetBoxValues(b, ilower[0], iupper[0], values_b);
    // HYPRE_StructVectorSetBoxValues(b, ilower[1], iupper[1], values_b);

    // HYPRE_StructVectorAssemble(b);

    /* Free memory */
    HYPRE_StructGridDestroy(grid);
    HYPRE_StructStencilDestroy(stencil);
    HYPRE_StructMatrixDestroy(A);
    // HYPRE_StructVectorDestroy(b);

    free(values);
    free(stencil_indices);
    free(ilower[0]);
    free(ilower[1]);
    free(ilower);
    free(iupper[0]);
    free(iupper[1]);
    free(iupper);

    for (int i = 0; i < size; i++)
        free(offsets[i]);

    free(offsets);

    /* Finalize Hypre */
    HYPRE_Finalize();

    /* Finalize MPI */
    MPI_Finalize();

    return 0;
}

```
</details>

Did I misuse the API in some way? Apparently there is also already another issue (#787) reporting the same error message. Let me know if I can provide more information in any way.

**Comment by lprc** [comment]
By now I tried various states of the code, including the current master branch and a few commits tagged as release going all the way back to v2.21.0 (where CUDA support was added), getting always essentially the same error.

I also digged a bit into the code. At first one is pointed to the call of `HYPRE_StructMatrixDestroy` where the buffer is released but that does not seem to be the actual root of the problem. [The CUDA docs](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) regarding error 700 says `This leaves the process in an inconsistent state and any further CUDA work will return the same error.`.
By inserting calls to `hypre_SyncCudaDevice(NULL)` I tracked down the root to the following section of `hypre_StructMatrixSetBoxValues` line 853 ff:

```
else if (action > -1)
{
   hypre_BoxLoop2Begin(hypre_StructMatrixNDim(matrix), loop_size,
                       data_box, data_start, data_stride, datai,
                       dval_box, dval_start, dval_stride, dvali);
   {
      datap[datai] = values[dvali];
   }
   hypre_BoxLoop2End(datai, dvali);
}
```

I honestly don't fully understand what is going on the in detail with all the preprocessor magic but the corresponding kernel seems to be `forall_kernel` which is called by the function `BoxLoopforall`. Maybe `datap` or `values` is invalid or the indices accessing the former arrays extend their boundaries? This is however the point where I can't advance without investing too much time learning the code.

I didn't bother trying different driver versions of my GPU but I get the same behavior on my Laptop and on our GPU cluster which has A100's anyway.

**Comment by lprc** [comment]
Oh also I tried not using unified memory (`-DHYPRE_ENABLE_UNIFIED_MEMORY=OFF`) and setting the memory location and execution policy after `HYPRE_Init`:
```
HYPRE_Init();
HYPRE_SetMemoryLocation(HYPRE_MEMORY_DEVICE);
HYPRE_SetExecutionPolicy(HYPRE_EXEC_DEVICE);
// ...
```

**Comment by lprc** [comment]
Today I retested this issue, apparently it was solved with some commit, the above mwe now works. I also updated to Cuda 12, which was not possible at the time creating this issue.

**Comment by lprc** [comment]
Unfortunately, I have to reopen this issue as I now get the same error again. The examples yield the same error upon execution. Other CUDA-projects I can compile and run just fine. E.g.

```
$ mpirun -np 2 ex1
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/projects/hypre/src/utilities/memory.c:736
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/projects/hypre/src/utilities/memory.c:736
```

**Comment by liruipeng** [comment]
Hi @lprc I can work with you on this issue. You mentioned you tried without unified memory. Any luck with it? Is there something possible we can reproduce the error on our side, because the cause of the problem seems unclear. Thank you!

**Comment by liruipeng** [comment]
Sorry I missed the example you gave in Feb.. Can I just try to compile and run it? Thanks again.

**Comment by lprc** [comment]
Hi @liruipeng, thank you for investigating! I created [a repository](https://github.com/lprc/hypreCudaMwe/) with the mwe, that you can clone and compile. It should work out-of-the-box, there are compile instructions in the Readme.

I just retried running it with and without unified memory, both resulting in the same error message.

I don't know the cause of the problem either, since other CUDA programs run fine on my machine. If I can provide any kind of debug information that might help you, let me know.

I will try again on our cluster soon, too.

Edit:

Tests on our cluster yield the same results:

Using unified memory:
`CUDA ERROR (code = 700, an illegal memory access was encountered) at /beegfs/shoffmann/projects/hypre/src/utilities/memory.c:507`

Not using unified memory:
`CUDA ERROR (code = 700, an illegal memory access was encountered) at /beegfs/shoffmann/projects/hypre/src/utilities/memory.c:472`

**Comment by lprc** [comment]
@liruipeng Did you have the chance to take a look into the mwe repository?

Maybe you can tell me on which system it works for you, i.e. do you also use Cuda 12 on a current Linux version with current Nvidia drivers?

**Comment by liruipeng** [comment]
> @liruipeng Did you have the chance to take a look into the mwe repository?
> 
> Maybe you can tell me on which system it works for you, i.e. do you also use Cuda 12 on a current Linux version with current Nvidia drivers?

Hi @lprc It took me a while to figure out the compiler issues when building hypre with cmake and your mwe. I ran
```
li50@lassen16:~/workspace/tmp/hypreCudaMwe/buiild$ mpirun -n 1  ./testMweHypreCuda                                                                                                                                                 
li50@lassen16:~/workspace/tmp/hypreCudaMwe/buiild$ 
```
which seemed OK. I didn't get the error message. This was with CUDA 10.1 on V100 GPUs.

**Comment by liruipeng** [comment]
Hi @lprc I know why the issues happen now. You need to allocate GPU memory for `values`. See my fix at https://github.com/lprc/hypreCudaMwe/issues/1.

The catch is that in hypre's example we redefine `malloc/calloc` to `cudaMallocManaged`, see https://github.com/hypre-space/hypre/blob/master/src/examples/ex.h. I know this confusing to users. The purpose was to keep the example for GPUs as simple as the CPU code.

**Comment by lprc** [comment]
Hi @liruipeng Thank you for trying out the mwe! I'm sorry to hear you had problems compiling it.

I updated the mwe with your suggestions, but still, it does not work on my machine nor our cluster. However I set up an old Ubuntu 18.04 installation using Cuda 10.1, and with that the **mwe works indeed** (using `clang++-10`).

However, the examples that come with hypre do not work. For example running `ex1`:

```
simon@simon-Precision-5550:~/tmp/hypre/src/cmbuild$ mpirun -n 2 examples/ex1
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:153
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:680
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:153
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:680
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:658
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:328
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:658
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:328
[simon-Precision-5550:12109] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[simon-Precision-5550:12109] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

Or similiarly when running `ex2`:

```
simon@simon-Precision-5550:~/tmp/hypre/src/cmbuild/examples$ mpirun -n 2 ex2
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:153
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:680
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:153
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:680
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:658
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:328
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:658
CUDA ERROR (code = 700, an illegal memory access was encountered) at /home/simon/tmp/hypre/src/utilities/memory.c:328
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[simon-Precision-5550:12033] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[simon-Precision-5550:12033] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

Do you have the chance to try running the examples or the mwe using Cuda 11 or 12?

**Comment by liruipeng** [comment]
@lprc Something is wrong with our cmake in building `examples`. I'll work on that. Meanwhile, can you try our autoconf build? In `src`, run `./configure --with-cuda --enable-unified-memory --enable-debug`, and in `example`, type `make use_cuda=1`. Thanks!

**Comment by lprc** [comment]
@liruipeng I'm trying to get the autoconf build working. The configure step works fine, but running `make use_cuda=1` inside the `example` directory yields the linker error 

`/usr/bin/ld: cannot find -libmc++: Datei oder Verzeichnis nicht gefunden`

Sorry halve of the message is in German, but apparently I have no libmc++ installed on my system. I tried finding it in the apt sources and on the internet, but all the results I get are on different topics. I browsed the Hypre docs and source code, but again, was not able to find anything related to a mc++ library. I tried installing the apt package `libmcpp-dev` but with no appeal.

Can you please point out for me which library it is and where I can get it? Thanks!

**Comment by liruipeng** [comment]
> @liruipeng I'm trying to get the autoconf build working. The configure step works fine, but running `make use_cuda=1` inside the `example` directory yields the linker error
> 
> `/usr/bin/ld: cannot find -libmc++: Datei oder Verzeichnis nicht gefunden`
> 
> Sorry halve of the message is in German, but apparently I have no libmc++ installed on my system. I tried finding it in the apt sources and on the internet, but all the results I get are on different topics. I browsed the Hypre docs and source code, but again, was not able to find anything related to a mc++ library. I tried installing the apt package `libmcpp-dev` but with no appeal.
> 
> Can you please point out for me which library it is and where I can get it? Thanks!
You don't need those libraries. They are for IBM xl compilers. Just ignore them.

**Comment by lprc** [comment]
> You don't need those libraries. They are for IBM xl compilers. Just ignore them.

Okay, just removed it from the Makefile and the examples compile.

On Ubuntu 18.04 using Cuda 10.1 running ex1 and ex2 work just fine, no error:

```
simon@simon-Precision-5550:~/tmp/hypreautoconf/hypre/src/examples$ mpirun -n 2 ex1
<C*b,b>: 1.800000e+01


Iters       ||r||_C     conv.rate  ||r||_C/||b||_C
-----    ------------    ---------  ------------ 
    1    2.509980e+00    0.591608    5.916080e-01
    2    9.888265e-01    0.393958    2.330686e-01
    3    4.572262e-01    0.462393    1.077693e-01
    4    1.706474e-01    0.373223    4.022197e-02
    5    7.473022e-02    0.437922    1.761408e-02
    6    3.402624e-02    0.455321    8.020061e-03
    7    1.214929e-02    0.357057    2.863616e-03
    8    3.533113e-03    0.290808    8.327628e-04
    9    1.343893e-03    0.380371    3.167586e-04
   10    2.968745e-04    0.220906    6.997400e-05
   11    5.329671e-05    0.179526    1.256215e-05
   12    7.308483e-06    0.137128    1.722626e-06
   13    7.411552e-07    0.101410    1.746920e-07


simon@simon-Precision-5550:~/tmp/hypreautoconf/hypre/src/examples$ mpirun -n 2 ex2
<C*b,b>: 5.488337e+01


Iters       ||r||_C     conv.rate  ||r||_C/||b||_C
-----    ------------    ---------  ------------ 
    1    3.503257e-02    0.004729    4.728807e-03
    2    1.386843e-04    0.003959    1.872005e-05
    3    8.429961e-07    0.006079    1.137903e-07
```

On MX Linux 23 using Cuda 12.3 running ex1 and ex2 yield the following errors, which are essentially the same as running the examples using CMake and Cuda 10.1 on Ubuntu 18.04:

```
simon@mx-precision-5550:~/tmp/hypre/src/examples
$ mpirun -n 2 ex1
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:153
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:680
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:658
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:328
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:153
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:680
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:658
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:328
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[mx-precision-5550:11134] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[mx-precision-5550:11134] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

simon@mx-precision-5550:~/tmp/hypre/src/examples
$ mpirun -n 2 ex2
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:153
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:680
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:153
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:680
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:658
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:328
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:658
CUDA ERROR (code = 700, an illegal memory access was encountered) at memory.c:328
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[mx-precision-5550:11081] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[mx-precision-5550:11081] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

```

**Comment by lprc** [comment]
I've added two Docker build files to the mwe repo for creating images using Cuda 11 and Cuda 12 with hypre. If I run the examples ex1 and ex2 inside of those containers, I don't get any error, so I guess the problem does not stem from the updated Cuda version. I'll try to do the same with a real installation of another Linux distribution for different Cuda versions, this might take a while though.

**Comment by lprc** [comment]
I just did a clean install of hypre on my main system (MX 23) using Cuda 12 and autoconf. With that, the examples are running just fine, which is really confusing to me. But when building with CMake, neither the examples nor my mwe work. They do, however, when running inside one of the docker containers. 

Edit:

Running the mwe using CMake now works also on my main system using Cuda 12. After completely removing all the build directories and rebuilding everything, it now works. I'm not entirely sure why, maybe VS Code messed up the build directories. This would however not explain why I get the same error on our cluster, which is terminal-only. I'll do some testing there again, too.

Running the examples when building with CMake still does not work, but that's another issue, I guess.

**Comment by liruipeng** [comment]
@lprc Thank you for the updates. I guess hypre's examples are running fine now with autoconf and different CUDA versions (10.1, 11, 12, ...), which is good to know. We are looking into the CMake build now.

**Comment by lprc** [comment]
Yes, it works on our cluster, too. Thank you very much for your assistance, your bug fixes in my mwe were crucial. Maybe the documentation should be updated, clarifying the usage of CUDA a little bit.

For my instance, the issue is closed now, but you might want to leave it open until the CMake issues regarding the examples are solved.

Edit:

I took a quick look into the CMake files for building the examples. There are two problems: 1. `ex.h` needs to be added for each example target and 2. `target_compile_definitions(${EXE_NAME} PRIVATE HYPRE_EXAMPLE_USING_CUDA=1)` must be added for each example target. I can provide a fix and a pull request next week, if you want.
