### ISSUE TITLE
Unable to get log or data output from the SMG solver

### ISSUE THREAD

**Issue by kellerdek** [hypre-space/hypre#846]
After setting up to get SMG solve information flag to 1 or to level 2 nothing is written to output - but it does a successful solve.

      Call HYPRE_StructSMGSetPrintLevel(solver, 1, ierr)
      Call HYPRE_StructSMGSetLogging(solver,1,ierr)
      Call HYPRE_StructSMGSetup(solver, A, b, x, ierr)
      Call HYPRE_StructSMGSolve(solver, A, b, x, ierr)

Is there something else that needs to be set?

**Comment by kellerdek** [comment]
Found I could work around the problem by using HYPRE_StructSMGGetNumIterations to see if it when it met solution criteria.
This issue is with version 2.27.0.

**Comment by zongy17** [comment]
I could not find somewhere to make SMG, PFMG, or SysPFMG print some statistics (as BoomerAMG does). Do you know what to do now?

**Comment by victorapm** [comment]
@zongy17 Additional statistics about the multigrid hierarchy (as BoomerAMG is able to show) are not implemented for these methods.

**Comment by kellerdek** [comment]
Hi Yi,

I also am having trouble getting PFMG to print iteration information.

Dave

From: Yi Zong ***@***.***>
Sent: Friday, August 25, 2023 2:12 AM
To: hypre-space/hypre ***@***.***>
Cc: Keller, David ***@***.***>; State change ***@***.***>
Subject: [EXT] Re: [hypre-space/hypre] Unable to get log or data output from the SMG solver (Issue #846)


I could not find somewhere to make SMG, PFMG, or SysPFMG print some statistics (as BoomerAMG does). Do you know what to do now?
