### ISSUE TITLE
Error while installing the Paris Simulator using HYPRE

### ISSUE THREAD

**Issue by ravij8716** [hypre-space/hypre#851]
I am getting the below error after installing HYPRE and when trying to install the PARIS simulator using HYPRE lib.
/usr/bin/ld: cannot find -lHYPRE collect2: error: ld returned 1 exit status make: *** [Makefile:77: install] Error 1

When i tried ld - verbose
ld: mode elf_x86_64
attempt to open /usr/local/lib/x86_64-linux-gnu/libHYPRE.so failed
attempt to open /usr/local/lib/x86_64-linux-gnu/libHYPRE.a failed
attempt to open /lib/x86_64-linux-gnu/libHYPRE.so failed
attempt to open /lib/x86_64-linux-gnu/libHYPRE.a failed
attempt to open /usr/lib/x86_64-linux-gnu/libHYPRE.so failed
attempt to open /usr/lib/x86_64-linux-gnu/libHYPRE.a failed
attempt to open /usr/lib/x86_64-linux-gnu64/libHYPRE.so failed
attempt to open /usr/lib/x86_64-linux-gnu64/libHYPRE.a failed
attempt to open /usr/local/lib64/libHYPRE.so failed
attempt to open /usr/local/lib64/libHYPRE.a failed
attempt to open /lib64/libHYPRE.so failed
attempt to open /lib64/libHYPRE.a failed
attempt to open /usr/lib64/libHYPRE.so failed
attempt to open /usr/lib64/libHYPRE.a failed
attempt to open /usr/local/lib/libHYPRE.so failed
attempt to open /usr/local/lib/libHYPRE.a failed
attempt to open /lib/libHYPRE.so failed
attempt to open /lib/libHYPRE.a failed
attempt to open /usr/lib/libHYPRE.so failed
attempt to open /usr/lib/libHYPRE.a failed
attempt to open /usr/x86_64-linux-gnu/lib64/libHYPRE.so failed
attempt to open /usr/x86_64-linux-gnu/lib64/libHYPRE.a failed
attempt to open /usr/x86_64-linux-gnu/lib/libHYPRE.so failed
attempt to open /usr/x86_64-linux-gnu/lib/libHYPRE.a failed
ld: cannot find -lHYPRE

How to fix this issue

**Comment by ravij8716** [comment]
compiling with FLAGS = -O3 -cpp -fimplicit-none -ffpe-summary=invalid,zero,overflow linking with FOPTS =
compiler is FC = mpifort, mpi override is OMPI_FC = gfortran-mp-8
mpifort -o paris  paris.o solids.o modules.o vofmodules.o front.o surface_tension.o lppmodules.o st_testing.o newsolver.o MGsolver.o  freesurface.o boiling.o vofnonmodule.o vof_functions.o rudman_modules.o rudman_procedures.o rudman_advection.o rudman_bc.o  -L/root/cfd/libs/hypre-2.10.0b/src/lib -lHYPRE
/usr/bin/ld: cannot find -lHYPRE
collect2: error: ld returned 1 exit status
make: *** [Makefile:77: install] Error 1
root@DESKTOP-REITVFJ:/Desktop/paris-stable#

**Comment by victorapm** [comment]
@ravij8716, this seems to be an issue with compiling another software (Paris) rather than hypre. Please, let us know if you have problems with building hypre. Thanks!
