### ISSUE TITLE
Incorrect data type in a function

### ISSUE THREAD

**Issue by Tomcat4891** [hypre-space/hypre#857]
Hi.

Please check the function below ( ams.c file  )  . 
Why is the third parameter (A_cheby_fraction)  of type INTEGER?

HYPRE_Int hypre_AMSSetChebySmoothingOptions(void *solver,
                                            HYPRE_Int A_cheby_order,
                                            HYPRE_Int A_cheby_fraction)  //    <<<<<<< WHY INTEGER?
{
   hypre_AMSData *ams_data = (hypre_AMSData *) solver;
   ams_data -> A_cheby_order =  A_cheby_order;
   ams_data -> A_cheby_fraction =  A_cheby_fraction; //         <<<<<<< (ams_data -> A_cheby_fraction)  IS REAL !

   return hypre_error_flag;
}

BR,
Andrew

**Comment by victorapm** [comment]
@Tomcat4891 thank you for pointing out the issues!
