### ISSUE TITLE
A misprint in the manual

### ISSUE THREAD

**Issue by Tomcat4891** [hypre-space/hypre#858]
Hi.

On this manual page:

https://hypre.readthedocs.io/en/latest/solvers-ams.html

In the sentence
********************************
The Poisson matrices  A_alpha and A_beta , corresponding to assembling of the forms (alpha grad u, grad v)+(beta grad u, grad v)
.......
********************************
The variational definition of the A_alpha matrix is wrong. It should be  
(alpha grad u, grad v)+(beta u, v)

See the paper:

https://global-sci.org/intro/article_detail/jcm/8592.html

page 614 , case A

BR, 
Andrew

**Comment by tzanio** [comment]
Good catch @Tomcat4891, this should indeed be `(alpha grad u, grad v)+(beta u, v)`

**Comment by rfalgout** [comment]
Thanks @Tomcat4891 .  We will fix.
