### ISSUE TITLE
OpenMP on Windows

### ISSUE THREAD

**Issue by duche-at-intel** [hypre-space/hypre#865]
We use Hypre in a thermal modeling and simulation software. The sstruct interface is a perfect fit, and we curently use the PCG and LGMRES solvers with SMG precond.

As compilers, we use gcc 10.3 on Linux and minGW 10.3 on Windows

When building with OpenMP, the behavior is correct on Linux, the runtime decreasing with an increase of the number of threads. This good behavior may be degraded on some poorly-connected models, which can be understood.

But this is definitely not the case on Windows. Even for well-constructed models, the runtime improves slightly between 1 and 2 threads then degrades continuously for more threads. 

Even worse, if we compile with OpenMP enabled and restrict the number of threads to 1 (OMP_NUM_THREADS=1), we observe a longer runtime than if we compile without OpenMP.

So, for now, we have to disable OpenMP for Windows builds.

Is this behavior known? What can we do for obtaining a real multithreading behavior on Windows? Change compiler? Change solver?
Thanks for your help.

**Comment by victorapm** [comment]
@duche-at-intel sorry for the late reply.

We've recently fixed a bug involving the misuse of OpenMP pragmas for Windows builds. Would you be able to try the new hypre release?

Thanks!

**Comment by duche-at-intel** [comment]
Thank you @victorapm , we will certainly try it and let you know.

**Comment by victorapm** [comment]
Hi @duche-at-intel, did you have a chance to revisit this? Thanks!

**Comment by duche-at-intel** [comment]
Hi @victorapm , thank you for following this. The answer is no, we did not take the time yet to upgrade the the latest Hypre release and re-activate OpenMP, yet. I am leaving Intel, so I will not be the guy that takes care of this next step. But I  think that this task is scheduled for Q1, 2024. The person that will probably be in charge of this work is [@breytnerjoseph](https://github.com/breytnerjoseph), you may want to follow up with him in some time.
Thank you again for the support.

**Comment by victorapm** [comment]
Thanks for the update! All the best in your next endeavor
