### ISSUE TITLE
incorrect int type bug in hypre_BigHash function (on Windows)

### ISSUE THREAD

**Issue by peter-zajac** [hypre-space/hypre#870]
Hello, I have found an issue with the hypre_BigHash() function in src/utilities/_hypre_utilities.h then using 64 bit integers under Windows: If HYPRE_BIGINT is defined, then 'HYPRE_BigInt' is defined as 'long long', which is the correct 64 bit int type, however, the hypre_BigHash() function uses 'hypre_ulongint' (aka 'unsigned long int') for its internal calculations, which is a 32 bit int type on Windows. In consequence, the hash may turn out to be zero even if the input is non-zero (6 is a valid example), which then triggers the hypre_assert inside the hashing function, thus causing the code to crash.

The bug was encountered in HYPRE version 2.26.0, but I have just checked the current master branch code and it seems that the affected code has not been changed since then.

The fix is obvious: replace the 'hypre_ulongint' type in the hashing function by 'hypre_ulonglongint' and it will work just fine.

**Comment by victorapm** [comment]
Thanks for reporting the issue @peter-zajac! We will take a look

**Comment by victorapm** [comment]
This issue has been fixed on master. Thanks again!
