### ISSUE TITLE
hypre error with rocm/5.4.3

### ISSUE THREAD

**Issue by liruipeng** [hypre-space/hypre#875]
Hi @pbauman 

On tioga, with `rocm/5.4.3`, `srun -n 4 ./ij -n 128 128 128 -P 2 2 1       -pmis -keepT 1 -rlx 7 -w 0.5  -exec_device -mm_vendor 0 -mv_vendor 0 -agg_nl 1 -agg_interp 5 -agg_Pmx 4 -interptype 18 -solver 1 -sysL 3 -nf 3 -benchmark 1 ` failed with error

```
Memory access fault by GPU node-8 (Agent handle: 0x1f8e9d0) on address 0x154dd47b8000. Reason: Unknown.                                                                                                                                                                        
Memory access fault by GPU node-8 (Agent handle: 0x1f8e990) on address 0x154e80568000. Reason: Unknown.                                                                                                                                                                        
Memory access fault by GPU node-8 (Agent handle: 0x1f8e990) on address 0x154dd3967000. Reason: Unknown.                                                                                                                                                                         
Memory access fault by GPU node-8 (Agent handle: 0x1f8e9b0) on address 0x154dd3e1f000. Reason: Unknown.       
```

`rocm/5.4.0` seemed OK.

Any ideas?

Thanks

**Comment by pbauman** [comment]
Hi @liruipeng Is this with GPU-aware MPI enabled? If so, could you test w/o GPU-aware enabled? I know several other users of Crusher have reported similar errors with their software (not HYPRE)?

**Comment by liruipeng** [comment]
Hi @pbauman This was without GPU-aware MPI. Thanks!

**Comment by PaulMullowney** [comment]
I am seeing similar behavior in ExaWind without GPU-aware MPI though I haven't confirmed that it's happening deep in Hypre. I'm seeing this on Frontier and Crusher.

**Comment by PaulMullowney** [comment]
I have a reproducible case (64 nodes) where one of my solvers fails during precon setup with:

Memory access fault by GPU node-4 (Agent handle: 0x7145e0) on address 0x7fff6a415000. Reason: Unknown.

If I turn on debugging, I see:

[par_strength_device.c, 212] hypre_assert failed: S_num_nonzeros_offd == tmp - S_offd_j
hypre_app: par_strength_device.c:212: HYPRE_Int hypre_BoomerAMGCreateSDevice(hypre_ParCSRMatrix *, HYPRE_Int, HYPRE_Real, HYPRE_Real, HYPRE_Int, HYPRE_Int *, hypre_ParCSRMatrix **): Assertion `0' failed.

@liruipeng Have you made any progress on your failing case?

**Comment by PaulMullowney** [comment]
Upon entering par_strength_device::hypre_BoomerAMGCreateSDevice(),
A_offd_j has at least one entry that is negative. This breaks the assumption of the SOC kernels and then triggers the assertion.

Now, I need to track back why there's a negative index in A_offd_j.

**Comment by PaulMullowney** [comment]
For my problem, the bad column index comes from:
https://github.com/hypre-space/hypre/blob/master/src/parcsr_ls/par_amg_setup.c#L3033

**Comment by liruipeng** [comment]
Do you use hypre's SpGEMM or rocm's? Thanks!

**Comment by PaulMullowney** [comment]
I see it with Hypre's SpGEMM. The ROCm version just ran to completion.

**Comment by liruipeng** [comment]
> I see it with Hypre's SpGEMM. The ROCm version just ran to completion.

OK. Thanks! I can debug from there.

**Comment by PaulMullowney** [comment]
When I try to run in ExaWInd using ROCm SpGEMM in the Hypre config, I see a similar seg fault after 5 time steps. A bunch of Boomer AMG precon setup calls have previously succeeded. In the 5th time step, I get:
Memory access fault by GPU node-5 (Agent handle: 0xde48fe0) on address 0x7ffd68a08000. Reason: Unknown.
In the middle of the precon setup. 

My point is, I think this is not necessarily isolated to the Hypre vs ROCm SpGEMM.

**Comment by PaulMullowney** [comment]
In between
https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/par_csr_triplemat_device.c#L1040
https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/par_csr_triplemat_device.c#L1056

the CSR Matrix, Cbar_local, has negative column indices placed into the data structure.

**Comment by PaulMullowney** [comment]
For the ij.c example at the top of this ticket, I am seeing negative column indices arising from:
https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_spgemm_device_numer.c#L67
which is called from
https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_matop_device.c#L219
on rank 1.

**Comment by PaulMullowney** [comment]
Some actual debugging output, just prior to find the first instance of negative column indices. The max row count looks suspicious.

rank=1 csr_spgemm_device_numer.c[55]: max RC 2097357, min RC 0
rank=1 csr_spgemm_device_numer.c[69]: nnzC 8842435
rank=1 csr_spgemm_device_numer.c hypreDevice_CSRSpGemmNumerWithRownnzUpperboundNoBin 76 : d_jc=0x7ff73d600000, nnz=8842435
        rank=1 BAD : found 2359288 bad column indices (<0)

**Comment by liruipeng** [comment]
Would it be easier to debug without hypre's SpGEMM? @PaulMullowney mentioned with Rocm SPGEMM it also had similar problems (still true?)

**Comment by PaulMullowney** [comment]
In the ExaWind application, I see problems with both hypre and Rocm SpGemm. It's a lot faster to debug with ij.c.  I hope there aren't multiple bugs :(

**Comment by PaulMullowney** [comment]
@liruipeng Do you expect hypre and ROCm SpGemm to produce identical sparsity patterns but not identical numerical values for the same set of AMG parameters?

**Comment by liruipeng** [comment]
> @liruipeng Do you expect hypre and ROCm SpGemm to produce identical sparsity patterns but not identical numerical values for the same set of AMG parameters?

Probably only true for the 2nd level of AMG. The nnz ordering can be different, which can lead to different AMG hierarchy  from there.

**Comment by PaulMullowney** [comment]
On the left is hypre SpGEMM, and the right is ROCm. Everything seems ok until the last line where the difference in nnz for the computed matrix is significant. It is at this point where I start to see negative column indices for hypre SpGemm.

![SpGEMM_nnz](https://user-images.githubusercontent.com/60452402/234713595-10a48b46-add7-4b40-8d7a-37ec015a585a.PNG)

**Comment by victorapm** [comment]
Hi Paul, are these lines representing statistics for RAP at a given AMG level? If so, which level?

**Comment by PaulMullowney** [comment]
Yes. I think it's level 1 but I'm not sure.

**Comment by victorapm** [comment]
We should have 1 RAP line per level and the first 4 lines match. So the first non-matching line would be for level 5? Maybe we can print levels counters to be sure...

**Comment by PaulMullowney** [comment]
![SpGEMM_nnz](https://user-images.githubusercontent.com/60452402/234715390-e4c54c5b-9d4d-44cf-9e76-b1dfd314de2f.PNG)

The statistics are computed in hypreDevice_CSRSpGemm (csr_spgemm_device.c) via:
HYPRE_Int            my_id;
hypre_MPI_Comm_rank(MPI_COMM_WORLD, &my_id);
hypre_printf("rank=%d %s[%d]: nnzA=%d, nnzB=%d, nnzC=%d\n", my_id, __FILE__, __LINE__, nnza, nnzb, nnzC);

**Comment by victorapm** [comment]
This is helpful. So the first difference happens in the first level. The inputs A and B on left and right have the same number of nonzeros, but the output C has a different number of nonzeros. Hmm.. I'm wondering if we are breaking some assumption in rocTHRUST that was added after 5.4.0. Apparently at rocm 5.4.0, this problem was running fine

**Comment by victorapm** [comment]
Some additional info. The following works fine
`srun -n 1 ./ij -n 70 70 70 -pmis -keepT 1 -rlx 7 -w 0.5 -exec_device -mm_vendor 0 -interptype 18 -solver 1 -sysL 3 -nf 3 -pout 1`

But this doesn't:
`srun -n 1 ./ij -n 64 64 64 -pmis -keepT 1 -rlx 7 -w 0.5 -exec_device -mm_vendor 0 -interptype 18 -solver 1 -sysL 3 -nf 3 -pout 1`

Note both are single GPU

**Comment by PaulMullowney** [comment]
I see the same behavior. Here's a comparison of my debugging output for 5.4.0 vs 5.4.3 for the single GPU case:
![SpGEMM_nnz_5 4 0vs5 4 3](https://user-images.githubusercontent.com/60452402/234892295-e5efe054-e2ad-4b4c-9b71-14e40e10d225.PNG)

**Comment by PaulMullowney** [comment]
If you activate this print statement:
https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_spgemm_device_symbl.c#L210

5.4.0 on left, 5.4.3 on right. Why does one compute failed rows in the symbolic phase in 5.4.3? What constitutes a failed row?

Notice it happens in both level 0 and 1 in 5.4.3.

![SpGEMM_nnz_5 4 0vs5 4 3](https://user-images.githubusercontent.com/60452402/234951893-a9276ad4-280e-441a-a031-98e588f087e2.PNG)

**Comment by liruipeng** [comment]
> If you activate this print statement: https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_spgemm_device_symbl.c#L210
> 
> 5.4.0 on left, 5.4.3 on right. Why does one compute failed rows in the symbolic phase in 5.4.3? What constitutes a failed row?
> 
> Notice it happens in both level 0 and 1 in 5.4.3.
> 
> ![SpGEMM_nnz_5 4 0vs5 4 3](https://user-images.githubusercontent.com/60452402/234951893-a9276ad4-280e-441a-a031-98e588f087e2.PNG)

Failed row means that row runs out of space of the shared memory hash table. It shouldn't differ between to versions of rocm.

**Comment by liruipeng** [comment]
And I assume that the shared memory hash size 512 should be sufficiently large for this problem. Is it?

**Comment by PaulMullowney** [comment]
I don't know if the hash size is big enough. I tried bumping changing to BIN 6  (same for SHMEM_HASH_SIZE and GROUP_SIZE). However, the template isn't instantiated. Is assuming 5 correct here?
https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_spgemm_device_symbl.in#L26

**Comment by liruipeng** [comment]
Assuming bin 5 is OK while actually any bin number should work. It is just a heuristic. The question that may be more important is that why the behaviors are different with different Rocm versions: in one case it finds enough memory but the opposite in the other case.

**Comment by PaulMullowney** [comment]
I agree about the distinction in the ROCm versions. I was able to get it to compile with BIN 6 and ROCm 5.4.3. This test now runs to completion successfully without finding failed rows or negative column indices.

**Comment by PaulMullowney** [comment]
The first time that we see differences in 
https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_spgemm_device_symbl.h#L518
between 5.4 and 5.4.3, the input is equivalent. That is I dumped the rows and columns of A and B to files and compared. No diffs. I'm gonna try to extract this kernel out into a small reproducer. If there is a problem with the compiler somewhere, this will make it easier to reproduce.

**Comment by PaulMullowney** [comment]
Here's a standalone reproducer outside of Hypre. I need to simplify this as much as possible
https://github.com/PaulMullowney/hypre_spgemm_symb_repro.git

**Comment by PaulMullowney** [comment]
@victorapm Can you pull and give this reproducer a try?

**Comment by victorapm** [comment]
Just did it :)

**Comment by PaulMullowney** [comment]
In the reproducer, disabling the unrolling in the loop with the atomics enables the code to run successfully.

**Comment by liruipeng** [comment]
> In the reproducer, disabling the unrolling in the loop with the atomics enables the code to run successfully.

This sounds like a compiler issue?

**Comment by PaulMullowney** [comment]
ij test in Hypre runs correctly also.

**Comment by PaulMullowney** [comment]
> > In the reproducer, disabling the unrolling in the loop with the atomics enables the code to run successfully.
> 
> This sounds like a compiler issue?

sure does

**Comment by PaulMullowney** [comment]
For one of my applications, a debug build succeeds but a release build still crashes with:

:0:rocdevice.cpp            :2673: 71237743452 us: 125941: [tid:0x7fffa3477700] Device::callbackQueue aborting with error : HSA_STATUS_ERROR_MEMORY_APERTURE_VIOLATION: The agent attempted to access memory beyond the largest legal address. code: 0x29
Memory access fault by GPU node-10 (Agent handle: 0x71a1c0) on address 0x7fff68175000. Reason: Unknown.


It looks like ij.c also crashes on a single node with a release build.

**Comment by PaulMullowney** [comment]
The numeric component has the same atomics to shmem embedded in a pragma unroll.

**Comment by PaulMullowney** [comment]
If I disable the unrolling at:
https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_spgemm_device_symbl.h#L36
https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_spgemm_device_numer.h#L41

Exawind runs on Frontier, albeit with degraded performance in the Hypre SpGemm.  I've run for 50 time steps in the simulation on 8, 16, 32, 64 and 128 nodes.

**Comment by victorapm** [comment]
Good! Are there any updates from the compiler team? @pbauman

**Comment by PaulMullowney** [comment]
I haven't submitted it as a bug yet. I'm going to start that process tomorrow.

**Comment by PaulMullowney** [comment]
I think this is definitely necessary:
https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_spgemm_device_rocsparse.c#L57

I was able to stabilize ExaWind using the ROCm SpGemm if I sort the matrix prior to multiplication. For the problem I'm testing, my AMG hierarchies definitely generate some long rows (~2000 entries).

**Comment by victorapm** [comment]
I agree!!

https://github.com/ROCmSoftwarePlatform/rocSPARSE/blob/d8e35fc37ea738c599a6ca7f97ad2fddd275a622/library/src/level3/rocsparse_csrmm.cpp#L117-L120

So, it seems that the storage method of a `descr` is `sorted` by default?

@pbauman @PaulMullowney Wouldn't it make more sense to have `descr->storage_mode` as `rocsparse_storage_mode_unsorted` by default? That would make it easier to catch bugs like this

**Comment by pbauman** [comment]
> I think this is definitely necessary:
https://github.com/hypre-space/hypre/blob/master/src/seq_mv/csr_spgemm_device_rocsparse.c#L57

Ack. This has been on my TODO list for a long while. AMG benchmark (27pt stencil) SHOULD NOT be hitting this, but it's possible that more dense matrices could. There is machinery in rocSPARSE to handle this now where a return code will tell you that, if you're columns are not sorted, then you're on a code path that requires sorted columns so it gives you a chance to recover and sort the columns and try again. I've just not had time to add it and the only time we hit it was a corner case by @liruipeng. But yes, the safest thing at this moment is sort the columns. It's like a 10% perf hit or something to the setup phase.

**Comment by PaulMullowney** [comment]
We could add an option for the user to turn it off, i.e. something like:
HYPRE_SetSpGemmSortVendor

**Comment by liruipeng** [comment]
Thanks folks. We've been moving back and forth on this. I thought for latest versions, we don't need to sort even for long rows. But I could be wrong. We can add it back.

**Comment by PaulMullowney** [comment]
To close the loop on this issue. 
1) I made the following changes to seq_mv/csr_spgemm_device_symbl.h/numer.h
-#pragma unroll UNROLL_FACTOR
+#pragma unroll 8 //UNROLL_FACTOR
2) I also turned on sorting for the ROCm Spgemm.

This enables ExaWind to run for a large number of time steps (many calls to BoomerAMG setup) for either SpGEMM algorithm on Frontier at many different GPU counts.

Since I don't know if/when the unrolling issue will be resolved, is it reasonable to put a patch around the unrolling for the HIP ROCm version?

**Comment by victorapm** [comment]
How about something like this:
```
#if HIP_VERSION_MAJOR == 5 && HIP_VERSION_MINOR == 4 && HIP_VERSION_PATCH == 3
#pragma unroll 8
#else
#pragma unroll UNROLL_FACTOR
#endif
```

assuming the HIP macros exist

My understanding is this is not an issue anymore with the recent `rocm-5.5.0`

**Comment by PaulMullowney** [comment]
The following works:
#if HIP_VERSION_MAJOR == 5 && HIP_VERSION_MINOR == 4 && HIP_VERSION_PATCH == 22804
