### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by Tomcat4891** [hypre-space/hypre#876]
Hi.

Tried to compile the mfem.
The current version (git clone) gives the error:

...... linalg/strumpack.cpp (226) : error: no operator "<<" matches these operands
operand types are : std ::basic_ostream<char,std::char_traits<char>> << strumpack::ReturnCode
MFEM_ABORT("STRUMPACK: 'factor()', error code = " << ret);

No such error for the version 4.4.

BR,
Andrew

**Comment by victorapm** [comment]
Hi @Tomcat4891, this error message does not seem to be related with hypre. Have you tried asking about it in the MFEM GitHub page? Thanks!

**Comment by Tomcat4891** [comment]
Sorry, :)
This is an error for the mfem
