### ISSUE TITLE
shell scripts use `function` keyword which is not POSIX compliant

### ISSUE THREAD

**Issue by drew-parsons** [hypre-space/hypre#881]
The shell scripts in hypre, e.g. [runtest.sh](https://github.com/hypre-space/hypre/blob/master/src/test/runtest.sh) use the `function` keyword, which is not in the POSIX shell standard. `function` was first defined in ksh, and is used by bash and zsh.

The scripts use the hashbang `#!/bin/sh`.  This creates a problem if `/bin/sh` points at a POSIX-strict shell such as dash, which is the case for debian-based linux systems for instance.  In this case runtest.sh fails with
```
./runtest.sh: 30: function: not found
```
(meaning the command "function" was not found)

I encountered the problem running hypre tests via runtest.sh on a Debian system, but all hypre scripts (*.sh and *job) may be affected, not just runtest.sh.

Should the `function` keyword be dropped and other necessary edits done to make all scripts POSIX-compliant?
Or should the hashbang be changed to `#!/bin/bash`?

**Comment by rfalgout** [comment]
The easiest way to fix this is probably to just change it to `#!/bin/bash`.  I don't think we really use functions in our other scripts (but I can check), and I don't see us having a real portability disadvantage here.

**Comment by victorapm** [comment]
I like the idea of changing to `#!/bin/bash`. That solves some problems that I have when running regression tests in my personal machine

**Comment by rfalgout** [comment]
I just checked and `runtest.sh` is the only script where we use `function` so I think we should go ahead and change that.

**Comment by victorapm** [comment]
Hi Rob, we are using `shopt`, which is specific to bash, in the `cleantest.sh` and `checktest.sh` scripts. Should we substitute with a shell independent keyword or change the scripts to use `#!/bin/bash`?

**Comment by rfalgout** [comment]
> Hi Rob, we are using `shopt`, which is specific to bash, in the `cleantest.sh` and `checktest.sh` scripts. Should we substitute with a shell independent keyword or change the scripts to use `#!/bin/bash`?

Hi Victor.  Let's officially make these two scripts bash scripts as well.  BTW, are you putting together a PR?  It doesn't have to be you, of course.  Just checking.

**Comment by victorapm** [comment]
@drew-parsons Could you test the branch https://github.com/hypre-space/hypre/tree/sh-to-bash and let us know if it works fine in your system?

**Comment by drew-parsons** [comment]
PR #900 (patched onto 2.29.0) passes Debian tests
