### ISSUE TITLE
Segmentation fault:    ver 2.28  FSAI+AMS

### ISSUE THREAD

**Issue by Tomcat4891** [hypre-space/hypre#883]
Hi.

There is a problem with the FSAI (HYPRE 2.28), namely with two functions:
                          HYPRE_BoomerAMGSetSmoothType(HYPRE_Solver solver, 4);
                          HYPRE_BoomerAMGSetSmoothNumLevels(HYPRE_Solver solver, HYPRE_Int num_levels);

I am experimenting with the ams_driver (test program).
I added two lines to the ams.c file. (This will allow me to use the FSAI smoother for the AMS solver.)

CODE: ams.c
LINE 3123 if (!ams_data->beta_is_zero && ams_data->cycle_type != 20)
LINE 3124    {
                  HYPRE_BoomerAMGCreate(&ams_data->B_G);
                   HYPRE_BoomerAMGSetCoarsenType(ams_data->B_G, ams_data->B_G_coarsen_type);
                   HYPRE_BoomerAMGSetAggNumLevels(ams_data->B_G, ams_data->B_G_agg_levels);
                  HYPRE_BoomerAMGSetRelaxType(ams_data->B_G, ams_data->B_G_relax_type);
      HYPRE_BoomerAMGSetNumSweeps(ams_data->B_G, 1);
      HYPRE_BoomerAMGSetMaxLevels(ams_data->B_G, 25);
      HYPRE_BoomerAMGSetTol(ams_data->B_G, 0.0);
      HYPRE_BoomerAMGSetMaxIter(ams_data->B_G, 1);
      HYPRE_BoomerAMGSetStrongThreshold(ams_data->B_G, ams_data->B_G_theta);
      HYPRE_BoomerAMGSetInterpType(ams_data->B_G, ams_data->B_G_interp_type);
      HYPRE_BoomerAMGSetPMaxElmts(ams_data->B_G, ams_data->B_G_Pmax);
      HYPRE_BoomerAMGSetMinCoarseSize(ams_data->B_G, 2); /* don't coarsen to 0 */

      /* Generally, don't use exact solve on the coarsest level (matrix may be singular) */
      HYPRE_BoomerAMGSetCycleRelaxType(ams_data->B_G, ams_data->B_G_coarse_relax_type, 3);
     
      HYPRE_BoomerAMGSetSmoothType(ams_data->B_G, 4);    // These two lines are my addition.          <-------------------------
      HYPRE_BoomerAMGSetSmoothNumLevels(ams_data->B_G, 4); // These two lines are my addition.    <-------------------------
.......

for the HYPRE 2.25.0 and 2.26 these two lines work well (I can use the FSAI).
*************************
* HYPRE FSAI Setup Info *
************************
---------------------------+
| No. MPI tasks:          4 |
| No. threads:            1 |
| Algorithm type:         1 |
| Max no. steps:          5 |
| Max step size:          3 |
| Kap grad tol:     1.0e-03 |
| Prec. density:      0.795 |
| Eig max iters:          5 |
| Omega factor:       0.828 |
+---------------------------+

for the HYPRE 2.28.0 These two lines generate a Seg.fault type error.   =((
                          Caught signal 11 (Segmentation fault: address not mapped to object at address 0x20)

I ran the test programs ams_driver as
mpirun -np 4 ./ams_driver -solver 3

BR,
Andrew

**Comment by victorapm** [comment]
Thanks for reporting @Tomcat4891! I will look at this issue. Out of curiosity, can you share some details on the type of linear system you are solving and why are you experimenting with FSAI? I am happy to know if FSAI is useful to your application

**Comment by Tomcat4891** [comment]
We solve a positive-defined vector Helmholtz equation for the electromagnetic waves. For this purpose we use the multigrid AMS method. The FSAI as a smoothing algorithm allows us to reduce the computation time by 15%.

**Comment by victorapm** [comment]
Thanks!! It's good to hear that the method is useful to your application. Is your code built on top of MFEM? I'm asking to understand how to expose better the setup options for FSAI to external users. In the meantime, I'm looking at your issue

**Comment by Tomcat4891** [comment]
Now we use the pure Hypre to test different multigrid preconditioners for our problem. It would be nice to be able to use the FSAI and other complex smoothers for the AMS preconditioner. Right now we need to modify the ams.c file manually to specify an arbitrary smoothing algorithm for the BoomerAMG for all four AMS matrices.

**Comment by victorapm** [comment]
Ok @Tomcat4891 , we will work on adding these options. How is your code called? Is it open-source?

**Comment by Tomcat4891** [comment]
We don't have an open source code. We are more interested in computational mathematics.

**Comment by victorapm** [comment]
@Tomcat4891 FSAI works with AMS now, I'm curious to see the results. Please share them with me when you finalize your study

**Comment by Tomcat4891** [comment]
@victorapm 
Thank you very much! 
The FSAI reduces the calculation time by about 15-20% compared to smoothers 2,4,8,16 for the AMS preconditioner.

**Comment by victorapm** [comment]
That's nice! If you want to open a PR with the code changes you made inside hypre, I can take a look. Thanks!
