### ISSUE TITLE
HYPRE_StructSMGSetMemoryUse documentation

### ISSUE THREAD

**Issue by kellerdek** [hypre-space/hypre#886]
Is there documentation describing what this interface does?

Thanks in advance.

Dave
Version 2.28 on Intel 2020.1 cluster.

**Comment by rfalgout** [comment]
Apparently not.  We'll try to update this when time permits.  Basically, this can be set to values 0, 1, or 2 (higher values work the same as 2), where larger values use less memory at the expense of doing more computations.

**Comment by kellerdek** [comment]
OK.  Thanks Rob!
