### ISSUE TITLE
usage confusion over setting boundary values

### ISSUE THREAD

**Issue by kellerdek** [hypre-space/hypre#893]
I am confused by the documentation.  In the current example there is a section about setting boundary values.  (the current documentation follows)
It seems that the example is referencing a six value boundary yet the sample code seems to set up for 12 values? 
Is this just a typo?

Matrix coefficients that reach outside of the boundary should be set to zero. For efficiency reasons, hypre does not do this automatically. The most natural time to insure this is when the boundary conditions are being set, and this is most naturally done after the coefficients on the grid’s interior have been set. For example, during the implementation of the Dirichlet boundary condition on the lower boundary of the grid in Figure [Structured Grid Example](https://hypre.readthedocs.io/en/latest/ch-struct.html#fig-struct-example), the south coefficient must be set to zero. To do this on process 0, the following code could be used:

int  ilower[2] = {-3, 1};
int  iupper[2] = { 2, 1};

/* create matrix and set interior coefficients */
...

/* implement boundary conditions */
...

for (i = 0; i < 12; i++)
{
   values[i] =  0.0;
}

i = 3;
HYPRE_StructMatrixSetBoxValues(A, ilower, iupper, 1, &i, values);

/* complete implementation of boundary conditions */

**Comment by rfalgout** [comment]
Yes, the loop only needs to go to 6.  Similarly, an earlier loop only needs to go to 24.  Thanks for pointing this out.

**Comment by kellerdek** [comment]
Glad to help.  And thanks for the clarification.

I was just going over my implementation looking for something basic I must be doing wrong.  Repeated solves with evolving grid values supplied take more and more iterations to solve with time.  I had not bothered setting values outside the internal box since I know the coefficients are zero for them - but  I will trying explicitly setting them to zero.
