### ISSUE TITLE
Number of OpenMP Threads

### ISSUE THREAD

**Issue by tmpnemophd** [hypre-space/hypre#9]
Hello,

Is there any way to specify the number of OpenMP Threads for the Hypre library? I know one can use **set omp_num_threads=** in the command window but I would like to hard-wire the number of threads. FYI, my codes are in Fortran and I am using Windows.

Thank you.

**Comment by rfalgout** [comment]
Hello,

There is no way provided by hypre to do this, but there may be OpenMP API routines that you can use in your driver, e.g., omp_set_num_threads().  See the OpenMP documentation for details.  Hope this helps!

-Rob

**Comment by tmpnemophd** [comment]
Thanks!
