### ISSUE TITLE
Is there a function to perform sparse matrix-matrix multiplication?

### ISSUE THREAD

**Issue by YongjunZHENG** [hypre-space/hypre#911]
Is there a function to perform sparse matrix-matrix multiplication in HYPRE:
C = A*B;
where A, B, and C are all a sparse matrix of HYPRE_ParCSRMatrix.
Thank you in advance.

**Comment by thartland** [comment]
It looks like there is, see [here](https://github.com/hypre-space/hypre/blob/master/src/parcsr_mv/par_csr_triplemat.c#L199).

**Comment by YongjunZHENG** [comment]
Thank you so much! I tried it and it works!
