### ISSUE TITLE
[Question] Reusing a Struct vector / memory leak?

### ISSUE THREAD

**Issue by nncarlson** [hypre-space/hypre#92]
For a situation where I have sequential Struct RHS vectors (all for the same grid) is this the correct call sequence?
```C
  HYPRE_StructVectorCreate
1 HYPRE_StructVectorInitialize
  HYPRE_StructVectorSetBoxValues
  HYPRE_StructVectorAssemble
  do stuff with the vector
  for next RHS go to 1
  HYPRE_StructVectorDestroy
```
With this organization valgrind is showing a big memory leak originating from `HYPRE_StructVectorInitialize`. Is it required that the vector be created and destroyed for each RHS?

**Comment by rfalgout** [comment]
Hi @nncarlson .  Only do the Initialize and Assemble once, so just call SetBoxValues for subsequent changes to the vector.  As long as your underlying grid is the same, this should work.

The interface design is such that Initialize and Assemble are also supposed to serve as Re-Initialize and Re-Assemble, but that doesn't work uniformly in the code right now and we don't regression test for it anyway.  This is something we need to revisit at some point and decide either to remove the Re-Initialize/Re-Assemble feature from the design or implement and test it.

**Comment by nncarlson** [comment]
So Assemble must not do anything at all with data set by SetBoxValues, is that right?

**Comment by rfalgout** [comment]
StructVectorAssemble currently does nothing.  That is correct.

**Comment by nncarlson** [comment]
Thanks for you help @rfalgout!
