### ISSUE TITLE
CUDA Error During `HYPRE_IJMatrixSetValues`

### ISSUE THREAD

**Issue by lwshanbd** [hypre-space/hypre#949]
Hi,

I am using BoomerAMG+PCG by HYPRE GPU version on ij matrix.
Whenever I use call the `HYPRE_IJMatrixSetValues` in my program, it will crash with a CUDA error: (code = 1, invalid argument)
The `ij` in `test` could  run normally.

In my setup of the hypre, I enable the unified memory.
I am wondering where the problem could be from?

Thanks.

**Comment by victorapm** [comment]
Hi Baodi,

can you share a minimum working example (MWE) for your issue?

**Comment by jrood-nrel** [comment]
I think I am seeing a similar issue using SyCL on Intel GPUs, it will segfault in this routine.

**Comment by jrood-nrel** [comment]
My problem turned out to be a simple mistake https://github.com/spack/spack/pull/39351

**Comment by victorapm** [comment]
@lwshanbd Has this issue been resolved?

**Comment by lwshanbd** [comment]
@victorapm Hi Victor, sorry for the late reply. I have fixed it, and the bug is not from the Hypre. Thanks.
