### ISSUE TITLE
How to call SpGEMM with cuda in hypre-2.18.2 ？

### ISSUE THREAD

**Issue by TXTsky** [hypre-space/hypre#95]
Dear hypre developers,

I am a graduate student, and now I need to use hypre for my project. The main direction is **SpGEMM** optimization, but I don't know how to configure correctly to use CUDA version, and I don't know what options are needed during execution. 

The GPU I used is RTX 2060, CUDA 10.2, and the test case is `src/test / ij`. 

I built hypre with the options: 
`HYPRE_CUDA_SM=75 CUDA_HOME=/usr/local/cuda-10.2 ./configure --with-cuda --with-openmp --enable-unified-memory`

And  i execute hypre with：

`mpirun -np 1 ./ij -27pt -n 100 100 100 -solver 3`

Here are the problems I encountered.

1. In the previous attempt, when I used `./configure --with-cuda  --with-device-openmp `at the same time,   error occurred in compilation
`nvcc fatal   : redefinition of argument 'x'  `
There are  in  config/Makefile.config ,
```
 CC       = nvcc
CFLAGS   = -x c++ -O2 -ccbin=mpic++ -gencode arch=compute_75,"code=sm_75" -expt-extended-lambda -dc -std=c++11 --x cu -Xcompiler "-O2 " -DHAVE_CONFIG_H $(C_COMPILE_FLAGS)
```
2. After using `mpirun -np 1 ./ij -27pt -n 100 100 100 -solver 3`, only GPU is used when calculating residuals. Is SPMV used for this part? I found the part of SpGEMM in seqmv (`csr_spgemm_device_attept. C`, etc.), but my current configuration does not call these files.

3. Could you please tell me how to configure and execute ij commands correctly? I've tried it for two weeks, and I'm looking forward to your help!

Thank you for your help all the time. Hope you reply soon.

Yours sincerely,
Xiaotian

**Comment by rfalgout** [comment]
Has this issue been resolved? Thanks! -Rob

**Comment by liruipeng** [comment]
@TXTsky Please check out hypre v2.20.0,  configure with

```
./configure --with-cuda --enable-unified-memory --enable-debug
```

compile, and run `ij` with

```
mpirun -np 4 ./ij -n 256 256 128 -P 2 2 1       -pmis -keepT 1 -rlx 18        -exec_device -rap 1 -mod_rap2 1 -mm_cusparse 0 -interptype  3 -solver 1
```
