### ISSUE TITLE
no HIP support for CMake build?

### ISSUE THREAD

**Issue by BenWibking** [hypre-space/hypre#958]
It looks like there is no way to enable HIP support in the CMake build. Did I miss something?

(I am trying to build on a Cray EX with AMD GPUs. If there is a better way to build on this system, please let me know.)

**Comment by victorapm** [comment]
HIP support via CMake is work in progress. For now, we recommend using hypre's configure (autotools).

Here's an example for a minimal build with HIP support:
```
./configure CC=cc CXX=CC FC=ftn \
            --with-MPI-include=${MPICH_DIR}/include \
            --with-MPI-lib-dirs=${MPICH_DIR}/lib \
            --with-MPI-libs=mpi \
            --with-hip
```

**Comment by BenWibking** [comment]
Ok, that works. Thanks.

Is there a reason that GPU-aware MPI is not enabled by default?

**Comment by victorapm** [comment]
We've experienced some instabilities with this option for large-scale runs, so it's disabled by default for better robustness of the library. This will be re-evaluated in the future.

**Comment by BenWibking** [comment]
Ok, thanks for the information. I'll close this issue.
