### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by prj-** [hypre-space/hypre#960]
With `gcc` 12.3.0, I get multiple warnings such as:
```
arch-linux-c-opt/include/_hypre_utilities.h(2714): warning #3012-D: a volatile destination type for a compound assignment expression is deprecated
              move_bucket->hopInfo |= (1U << move_free_dist);
arch-linux-c-opt/include/_hypre_utilities.h:2742:91: warning: unused parameter ‘m’ [-Wunused-parameter]
 2742 | hypre_UnorderedBigIntMapFindCloserFreeBucket( hypre_UnorderedBigIntMap   *m,
      |                                                                 ~~~~~~~~~~~~              ^
```
Could you please fix this?

**Comment by victorapm** [comment]
Hi Pierre, I'm working on a branch to get rid of those warnings: #896

**Comment by prj-** [comment]
Hi Victor, any idea when this will land in `master`?

**Comment by victorapm** [comment]
Hi Pierre, I have a few other tasks ahead of this. I would say about a month to get this into master. Would this update be critical for PETSc?

**Comment by prj-** [comment]
No, it's only critical for lunatics like me who use all imaginable compiler warnings.

**Comment by victorapm** [comment]
hahaha I understand you... I'll let you know once this is ready...
