### ISSUE TITLE
Is the mixed-precision version of KSP on GPU available?

### ISSUE THREAD

**Issue by hanfluid** [hypre-space/hypre#963]

**Comment by victorapm** [comment]
Hi @hanfluid,

Are you referring to hypre's mixed-int configuration option (internal support to both 32-bit and 64-bit integers) or to the ability of solvers to handle multiple floating-point data types, e.g., float and double, in the same run?

**Comment by hanfluid** [comment]
Hi Victorapm, I was referring to the second one, which is handling multiple floating-point data types in the same run.

**Comment by victorapm** [comment]
Thanks! This is a work-in-progress by @oseikuffuor1

**Comment by victorapm** [comment]
Please let us know if you have any questions, @hanfluid. I'm closing this issue for now
