### ISSUE TITLE
Enhancement: explicit link to installation instructions

### ISSUE THREAD

**Issue by VictorEijkhout** [hypre-space/hypre#964]
Page https://hypre.readthedocs.io/en/latest/ch-intro.html#installing-hypre states "or refer to the last chapter in this manual". But the last chapter is "API". Please give explicit link to https://hypre.readthedocs.io/en/latest/ch-misc.html#building-the-library

**Comment by victorapm** [comment]
@VictorEijkhout thanks for reporting! The linked PR will solve this issue. Best!
