### ISSUE TITLE
CMake does not build shared library

### ISSUE THREAD

**Issue by VictorEijkhout** [hypre-space/hypre#965]
I would have thought the standard option `-D BUILD_SHARED_LIBS=TRUE` would give shared libraries, but that doesn't seem to be the case. The installation instructions only mention a `--enable-shared` option for the autoconf installation.

**Comment by osborn9** [comment]
Please use the CMake option `HYPRE_ENABLED_SHARED` to enable or disable this feature. 

As you point out, we are currently not respecting the standard `BUILD_SHARED_LIBS` option (but we should in the future).

**Comment by VictorEijkhout** [comment]
You meant to write `HYPRE_ENABLE_SHARED` (without the `D`).... Works. Thanks.

**Comment by osborn9** [comment]
Oops, yes! Thanks for the correction!
