### ISSUE TITLE
Question on setting up resistivity using face centered B fields (and AMR)

### ISSUE THREAD

**Issue by johannjc** [hypre-space/hypre#997]
I'm planning on using the semistruct interface to setup a matrix to solve magnetic resistivity using face centered Bx and By fields. 
 I'm trying to decide whether to use separate parts for my x-face Bx fields and y-face By fields - or to try and have them be on the same part even though they have different indexing.  
 
 My understanding is that each grid is responsible for setting up the matrix entries for the 'upper' faces of each zone - but I'm unclear how the matrix entries for the lower faces are meant to be set.   For fixed grid this becomes an issue at the lower domain boundaries - and for AMR it becomes an issue at every coarse-fine interface.  

Using separate parts - so that the Bx and By fields can have separate indices - seems a lot simpler conceptually - though having separate parts means a lot more calls to graphaddentries instead of relying on stencil connections.

**Comment by rfalgout** [comment]
Hi @johannjc .  You should use one part.  You can set both the lower and upper faces on the same part (and part box).  See Figure 5 here: https://hypre.readthedocs.io/en/latest/ch-sstruct.html.  The right x-face variable is referenced with index (i,j) in the SetValues() call (for example), while the left x-face variable is referenced with index (i-1,j).  Similarly for y-face variables.

Hopefully I understood your question correctly.  Thanks!

**Comment by johannjc** [comment]
So if I had a single square 4x4 grid with x and y face centered vars

HYPRE_SStructGridSetVariables(grid, part, nvars=2, vartypes=(/XFACE,YFACE/))
HYPRE_SStructGridSetExtents(grid,part,(/0,0/),(/3,3/))

would I pass in values for the x faces that included the leftmost and rightmost faces (ie a flattened 5x4 array)?

HYPRE_SStructVectorSetBoxValues(vector, part, (/0,0/),(/3,3/), var=0, (/((values(i,j),i=-1,3),j= 0,3)/))

and then do something like this for y (ie a flattened 4x5 array)?
HYPRE_SStructVectorSetBoxValues(vector, part, (/0,0/),(/3,3/), var=1, (/((values(i,j),i= 0,3),j=-1,3)/))


or would I do something like

HYPRE_SStructVectorSetBoxValues(vector, part, (/-1,0/),(/3,3/), var=0, (/((values(i,j),i=-1,3),j= 0,3)/))
HYPRE_SStructVectorSetBoxValues(vector, part, (/0,-1/),(/3,3/), var=1, (/((values(i,j),i=0,3),j= -1,3)/))

where the ilower and iupper indices are outside the range of the limits I passed to GridSetExtents?

**Comment by rfalgout** [comment]
> or would I do something like
> 
> HYPRE_SStructVectorSetBoxValues(vector, part, (/-1,0/),(/3,3/), var=0, (/((values(i,j),i=-1,3),j= 0,3)/)) HYPRE_SStructVectorSetBoxValues(vector, part, (/0,-1/),(/3,3/), var=1, (/((values(i,j),i=0,3),j= -1,3)/))
> 
> where the ilower and iupper indices are outside the range of the limits I passed to GridSetExtents?

This second approach is the right one.  We have some examples that illustrate this, e.g., `ex12.c` (for NODAL variables).

**Comment by johannjc** [comment]
So looking at ex12.c, if you have node centered values, Hypre basically figures out what node entries to include in the matrix by augmenting the bounds passed to gridsetextents.  And adjacent grids that share a node - should both set the matrix / vector values consistently.  

Two other quick questions related to periodic BC's...  
  1.)  If you had periodic BC's, you would set the periodic extents based on the number of zones (not nodes) and then set the leftmost node and rightmost node consistently?  
  2.)  Do the actual extends of the grids for a given part matter - or does HYPRE just use the lowermost/uppermost grid extents for each part to figure out how to periodically wrap stencil entries?  Or in other words, does the lowest grid extent need to be 0 or 1 for periodic wrapping to work - or can it be arbitrary?

**Comment by rfalgout** [comment]
> So looking at ex12.c, if you have node centered values, Hypre basically figures out what node entries to include in the matrix by augmenting the bounds passed to gridsetextents. And adjacent grids that share a node - should both set the matrix / vector values consistently.

All processes that share a node should set the same consistent value(s).  AddValues() is done independently and accumulated by hypre (even across process boundaries).  Internally, hypre only stores one value for shared nodes, on one of the processes.
 
> Two other quick questions related to periodic BC's...
> 1.) If you had periodic BC's, you would set the periodic extents based on the number of zones (not nodes) and then set the leftmost node and rightmost node consistently?

Yes.

> 2.) Do the actual extends of the grids for a given part matter - or does HYPRE just use the lowermost/uppermost grid extents for each part to figure out how to periodically wrap stencil entries? Or in other words, does the lowest grid extent need to be 0 or 1 for periodic wrapping to work - or can it be arbitrary?

The indices are arbitrary and set by the user.  They can even be negative if you really wanted to do that.  The min/max grid extents are not used to figure out the periodicity.  You need to explicitly set the period.

Hope this helps!

**Comment by johannjc** [comment]
Interesting - so I will need to be careful calling addvalues - to not "double add" on shared nodes.

Do I have to call setvalues on shared nodes multiple times - or can I adjust the indices passed by neighboring grids - so that only one processor/grid actually tries to set the values for a given node?  Presumably this would be the same indexing pattern I would use for addvalues.  

That is - only zones with no neighbors to the left would try to setvalues (or addvalues) for nodes on the leftmost boundary - while they would always setvalues and addvalues for nodes on the rightmost boundary.

**Comment by rfalgout** [comment]
> Interesting - so I will need to be careful calling addvalues - to not "double add" on shared nodes.

Yes

> That is - only zones with no neighbors to the left would try to setvalues (or addvalues) for nodes on the leftmost boundary - while they would always setvalues and addvalues for nodes on the rightmost boundary.

No, this doesn't sound right.  Set and Add have different rules.  If I am a processor and own a node (i.e., it is in one or more of my local grid boxes), then I am responsible for calling SetValues() (hence all processors who share ownership must set the same value).  On the other hand, any calls to AddValues() are in cooperation with other processors who share ownership (all AddValues calls for a node are accumulated, even when different processors are involved).  This is natural for finite element codes, where each processor would Set an initial value of zero and call AddValues to accumulate the entries of the element matrices.  If your code already decomposes the data uniquely in parallel, then you could still use a similar strategy of first calling Set to initialize to zero, then calling Add on those processes that own the information (so only one processor would make the call to Add for any given shared node).  Or you could do something else, as long as you know the rules.

**Comment by johannjc** [comment]
Ok - that all makes sense.  Thanks for the very helpful discussion!
